### PR TITLE
Feature/qt5: TOPPAS fix

### PR DESCRIPTION
**Pull request by cbielow**
fixes https://github.com/OpenMS/OpenMS/issues/3207

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Looks good. Is the QPA path necessary right after build or only if you move the binaries? I did not recognize it while testing Qt5 on Win. But maybe I did something similar. Or I only tested after the packaging/install steps which copy the plugins.

**Comment by jpfeuffer** [comment]
There were some python failures though. I restarted.

**Comment by jpfeuffer** [comment]
@cbielow Did you test packaging with this. I just can say from experience that making something a QApplication has a lot of consequences.

**Comment by cbielow** [comment]
Qpa is required after build to run it (without install)
-- 
Sent via mobile phone.

Am 10. März 2018 23:11:48 MEZ schrieb jpfeuffer <notifications@github.com>:

**Comment by jpfeuffer** [comment]
Yes I guess if the class is only called by something that already has an include before, it is fine. I mean stuff like ExecutePipeline. Would be a shame if they suddenly need these horrible Qt plugins.

**Pull request merged**
