### PR TITLE
Fix/pyopenms mac fix

### PR DESCRIPTION
**Pull request by hroest**

### CODE REVIEW

**Comment by hroest** [comment]
addresses #1777

**Comment by timosachsenberg** [comment]
is this also in master?

**Comment by hroest** [comment]
no not yet

**Comment by timosachsenberg** [comment]
in github its 755
in the script 744
is this correct?

**Comment by timosachsenberg** [comment]
bump

**Comment by jpfeuffer** [comment]
Can't set status; build failed.

**Comment by timosachsenberg** [comment]
any update on this one? close?

**Comment by hroest** [comment]
honestly, I dont know. We would need some feedback from the OSX people, @grosenberger ?

**Comment by lars20070** [comment]
I can help with testing on `macOS`, but I am no expert on `macOS` build system.

**Comment by grosenberger** [comment]
I just started working on making PyOpenMS on macOS building and distributing smoother again and I can confirm that this patch is required.

**Comment by hroest** [comment]
thanks @grosenberger i just merged #2819 into master so that we can build the 2.2 Release there

**Comment by grosenberger** [comment]
Great, I'm trying to fix some other issues and will make a PR ASAP. We should then check if the wheels work for others, I will attach them to the PR.

**Comment by hroest** [comment]
great, I have the windows stuff built and I am doing Linux over here: https://github.com/OpenMS/OpenMS/pull/2820

**Pull request closed without merging**
