### PR TITLE
[FIX] Spelling

### PR DESCRIPTION
**Pull request by oliveralka**
# Description

FIX spelling (#5110)

Some typos remain in old toppas workflows and .ini files.

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

Note: If your PR is failing you can check out http://cdash.openms.de/index.php?project=OpenMS and look for your PR with detailed error messages.

### CODE REVIEW

**Review by cbielow — APPROVED** [review]

**Comment by oliveralka** [comment]
INIUpdater tests fail due to the changed parameter description. 
```
/Users/alka/Documents/work/software/openms_oa/OpenMS/src/tests/topp/INIUpdater_1_noupdate.toppas   (line: 48, position/column: 195/196)
2387:             <ITEM name="slope_bound" value="0.5" type="double" description="The maximum slope of mass trace intensities when extending from the highest peak.#br#This parameter is important to sep!
2387:                                                                                                                                                                                                    erate overlapping elution peaks.#br#It should be increased if feature elution profiles fluctuate a lot." required="false" advanced="false" restrictions="0:" />
```
It seems in the newer version all numbers are represented as a float. 

`<ITEM name="slope_bound" value="0.5" type="double" description="The maximum slope of mass trace intensities when extending from the highest peak.#br#This parameter is important to separate overlapping elution peaks.#br#It should be increased if feat    ure elution profiles fluctuate a lot." required="false" advanced="false" restrictions="0.0:" />`

Just wanted to point that out.

**Comment by oliveralka** [comment]
rebuild jenkins

**Comment by oliveralka** [comment]
rebuild jenkins

**Comment by oliveralka** [comment]
Failing tests seems unrelated (XTandemAdapter)
Travis - all tests passed but timed out uploading results

@jpfeuffer Both happened three times in a row.

**Comment by jpfeuffer** [comment]
Hmm on the one hand. Those two problems are common candidates for flaky tests. On the other, three times seems a bit much. If you merge, please keep a close eye on the nightlies.

**Comment by oliveralka** [comment]
rebuild jenkins

**Pull request merged**
