### PR TITLE
Test: Sirius Tests Jenkins

### PR DESCRIPTION
**Pull request by oliveralka**
# Description

Some of the SIRIUS tests are not running on Jenkins due to either THIRDPARTY or test configuration
http://cdash.openms.de/viewTest.php?onlyfailed&buildid=121031

# Checklist:
- [X] Make sure that you are listed in the AUTHORS file
- [X] Add relevant changes and new features to the CHANGELOG file
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] New and existing unit tests pass locally with my changes
- [X] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

### CODE REVIEW

**Comment by oliveralka** [comment]
Currently testing with:
https://github.com/OpenMS/THIRDPARTY/tree/fix/sirius_binary_462

**Comment by oliveralka** [comment]
Discrepancy:
Linux: http://cdash.openms.de/viewTest.php?onlyfailed&buildid=121634 3 fails 
MacOS: http://cdash.openms.de/viewTest.php?onlyfailed&buildid=121625 1 fail
Win: http://cdash.openms.de/viewTest.php?buildid=121640 all passed

Locally MacOS works without any issues.

**Comment by jpfeuffer** [comment]
The SiriusAdapter1 issue seems something worse.

**Comment by jpfeuffer** [comment]
Just go to abibuilder1 and check

**Comment by jpfeuffer** [comment]
You can disable it for further builds

**Comment by oliveralka** [comment]
There is no output generated for SiriusAdapter1, but also only on the unix machines.

**Comment by oliveralka** [comment]
Seems to work with the changes to THIRDPARTY (binary location/start scripts) and the whitelisting of mass 522 for SiriusAdapter 9 & 10 (due to differences in rank):

Linux: http://cdash.openms.de/viewTest.php?buildid=121748&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=Sirius
MacOs: http://cdash.openms.de/viewTest.php?buildid=121739&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=Sirius
Win: http://cdash.openms.de/viewTest.php?buildid=121766&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=SiriusAdapter

I would still keep an eye on `SiriusAdapter_1` just in case.

**Pull request merged**
