### PR TITLE
[FIX] force repaint after update_ was called

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@jpfeuffer can you test on Mac? Only tested on linux

**Comment by timosachsenberg** [comment]
log stream failed

**Comment by jpfeuffer** [comment]
works flawlessly

**Comment by hroest** [comment]
:+1: great - I think I may have removed that update at some point when trying to fix a bug on Linux. I will test again later today

**Comment by hroest** [comment]
:+1: can confirm on Linux, works very well

**Pull request merged**
