### PR TITLE
fix name clash of FeatureFinderIdentification test

### PR DESCRIPTION
**Pull request by bernt-matthias**
in particular the clash of the output name is nasty for the autogenerated Galay tests

# Description

Please include a summary of the change and which issue is fixed.

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Thanks!

**Review by timosachsenberg — APPROVED** [review]

**Comment by timosachsenberg** [comment]
http://cdash.openms.de/viewTest.php?onlyfailed&buildid=61277

**Comment by bernt-matthias** [comment]
Not entirely sure why this fails .. and what :) .. 

I guess before one of the two tests called `TOPP_FeatureFinderIdentification_4` was not executed .. and now it is and fails. Do I need to update/add the test data, e.g. replace FeatureFinderIdentification_1_output.featureXML with FeatureFinderIdentification_2_output.featureXML (which I would need to add).

?

**Comment by timosachsenberg** [comment]
I can take a look at it later

**Comment by timosachsenberg** [comment]
superseded by https://github.com/OpenMS/OpenMS/pull/5003

**Pull request closed without merging**
