### PR TITLE
Fix python_versions read in

### PR DESCRIPTION
**Pull request by matteopilz**
## Description
This is not done, but I would need some help. I have tested the read in with a separate action and it works for windows, macos and ubuntu. I also think reading in works now in the pyopenms-wheels action, but I get new errors. It would be great if someone could look into it, because I don't know what they mean.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
What are the errors? Where did you test it, so we could check?

**Comment by matteopilz** [comment]
You can see the error messages here:
https://github.com/matteopilz/OpenMS/actions/runs/4414417772

I have tested reading it in inside my own repository with a separate action, which I have already deleted. If necessary, I can push it back in.

**Comment by jpfeuffer** [comment]
`sudo: command not found` means there is no sudo on the container.

```
environment 'XYZ.xyz
.' could not be created.
```

means you are not following the naming scheme for conda environments.

I fixed it on your branch

**Comment by jpfeuffer** [comment]
I think in the new test jobs (*not steps*)  you have a fresh workspace. I would wget the file or do a very shallow clone only for the .GitHub folder instead of cloning the whole repo again.

**Comment by jpfeuffer** [comment]
Aaah or it was checked out in another location, yes.

**Comment by matteopilz** [comment]
I think it works now https://github.com/matteopilz/OpenMS/actions/runs/4434062988/jobs/7781208635

**Review by jpfeuffer — APPROVED** [review]
Thanks. Will merge for now. Please keep an eye on its success/failure!

**Pull request merged**
