### PR TITLE
[FIX, FEATURE] some code refactoring and small fixes

### PR DESCRIPTION
**Pull request by timosachsenberg**
- moved some code from FFM tool to algorithm
- FIX: update meta value "map_index" if consensus maps are appended
- more verbose import of experimental design from consensus map

### CODE REVIEW

**Comment by lars20070** [comment]
Do we still require unique IDs for the features?
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderMultiplexAlgorithm.cpp#L749

**Comment by timosachsenberg** [comment]
How to test that? Tests passed...

**Comment by lars20070** [comment]
IMO, `unique_id` can be optional.

Hence, +1 for merge.

**Comment by lars20070** [comment]
I think `-test` takes care of the unique ids, i.e. we get the same, identical ID every time the tool is run.

**Pull request merged**
