### PR TITLE
Fix/consensus map id map index order

### PR DESCRIPTION
**Pull request by timosachsenberg**
potentially fixes some of the occasionally occurring

```
in1:  C:\dev\NIGHTLY\builds\masterwin8-VS12_x86-Debug\src\tests\topp\FeatureLinkerUnlabeledQT_6_output.tmp   (line: 92, position/column: 50/79)
				<UserParam type="int" name="map_index" value="!
				                                              2"/>

in2:  C:\dev\NIGHTLY\OpenMS-master\src\tests\topp\FeatureLinkerUnlabeledQT_6_output.consensusXML   (line: 92, position/column: 50/79)
				<UserParam type="int" name="map_index" value="!
				                                              0"/>
```

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Ah that's great. First lambda, also.
What was the consensus on one-line ifs (codacy)?

**Comment by timosachsenberg** [comment]
ah yeah that is old code. a block of {} should be put around them

**Comment by jpfeuffer** [comment]
#1584 solves a part of this, too. Important for Windows CI also.

**Comment by timosachsenberg** [comment]
hmm did this PR trigger
http://cdash.openms.de/viewBuildError.php?buildid=229739
or are these a result of the c11 merge?

**Comment by hroest** [comment]
please also merge this PR: https://github.com/timosachsenberg/OpenMS/pull/9

this adds the sorting to the FeatureLinker

**Pull request merged**
