### PR TITLE
Cstd ptrs

### PR DESCRIPTION
**Pull request by poshul**
Replaces boost::shared_ptr with std::shared_ptr.

### CODE REVIEW

**Comment by poshul** [comment]
This fails to build on win10_64. Can someone with a Windows machine take a look at it and see what the error is?

**Comment by jpfeuffer** [comment]
You can usually see the errors on our CDash:
http://cdash.openms.de/index.php?project=OpenMS&date=2019-10-17
Look for the day and number of your PR (I found it for you already in the link)

**Comment by jpfeuffer** [comment]
Unfortunately this also seems to affect the python bindings:
https://abibuilder.informatik.uni-tuebingen.de/jenkins/job/openms_pr_docker_pyopenms/1963/console
The cython compilation is not yet shown on CDash. Only the failing py tests.

**Comment by poshul** [comment]
> Unfortunately this also seems to affect the python bindings:
> https://abibuilder.informatik.uni-tuebingen.de/jenkins/job/openms_pr_docker_pyopenms/1963/console
> The cython compilation is not yet shown on CDash. Only the failing py tests.
> 
> Let me know if you have access to the logs there (should be if you are a OpenMS team member on GitHub)

Thanks, I found the logs. I'm working on the pyOpenMS issues.

**Comment by hroest** [comment]
@poshul boost::shared_ptr is tied very strongly to the autowrap code, you may want to create a toy example first and play around with autowrap to make sure that you can get it to work on a small toy examples

**Comment by poshul** [comment]
With a lot of help from @hroest PyOpenMS compiles and passes all its tests, but only with https://github.com/poshul/autowrap/tree/cstd_ptrs.

**Comment by hroest** [comment]
overall looks good, I suggest we merge the autowrap code first. Probably a few things that need to be parametrized, e.g. C++11 compiler option

**Comment by hroest** [comment]
> With a lot of help from @hroest PyOpenMS compiles and passes all its tests, but only with https://github.com/poshul/autowrap/tree/cstd_ptrs.

@poshul can you open a PR for this?

**Comment by timosachsenberg** [comment]
will try to add this to my C17 update

**Pull request closed without merging**
