### PR TITLE
[FEATURE ] qt5

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
rebuild win

**Comment by jpfeuffer** [comment]
rebuild win

**Comment by hroest** [comment]
jenkins still looks for the old qt, I dont quite understand why?

http://cdash.openms.de/viewConfigure.php?buildid=255166
http://cdash.openms.de/viewConfigure.php?buildid=255165
```
CMake Error at /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "5.10.0" from /usr/local/opt/qt/bin/qmake, this
  code requires Qt 4.x
Call Stack (most recent call first):
  src/openms/cmake_findExternalLibs.cmake:150 (find_package)
  src/openms/CMakeLists.txt:63 (include)
```

and

```
CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindQt4.cmake:1318 (message):
  Found unsuitable Qt version "5.10.0" from
  C:/dev/Qt5/5.10.0/msvc2017_64/bin/qmake, this code requires Qt 4.x
Call Stack (most recent call first):
```

**Comment by jpfeuffer** [comment]
We both had a number twister ;) I restarted 3169 and it showed up in CDash. But this one is 3196.

There are some errors on Mac now. And some issues with the Path to DLLs for TOPPDocumenter on Win (I have a clue why).

**Comment by jpfeuffer** [comment]
rebuild win

**Comment by hroest** [comment]
looks like its mostly working now, only 6 tests fail. Could it be that the INIUpdater does not compile on OSX / Win?

**Comment by jpfeuffer** [comment]
From the test log on Mac:
`This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".`

**Comment by jpfeuffer** [comment]
So the bundling has to be adapted, as feared.

**Comment by jpfeuffer** [comment]
It only affects inifileeditor. It seems to have a dependency on the qt Plugins for the native ui. Someone knows why? TOPPView e.g. does not and works fine.

**Comment by jpfeuffer** [comment]
I would prefer getting rid of the dependency if possible. Cmake does not seem to ship a Deployqt5 module.

**Comment by timosachsenberg** [comment]
just an idea: 
here we disable the loading of plugins (as suggested on stackoverflow)
https://github.com/OpenMS/OpenMS/blob/develop/src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/INIFileEditor.cpp#L78

Here we set native styles for different platforms which *might* require loading the cocoa plugin
https://github.com/OpenMS/OpenMS/blob/develop/src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/INIFileEditor.cpp#L140

we could just not set the native styles on mac?

**Comment by jpfeuffer** [comment]
Good idea! Maybe we can disable it on any platform and use an independent style?

**Comment by timosachsenberg** [comment]
@philthiel how do you deploy ball on mac? seems you use deployqt?

**Comment by timosachsenberg** [comment]
rebuild mac

**Comment by timosachsenberg** [comment]
Not sure if this trigger exists ;)

**Comment by jpfeuffer** [comment]
Haha rebuild win triggers both right now.

**Comment by hroest** [comment]
haha, now Windows worked (but still not OSX)

**Comment by hroest** [comment]
http://cdash.openms.de/viewConfigure.php?buildid=255475

```
CMake Error at /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find WM5 (missing: WM5_INCLUDE_DIR WM5_Wm5Core_LIBRARY
  WM5_Wm5Mathematics_LIBRARY)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindWM5.cmake:70 (find_package_handle_standard_args)
  src/openms/cmake_findExternalLibs.cmake:114 (find_package)
  src/openms/CMakeLists.txt:63 (include)
```

**Comment by jpfeuffer** [comment]
rebuild win

**Comment by hroest** [comment]
rebuild win

**Comment by hroest** [comment]
looks like Windows worked: http://cdash.openms.de/buildSummary.php?buildid=255585

```
Test (2126 passed, 0 failed, 0 not run) 
```

**Comment by jpfeuffer** [comment]
I removed all the QT Style plugin stuff. It is done in QTOPPApplication anyway. Works on my Mac now.

**Comment by timosachsenberg** [comment]
what about disabling the search for libraries? you also removed that one?

**Comment by jpfeuffer** [comment]
Hmm yes. I will try with it again.

**Comment by jpfeuffer** [comment]
Wait. Tests still fail anyway. The Gui opens now, though.

**Comment by jpfeuffer** [comment]
I think I found something . Will push after some further tests.

**Comment by jpfeuffer** [comment]
Well.... as expected packaging is broken, too.

**Comment by jpfeuffer** [comment]
Changes worked.

**Comment by hroest** [comment]
great, looks like only CruxAdapter fails now (unrelated failure).

**Comment by timosachsenberg** [comment]
So how should we proceed? I think we will need fixes to do the packages / create nightly installers.

**Comment by hroest** [comment]
So where is our testing at? Did we for example do any of the tutorials / basic workflows? I think we should at least test doing some basic stuff in TOPPView and running basic workflows in TOPPAS on at least one platform. How is testing for 

- TOPPAS
- TOPPView
- ?

Also, I suggest to give people at least 1 week advance notice before merging anything. E.g after we write to the mailing list, set a deadline of at least 1 week so if somebody finds a blocker, they had time to do so. What is your estimate on how many people have now built and worked with this branch?

**Comment by hroest** [comment]
PS: has anybody tried to work with TOPPAS? I am getting segmentation faults left and right when even trying to open a workflow or dragging a node onto the canvas:

```
QGraphicsView::dragLeaveEvent: drag leave received before drag enter
Segmentation fault (core dumped)
```

so no, I dont think we are really ready for a merge.

**Comment by timosachsenberg** [comment]
I think there was some basic testing done in TOPPView and TOPPAS, apparently not enough. Maybe some of this errors affect certain platforms only. BTW Warning email was already sent to the mailing list and afaik only the contributors to this branch worked with it.
While this is not ideal, with a merge we certainly would get more testers of the build scripts and the actual library. Also means faster feedback and more reported issues. But I agree that everyone should give it another try to determine the obvious blockers.

**Comment by timosachsenberg** [comment]
I created the QT5 label. Please use it to add issues.

**Comment by hroest** [comment]
looking at https://github.com/OpenMS/OpenMS/labels/QT5 we need some more work but we are on the way. I think we need to figure out some big ticket items, e.g. drop support for a full tool such as IDEvaluator

**Comment by jpfeuffer** [comment]
I probably fixed the IDEvaluator issue. But Windows packaging and KNIME packaging is still missing.

**Comment by timosachsenberg** [comment]
```
Offending lines:			(tab_width = 8, first_column = 1)

in1:  C:\jenkins\ws\openms_pr_ci\979a8a2f\source\src\tests\topp\OpenSwathFeatureXMLToTSV_output.long.csv   (line: 2, position/column: 360/531)
tr_gr1_run0	0	testfile.file	3119.09196821988	f_11965988948540676971	PEPTIDEA	NA	NA	500	3574.23		0	3118.65196821988	3096.28002929688	-21994.8526298809	2	3147.67993164062	3118.65196821988	86.0041379995282	3680.16062933207	0.985403060913086	0.971216417399615	1	0.108663236021716	4.45439541136954	3118.65196821988	0	0	0.998183460545928	0.997577947394571	803.023010!
           	 	             	                	                      	        	  	  	   	       		 	                	                	                 	 	                	                	                	                	                 	                 	 	                 	                	                	 	 	                 	                 	          	NA	tr1	628.435000

in2:  C:\jenkins\ws\openms_pr_ci\979a8a2f\build\src\tests\topp\OpenSwathFeatureXMLToTSV_output.long.csv.tmp   (line: 2, position/column: 353/524)
tr_gr1_run0	0	testfile.file	3119.09196821988	f_11965988948540676971	PEPTIDEA	NA	NA	500	3574.23		0	3118.65196821988	3096.28002929688	-21994.8526298809	2	3147.67993164062	3118.65196821988	86.0041379995282	3680.16062933207	0.985403060913086	0.971216417399615	1	0.108663236021716	4.45439541136954	3118.65196821988	0	0	0.998183460545928	0.997577947394571	803!
           	 	             	                	                      	        	  	  	   	       		 	                	                	                 	 	                	                	                	                	                 	                 	 	                 	                	                	 	 	                 	                 	   ,023010	NA	tr1	628,435000
```

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/edit/feature/qt5/src/topp/OpenSwathFeatureXMLToTSV.cpp still has sprintf

**Comment by hroest** [comment]
@timosachsenberg another approach would be to merge #3253 into qt5

**Comment by hroest** [comment]
great, now all tests pass again! Thanks @timosachsenberg

**Comment by hroest** [comment]
@timosachsenberg @jpfeuffer should we maybe send out an email to inform the developers that they have to rebuild their OpenMS ?

**Comment by jpfeuffer** [comment]
Sure. Just did. Thanks. Feel free to add infos.

**Pull request merged**
