### PR TITLE
[TEST] openms-ci THIRDPARTY tests

### PR DESCRIPTION
**Pull request by oliveralka**
# Description

Check if THIRDPARTY tests work in openms-ci github actions and how much longer the runtime is.

Part of #5223

Current runtime without THIRDPARTY test integration:
Windows 3h 27m
MacOS 60 min
Linux 59 min

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

### CODE REVIEW

**Comment by oliveralka** [comment]
@jpfeuffer Is it not enough to add the `SEARCH_ENGINES_DIRECTORY` to cmake to allow for automated THIRDPARTY testing?

**Comment by jpfeuffer** [comment]
No, this is only for packaging. For testing it needs to be in the PATH.
I find it confusing, too but people were against a change: https://github.com/OpenMS/OpenMS/issues/1775

**Comment by oliveralka** [comment]
Seems to work! PS: I guess I will remove OMSSA.

**Comment by oliveralka** [comment]
Runtime without THIRDPARTY (n tests: 2490):
e.g. https://github.com/OpenMS/OpenMS/actions/runs/917794107
Windows 3h 11min
MacOS 60 min
Linux 48 min

Runtime with THIRDPARTY (n tests: 2582): 
e.g. https://github.com/OpenMS/OpenMS/actions/runs/922138786
Windows 3h 15min
MacOS 53 min
Linux 1h 2 min

The difference does not seem to be too substantial (it also seems that there is some fluctuation up to around 15 minutes in general)

**Review by jpfeuffer — APPROVED** [review]
Looks good!

**Pull request merged**
