### PR TITLE
added annotate_features param in Deisotoper.cpp

### PR DESCRIPTION
**Pull request by anamaria-uofg**
## Description

As discussed: added bool annotate_features param

if (annotate_features)
{
    spec.getIntegerDataArrays().back().setName("feature_number");
    feature_number_dataarray_index = spec.getIntegerDataArrays().size() - 1;
    spec.getIntegerDataArrays()[feature_number_dataarray_index].swap(features);
}

## Checklist
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

___

### **PR Type**
enhancement

___

### **Description**
- Introduced a new boolean parameter `annotate_features` in the `deisotopeAndSingleCharge` method of `Deisotoper.cpp`.
- Implemented feature annotation logic that updates the integer data arrays with "feature_number" when `annotate_features` is enabled.
- Enhanced the functionality of the Deisotoper to support feature annotation, improving data analysis capabilities.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Deisotoper.cpp</strong><dd><code>Add feature annotation capability in Deisotoper</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/openms/source/PROCESSING/DEISOTOPING/Deisotoper.cpp

<li>Added a new parameter <code>annotate_features</code> to the <br><code>deisotopeAndSingleCharge</code> function.<br> <li> Implemented logic to annotate features when <code>annotate_features</code> is true.<br> <li> Modified integer data arrays to include a "feature_number" when <br>annotating features.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7643/files#diff-018abc91249a75e74035b0f0f187ee3f15a5b6a3d1b9d975011d4f0224d46087">+7/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by timosachsenberg** [comment]
I made some quick changes. Let's see if tests pass. Some might need an update.

**Comment by timosachsenberg** [comment]
@OpenMS/doc-team can someone double check that this doesn't break our pyopenms doc?

**Comment by matteopilz** [comment]
I would like to test the pyopenms readthedocs with this, could you enable actions in your repository and let the pyopenms wheels action run?

**Comment by poshul** [comment]
I've created a copy of this branch in our repo and am running the wheels build here: https://github.com/OpenMS/OpenMS/actions/runs/11740078641

**Review by matteopilz — APPROVED** [review]
Looks like it is not breaking anything with our docs.

**Review by poshul — APPROVED** [review]

**Pull request merged**
