### PR TITLE
[FIX] specify memory allocated by VM

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
should fix https://github.com/OpenMS/OpenMS/issues/2212

**Comment by timosachsenberg** [comment]
I basically just used the convention from MSGFPlus adapter.
Maybe @hendrikweisser knows if using the default of the VM is more appropriate.

**Comment by hendrikweisser** [comment]
> Maybe @hendrikweisser knows if using the default of the VM is more appropriate.Maybe @hendrikweisser knows if using the default of the VM is more appropriate.

3500 MB was the default used for MS-GF+, which we took from the corresponding documentation. As it seems that LuciPHOr doesn't specify a default, I think Chris' suggestion of using zero as the default - in which case the parameter isn't passed to the JVM - makes sense to me.

**Comment by timosachsenberg** [comment]
hmm ok I can do that ... on the other hand, the default created the problem for the user on the user meeting. Would it hurt to just take the same default as MSGFPlus and make this kind of or minimal requirement for java based program (still tweakable by overwriting the parameter)

**Comment by hendrikweisser** [comment]
> Would it hurt to just take the same default as MSGFPlus and make this kind of or minimal requirement for java based program (still tweakable by overwriting the parameter)

How do we know that 3500 is actually a useful default for LuciPHOr?
But you could argue either way, so I'm fine with whichever default you choose.

**Comment by timosachsenberg** [comment]
ok let's try 3500 first and see if we still run into the problem of a too small heap space

**Comment by timosachsenberg** [comment]
I think there no additional comments and we agreed on how we handle this now -  so I merge

**Pull request merged**
