### PR TITLE
Fix plotting.py for existing annotations from SpectrumAnnotator

### PR DESCRIPTION
**Pull request by jpfeuffer**
## Description

Before, it raised exceptions, and after fixing it didn't color.
Now, matched peaks take precendence but already present annotations can still be plotted.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by matteopilz** [comment]
Coloring ions works, but coloring matching peaks doesn't.

**Comment by jpfeuffer** [comment]
The question is how this is supposed to be used.
What is a matching peak for you? How do you give it to the function?
Why would you need matching peaks in a non-mirrored plot? Where do you want to put/plot them? You can just annotated in the meta arrays if a peak was matched.

My use case is to have an annotated spectrum. I don't need matching peaks for this. The peaks are already in the spectrum. I only want to plot this one spectrum with colors if a peak is annotated as a fragment ion in their string data array.

**Comment by matteopilz** [comment]
It's more about mirror plots. I tried to reproduce the output of the example we have in our documentation: https://pyopenms.readthedocs.io/en/latest/user_guide/spectrum_alignment.html

Right now it will not color matching peaks, but only ions.
I don't know if we need this feature at all, but otherwise, what would we need mirror plots then for?

**Comment by jpfeuffer** [comment]
I think both mirror plots and single plots with colored peaks according to an internal annotation should be supported.

**Comment by matteopilz** [comment]
Doesn't this mean we have to change what `getSpectrumAlignment` returns?

**Comment by jpfeuffer** [comment]
No, we have a class spectrum annotator that does everything at once and
just writes the annotations into the original spectrum. I would like both
ways to work.

Matteo Pilz ***@***.***> schrieb am Mi., 22. Nov. 2023, 14:05:

**Review by matteopilz — APPROVED** [review]

**Comment by matteopilz** [comment]
It's probably best to merge this, I will look into implementing the spectrum annotator compatibility.

**Comment by jpfeuffer** [comment]
I don't think we should merge it if it does not reproduce our documentation examples, no?

**Comment by matteopilz** [comment]
I can either look into extending this PR to fix that or make a new one, I don't know what would be better.

**Comment by jpfeuffer** [comment]
I think you should have rights to push to my branch here on the OpenMS repo. Therefore you can just extend this PR.

**Comment by matteopilz** [comment]
It looks like I'm lacking the permission.

**Comment by jpfeuffer** [comment]
Ah weird. Then you can just open another PR if you want.

**Comment by timosachsenberg** [comment]
@matteopilz is this superseded?

**Comment by matteopilz** [comment]
It should be.

**Pull request closed without merging**
