### PR TITLE
Use macos-13 runner as it's the last x86 mac one

### PR DESCRIPTION
**Pull request by poshul**
## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

___

### **PR Type**
enhancement

___

### **Description**
- The PR updates the GitHub Actions workflow file `.github/workflows/pyopenms-wheels.yml` to use `macos-13` instead of `macos-latest` for building macOS wheels. This change affects both the `build-macos` job and the matrix strategy for operating systems.
- This update ensures compatibility with the last x86 macOS version available, following the deprecation of older versions.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pyopenms-wheels.yml</strong><dd><code>Update macOS Runner Version to macos-13 in GitHub Actions Workflow</code></dd></summary>
<hr>

.github/workflows/pyopenms-wheels.yml
<li>Updated the macOS runner version from <code>macos-latest</code> to <code>macos-13</code> in the <br><code>build-macos</code> job.<br> <li> Updated the macOS version in the matrix strategy from <code>macos-latest</code> to <br><code>macos-13</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7485/files#diff-084f20ae9727db0905c5fbbc32ef797e048c87887ccfc57b0f89b2bf82f45979">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by timosachsenberg** [comment]
looks legit...

**Comment by jpfeuffer** [comment]
We should start thinking about a deprecation strategy for macOS Intel. Support as long as GHA does? Otherwise we should start thinking about how to build universal binaries/libs.

**Comment by poshul** [comment]
> We should start thinking about a deprecation strategy for macOS Intel. Support as long as GHA does? Otherwise we should start thinking about how to build universal binaries/libs.

I think that's reasonable.

**Review by timosachsenberg — APPROVED** [review]

**Review by jpfeuffer — COMMENTED** [review]
Only the current version, MacOS 14 seems to be very strict. Is there a reason for that?
Even 12 is still supported.
https://endoflife.date/macos

**Comment by poshul** [comment]
> Only the current version, MacOS 14 seems to be very strict. Is there a reason for that? Even 12 is still supported. https://endoflife.date/macos

I hadn't realized that ARM was supported on 12 and 13. I've relaxed it now.

**Comment by poshul** [comment]
I guess the idea of a major OS release every 12 months is so foreign to me.

**Pull request merged**
