### PR TITLE
Update MatrixUtils.h with correct(?) eigen include path

### PR DESCRIPTION
**Pull request by timosachsenberg**
## Description

was reported inother projects and resolved by adding eigen3 to the include path: https://github.com/opencv/opencv/issues/14868

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Where was this failing? Here on GHA? Have not seen it before.
It's probably again a difference in how different package managers install eigen headers. In a subfolder or not.
You might need to handle it in CMake to make it work across multiple pkgmanagers/contrib, like we did for coinor.

Why do other occurrences work then?
https://github.com/OpenMS/OpenMS/blob/26b6bfa84993a9db05f131a809a42b70cbb49c8c/src/openms/source/FILTERING/SMOOTHING/SavitzkyGolayFilter.cpp#L12

**Comment by timosachsenberg** [comment]
I think this happened because of the update of eigen in the contrib and switch to eigen from package manager.
It also failed on my PC and was resolved with the fix in this PR.
My CMakeCache points to the package:
```
Eigen3_DIR:PATH=/usr/lib/cmake/eigen3
```
and in Eigen3Targets.cmake
```
set_target_properties(Eigen3::Eigen PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/eigen3"
)
```
So I am not sure how to debug this...
I would say we merge and see if something else breaks ;)

**Comment by timosachsenberg** [comment]
this is the other change that happened in contrib. https://github.com/OpenMS/contrib/commit/554551862ed1000e6b074d35cb887943e81f8606 nothing obvious to me

**Comment by timosachsenberg** [comment]
ah forget it... might be that the branch was not updated? will merge develop into it first

**Comment by timosachsenberg** [comment]
hmm unfortunately failed again on GitHub actions even after the branch was updated see https://github.com/OpenMS/OpenMS/pull/7298
could this be caching related?

**Comment by jpfeuffer** [comment]
Hmm not sure. You can also delete caches in the UI to test.
But TBH it feels like Eigen/Core is the correct way to include. Everything else should be handled by CMake.

**Pull request merged**
