### PR TITLE
fix silent conversion of incomplete strings

### PR DESCRIPTION
**Pull request by cbielow**
we currently use Boost's qi::phrase_parse
to convert a string to any other type (usually double, float or int).

However, passing a string with trailing characters, e.g., "1.2   3.4" would lead to successful conversion,
to 1.2, but does not throw an error.
**This is bad!**

Imagine the following command:
`Filefilter -in infile.mzML  -peak_options:level "1 2" -out outfile.mzML`

MS-level 2 would be removed, without the user even noticing (you can make up more complicated cases ofc).

With this PR, the above command will fail with:
`Invalid parameter values: Prefix of string '1 2' successfully converted to an integer value. Additional characters found at position 3. Aborting!`

This allows to correct the above command to (removing quotes):
` ....   -peak_options:level 1 2  ... `

### CODE REVIEW

**Comment by hroest** [comment]
:+1: makes a lot of sense

**Comment by hroest** [comment]
however it seems like 9 tests fail: http://cdash.openms.de/viewTest.php?onlyfailed&buildid=165385

It seems some tests use/rely on the old behavior and convert double to integers and other crazy things...

**Comment by cbielow** [comment]
I'm in the process of fixing it, but I keep encountering errors in boost, i.e.
https://svn.boost.org/trac/boost/ticket/6955
It's 4 years old (1.49) and is still in our contrib (1.52). Fixed in Boost 1.60 (or earlier?), but that does not help. I'm currently trying to work around it....

**Comment by cbielow** [comment]
Checks passed. Any additional thoughts?

**Comment by timosachsenberg** [comment]
+1

**Comment by timosachsenberg** [comment]
maybe we can add / create a label "revisit" to mark an issue or PR to be revisited from time to time. This would allow removing workarounds in the future

**Pull request merged**
