### PR TITLE
[pyopenms] FAIMS bindings / wrapping of rvalue references

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Please include a summary of the change and which issue is fixed.

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@jpfeuffer probably can't use the move here as we do in c++

**Comment by timosachsenberg** [comment]
pyopenms/pyopenms_1.cpp:24660:58: error: cannot bind rvalue reference of type 'OpenMS::PeakMap&& {aka OpenMS::MSExperiment&&}' to lvalue of type 'boost::shared_ptr<OpenMS::MSExperiment>::element_type {aka OpenMS::MSExperiment}'
     __pyx_t_2 = OpenMS::MSRunIMSplitter::splitByFAIMSCV((*__pyx_v_exp->inst.get()));
                                                         ~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from pyopenms/pyopenms_1.cpp:662:0:
/home/jenkins/ws/openms/PR/pyOMSDckr/OpenMS/src/openms/include/OpenMS/IONMOBILITY/MSRunIMSplitter.h:65:35: note:   initializing argument 1 of 'static std::vector<OpenMS::MSExperiment> OpenMS::MSRunIMSplitter::splitByFAIMSCV(OpenMS::PeakMap&&)'
       static std::vector<PeakMap> splitByFAIMSCV(PeakMap&& exp);

**Comment by jpfeuffer** [comment]
I think the contents of the returned vector elements can be moved one by one to elements in a python list. But this is not implemented. See my PR, where this is done for input lists.

**Comment by jpfeuffer** [comment]
Ah but not by rvalue

**Comment by jpfeuffer** [comment]
I guess you could implement something that allows a move. But what do you do with the invalidated python object?

**Comment by jpfeuffer** [comment]
No, you have to change the C++ code.
You need an overload that accepts references and does the move internally.

**Comment by timosachsenberg** [comment]
My impression was that the copy should work

**Comment by timosachsenberg** [comment]
@hroest I thought it already just worked by wrapping it without reference (or normal reference?) in the pxd?

**Comment by timosachsenberg** [comment]
k I close this one. we might need some c++ wrappers though in the future to make it usable in pyOpenMS

**Pull request closed without merging**
