### PR TITLE
Fast TraML reading

### PR DESCRIPTION
**Pull request by hroest**
- substantially improves the TraML Handler in memory efficiency and speed
- introduces new CVTermListInterface that is less memory intensive as it simply stores a pointer to its data structure (similar to MetaInfoInterface)
- explicitly stores `<Interpretation>` in TraML and maps the OBO terms to ion types
- explicitly stores product ion m/z
- explicitly stores unimod identifiers for modifications in TraML

on a blood plasma library by Liu et al (http://proteomecentral.proteomexchange.org/cgi/GetDataset?ID=PXD001064 ) of 898590 KB, the `ConvertTSVToTraML` tool now only takes 2:11 minutes to convert and utilizes 940.35 MB of memory. The same tool of Release 2.0 uses 4:01 minutes and utilizes 5760.74 MB of memory. This amounts to a 6-fold reduction in memory footprint and 2-fold reduction in execution time.

### CODE REVIEW

**Comment by hroest** [comment]
@grosenberger this makes some changes to the MRMIonseries and other classes, could you have a look? I think by explicitly coding the ion types, the code is easier to read and maintain, what do you think?

**Comment by grosenberger** [comment]
The performance improvements are also propagated to OpenSwathAssayGenerator and OpenSwathDecoyGenerator. The speed improvements on my (medium sized) test file is ~25%.

Great work! 👍

**Comment by hroest** [comment]
I added a few more commits that also deals with  the transition type. @grosenberger has already reviewed the additional patches and the PR should now be ready to go!

**Comment by grosenberger** [comment]
I checked the latest commits and this further improves speed and memory requirements. Thanks, @hroest 👍

**Comment by timosachsenberg** [comment]
+1

**Comment by hroest** [comment]
@grosenberger @timosachsenberg 
PS: On a medium sized TraML of about 800 MB, I see substantial improvements in execution time

# OpenSwathDecoyGenerator took 43:11 m (wall), 42:35 m (CPU), 0.00 s (system), 42:35 m (user).
# OpenSwathDecoyGenerator took 13:02 m (wall), 12:22 m (CPU), 0.00 s (system), 12:22 m (user).

so these patches make the it makes it about 3x faster!

**Pull request merged**
