### PR TITLE
pyopenms-nightly - change date format

### PR DESCRIPTION
**Pull request by oliveralka**
@jpfeuffer is there an easy way to test the CMake syntax locally?

### CODE REVIEW

**Comment by jpfeuffer** [comment]
In theory you just have to configure the project with -DPYOPENMS=ON after configuration you will see in the setup file if it is correct.

**Comment by jpfeuffer** [comment]
But looks good

**Comment by oliveralka** [comment]
Representation of the initial format looked different:

yyyy-mm-dd 08:04:17 +0200

Corrected - now it should work as expected in the nightlies.

**Comment by jpfeuffer** [comment]
Great. I assume you could test it locally now?

**Comment by oliveralka** [comment]
Yes, tested it locally - thanks for the hint ;)

**Pull request merged**
