### PR TITLE
[FEATURE] createTransition_() adds the metavalue LabelType to the transition

### PR DESCRIPTION
**Pull request by pasqoo**
Would you recommend a different way to add the `LabelType` information to a transition?
I went for a metavalue.

### CODE REVIEW

**Comment by pasqoo** [comment]
Some CIs crashed, but TOPP tests data files need to be updated.
I'll do it once it's confirmed that using the `MetaInfoInterface` is the way to go for `LabelType`.

**Comment by hroest** [comment]
this is already added to the peptide/compound - is there a need to add it to the transition as well?

**Comment by pasqoo** [comment]
I tried fetching the info from the peptides, but I couldn't find a way to "locate" the correct peptide, given a `transition_name` from the traml.csv file (we briefly discussed this in February, on Gitter).

**Comment by hroest** [comment]
> I tried fetching the info from the peptides, but I couldn't find a way to "locate" the correct peptide, given a `transition_name` from the traml.csv file (we briefly discussed this in February, on Gitter).

I suggest to do 
```
auto pep = exp.getPeptideByRef(transition.getPeptideRef())
```

**Pull request closed without merging**
