### PR TITLE
[FEATURE] export from mzID

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by hroest** [comment]
sure. can you add a test?

**Comment by timosachsenberg** [comment]
The mzTab Exporter part is (most likely) correct and the resulting mzTab most likely missing information because these are not carried over by the mzIdentML parser. I actually wanted to create a simple test but I already got a segmentation fault on parsing one of our example mzIDs. Mathias tracked it down to https://github.com/OpenMS/OpenMS/issues/1699 and will prepare a fix. So I think we should wait for this and include this PR later with a test that at least tests for export of some basic mzIdentML information.

**Comment by hroest** [comment]
agreed, lets do that

**Comment by mwalzer** [comment]
https://github.com/OpenMS/OpenMS/commit/2b7391dbd0d6a0636ca83d0174bc592119f3d5f5

**Pull request merged**
