### PR TITLE
Categorize branch

### PR DESCRIPTION
**Pull request by timosachsenberg**
## Description

a colleague found out that quite some nodes are “uncategorized” now, see screenshot.
In his log is the following (spacing issue?):
ERROR RepositoryManager Category 'Merging' from plugin 'de.openms' could not be created in parent path '/community/OpenMS/File Filtering / Extraction/'.

image (2)

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

___

### **PR Type**
enhancement

___

### **Description**
- Enabled multiple tools by setting their third parameter to `true`, allowing them to be recognized as official tools.
- Improved comments and ensured alphabetical order in `ToolHandler.cpp` for better maintenance.
- Updated descriptions for several tools to enhance clarity and comprehensiveness.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>11 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>ToolHandler.cpp</strong><dd><code>Improve tool handler comments and sorting</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/openms/source/APPLICATIONS/ToolHandler.cpp

<li>Updated comment for better clarity.<br> <li> Ensured alphabetical order for tool insertion.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7621/files#diff-34cb218563c65815d738fb6172d2ad775e8e190e565b4bc7eb78a0a04ffbb99c">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>OpenSwathWorkflow.cpp</strong><dd><code>Update OpenSwathWorkflow description</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/topp/OpenSwathWorkflow.cpp

- Changed workflow description to be more comprehensive.

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7621/files#diff-a3a2201361d0fa1b7f08d6e8a3789ff1513cac308c34029aad8435081eed34c6">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>QCCalculator.cpp</strong><dd><code>Enable QCCalculator tool</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/topp/QCCalculator.cpp

<li>Enabled the QCCalculator tool by setting the third parameter to true.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7621/files#diff-ec62f7d19805d2d34bfbbf36823dcb627ae6a1f9f3433b2826b0b550679d5dd9">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>QCExporter.cpp</strong><dd><code>Enable QCExporter tool</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/topp/QCExporter.cpp

<li>Enabled the QCExporter tool by setting the third parameter to true.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7621/files#diff-4232449e16b325875f78dc68644930c73cbfbc79370d4a7f0256e12962a88be9">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>QCExtractor.cpp</strong><dd><code>Enable QCExtractor tool</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/topp/QCExtractor.cpp

<li>Enabled the QCExtractor tool by setting the third parameter to true.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7621/files#diff-3048eb1b9c50ecd7ce542a55b59465170478234704d0271050df326711689baa">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>QCImporter.cpp</strong><dd><code>Enable QCImporter tool</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/topp/QCImporter.cpp

<li>Enabled the QCImporter tool by setting the third parameter to true.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7621/files#diff-c8b8d7772b19a5ed758c3ae90289fbffb36919a1b4d1f38e60921cda7faadf76">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>QCMerger.cpp</strong><dd><code>Enable QCMerger tool</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/topp/QCMerger.cpp

- Enabled the QCMerger tool by setting the third parameter to true.

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7621/files#diff-9b023dda8ed65dcd88bc86d3a4a54d30cf88660389d1979d242e7879643540cf">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>QCShrinker.cpp</strong><dd><code>Enable QCShrinker tool</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/topp/QCShrinker.cpp

<li>Enabled the QCShrinker tool by setting the third parameter to true.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7621/files#diff-3873f8974f303c965bb050e16ec661fdefb91a8326a3a6a5369e948a60293458">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>SimpleSearchEngine.cpp</strong><dd><code>Enable SimpleSearchEngine tool</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/topp/SimpleSearchEngine.cpp

<li>Enabled the SimpleSearchEngine tool by setting the third parameter to <br>true.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7621/files#diff-07e2e18eb360e6a7dff24c9728bc4bc939542b693ee841aedb6c6f4d705d0b26">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>SiriusExport.cpp</strong><dd><code>Enable SiriusExport tool</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/topp/SiriusExport.cpp

<li>Enabled the SiriusExport tool by setting the third parameter to true.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7621/files#diff-6a3b838e5a56f409eed6aa9d49046b98ee2adea5ec9bec7abad3a80d98a45e32">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>TICCalculator.cpp</strong><dd><code>Enable TICCalculator tool</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/topp/TICCalculator.cpp

<li>Enabled the TICCalculator tool by setting the third parameter to true.<br> <br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7621/files#diff-837c1fef55910e2a8ebab36db07092d5bf064ccb5eb1d496961d7c3cc29edfba">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@jpfeuffer any idea? I checked and the uncategorized ones have a category assigned in the ToolHandler

**Comment by jpfeuffer** [comment]
So it only affects non-official tools? We removed the utils/topp tool distinction right?
Probably because of this.

**Comment by timosachsenberg** [comment]
According to the image also others. Will generate ttd files and investigate

**Comment by jpfeuffer** [comment]
It looks like all the affected tools are in categories that now contain a slash.
Remember that a slash signals a category hierarchy in KNIME. And I think you have to "create" "subcategories" first before adding nodes under there.
But in this case the slash means something else anyway.

Maybe try ampersand or just the words "or" or "and"

**Comment by jpfeuffer** [comment]
@timosachsenberg 
E.g. https://github.com/OpenMS/OpenMS/blob/develop/src%2Fopenms%2Fsource%2FAPPLICATIONS%2FToolHandler.cpp#L38

**Pull request merged**
