### PR TITLE
Another FidoAdapter test fix

### PR DESCRIPTION
**Pull request by hendrikweisser**
I don't understand why this test didn't fail before, but in any case, it's fixed now.

### CODE REVIEW

**Comment by hendrikweisser** [comment]
I just realized there's a conflict with #1173.

**Comment by hendrikweisser** [comment]
> I don't understand why this test didn't fail before, but in any case, it's fixed now.

It didn't fail before because the date wasn't updated (in that particular case) before a recent change to FidoAdapter.

**Comment by hendrikweisser** [comment]
Should hopefully be good to go now.

**Comment by jpfeuffer** [comment]
+1

**Pull request merged**
