### PR TITLE
Replaced non-UTF8 beta in updated Unimod.xml

### PR DESCRIPTION
**Pull request by jpfeuffer**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Failure unrelated. Merge?
Important for KNIME builds and our HiWi.

**Comment by timosachsenberg** [comment]
+1

**Comment by hroest** [comment]
@timosachsenberg @jpfeuffer how come using a non-compatible xml does not trigger any of our tests? maybe having one that checks whether we can parse the file would be a good idea?

**Comment by jpfeuffer** [comment]
I am actually not sure where exactly this error occurred. I rechecked the travis and e.g. TOPPWRITEINI_XTandemAdapter passed with the non-compatible XML.
On our build machines however it failed on an Ubuntu during KNIME package creation which calls -write_ctd for every tool. And in the case of XTandem it needs to read the unimod to list the restrictions.
Maybe this was something xerces-version/platform-dependent?
I attached the full error. This PR actually resolved it.
https://gist.github.com/jpfeuffer/9e57486545a7d7c6454aae05384a1901

**Comment by hroest** [comment]
well we could check within xerces whether we have ASCII input only -- I think as long as we only read and write out the string we should be fine. However, if we manipulate the string I think we would be in trouble

**Pull request merged**
