### PR TITLE
[FIX] OpenSwath: error in PASEF window determination

### PR DESCRIPTION
**Pull request by jcharkow**
## Description

Typo in OpenSWATH window determination with PASEF. Ran into this issue if `lowerIm` bound is the same and `upperIm` bound is not the same

## Checklist
- [ X] Make sure that you are listed in the AUTHORS file
- [ X] Add relevant changes and new features to the CHANGELOG file
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] New and existing unit tests pass locally with my changes
- [ X] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

___

### **PR Type**
Bug fix

___

### **Description**
- Fixed a typo in the OpenSWATH window determination logic for PASEF in `SwathFile.cpp`.
- Corrected the placement of parentheses in the conditional statement to ensure proper comparison of `upperIm` bounds.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>SwathFile.cpp</strong><dd><code>Fix typo in PASEF window determination logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/openms/source/FORMAT/SwathFile.cpp

<li>Fixed typo in conditional statement for PASEF window determination.<br> <li> Corrected parentheses placement in the comparison logic.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7546/files#diff-c00d3fb0d4ee4efac6952a01b40953168eb9b8e3ec20bf2bd90daf20715d845a">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by cbielow — APPROVED** [review]
moving this code into a separate function is probably helpful here?!
Would have made this testable.

However, fine as is.

Please add this PR to the CHANGELOG before merging.

**Review by timosachsenberg — APPROVED** [review]

**Review by timosachsenberg — APPROVED** [review]

**Comment by timosachsenberg** [comment]
@jcharkow do you want this merged before the release? if so, can you address @cbielow comment?

**Comment by timosachsenberg** [comment]
@jcharkow any update?

**Comment by jcharkow** [comment]
> @jcharkow any update?

Sorry I have been busy lately. Will get this done by Monday

**Pull request merged**
