### PR TITLE
[DEPRECATED] removed PILIS tools

### PR DESCRIPTION
**Pull request by timosachsenberg**
Additional include files we could most likely remove are:
```
#include <OpenMS/ANALYSIS/ID/HiddenMarkovModel.h>		
#include <OpenMS/ANALYSIS/ID/ProtonDistributionModel.h>
SuffixArrayPeptideFinder
SuffixArraySeqan
```

Potentially interesting functions of general use are:
PILISScoring which contains an E-Value calculation algorithm

### CODE REVIEW

**Comment by hroest** [comment]
what did PILIS actually do? I could only find this documentation: http://ftp.mi.fu-berlin.de/pub/OpenMS/documentation/html/TOPP_PILISIdentification.html  -- is it an unfinished protein inference engine? is it published?

**Comment by timosachsenberg** [comment]
It is a peptide identification engine that uses hmms to predict peak intensities. It has been started by Andreas and not been finished as far as I know.

**Comment by hroest** [comment]
I agree, it would be good to get rid of unused / old stuff, especially if it is only half-done and not described in any publication. Do you want to keep the E value algorithm somewhere or re-add it in a second step once it will get used somewhere?

**Comment by timosachsenberg** [comment]
Those modules might be closely associated with PILIS and should be checked for general use in the future
```
        292 - BinnedSharedPeakCount_test (Failed)
        293 - BinnedSpectralContrastAngle_test (Failed)
        295 - BinnedSpectrum_test (Failed)
        296 - BinnedSumAgreeingIntensities_test (Failed)
        299 - ClusterHierarchical_test (Failed)
        302 - PeakAlignment_test (Failed)
        311 - ZhangSimilarityScore_test (Failed)
```

**Comment by timosachsenberg** [comment]
failed tests are unrelated

**Comment by cbielow** [comment]
+1

also +1 to remove
#include <OpenMS/ANALYSIS/ID/ProtonDistributionModel.h>
SuffixArrayPeptideFinder
SuffixArraySeqan

HMM (#include <OpenMS/ANALYSIS/ID/HiddenMarkovModel.h>) might be useful to have at some point?!

**Pull request merged**
