### PR TITLE
[NOP] added additional checks to prevent wrong order of input files

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by cbielow** [comment]
can the code be pulled into the library? The main method seems pretty large...

**Comment by timosachsenberg** [comment]
For just checking Input basename - yes. The code that involves reading the full Id files to access the annotated ms run I don’t think so.

**Comment by timosachsenberg** [comment]
Where would you put it? TOPPBase would be an option.

**Comment by cbielow** [comment]
Toppbase is already a beast. 
In File.cpp or a new class?

**Comment by cbielow** [comment]
very nice!
+1 for merge if tests pass

**Pull request merged**
