### PR TITLE
[FEATURE] Add pkg installer and faster, less latexy documentation.

### PR DESCRIPTION
**Pull request by jpfeuffer**
## Description

- Refactors cmake vars like Logo, Plugin dir etc.
- Adds pkg installer for macOS
- Do not use Latex to render two single arrows for almost every page in our documentation.....
- Try Mathjax in general
- Extend fix_deps script on macOS to be able to just fix loading without copying. We can then use CMake 3.21+'s runtime dependency functionality

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
https://easyupload.io/ke5bas

@JeeH-K Can you maybe test that installer?

**Comment by poshul** [comment]
FYI CMAKE 3.21 is not installed in the Ubuntu 20.04 images.

**Comment by jpfeuffer** [comment]
rebuild jenkins

**Comment by JeeH-K** [comment]
@KyowonJeong

**Comment by KyowonJeong** [comment]
In my M1 Macbook, the installation finished without a problem. I tested a few TOPP tools and they work fine. But the apps are not working. TOPPView.app, SwathWizard.app etc. make the message  : "You can’t open the application “TOPPView.app” because it may be damaged or incomplete."

In my own built version TOPPView etc. works fine.

**Comment by jpfeuffer** [comment]
Thanks. Can you run it from the command line? I.e. ./TOPPView.app/Contents/macOS/TOPPView

Or does the "remove quarantine" trick with sudo xattr -dr ... work?

**Comment by KyowonJeong** [comment]
So ./TOPPView.app/Contents/macOS/ is empty basically. The same goes for SwathWizard.app etc.

**Comment by jpfeuffer** [comment]
Interesting. Ok then I need to check.

**Comment by KyowonJeong** [comment]
Thanks. I think Jihyung is observing similar results. I could ask ..

**Comment by JeeH-K** [comment]
> Thanks. I think Jihyung is observing similar results. I could ask ..

Same in my Mac as well

**Pull request merged**
