### PR TITLE
Fix handling of protein references when writing idXML

### LINKED ISSUE #2596: idXML: protein references written in wrong order or missing
When writing idXML, protein accessions for peptide hits are collected via `PeptideHit::extractProteinAccessions` (https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/IdXMLFile.cpp#L301). This function collects the accessions from all "peptide evidences" associated with the hit into a `set<String>`. Problematically, this operation:
1. potentially reorders the accessions relative to the order of the evidences;
2. removes duplicates (a peptide can match in different locations on the same protein).

This means that the references in the "protein_refs" attribute in the idXML may no longer correspond to the "aa_before"/"aa_after" and "start"/"end" attributes.

For peptides that match multiple times in the same protein, this can lead to crashes when converting the idXML to mzIdentML using IDFileConverter (because protein accessions are "missing" due to the de-duplication).

### PR DESCRIPTION
**Pull request by hendrikweisser**
Fixes #2596.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
hi @hendrikweisser I have a PR open https://github.com/OpenMS/OpenMS/pull/2592

**Comment by timosachsenberg** [comment]
also referenced from https://github.com/OpenMS/OpenMS/issues/2343

**Comment by timosachsenberg** [comment]
may I take the fixed Fido files ;) I did also fix consensusXML and featureXML

**Comment by timosachsenberg** [comment]
if its fine with you I make a merge of our two PRs?

**Comment by hendrikweisser** [comment]
> if its fine with you I make a merge of our two PRs?

Yes, sure. This one can be closed then, right?

**Comment by timosachsenberg** [comment]
Yes, you can close it now! Thanks, for taking care of this critical issue.

**Comment by mwalzer** [comment]
nice

**Pull request closed without merging**
