### PR TITLE
include UndefinedBehaviorSanitizer

### PR DESCRIPTION
**Pull request by timosachsenberg**
## Description

Quick test if this compiles...

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Tentatively enable this? Should only affect our nightly ASAN build.

**Comment by cbielow** [comment]
lets see what it spits out.
There may be some fixing ahead of us.

**Comment by timosachsenberg** [comment]
Any idea about?
https://cdash.seqan.de/viewBuildError.php?buildid=157263

CMakeFiles/MascotAdapterOnline.dir/MascotAdapterOnline.cpp.o:(.data.rel+0x678): undefined reference to `typeinfo for OpenMS::MascotRemoteQuery'

Is this linker related? Virtual functions seem all implemented.

https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/FORMAT/MascotRemoteQuery.h
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/MascotRemoteQuery.cpp

**Comment by timosachsenberg** [comment]
https://stackoverflow.com/questions/37358573/why-does-fsanitize-undefined-cause-undefined-reference-to-typeinfo

**Comment by jpfeuffer** [comment]
Good find! Looks like it indeed.
I'm fine with both fixes (disabling the check or exporting the full class)

**Pull request merged**
