### PR TITLE
[NOP] sync with master

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by hroest** [comment]
why do the tests fail?

**Comment by timosachsenberg** [comment]
last one did not fail :)

**Comment by hroest** [comment]
because I restarted it :-)

**Comment by timosachsenberg** [comment]
hehe ok I see. travis had some hickups recently and also ran into some log size issues with the address sanitizer build

**Comment by hroest** [comment]
@timosachsenberg is there a way to reduce the log size of our output?

**Comment by timosachsenberg** [comment]
There are some scripts around in the travis community. One of our priorities after the release is getting all CI and nightly tests to build. I think we will then take a look at it.

**Pull request merged**
