### PR TITLE
Feature/de template

### PR DESCRIPTION
**Pull request by hroest**
A big push to de-template the mzML handler and the mzMLFile.

Overall, there were only 2 instances in the code base that actively used any other loading strategy than `MSExperiment<>`:

- src/topp/SpecLibSearcher.cpp
- src/utils/IDMassAccuracy.cpp

This simplifies the code base substantially, improves compile time and reduces compiled size for tools and utils:

before:
```
$ time make -j4 TOPP 
real    6m14.794s
user    22m36.968s
sys     1m15.672s
$ du -sh bin/
42M     bin/
```

after:
```
$ time make -j4 TOPP 
real    3m40.141s
user    12m55.000s
sys     1m1.736s
$ du -sh bin/
15M     bin/
```

so compile time is about half and compiled size is 2.8-fold reduced. The only downside is for the two tools mentioned above that try to load a RichPeakMap that there is a conversion cost as we load a PeakMap and then convert. Note that no data gets lost as the MzMLHandler anyways does not do anything with the RichPeak.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
nice. I think the PR by @enetz is also ready for review. I helped a bit in removing RichPeak* and there is not that much left that needs to be removed (but maybe in another PR). Without RichPeak* the way is free for removing quite a lot of templates in the core. One downside of using the DataArrays is that write/erase/swap... STL-like access to the vector of peaks in MSSpectrum is pretty unsafe if we have DataArrays and forget to manipulate them as well. Also, many of our filter algorithms that remove peaks didn't even bother about the data arrays. I converted a few of them but the are more.

**Comment by hroest** [comment]
@timosachsenberg yes, I think that this will make quite a few things easier and RichPeak should be removed in the long run - I think the cases you describe are simply bugs and need to be fixed anyways since one cannot know whether a spectrum comes with DataArrays or not (they could be in the mzML file when reading). So I guess there is some work ahead ... fortunately this PR is pretty independent from that

**Comment by hroest** [comment]
PS: I think total build time is now quite a bit lower (I only tested the new build) and the build uses much less space

```
$time make -j4 
real    14m34.621s
user    51m32.120s
sys     5m5.532s
$ du -sh 
106M    openms_release/src/tests/class_tests/bin/
537M    openms-contrib-all-old/src/tests/class_tests/bin/
```

**Comment by hroest** [comment]
another nice feature: travis may run through now faster and this may also solve #2384

**Comment by timosachsenberg** [comment]
+1
@cbielow @jpfeuffer @hendrikweisser any objections?

**Comment by jpfeuffer** [comment]
No. +1 I like it!

**Comment by hroest** [comment]
this is now superseded by #2477

**Pull request closed without merging**
