### PR TITLE
PLFQ Write chromatograms for debugging

### PR DESCRIPTION
**Pull request by jpfeuffer**
at certain debug level

### CODE REVIEW

**Comment by timosachsenberg** [comment]
I think that makes sense. In principle, one could even combine those into peak groups for several files and store them in an osw file

**Comment by jpfeuffer** [comment]
Unfortunately I dont know how to do that. All I can say is that you can also write the transitions.

**Comment by jpfeuffer** [comment]
Also, it sounds prohibitively expensive for large datasets to store all chromatograms across all files and then merge them.

**Comment by jpfeuffer** [comment]
The only possibility I see is to fill the OSW db incrementally. But I have no idea if it is possible to create peakgroups with this.

**Pull request merged**
