### PR TITLE
Add action to test nightly conda pyOpenMS

### PR DESCRIPTION
**Pull request by enetz**
Installs Miniconda on three VMs for the three OSes.
Installs pyOpenMS in different conda environments for the specified python versions in each VM.
Runs a trivial test.
Triggered by successful execution of the pyopenms-wheels workflow.

## Checklist
- [x] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by enetz** [comment]
Is the trigger correct this way? Is it possible to set up a trigger on the upload to the conda channel? Or when a new version is available there.

**Comment by jpfeuffer** [comment]
Hmm why not just add another dimension to the existing action's matrix?

I think that would be the most efficient and maintainable solution.

**Comment by jpfeuffer** [comment]
Hm but that would make triggering difficult since it needs to wait for a Jenkins and a GHA job. We would need to send a Push to the GitHub API from Jenkins.

Now that I'm thinking about it, I'm not sure if conda needs testing at all since bioconda build can do mulled-tests. They do exactly what we want. Conda tests in an empty container after the build finishes. This needs to be activated on Jenkins.

We can also move conda builds to GHA. Should work. We could introduce macOS. Remove dockerized builds. Probably parallelize by first building OpenMS, saving the conda artifacts and then spawn one runner per python version. But it's a bit of work for something that we get for free if we just release quicker.

@timosachsenberg

**Comment by timosachsenberg** [comment]
How would moving this to the mulled test look like?
Changing:
bioconda-utils build --docker --pkg_dir $WORKSPACE/output --packages pyopenms
in
https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/ntly/job/conda/configure
to something like:  
bioconda-utils build --docker --mulled-test --pkg_dir $WORKSPACE/output --packages pyopenms
?
is that suffiient?

**Comment by jpfeuffer** [comment]
yes

**Comment by timosachsenberg** [comment]
k I can try to add it and we will see what happens in the nightly build...

**Comment by jpfeuffer** [comment]
you can just run it after every change. no need to wait for new nightlies.

**Comment by timosachsenberg** [comment]
works?
```
18:02:25 BIOCONDA INFO (OUT) Preparing transaction: ...working... done
18:02:37 BIOCONDA INFO (OUT) Verifying transaction: ...working... done
.18:02:48 BIOCONDA INFO (OUT) Executing transaction: ...working... done
18:02:48 BIOCONDA INFO (OUT) export PREFIX=/opt/conda/conda-bld/pyopenms_1677770805425/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
18:02:48 BIOCONDA INFO (OUT) export SRC_DIR=/opt/conda/conda-bld/pyopenms_1677770805425/test_tmp
18:02:49 BIOCONDA INFO (OUT) + python -c 'import pyopenms; print(pyopenms.__version__)'
18:02:50 BIOCONDA INFO (OUT) 3.0.0
18:02:50 BIOCONDA INFO (OUT) + exit 0
18:02:50 BIOCONDA INFO (OUT) 
18:02:50 BIOCONDA INFO (OUT) Resource usage statistics from testing pyopenms:
18:02:50 BIOCONDA INFO (OUT)    Process count: 1
18:02:50 BIOCONDA INFO (OUT)    CPU time: Sys=0:00:00.1, User=-
18:02:50 BIOCONDA INFO (OUT)    Memory: 2.3M
18:02:50 BIOCONDA INFO (OUT)    Disk usage: 16B
18:02:50 BIOCONDA INFO (OUT)    Time elapsed: 0:00:02.4
18:02:50 BIOCONDA INFO (OUT) 
18:02:50 BIOCONDA INFO (OUT) 
18:02:50 BIOCONDA INFO (OUT) TEST END: /opt/conda/conda-bld/linux-64/pyopenms-3.0.0dev-py39h4b47abe_0.tar.bz2
```

**Comment by jpfeuffer** [comment]
Do you see any signs that it actually did a mulled test? If so, it seems to work

**Comment by timosachsenberg** [comment]
ah you mean this might be run in the container that build the package. Hmm not sure.
I don't find any "mulled" string in
https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/ntly/job/conda/539/console

**Comment by jpfeuffer** [comment]
Hmm I guess it's fine then? I'm think I am not so worried about conda so much. They have a lot of automatic relinking and checking in place.
We could still have a quick conda install job. But a) it's just gonna be on Linux and b) it must be triggered from Jenkins.

One thing we should make sure though, is either to increase the build number all the time or to make sure that we only upload when both packages were successful (needs the upstream fix). We had the case before that libopenms passed but pyopenms didn't. And then we had incompatible packages because one was newer than the other.

**Comment by timosachsenberg** [comment]
sorry

**Pull request closed without merging**
