### PR TITLE
[FIX] fixed update check after writing of .ini is not mandatory any more

### PR DESCRIPTION
**Pull request by timosachsenberg**
@hroest readded update check functionality after PR "[FIX] address missing OpenMS.ini problem"

### CODE REVIEW

**Comment by hroest** [comment]
fixes #1967 addressing the problems from #2323

**Comment by hroest** [comment]
the other solution could be that `File::getSystemParameters` guarantees the creation of `home_path + '/.OpenMS` if at all possible (as it did before).

**Comment by timosachsenberg** [comment]
I am fine with this. What I dislike a bit about the alternative is that the name getSystemParameters suggests there are not many side effects ;)

**Comment by hroest** [comment]
yes, I agree. On the other hand, having to create `.OpenMS` each time we do something there is also not a good option. For now either solution works.

**Pull request merged**
