### PR TITLE
rename param in MSGFPlus adapter conforming with MS-GF+ API

### PR DESCRIPTION
**Pull request by lars20070**
Change of protocol `none` to `automatic` as used in MS-GF+ API.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
This is a breaking change so we probably need to discuss that.
-p ProtocolID (Default: 0)
Protocol identifier. Protocols are used to enable scoring parameters for enriched and/or labeled samples.
0: No protocol (Default)

Looking at the documentation at https://omics.pnl.gov/software/ms-gf, the API is to only provide an integer value.
At the top it is called automatic
at the detailed description at the bottom it is called no protocol

So not sure if it is worth to change that

**Comment by lars20070** [comment]
For example, for TMT one can work with `protocol = automatic`. Choosing `protocol = none` for TMT I found not intuitive.
https://gitter.im/lars20070/FreiburgOpenMS?at=5a9e87f9c3c5f8b90d3c6986

**Comment by timosachsenberg** [comment]
if you look at: https://bix-lab.ucsd.edu/pages/viewpage.action?pageId=13533355
it seems our name just matches the description in the MSGFPlus documentation. 
So I guess they changed 0=auto later.
What about a non-breaking change? adding auto as default but also keeping "none"

**Comment by lars20070** [comment]
Good solution.

@klemens1 Do you agree? Then I make the changes.

**Comment by faceless123454** [comment]
sounds good

**Comment by lars20070** [comment]
Yep. The MS-GF+ docu changed from `0: none` (2013) to `0: automatic` (2017).

**Pull request merged**
