### PR TITLE
fix neon flags (not needed)

### PR DESCRIPTION
**Pull request by cbielow**
## Description

armv8 should by design support neon, yet it's very messy to find which compile flags are needed since the architecture is so fragmented.
SIMDe seems to do a much better job than we could, and as long as we stick to SIMDe, neon should be used (even without compile flags).

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
nice. is there an easy way to check in e.g. a test if the binary has hardware support for vectorization compiled in?

**Comment by cbielow** [comment]
good point.
We should add that to OpenMSInfo.
Just needs querying the correct SIMDe macros per platform (and feature, e.g. neon, SSE3/4, AVX etc)

**Comment by jpfeuffer** [comment]
Great idea

**Comment by cbielow** [comment]
merging to see what nightlies do.
Adding to OpenMSInfo is certainly another PR.

**Comment by timosachsenberg** [comment]
snap... seems to fail now.

**Comment by cbielow** [comment]
that's ok (its another bug), see https://github.com/OpenMS/OpenMS/pull/7022

**Pull request merged**
