### PR TITLE
[FIX] issue #2206

### PR DESCRIPTION
**Pull request by hannesveit**

### CODE REVIEW

**Comment by hendrikweisser** [comment]
Nice, thanks for the fix! 👍 
@timosachsenberg: Should this go into "master" as well?

**Comment by timosachsenberg** [comment]
In think this would be a good idea

**Comment by hroest** [comment]
:+1: this fixes the bug but now the mz_diff is too conservative. I think optimally we would re-compute the ppm diff inside the loop :

```
141         if (fabs(massrange[j] - massrange[j+1]) > massrange_diff)
```

**Comment by hannesveit** [comment]
Good point, @hroest. I'll improve it.

**Comment by hannesveit** [comment]
OK?

**Comment by hannesveit** [comment]
>@timosachsenberg: Should this go into "master" as well?

just a reminder, in case you still want to include it

**Comment by timosachsenberg** [comment]
tks. I moved it on master

**Pull request merged**
