### PR TITLE
Fix sqlite win

### PR DESCRIPTION
**Pull request by cbielow**
fixes the most imminent compile errors on windows introduced in #2480

### CODE REVIEW

**Comment by timosachsenberg** [comment]
+1 looks good. feel free to merge

**Comment by hroest** [comment]
makes  #2552 unnecessary

**Comment by grosenberger** [comment]
Thank you for the patch!

**Comment by hroest** [comment]
after merging, http://cdash.openms.de/testDetails.php?test=38934748&build=221167 OMSSAAdapter_1_out failed strange -- I will restart

**Pull request merged**
