### PR TITLE
Update wrapper for Percolator

### PR DESCRIPTION
**Pull request by hendrikweisser**
We've updated our Percolator installation to the current version from their GitHub. There was a change in some parameters that needs to be reflected in our GenericWrapper for Percolator.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Hi. Can you add a note to which version / revision this corresponds?

**Comment by hendrikweisser** [comment]
I don't know if/how Percolator does version numbers. The version that I compiled from source just says "version 0.00". It's the current revision, so [6af376e](https://github.com/percolator/percolator/commit/6af376eec8de26a6d31440aa311c92b4346a7d0b).

**Comment by timosachsenberg** [comment]
Are there any conflicts with Topperc @mwalzer?  otherwise I think we can merge.

**Comment by mwalzer** [comment]
no conflicts :+1:

**Pull request merged**
