### PR TITLE
mzid validation in FileInfo switched on

### LINKED ISSUE #1549: Validation of mzIdentML not supported out of the box
FileInfo (with the "v" option) and XMLValidator don't yet support validation of mzIdentML out of the box. They give this message:
> Validating mzid file
> Aborted: Validation of this file type is not supported!

Validation works if the mzIdentML schema is passed explicitly to XMLValidator via the "schema" option.

### PR DESCRIPTION
**Pull request by lars20070**
Resolves #1549. Needed for #1655.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
do we have a small mzID we could add to the TOPP tests?

**Comment by timosachsenberg** [comment]
looks good otherwise

**Comment by lars20070** [comment]
I will add a test once we can write valid `mzid`.

**Comment by timosachsenberg** [comment]
Sounds sensible. +1

**Comment by timosachsenberg** [comment]
You could still test a valid Mzid from another source, though

**Comment by cbielow** [comment]
please write a test, even with our current mzid.
(or better, write 2, one failing, one passing).
The passing one will need to be adapted from time to time, but if you don't do it now, I'm afraid it will never happen.

**Comment by lars20070** [comment]
@cbielow I will the tests before the WE.

**Comment by hendrikweisser** [comment]
@lars20070: There is an mzid generated by MS-GF+ in "src/tests/topp/THIRDPARTY". Maybe that would work.

**Comment by lars20070** [comment]
@cbielow @hendrikweisser I would appreciate a comment in #1848. Then I could finalise the `mzid` fixes before the WE (and add the `FileInfo` tests as promissed).

**Comment by mwalzer** [comment]
What about that minimal ```mzid``` from OpenMS as @cbielow mentioned? I think there are already some pretty basic ones written in the tests. 
I think it would be good to test basic first, and building another test with complex content (like @lars20070 mutliple fractions) ontop.

**Pull request merged**
