### PR TITLE
Update unimod

### PR DESCRIPTION
**Pull request by bernt-matthias**
# Description

Update unimod.xml 

fixes https://github.com/OpenMS/OpenMS/issues/5874

Added the custom modifications to the end. Please double check

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Hmm seems one might be missing from the old one (or was manually added by us?). Or renamed
https://cdash.openms.de/test/5433070
```
const OpenMS::ResidueModification *OpenMS::ModificationsDB::searchModificationsFast(const OpenMS::String &, bool &, const OpenMS::String &, ResidueModification::TermSpecificity) constModification not found: Methyl:2H(2)13C
Error: Unexpected internal error (the value 'Methyl:2H(2)13C' was used but is not valid; Retrieving the modification failed. It is not available for the residue '' and term specificity 'N-term'. )
```

**Comment by timosachsenberg** [comment]
see https://github.com/OpenMS/OpenMS/issues/3561

**Comment by bernt-matthias** [comment]
I guess we need to add all/most of the modifications that were below the custom modifications in the old version of the file. But I guess it would be best if someone with expert knowledge would inverstigate the diff with a proper diff viewer, because there seem to be also some differences above that seem worth to check ..

**Comment by timosachsenberg** [comment]
ok I will take a look

**Comment by timosachsenberg** [comment]
ok we need to add those (I wasn't able to add it to your branch):
```
      <umod:mod title="Methyl:2H(2)13C"
        full_name="Mono-methylation 2H(2)13C"
        username_of_poster="Weng"
        group_of_poster="admin"
        date_time_posted="2015-07-10 12:00:00"
        date_time_modified="2015-07-10 12:00:00"
        approved="0"
        record_id="99987">
        <umod:specificity hidden="1" site="T" position="Anywhere" classification="Post-translational" spec_group="14"/>
        <umod:specificity hidden="1" site="S" position="Anywhere" classification="Post-translational" spec_group="13"/>
        <umod:specificity hidden="1" site="N-term" position="Protein N-term" classification="Chemical
derivative" spec_group="10"/>
        <umod:specificity hidden="0" site="E" position="Anywhere" classification="Post-translational" spec_group="12"/>
        <umod:specificity hidden="0" site="D" position="Anywhere" classification="Post-translational" spec_group="15"/>
        <umod:specificity hidden="0" site="C-term" position="Any C-term" classification="Multiple" spec_group="11"/>
        <umod:specificity hidden="1" site="L" position="Anywhere" classification="Post-translational" spec_group="9"/>
        <umod:specificity hidden="1" site="I" position="Anywhere" classification="Post-translational" spec_group="8"/>
        <umod:specificity hidden="1" site="R" position="Anywhere" classification="Post-translational" spec_group="7"/>
        <umod:specificity hidden="1" site="N-term" position="Any N-term" classification="Chemical
derivative" spec_group="5"/>
        <umod:specificity hidden="1" site="Q" position="Anywhere" classification="Post-translational" spec_group="6"/>
        <umod:specificity hidden="1" site="N" position="Anywhere" classification="Post-translational" spec_group="4"/>
        <umod:specificity hidden="1" site="K" position="Anywhere" classification="Chemical derivative" spec_group="3"/>
        <umod:specificity hidden="1" site="H" position="Anywhere" classification="Post-translational" spec_group="2"/>
        <umod:specificity hidden="1" site="C" position="Anywhere" classification="Post-translational" spec_group="1"/>
        <umod:delta mono_mass="17.031558" avge_mass="17.0344805" composition="2H(2) 13C">
          <umod:element symbol="2H" number="2"/>
          <umod:element symbol="13C" number="1"/>
        </umod:delta>
      </umod:mod>
      <umod:mod title="Glu->pyro-Glu+Methyl"
        full_name="Pyro-gly from E + Mono-Methylation"
        username_of_poster="Weng"
        group_of_poster="admin"
        date_time_posted="2015-07-06 12:00:00"
        date_time_modified="2015-07-06 12:00:00"
        approved="0"
        record_id="99988">
        <umod:specificity hidden="1" site="E" position="Any N-term" classification="Artefact"
        spec_group="1"/>
        <umod:delta mono_mass="-3.9949149358" avge_mass="-3.98872" composition="O(-1) C(1)">
          <umod:element symbol="O" number="-1"/>
          <umod:element symbol="C" number="1"/>
        </umod:delta>
      </umod:mod>
      <umod:mod title="Glu->pyro-Glu+Methyl:2H(2)13C"
        full_name="Pyro-gly from E + Mono-Methylation-Medium"
        username_of_poster="Weng"
        group_of_poster="admin"
        date_time_posted="2015-07-06 12:00:00"
        date_time_modified="2015-07-06 12:00:00"
        approved="0"
        record_id="99989">
        <umod:specificity hidden="1" site="E" position="Any N-term" classification="Artefact"
        spec_group="1"/>
        <umod:delta mono_mass="-0.979005" avge_mass="-0.983746" composition="H(-2) O(-1) 2H(2) 13C(1)">
          <umod:element symbol="H" number="-2"/>
          <umod:element symbol="O" number="-1"/>
          <umod:element symbol="2H" number="2"/>
          <umod:element symbol="13C" number="1"/>
        </umod:delta>
      </umod:mod>
      <umod:mod title="Dimethyl:2H(2)13C"
        full_name="Dimethyl-Mono-Medium" username_of_poster="Lars"
        group_of_poster="admin"
        date_time_posted="2015-07-06 12:00:00"
        date_time_modified="2015-07-06 12:00:00"
        approved="0"
        record_id="99990">
        <umod:specificity hidden="1" site="N" position="Anywhere" classification="Post-translational" spec_group="4"/>
        <umod:specificity hidden="1" site="N-term" position="Any N-term" classification="Chemical derivative" spec_group="3"/>
        <umod:specificity hidden="1" site="R" position="Anywhere" classification="Post-translational" spec_group="2"/>
        <umod:specificity hidden="1" site="K" position="Anywhere" classification="Post-translational" spec_group="1"/>
        <umod:specificity hidden="1" site="P" position="Protein N-term" classification="Post-translational" spec_group="5"/>
        <umod:delta mono_mass="31.047208" avge_mass="31.05814" composition="H(2) 2H(2) C(1) 13C(1)">
          <umod:element symbol="H" number="2"/>
          <umod:element symbol="2H" number="2"/>
          <umod:element symbol="C" number="1"/>
          <umod:element symbol="13C" number="1"/>
        </umod:delta>
      </umod:mod>
      <umod:mod title="RNPXlink1" full_name="Cysteine Adduct" username_of_poster="Timo"
                group_of_poster="admin"
                date_time_posted="2002-08-19 19:17:11"
                date_time_modified="2008-02-15 05:20:02"
                approved="0"
		record_id="99991">
         <umod:specificity hidden="0" site="C" position="Anywhere" classification="Post-translational"
		 spec_group="1"/>
         <umod:delta mono_mass="151.99436" avge_mass="152.043276" composition="H(2) C(1) O(6) N(3)">
            <umod:element symbol="H" number="2"/>
            <umod:element symbol="C" number="1"/>
            <umod:element symbol="O" number="6"/>
            <umod:element symbol="N" number="3"/>
         </umod:delta>
      </umod:mod>
```

**Comment by bernt-matthias** [comment]
Two of these seem to be included already, but `&gt;` instead of `>` in the name: 

- `Glu-&gt;pyro-Glu+Methyl`
- `Glu-&gt;pyro-Glu+Methyl:2H(2)13C(1)`

**Comment by timosachsenberg** [comment]
good catch so the "->" can go

**Comment by bernt-matthias** [comment]
> hmm if is in there Glu->pyro-Glu+Methyl:2H(2)13C(1)
> then maybe also Methyl:2H(2)13C(1)
> and we can get rid of that addition as well.

`Glu->pyro-Glu+Methyl:2H(2)13C(1)` and `Methyl:2H(2)13C(1)` look quite different to me

**Comment by timosachsenberg** [comment]
k sorry I meant Methyl:2H(2)13C(1)  vs Methyl:2H(2)13C but right it is not contained

**Review by timosachsenberg — APPROVED** [review]

**Comment by timosachsenberg** [comment]
nice. looks good to me!

**Pull request merged**
