### PR TITLE
Feature/mtd cleanup

### PR DESCRIPTION
**Pull request by hroest**
cleanup, refactoring and documentation of the masstrace extractor code

### CODE REVIEW

**Comment by hroest** [comment]
one random unrelated failure in travis http://cdash.openms.de/testDetails.php?test=23319606&build=122187

**Comment by cbielow** [comment]
this will probably conflict with https://github.com/OpenMS/OpenMS/pull/1275

**Comment by cbielow** [comment]
in addition, we should remove 'the whole smoothed_intensity branching.
It  blows up the code, is highly confusing and probably has side effects.
Instead, MT's should be constructed from either real or smoothed data, not both.

**Comment by timosachsenberg** [comment]
merge conflicts

**Comment by hroest** [comment]
yes, I will not have time in the near future to do this but I think the changes should be made at some point

**Comment by hroest** [comment]
this is replaced by #1588

**Pull request closed without merging**
