### PR TITLE
Feature/spectrum addition

### PR DESCRIPTION
**Pull request by hroest**
- [FEATURE] spectra addition for MSSpectrum
- [FIX] fix segfault in SpectrumAddition

### CODE REVIEW

**Comment by timosachsenberg** [comment]
I think this closely related to consensus spectra and spectra merger. Maybe these algorithms could go together?

**Comment by hroest** [comment]
good point, I agree we should put that on the TODO list. I think the tools have the same goal but use different algorithms

currently, this uses the LinearResampler to resample the spectra. SpectraMerger uses the SpectrumAlignment algorithm which aligns two spectra. I think the main question is how to "distribute" intensity of the aligned peaks and here the resampling approach is probably more accurate than the approach of SpectrumAlignment. In the latter, the algorithm basically just aligns the data and then adds up the intensities of the aligned peaks. Instead, the resampling approach allows (i) to have a grid for alignment (e.g. a given raster) and secondly (ii) specify how the intensity should be interpolated between grid points

**Comment by hroest** [comment]
PS: this depends on #2314

**Comment by timosachsenberg** [comment]
http://cdash.openms.de/viewBuildError.php?onlydeltap&buildid=203888

**Comment by hroest** [comment]
@timosachsenberg that is actually a problem as these parameters are used in the PRECONDITION macros and therefore only unused in the Release versions ... not really sure what to do here, any ideas?

**Comment by timosachsenberg** [comment]
can we (easily) include these parameters only if we create a debug build?

**Comment by hroest** [comment]
`OPENMS_ASSERTIONS` should be the right preprocessor macro

**Comment by hroest** [comment]
merge?

**Pull request merged**
