### PR TITLE
Stream segfault 2

### PR DESCRIPTION
**Pull request by pasqoo**
A continuation of the work done in https://github.com/OpenMS/OpenMS/pull/3998

I updated the branch with what is found in `develop`, taking care of the merge conflicts.
My goal is to see what the CI has to say about the proposed code.

I am working on some multi-threaded code that segfaults. gdb's `bt` command makes me suspect that it might be this logger. I need to do more tests to be sure.

```
(gdb) bt
#0  __memchr_avx2 () at ../sysdeps/x86_64/multiarch/memchr-avx2.S:92
#1  0x00007f7b8a49f6f0 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f7b8c28c419 in OpenMS::Logger::LogStreamBuf::expandPrefix_ (this=0x55ae17d458d0, prefix=<error: Cannot access memory at address 0x616c600000000a2e>, 
    time=1561636050) at /home/pasdom/OpenMS/src/openms/source/CONCEPT/LogStream.cpp:332
#3  0x00007f7b8c28be3c in OpenMS::Logger::LogStreamBuf::distribute_ (this=0x55ae17d458d0, outstring="computeScore_(): Metavalue \"peak_apex_int\" not found.")
    at /home/pasdom/OpenMS/src/openms/source/CONCEPT/LogStream.cpp:227
#4  0x00007f7b8c28c25f in OpenMS::Logger::LogStreamBuf::syncLF_ (this=0x55ae17d458d0) at /home/pasdom/OpenMS/src/openms/source/CONCEPT/LogStream.cpp:301
#5  0x00007f7b8c28c38a in OpenMS::Logger::LogStreamBuf::sync (this=0x55ae17d458d0) at /home/pasdom/OpenMS/src/openms/source/CONCEPT/LogStream.cpp:320
#6  0x00007f7b8c28b5c0 in OpenMS::Logger::LogStreamBuf::overflow (this=0x55ae17d458d0, c=110) at /home/pasdom/OpenMS/src/openms/source/CONCEPT/LogStream.cpp:100
#7  0x00007f7b8a49c5ab in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f7b8a48ccb4 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f7b8a48d027 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
```

Sorry for the PR duplication. Maybe I could get permission to push in #3998 and close this one?

### CODE REVIEW

**Comment by pasqoo** [comment]
rebuild jenkins

**Comment by hroest** [comment]
rebuild jenkins

**Comment by pasqoo** [comment]
Keeping track of what has passed without adding more commits:
- continuous-integration/travis-ci/pr
- openms_pr_ci/compiler=g++-7,os_label=ubuntu_1804

**Comment by pasqoo** [comment]
rebuild jenkins

**Comment by jpfeuffer** [comment]
Yes windows was an error because of the updated contrib that I built with a newer version of VS2017. Mac seemed to be fine, I don't know why it always has problems uploading the results to cdash in this PR.

**Comment by pasqoo** [comment]
The pyOpenMS one seems serious... ? https://abibuilder.informatik.uni-tuebingen.de/jenkins/job/openms_pr_docker_pyopenms/1716/testReport/junit/projectroot/pyOpenMS/pyopenms_test_memoryleaktests/ There is only one test failing, the memory leak

**Comment by jpfeuffer** [comment]
Ok LOG_STREAM fails on Windows. The memory_leak is not so serious in pyopenms. It comes from the fact that it runs in a container I think.

**Comment by jpfeuffer** [comment]
It fails after passing though. Probably at some destructor then. I remember having such kind of problems with multithreading before.

**Comment by pasqoo** [comment]
> It fails after passing though. Probably at some destructor then. I remember having such kind of problems with multithreading before.

Yeah, I would not be able to say what's the issue from this output: https://abibuilder.informatik.uni-tuebingen.de/jenkins/job/openms_pr_ci/compiler=msvc-15,os_label=win10_64/3207/testReport/projectroot.src.tests.class_tests/openms/LogStream_test/

**Comment by jpfeuffer** [comment]
Exception thrown at 0x00007FFE3287F55C (OpenMS.dll) in LogStream_test.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

**Comment by jpfeuffer** [comment]
Unfortunately I would need to rebuild everything in debug mode to get more info. Would it help? What would I look for?

**Comment by pasqoo** [comment]
@jpfeuffer Where did you get that output from?

I do not have an answer to your question, I am not familiar with `LogStream` nor with the fix implemented  by @hroest

**Comment by jpfeuffer** [comment]
Ah I logged into the CI machine. I don't know why but ctest does not record such kind of error output.
`At assembly line: 00007FFE3287F55C  lock xadd   dword ptr [rbx+8],eax`
That's the assembly line. The lock probably means it happens in some multithreaded part.

**Comment by pasqoo** [comment]
Does ctest also print cerr, or only cout?

**Comment by jpfeuffer** [comment]
The thing is, on windows it is not really in the std error but it pops up as a warning popup window. Maybe that is why it is not captured.

**Comment by cbielow** [comment]
> 
> 
> The thing is, on windows it is not really in the std error but it pops up as a warning popup window. Maybe that is why it is not captured.

There is a solution for that: https://stackoverflow.com/questions/735170/can-the-application-error-dialog-box-be-disabled
:-)

**Comment by cbielow** [comment]
this will also prevent all affected tests from timing out -- the popup will force them to stay open and thus waste time

**Comment by jpfeuffer** [comment]
Cool. I prefer https://docs.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-seterrormode over some system-wide registry magic. Maybe in the Class_test.h?

Stack trace by the way:
```
 	OpenMSd.dll!operator delete(void * block) Line 21	C++
 	OpenMSd.dll!std::_Deallocate(void * _Ptr, unsigned __int64 _Count, unsigned __int64 _Sz) Line 141	C++
 	OpenMSd.dll!std::allocator<char>::deallocate(char * _Ptr, unsigned __int64 _Count) Line 824	C++
 	OpenMSd.dll!std::_Wrap_alloc<std::allocator<char> >::deallocate(char * _Ptr, unsigned __int64 _Count) Line 1089	C++
 	OpenMSd.dll!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy_deallocate() Line 3616	C++
 	OpenMSd.dll!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> >() Line 2216	C++
 	[External Code]	
 	OpenMSd.dll!std::allocator<std::_Tree_node<std::pair<unsigned __int64 const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,void * __ptr64> >::destroy<std::pair<unsigned __int64 const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >(std::pair<unsigned __int64 const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > * _Ptr) Line 847	C++
 	OpenMSd.dll!std::allocator_traits<std::allocator<std::_Tree_node<std::pair<unsigned __int64 const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,void * __ptr64> > >::destroy<std::pair<unsigned __int64 const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >(std::allocator<std::_Tree_node<std::pair<unsigned __int64 const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,void *> > & _Al, std::pair<unsigned __int64 const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > * _Ptr) Line 966	C++
 	OpenMSd.dll!std::_Wrap_alloc<std::allocator<std::_Tree_node<std::pair<unsigned __int64 const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,void * __ptr64> > >::destroy<std::pair<unsigned __int64 const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >(std::pair<unsigned __int64 const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > * _Ptr) Line 1104	C++
 	OpenMSd.dll!std::_Tree<std::_Tmap_traits<unsigned __int64,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::less<unsigned __int64>,std::allocator<std::pair<unsigned __int64 const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >,0> >::erase(std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned __int64 const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > > > _Where) Line 1442	C++
 	OpenMSd.dll!OpenMS::Logger::LogStreamBuf::addToCache_(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & line) Line 188	C++
 	OpenMSd.dll!OpenMS::Logger::LogStreamBuf::syncLF_() Line 295	C++
 	OpenMSd.dll!OpenMS::Logger::LogStreamBuf::sync() Line 320	C++
 	[External Code]	
 	LogStream_test.exe!std::endl<char,std::char_traits<char> >(std::basic_ostream<char,std::char_traits<char> > & _Ostr) Line 986	C++
 	[External Code]	
>	LogStream_test.exe!main$omp$1() Line 104	C++
```

**Comment by jpfeuffer** [comment]
I'm trying to use the same name for the critical region right now.

**Comment by pasqoo** [comment]
Work has continued in the original PR. Closing this one.

**Pull request closed without merging**
