### PR TITLE
[Feature] GH actions ccache

### PR DESCRIPTION
**Pull request by jpfeuffer**
## Description

Adds ccache to out GH actions. No windows yet. I just did not try.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
ccache segfaults on redhat? great

**Comment by jpfeuffer** [comment]
TODO Upload as long as build succeeds and don't care about tests (maybe we need another caching action, since this one is too inflexible)

**Comment by jpfeuffer** [comment]
TODO check actual usage of the cache IDs. If it works as expected (e.g. cache for develop, then cache for PRs).
Caches are deleted after 7 days by GitHub. We have max. 10gb of caches (i.e. 20 caches with different IDs if we limit them at 500mb).
Unfortunately, I don't know how GitHub decides which cache to delete when it's full (undocumented). Probably least recently used.

**Comment by jpfeuffer** [comment]
Regarding caching even when tests fail: https://github.com/actions/cache/issues/92#issuecomment-1362456629

Starting from v3, there are separate save/load actions.

**Comment by jpfeuffer** [comment]
Hmm https://github.com/OpenMS/OpenMS/actions/caches
40 Bytes of cache does not seem to be correct.

**Comment by jpfeuffer** [comment]
Looks better. 660MB on lnx and 100MB on mac.

**Comment by jpfeuffer** [comment]
That means we have space for around 10 PRs only (and only if we change the cache ID to per PR, not per run).
Either we live with this limitation and make sure that the develop cache is at least always available.
Or we roll our own cache hosting solution.

**Comment by jpfeuffer** [comment]
@timosachsenberg Ping. This is ready

**Review by timosachsenberg — APPROVED** [review]
Thanks also for fixing / disabling the annoying mrm tests

**Pull request merged**
