### PR TITLE
use separate testfile for FidoAdapter tests

### PR DESCRIPTION
**Pull request by bernt-matthias**
Before test1 and test6 used the same file for the comparison
which is fine if compared with FuzzyDiff, but leads to problems
for my Galaxy tests.

My change anctually does not change the current situation
for OpenMS, since the file used for comparison for test6 is
a symlink.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
does that work on win?

**Comment by timosachsenberg** [comment]
@jpfeuffer should we duplicate that file or rely on symlinks?

**Comment by jpfeuffer** [comment]
Well, I think it failed on Windows. So, duplicating would be the only platform-independent option.

**Comment by jpfeuffer** [comment]
Hm sorry, but this is not a copy of FidoAdapter_1_output.idXML. At least not from develop. Maybe from 2.4?
We updated the path to the XSL.

**Comment by bernt-matthias** [comment]
Done. Rebased and squashed the commits. Hope that I got it correct this time.

**Comment by jpfeuffer** [comment]
Looks good. failures unrelated, I am currently testing external code snippets in the CI.
Let me restart travis with cache tho.

**Pull request merged**
