### PR TITLE
Feature/sqlite fixid

### PR DESCRIPTION
**Pull request by hroest**
fixes an issue that came up when using pqp input files:

- transitions and peptide precursors had the same id
- when writing them out to mzML, we had chromatograms with the same id which could then not be mapped back any more to the pqp / traml file

the solution for this is to label precursor XIC with the tag "_Precursor_i0" at the end, which will also allow for XIC of other isotopes and makes 1:1 mappings possible

### CODE REVIEW

**Comment by hroest** [comment]
maybe @grosenberger could comment on this

**Comment by grosenberger** [comment]
Thanks for the fix, @hroest! 👍

**Comment by hroest** [comment]
there is still an underlying problem which is not well addressed: how to link to / refer to peptides and how to refer to transitions. Right now that is not well done, especially as for a chromatogram it is not clear whether its a fragment ion chromatogram or a precursor XIC. And I dont really know whether we should try to propagate some unique INT identifier to the chrom sqMass files or not, we could potentially write it in a precursor field somewhere...

**Comment by hroest** [comment]
hmm this is strange:

http://cdash.openms.de/testDetails.php?test=39617931&build=220982
```

Offending lines:			(tab_width = 8, first_column = 1)

in1:  /home/travis/build/OpenMS/OpenMS/_build/src/tests/topp/OpenSwathWorkflow_14.chrom.tmp.mzML   (line: 44, position/column: 2/10)
	<!
	 /dataProcessingList>

in2:  /home/travis/build/OpenMS/OpenMS/src/tests/topp/OpenSwathWorkflow_14_output.chrom.mzML   (line: 44, position/column: 3/18)
		<!
		 dataProcessing id="dp_sp_0">

```

it writes out one data processing instead of two but only in debug mode with clang... ??

**Comment by jpfeuffer** [comment]
Did you forget the "-test" option?

**Comment by jpfeuffer** [comment]
Still not sure why only on debug and clang.

**Comment by hroest** [comment]
doesnt look like I forgot -test

 +  add_test("TOPP_OpenSwathWorkflow_14_step2" ${TOPP_BIN_PATH}/OpenSwathMzMLFileCacher -in OpenSwathWorkflow_14.chrom.tmp.sqMass -out OpenSwathWorkflow_14.chrom.tmp.mzML -test) 

however there is an issue with writing out data processing tags as sometimes multiple tags are written...

**Comment by hroest** [comment]
even more strange:

http://cdash.openms.de/testDetails.php?test=39617928&build=220982

```
Warning: Could not determine format of input file 'OpenSwathWorkflow_1_input.pqp.tmp'!
Progress of 'Load TraML file':
-- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
Loading mzML file /home/travis/build/OpenMS/OpenMS/src/tests/topp/OpenSwathWorkflow_1_input.mzML using readoptions normal
Progress of 'Loading metadata file /home/travis/build/OpenMS/OpenMS/src/tests/topp/OpenSwathWorkflow_1_input.mzML':
Will analyze the metadata first to determine the number of SWATH windows and the window sizes.
Determined there to be 5 SWATH windows and in total 19 MS1 spectra
Determined there to be 5 SWATH windows and in total 19 MS1 spectra
-- done [took 2.02 s (CPU), 2.09 s (Wall)] -- 
Progress of 'Loading data file /home/travis/build/OpenMS/OpenMS/src/tests/topp/OpenSwathWorkflow_1_input.mzML':
-- done [took 3.82 s (CPU), 3.96 s (Wall)] -- 
Done creating tables
Will analyze 0 transitions in total.
Progress of 'Extracting and scoring transitions':
-- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
OpenSwathWorkflow took 6.09...
``` 

so it analyzes 0 transitions? something must be wrong with the PQP file ...

**Comment by hroest** [comment]
damn, it may have been the missing 25a8e8a which is hard to catch because a valid SQL file is created but not fully filled with data yet. Lets see what travis says...

**Comment by hroest** [comment]
now its green, travis passed. We are good to go, please merge

**Comment by grosenberger** [comment]
I did observe a problem that might be related to this PR, particularly the IDs for the MS1 chromatograms. When extracting from MS1 maps, (irregardless of whether TraML or PQP is used), a segfault occurs.

@hroest does MS1 extraction work for you with recent builds? I will follow up on the problem tomorrow and provide example data.

**Comment by hroest** [comment]
@grosenberger I just did an extraction using MS1 chromatograms using this data http://openswath.org/openswath_data.html ( Methods Mol Biol. Data ) and everything worked:

```
MS1OPTIONS="-use_ms1_traces -Scoring:Scores:use_ms1_fullscan -Scoring:Scores:use_ms1_correlation"
OPTIONS="-tr Mtb_TubercuList-R27_iRT_UPS_decoy_OpenMS21compatible.tsv -sort_swath_maps -readOptions cacheWorkingInMemory -tempDirectory /tmp/ -batchSize 1000 -tr_irt iRTassays.TraML  -swath_windows_file SWATHwindows_analysis.tsv -threads 4"
OpenSwathWorkflow  -in olgas_K121026_001_SW_Wayne_R1_d00.wiff.profile.lc_05.mzML.gz \
-out_tsv olgas_K121026_001_SW_Wayne_R1_d00.wiff.osw.profile.compress.lc_05.tsv \
$OPTIONS $MS1OPTIONS -out_chrom /tmp/testout.sqMass
```

if you have some test data that does not work, please send it over and I will have a look

**Pull request merged**
