### PR TITLE
[Feature] DeepLC pyTOPP

### PR DESCRIPTION
**Pull request by dvdvgt**
# Description

This PR aims to add [DeepLC](https://github.com/compomics/DeepLC) as a pyTOPP tool.

# Todo
- [ ] Create calibration data (as pandas DataFrame) in order to calibrate DeepLC.

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
For discussion: to have proper retention times we probably need to filter the idXML for confident identifications on which we base the retention times. E.g., we could filter by 1% FDR

TODO:
- check if target/decoy information is present
- if so, calculate and filter by 1% FDR using the FalseDiscoveryRate algorithm with psm fdr set to 0.01
- write the resulting peptides out as calibrants

TODO for percolator:
- add extra_features meta value to SearchParameters that contains "score" and "RT error" so percolator can use the additional information for score recalibration

**Comment by dvdvgt** [comment]
# How to setup the environment

1. [Install `miniconda`](https://docs.conda.io/en/latest/miniconda.html) 
2. Create a new conda environment. 
   It is mandatory that you specify a python version >= 3.6 and <= 3.8 as DeepLC requires at least python 3.6 and tensorflow only supports python 3.8 or earlier. (The name of the environment is of course up to you. You may choose a shorter name and substitute the env name in the following commands accordingly). 
  `$ conda create -n pyopenms_env python=3.7`
  Refer to the [official documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) for more information.
3. Add the required channels in order to install `deeplc`
   `$ conda config --add channels bioconda conda-forge`
4. Install `pyopenms` and `deeplc` (other dependencies will be detected and installed automatically. This may take some time):
    `$ conda install -n pyopenms_env pyopenms deeplc`
5. **Activate** the newly created environment.
    `$ conda activate pyopenms_env`
6. Optionally setup your IDE to use the newly created conda environment and python interpreter in order to have proper code completion and linting. Please refer to the documentation of your IDE of choice.

**Comment by jpfeuffer** [comment]
You could provide an [environment.yml](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment)

**Comment by timosachsenberg** [comment]
will be replaced / extended by Tobias

**Comment by timosachsenberg** [comment]
replaced by https://github.com/OpenMS/OpenMS/pull/5658

**Pull request closed without merging**
