### PR TITLE
Add conversion for MSSpectrum & PeptideHit to spectrum_utils MsmsSpectrum

### PR DESCRIPTION
**Pull request by matteopilz**
## Description

Converting from MSSpectrum to MsmsSpectrum works with tested spectrum. PeptideHit is currently missing and interactive plotting needs to be tested as well.

image

image

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by matteopilz** [comment]
Added the peptideHit conversion, thanks to @Arslan-Siraj. I have also added a predefined function for disabling annotation types like ion type or neutral losses.
```
sp = peptide_hit_to_spectrum_utils(hit)
fig, ax = plt.subplots(figsize=(12, 6))
sup.spectrum(sp, grid=False, ax=ax, annot_fmt=lambda x: show_annotations(x, charges=False, losses=True, adducts=True))
plt.show()
```

**Comment by matteopilz** [comment]
What I currently don't know is the correct assignment of compound, chemical formula and neutral loss. spectrum_utils is using the ProForma 2.0 annotation standard, while we follow a seemingly different formatting. https://spectrum-utils.readthedocs.io/en/latest/annotating.html#supported-proforma-2-0-features

**Review by timosachsenberg — APPROVED** [review]
would be good to have it somewhere tested

**Comment by Arslan-Siraj** [comment]
image
what discussed with @matteopilz 
- every peak should at least +1 charge 
- parse_annotation function can be modify, depends on use case
-  suggestion: put charge state at the end of annotaion

**Comment by Arslan-Siraj** [comment]
Currently, checking with different use cases.

**Comment by matteopilz** [comment]
@Arslan-Siraj, have you found something that needs changing?

**Comment by timosachsenberg** [comment]
any update here? @Arslan-Siraj did you have a chance to look at it?

**Comment by timosachsenberg** [comment]
do you have some screenshots how the plots currently look? Just to double check so we can merge

**Comment by matteopilz** [comment]
image
image

**Comment by timosachsenberg** [comment]
looks good to me but I don't have a good overview on how this is currently documented and reflected in dependencies (e.g., is spectrum_utils in the requirements etc.) if we merge this now. Just want to make sure that this does not break pyopenmd docs(e.g., not render anymore because it now depends on spectrum_utils?)

**Comment by matteopilz** [comment]
Only the function `spectrum_to_spectrum_utils` depends on spectrum utils. The import is inside the function and should throw by default a dependency error if spectrum utils is missing and the function is called.

**Comment by timosachsenberg** [comment]
is this dependency anywhere reflected (e.g. requirements.txt?) because such an exception might be highly annoying for users.

**Comment by matteopilz** [comment]
I have put the dependency in our API documentation now. I don't think we should put it in the requirements.txt, as it is really only necessary for the conversion.

**Comment by timosachsenberg** [comment]
@jpfeuffer if some of our pyopenms code depends on a third-party library. What is the proper way to handle this dependency?
e.g. to make the tutorial work with this code we need to add it here: https://github.com/OpenMS/pyopenms-docs/requirements.txt
would that be fine and pytonic?

**Comment by jpfeuffer** [comment]
Since the imports are inside the function (hopefully only the ones that use specutils classes), python will raise ImportErrors when using that function (only) without specutils installed.

However, ideally, you would add optional dependencies and check them with try except early on.
https://stackoverflow.com/questions/27361427/how-to-properly-deal-with-optional-features-in-python

**Comment by timosachsenberg** [comment]
I believe that for the time being, we can accept that. Having the optional dependencies would probably be better in the future.
@matteopilz can you add this dependency also to the pyopenms-docs repo. As I understood it this will be used in the tutorials right?

**Comment by matteopilz** [comment]
Currently we do not have any tutorials about the conversion, but I can write one.

**Comment by timosachsenberg** [comment]
the question is: do we want to use spectrum_utils for plotting? then the conversion should be called internally by the current plot spectrum methods we have (such that the conversion is not visible to the user).

**Comment by matteopilz** [comment]
I think that is something we should discuss with everyone in the team currently making / requiring visualization tools.

**Comment by timosachsenberg** [comment]
k please open a github discussion and assign people.https://github.com/OpenMS/OpenMS/discussions

**Pull request closed without merging**
