### PR TITLE
[FIX] fix return a reference to local variable.

### PR DESCRIPTION
**Pull request by timosachsenberg**
this fixes the build issue so I would like to merge this quickly. @enetz it currently doesn't check for the presence of the name and if it is missing we probably get a segfault. Best way would probably be to return the iterator but then the function is not easily wrapped with pyOpenMS.

### CODE REVIEW

**Comment by cbielow** [comment]
mhh.. both solutions are illegal C++ if the name is not found :/ (segfault as you mentioned)

Why not use the iterator and provide another (less efficient) interface for pyOpenMS? Or would Raw pointers be any better?
Alternatively, throw an exception if the array is not found -- but I guess sometimes its expected that it does not exist, so exception is not warranted.

**Comment by timosachsenberg** [comment]
@hroest is there any way we could use the iterator solution? would this mean that autowrap needs to be extended or only some addon file for pyOpenMS

**Comment by timosachsenberg** [comment]
another solution would be to return a reference to a static instance of an empty vector

**Comment by cbielow** [comment]
since the return value is not const, how does the user tell if he got the real array or the 'does not exist' dummy version? People might even start to fill in data... this gets messy quickly...

**Comment by timosachsenberg** [comment]
Yep. These are no real solutions. Iterator would be best or we need a has/get combination

**Comment by hroest** [comment]
there are ways to get an iterator, but its quite ugly and also there is a chance that it will point to an invalid `end()` element which cannot be tested in Python. See https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/MSChromatogram.pxd#L46 for examples, so `libcpp_vector[Klass].iterator` works as return value

**Pull request merged**
