### PR TITLE
[NOP] Changes Years in non-source header and adds newlines at end of file for some.

### PR DESCRIPTION
**Pull request by jpfeuffer**
I used sed to change the years in the files. It automatically added newlines for some other files. I guess it is favorable to have them.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
looks good

**Comment by hroest** [comment]
hey guys, this does not look good at all just before the release: tests on all travis builds fail !!

**Comment by hroest** [comment]
seems like you need to update the sha1 hashes in these files: http://cdash.openms.de/viewTest.php?onlyfailed&buildid=174048

**Comment by jpfeuffer** [comment]
Yes. I think you are right! The added newline affects the hash of course.

**Comment by jpfeuffer** [comment]
See #1957 .

**Pull request merged**
