### PR TITLE
[FIX] blind attempt to fix clang compile error

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by cbielow** [comment]
test timed out.
+1 for merge

**Comment by timosachsenberg** [comment]
interesting... seems to be an clang issue:
https://llvm.org/bugs/show_bug.cgi?id=13657

**Comment by timosachsenberg** [comment]
"The workaround is to add parentheses around the default argument expression."

**Comment by hendrikweisser** [comment]
> "The workaround is to add parentheses around the default argument expression."

Yes, the changes in this pull request don't actually solve the compile error (for me).

**Comment by cbielow** [comment]
mhh.. so if you have it running, could you try the suggested fix please?!
We are just doing reinforcement learning here :)

**Comment by hendrikweisser** [comment]
> so if you have it running, could you try the suggested fix please?!

The suggested fix works. Do you want to revert the "string -> String" change, then?

**Comment by cbielow** [comment]
since String is not required here, yes please

**Comment by hendrikweisser** [comment]
@timosachsenberg: Can you make another pull request, please?

**Comment by timosachsenberg** [comment]
yep

**Pull request merged**
