### PR TITLE
Fix/qt5 fix3d

### PR DESCRIPTION
**Pull request by hroest**
fixes some issues on Linux with 3D rendering

- removes flicker
- fixes the positioning of the 3D object

### CODE REVIEW

**Comment by hroest** [comment]
for Linux, this is a marked improvement :-) 

before:

3dview_1

after:

paint3d_after

**Comment by hroest** [comment]
In my testing, `QPainter::beginNativePainting()` was responsible for the behavior above where nothing would get painted // all painting would be in the upper right corner

Regarding begin/end I dont think we need them and they only create warning output on the CLI. see also the docu: http://doc.qt.io/qt-5/qpainter.html#begin

* Note that most of the time, you can use one of the constructors instead of begin(), and that end() is automatically done at destruction.

**Comment by hroest** [comment]
@jpfeuffer @timosachsenberg can you also have a look here?

**Comment by hroest** [comment]
@jpfeuffer @timosachsenberg can you also have a look here?

**Comment by hroest** [comment]
@jpfeuffer @timosachsenberg can you also have a look here? merge?

**Comment by timosachsenberg** [comment]
I think this is good to merge. Can't confirm on mac right now.

**Pull request merged**
