### PR TITLE
Try to add D and T to elements

### PR DESCRIPTION
**Pull request by jpfeuffer**
untested

### CODE REVIEW

**Comment by timosachsenberg** [comment]
see **https://github.com/OpenMS/OpenMS/pull/5448/files#diff-8ebe022fac5a9f3c0eb06f940c6706d8d9bb652131218ee474d495451af8627dR154**
not sure if we should add it that way. Were do you need it? Parsing?

**Comment by jpfeuffer** [comment]
Yes. A lot of DBs have D in chemical formulas.

**Comment by timosachsenberg** [comment]
I would prefer the parser I think if it is easily feasible.

**Comment by timosachsenberg** [comment]
But if it is well documented I guess it would be also fine to do it your way

**Comment by timosachsenberg** [comment]
superseeded by https://github.com/OpenMS/OpenMS/pull/5453

**Pull request closed without merging**
