### PR TITLE
Fix/py

### PR DESCRIPTION
**Pull request by hroest**
@jpfeuffer can you update autowrap to the newest version on cdash?

```
pip -U install autowrap
```

should do it

### CODE REVIEW

**Comment by hroest** [comment]
makes pyOpenMS compile again ...

**Comment by hroest** [comment]
@timosachsenberg can this go into master as well?

**Comment by timosachsenberg** [comment]
sure. I guess I can just cherry-pick the merge commit 77c863b? Will try...

**Comment by timosachsenberg** [comment]
```
git cherry-pick 92923a6..787b82d
```
did the job

**Pull request merged**
