### PR TITLE
fix mzTab2tsv_PRT script

### PR DESCRIPTION
**Pull request by lars20070**
Fixes R script for `mzTab` post-processing of the `PRT` section.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
can you give a visual output how this looks like

**Comment by lars20070** [comment]
@timosachsenberg Is `opt_global_protein_group_type` in `mzTab` somewhere documented?
I have got Fido output without any `opt_global_protein_group_type = protein_group`.

**Comment by timosachsenberg** [comment]
it is not documented because it is an optional column.

**Comment by lars20070** [comment]
Do you have an example `mzTab` with `single_protein`, `protein_group` and `indistinguishable_group`? Then I could figure out how groups are reported.

**Comment by jpfeuffer** [comment]
I think the standard behaviour of Fido is to just group indistinguishable groups. Connected components (bigger groups) are currently only annotated if you do the group resolution with the flag.

**Pull request merged**
