### PR TITLE
Major update of FeatureFinderIdentification

### PR DESCRIPTION
**Pull request by hendrikweisser**
FeatureFinderIdentification (FFId) gets the ability to combine peptide IDs from multiple LC-MS/MS runs in a smarter fashion. "Internal" IDs (same LC-MS/MS run) are distinguished from "external" ones (other LC-MS/MS runs). A machine learning approach (SVM) is used to predict correct features for external IDs.

Introduces two helper classes, SimpleSVM (wrapper of LIBSVM for classification of features) and ElutionModelFitter (for fitting elution models to features). Tests for those classes are missing at the moment, but will be added.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@hendrikweisser these are quite some changes. Could you briefly explain here how the SVM is used? Can we find some better or more expressive names for the various SVM Wrapper we have?

**Comment by hendrikweisser** [comment]
> Could you briefly explain here how the SVM is used?

From the FFId tool documentation:

> The aim is to detect features that enable the quantification of (ideally) all peptides in the identification input. This is based on the following principle: When a high-confidence identification (ID) of a peptide was made based on an MS2 spectrum from a certain (precursor) position in the LC-MS map, this indicates that the particular peptide is present at that position, so a feature for it should be detectable there.
> The situation becomes more complicated when several LC-MS/MS runs from related samples of a label-free experiment are considered. In order to quantify a larger fraction of the peptides/proteins in the samples, it is desirable to infer peptide identifications across runs. Ideally, all peptides identified in any of the runs should be quantified in each and every run. However, for feature detection of inferred ("external") IDs, the following problems arise: First, retention times may be shifted between the run being quantified and the run that gave rise to the ID. Such shifts can be corrected (see @ref TOPP_MapAlignerIdentification), but only to an extent. Thus, the RT location of the inferred ID may not necessarily lie within the RT range of the correct feature. Second, since the peptide in question was not directly identified in the run being quantified, it may not actually be present in detectable amounts in that sample, e.g. due to differential regulation of the corresponding protein. There is thus a risk of introducing false-positive features.
> FeatureFinderIdentification deals with these challenges by explicitly distinguishing between internal IDs (derived from the LC-MS/MS run being quantified) and external IDs (inferred from related runs). Features derived from internal IDs give rise to a training dataset for an SVM classifier. The SVM is then used to predict which feature candidates derived from external IDs are most likely to be correct.

Please look at the documentation for more details. I also have a manuscript about the algorithm that we want to publish, which I'll reference in the documentation once it's out.

> Can we find some better or more expressive names for the various SVM Wrapper we have?

The purpose of my wrapper was to make a simple, all-purpose interface to the main (but not all) functionality of LIBSVM. I looked into using the existing one, but found that too complex and specialized. I can't think of a better name than "SimpleSVM", but maybe you have a suggestion?

**Comment by timosachsenberg** [comment]
@cbielow @jpfeuffer any idea for a name? Would MultiClassSVM be a better name?

**Comment by jpfeuffer** [comment]
Actually I don't think SimpleSVM is too bad. But yes, maybe we could add something about why it is simple (e.g. only supports classification, only linear and RBF kernel).
But it could get long in this case.

**Comment by hendrikweisser** [comment]
> Would MultiClassSVM be a better name?

I'm not a fan of that because the only use case so far is two-class classification.

> But yes, maybe we could add something about why it is simple (e.g. only supports classification, only linear and RBF kernel).

More kernels could be easily added in the future (as long as LIBSVM supports them), so I wouldn't want to put that in the class name.

The restriction to classification is probably more ingrained in the code (although I haven't thought about how much would need to be changed to support regression). If you want a longer name, maybe "[Simple]SVMClassifier"? (However, to some extent the "M" already implies classification; otherwise it should be "SVR" for "Support Vector Regression".)

**Comment by timosachsenberg** [comment]
@hendrikweisser ok we can keep it if there is no strong opinion or better suggestions. FeatureFinderIdentification is currently a TOPP tool and would require tests for inclusion of the PR.

**Comment by hendrikweisser** [comment]
> FeatureFinderIdentification is currently a TOPP tool and would require tests for inclusion of the PR.

There are already tests for the TOPP tool. I'm working on class tests for SimpleSVM and ElutionModelFitter.

**Comment by hendrikweisser** [comment]
Okay, class tests are in place. CI tests run through, except for one time-out.
Any more comments?

**Comment by timosachsenberg** [comment]
thanks for the PR. Adding pyopenms bindings would be great I think but no objection to the merge from my side.

**Comment by timosachsenberg** [comment]
@hendrikweisser can you give a rough estimate on the memory, speed, and computational requirements.
For instance, would it be feasible to run your approach on 200 maps?

**Comment by hendrikweisser** [comment]
@timosachsenberg: I haven't tested on such a large dataset, but would of course be very interested to see how that goes. To give you some more information:
- I haven't invested time to optimize for speed. On my main benchmark dataset, it took up to 27 hours per file (to quantify ~40,000 distinct peptides, using 337,000 IDs in total).
- The algorithm uses only one thread, so you can run multiple files in parallel.
- You analyse one mzML file at a time, but (potentially) using IDs from all files.
- Memory shouldn't be much of an issue (since it's one mzML at a time), but I haven't profiled it.

The runtime scales about linearly with the number of distinct peptides to analyse, plus some offset for reading data and training the SVM. The spread in RT of your peptide IDs influences the runtime as well (the XICs get longer), but potentially also affects the accuracy of the algorithm. So having reproducible chromatography and a good RT alignment helps (although the point of the SVM approach is that you don't have to fully rely on the RTs).

With 200 runs, I would expect a lot of redundancy in the peptide IDs, but also significant differences in the chromatography between early and late runs. So there may be some challenges there in avoiding to accumulate redundant IDs with less reliable RTs (maybe use `IDMerger -add_to`). Similarly, you may want to control for false positives (FDR) at the whole dataset level, rather than just in each run individually.

If you want to do protein quantification, a nice idea might be to remove uninformative peptides (that map to too many proteins) before doing the FFId runs, to save time there.

I'm happy to discuss this more thoroughly with you directly if you want. In any case, a good starting point may be to just run FFId on one (or more) sample file(s) using only the IDs from that file. That should avoid all complications and give you a baseline for what runtime and results to expect.

**Comment by timosachsenberg** [comment]
Thanks for the answer. I think we can chat about this at the developer retreat.

**Comment by hroest** [comment]
@hendrikweisser which part is slow in your experience, does the OpenSWATH part slow it down or is it some other part?

**Comment by hendrikweisser** [comment]
@hroest: I haven't profiled the execution, but just from observing the progress output in the log, the majority of the time is spent in the "inner loop" running feature detection for every peptide. There, the heavy lifting (chromatogram extraction and peak group detection) is done by OpenSWATH.
In that context, one idea for saving time would be to "switch off" the calculation of OpenSWATH scores that are not needed by FFId.

**Comment by hroest** [comment]
Hmm it seems a bit strange as we routinely do 20k assays with 100k+ chromatogram extractions and scoring in less than 1 hour and in your case things should be easier as there are no MS2. The only important point here is to "bundle" chromatogram extraction and not do it 1 by 1 as this is very inefficient. Best to do a few thousand chromatograms together and then score them individually as each extraction requires the algorithm to go through all spectra and all peaks, e.g. it is `O(N*M + k)` for N spectra with M peaks each for k chromatograms, so it scales well with the number of chromatograms provided but has a high constant overhead for a given map

**Comment by hendrikweisser** [comment]
> The only important point here is to "bundle" chromatogram extraction and not do it 1 by 1 as this is very inefficient.

I was not aware of that. The algorithm currently extracts chromatograms one by one. :-(

**Pull request merged**
