### PR TITLE
Merge Release 2.7.0

### PR DESCRIPTION
**Pull request by oliveralka**
# Description

Corresponding to #5540

Fixing the pyopenms introduced merge conflicts, without changing the actual release/2.7.0 branch.

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Review by timosachsenberg — APPROVED** [review]

**Comment by poshul** [comment]
This looks much neater, Thanks!

**Comment by oliveralka** [comment]
rebuild jenkins

**Comment by poshul** [comment]
The Mac build fails with `   Error when uploading file: /Users/builder/jenkins/ws/openms/PR/bldtst/85c1a982/build/Testing/20210920-1434/Test.xml
   Error message was: The requested URL returned error: 500 Internal Server Error
   Problems when submitting via HTTP`
   Is this a Jenkins issue or something with the branch?

**Review by poshul — APPROVED** [review]

**Comment by jpfeuffer** [comment]
Cdash issue only. It sometimes overloads when too many things (mostly warnings) are uploaded at the same time. We need to fix some warnings, clean Cdash, and/or reduce the limit for warnings to be uploaded.

**Comment by poshul** [comment]
Okay, good to know. We should be good to merge it then?

**Pull request merged**
