### PR TITLE
[DOC] Updated installation instructions for contrib/Qt and VS2015

### PR DESCRIPTION
**Pull request by cbielow**
[DOC] updated and simplified installation instructions for Windows (up to and including VS2015), including embedded patch.exe, updated Qt4 instructions and fixes typos. This completes OpenMS/contrib#35.

Other minor changes:
[FEATURE] build.bat uses all CPU cores now by default, minor typo fixed

### CODE REVIEW

**Comment by cbielow** [comment]
it seems the test outright worked:
```
CMake Error at CMakeLists.txt:35 (cmake_minimum_required):
  CMake 2.8.10 or higher is required.  You are running version 2.8.7
``` http://cdash.openms.de/viewConfigure.php?buildid=210816

**Comment by cbielow** [comment]
by making Travis use 'trusty' the CMake restriction is gone, but now:
```
-- PDFLaTeX missing. Disabling 'doc_tutorials' target!
CMake Error in src/openms/CMakeLists.txt:
  Cannot find source file:

    source/CHEMISTRY/CrossLinksDB

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
```
Ideas anyone? I cannot find `CrossLinksDB` anywhere in the source. Weird magic?

**Comment by cbielow** [comment]
clang tests fail (since this now is clang version 3.5.0 (tags/RELEASE_350/final)) instead of clang version 3.4 in the previous builds....
Not sure though.
Since this is a pure documention commit, it cannot be changed code in OpenMS itself

**Comment by cbielow** [comment]
build passed (Clang timed out). Merge?

**Comment by jpfeuffer** [comment]
I would say yes, but we should investigate the clang issue. If the builds always timeout for example, it does not make sense to keep them.

**Comment by cbielow** [comment]
Yes, agreed. Will open a new ticket for that and merge this one.

**Pull request merged**
