### PR TITLE
[discussion] remove utils and model as topp tool with utilities category

### PR DESCRIPTION
**Pull request by timosachsenberg**
## Description

Simplify OpenMS by removing the concept of a util. 
I personally think this is a good idea as it simplifies the build system, makes it more accessible for users etc.
There might be some implications on packaging etc. that I am not aware of so I think this is worth discussing.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
I move DecoyDatabase from util to topp.
Now I get an error message about undefined reference to boost regex.

I even removed boost regex from this file, so I guess it is included through the headers.
```
/usr/bin/ld: src/topp/CMakeFiles/DecoyDatabase.dir/DecoyDatabase.cpp.o: undefined reference to symbol '_ZNK5boost16re_detail_10740031cpp_regex_traits_implementationIcE17transform_primaryB5cxx11EPKcS4_'
```

How can this happen? I quickly skimmed the UTIL target but did not see any additional boost being added as target_link_library or else.

**Comment by jpfeuffer** [comment]
It's specific for the tool:
https://github.com/search?q=repo%3AOpenMS%2FOpenMS+Boost%3A%3Aregex+language%3ACMake&type=code&l=CMake

**Comment by timosachsenberg** [comment]
Builds and seems to be in a state for discussion.
I think I changed all obvious things like targets, docs, build system etc.
Do we need to update other repos as well? e.g., GKN? or do we have somewhere else different semantics depending on whether it is a tool or util?

**Comment by timosachsenberg** [comment]
Follow-up task:
- add proper categories for some (former) utils

**Comment by jpfeuffer** [comment]
Fine with me. There might be some smaller changes to KNIME categories and User docs necessary.

**Review by poshul — APPROVED** [review]

**Comment by timosachsenberg** [comment]
general feedback was positive for removel. will merge and update documentation if CI runs through

**Pull request merged**
