### PR TITLE
[ADD] GitHub Action Clang Format

### PR DESCRIPTION
**Pull request by oliveralka**
# Description

Please include a summary of the change and which issue is fixed.
fixes: #5534

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Et voilà

**Comment by timosachsenberg** [comment]
> hm, which style do we want to use?
> https://clang.llvm.org/docs/ClangFormatStyleOptions.html

Isn’t there a clang format file already in the repo?

**Comment by timosachsenberg** [comment]
I think running clang format on only the files of a PR is probably best. I wonder what the best point and way for adding format changes is. What do other projects do?

**Comment by timosachsenberg** [comment]
is this done and can we merge it?

**Comment by oliveralka** [comment]
Yes, but we have to test after merging if the keyword works as expected.

**Comment by timosachsenberg** [comment]
AccurateMassSearch seems to contain the wrong formatting .

**Comment by oliveralka** [comment]
Ah, correct, that was supposed to fixed by using "/reformat". That does only work if it is already merged to develop. I will revert the changes in AMS and push again.

**Comment by timosachsenberg** [comment]
minor formatting "bugs" I found. + means added by clang-format
Maybe we can add those to the yaml if we have a consent on them
```
     template<typename ContainerValueType, bool addMassTraces>
-    struct ContainerAdd_
-    {
+    struct ContainerAdd_ {
       static void addData_(SpectrumType* spectrum, const ContainerValueType* item);
       static void addData_(SpectrumType* spectrum, const ContainerValueType* item, const StringList& store_metadata_names);
     };
```

```
   /// Constructor
   MSExperiment::MSExperiment() :
-    RangeManagerType(),
-    ExperimentalSettings(),
-    ms_levels_(),
-    total_size_(0)
-  {}
+      RangeManagerType(),
+      ExperimentalSettings(),
+      ms_levels_(),
+      total_size_(0)
+  {
+  }
```

```
     bool meta_present = false;
     for (Size i = 0; i < spectra_.size(); ++i)
     {
-      if (!spectra_[i].getFloatDataArrays().empty() 
-        || !spectra_[i].getIntegerDataArrays().empty() 
-        || !spectra_[i].getStringDataArrays().empty())
+      if (!spectra_[i].getFloatDataArrays().empty() || !spectra_[i].getIntegerDataArrays().empty() || !spectra_[i].getStringDataArrays().empty())
       {
         meta_present = true;
       }
```

```
-    if (ms_level == 1) // assumes there is not level 0
+    if (ms_level == 1)// assumes there is not level 0
     {
```

```
-    if (pc_spec == spectra_.cend()) return -1;
-    return pc_spec - spectra_.cbegin(); 
+    if (pc_spec == spectra_.cend())
+      return -1;
+    return pc_spec - spectra_.cbegin();
```

**Comment by oliveralka** [comment]
I think we just have to specify our preference in the `.clang-format` file, or?

**Comment by timosachsenberg** [comment]
yes some are documented here: https://github.com/OpenMS/OpenMS/wiki/Coding-conventions

**Pull request merged**
