### PR TITLE
re-implement StopWatch to allow for 'resume()' and querying time while still running

### PR DESCRIPTION
**Pull request by cbielow**
Cleans up the implementation and fixes a bug (querying a stopwatch without stop() would yield arbitrary numbers -- at least on Windows)

Also allows to `start()` ... `stop()` `<do not time this>` `resume()`  to allow for more fine-grained measurements (e.g. benchmarking).

It also prevents accidental wrong usage (e.g. stop()'ing twice) by throwing exceptions.

### CODE REVIEW

**Comment by cbielow** [comment]
ready for merge

**Comment by timosachsenberg** [comment]
could some of the new code in the header files be moved to the c++ files?

**Comment by cbielow** [comment]
yes, but the `TimeDiff_` stuff is not that much.
I thought about using PIMPL. This would even avoid including any`*time` headers. But it forces me to use new/delete... so I thought not worth the trouble... Any strong opinions?

**Comment by timosachsenberg** [comment]
PIMPL might be overkill. 
Just thought we were pretty good in moving implementation to cpp files so I think we should continue that.

**Comment by cbielow** [comment]
I tried PIMPL and it just makes the code look ugly, due to forwarding functions and new/delete (could be solved by unique_ptr, at the cost of including `<memory>`) and more code in general.
So I simply moved stuff to cpp.

**Pull request merged**
