### PR TITLE
bump autowrap in travis CI

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

update build dependency for our pyOpenMS builds on travis

Also please:
- Make sure that you are listed in the AUTHORS file
- Add relevant changes and new features to the CHANGELOG file

# Checklist:
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Can you please update it everywhere else, too?
GitHub Actions, manylinux dockerfile, jenkins

**Comment by jpfeuffer** [comment]
Can't we put a requirements.txt somewhere and use this? Potential with version ranges like >=22.0?

**Comment by jpfeuffer** [comment]
Also: This broke the conda builds. Please update the autowrap package on conda as well. Full release and add a min. requirement to our package.

**Comment by timosachsenberg** [comment]
Feel free to revert. I can take a look at it once I am back

**Pull request merged**
