### PR TITLE
Poshul test package

### PR DESCRIPTION
**Pull request by poshul**
Force building of packages on new CI yml. DO NOT MERGE!!!

### CODE REVIEW

**Comment by jpfeuffer** [comment]
I would suggest deactivating old CI first to not reach GitHub limits while testing.
You can also use manual dispatch:
- no additional branch
- you can test the workflow inputs
- no temporary hacking of the do_package variable

**Comment by poshul** [comment]
> 

Hmm, I see that there is a workflow_dispatch trigger in the yml, but I don't see a "run workflow" button under the actions tab.

**Comment by jpfeuffer** [comment]
Ah yes, you need to merge first.
I think it might be already ready to replace openms-ci.
I think normal tests work already.

**Comment by poshul** [comment]
There's some stuff on the archive server that needs to be resolved before I will feel comfortable running this on the nightlies. If you are okay with merging it with the `rsync` commands commented out I'd be okay with that.

**Pull request closed without merging**
