### PR TITLE
Fix toppas merge

### LINKED ISSUE #2166: IDMerger fails in TOPPAS
[This](https://gist.github.com/lars20070/b97e58533f36fef5ae1346c1459b2a60) IDMerger workflow fails for any `idXML` [files](https://gist.github.com/lars20070/f03d5c77ac65a7022e82b9d1fe390884) with
```
Did not find upstream nodes with un-recycled names. Something is fishy!

==============================================================================
11:53:57 ERROR: IDMerger failed!
Did not find upstream nodes with un-recycled names. Something is fishy!
```
From the command line `IDMerger` works fine.
screen shot 2016-09-02 at 11 53 34

### PR DESCRIPTION
**Pull request by cbielow**
fix #2166 and the TOPPAS tutorials (updated some TOPP params and GenericWrapper examples)

### CODE REVIEW

**Comment by timosachsenberg** [comment]
seems good - @lars20070 can you test this?

**Comment by lars20070** [comment]
Does not fix #2166. Same error message.
Tested under Windows and OS X.

**Comment by timosachsenberg** [comment]
did you use the master branch?

**Comment by lars20070** [comment]
Tested on `master`. This fixes #2166.
Thanks @cbielow and @timosachsenberg.

**Pull request merged**
