### PR TITLE
Update THIRDPARTY with Sirius 5.6.3

### PR DESCRIPTION
**Pull request by axelwalter**
## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
macOS fails somehow

**Comment by bernt-matthias** [comment]
Would suggest to go for 5.6.4., because https://github.com/conda-forge/staged-recipes/pull/16235/

**Comment by jpfeuffer** [comment]
Oh yes, it would be very useful to have the same.

**Comment by jpfeuffer** [comment]
Where do you see that error? SiriusAdapter seems to work fine.

**Comment by jpfeuffer** [comment]
Only AGM and the output tests are failing.

**Comment by axelwalter** [comment]
The outputs are [empty](https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/PR/job/bldtst/compiler=g++-9,os_label=ubuntu_2004/3894/artifact/build/src/tests/topp/) and [SEVERE  13:45:23 - Error loading CBC!](https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/PR/job/bldtst/compiler=g++-9,os_label=ubuntu_2004/3894/artifact/build/General_Testing/Testing/Temporary/LastTest_20230212-1310.log) errors are raised during Sirius execution. 
In the last commit I updated the jar files again to make sure everything is there, however still the same test results.
I would suggest to revert to the latest release version 5.6.3 and prior to the OpenMS 3.0 update to the latest stable Sirius, instead of updating every snapshot.

**Comment by poshul** [comment]
> 
I agree with @axelwalter on this. I think updating to resolve the security issue is one thing, but at this point we are spending a lot of time dealing with the fact that Sirius behaves differently between versions.

**Comment by jpfeuffer** [comment]
The update here was to be on the same state as bioconda. I have NO idea why they chose a snapshot. I would not have suggested to update if I knew it was a snapshot.

**Comment by jpfeuffer** [comment]
Ideally, we would have just much less strict tests for Sirius that mainly test execution and at least a certain amount of results. Should not be too hard.

**Comment by jpfeuffer** [comment]
See also #6705. We should separate THIRDPARTY from TOPP and move towards releases with and without thirdparty.

**Comment by axelwalter** [comment]
> 

Good point, we need more robust testing for sure. Will look into that in a separate PR.

**Review by poshul — APPROVED** [review]

**Pull request merged**
