### PR TITLE
[NOP] renamed "thirdparty" folder to the more common "extern"

### PR DESCRIPTION
**Pull request by timosachsenberg**
## Description

most current modern cmake tutorials I found suggest "extern" so why not...
also reduces ambiguities with THIRDPARTY folder - which contains executables

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@jpfeuffer this is globally set.
https://github.com/OpenMS/OpenMS/blob/af95149b2d0b2aa24a37da75ade82d7ae6d07cbc/cmake/compiler_flags.cmake#L190-L195
is there an easy way to just do instead:
set_target_properties(targetname PROPERTIES POSITION_INDEPENDENT_CODE ON)

I could do that in add_library_macros.cmake but would we also need this somewhere else?

**Comment by jpfeuffer** [comment]
Yes, you need it exactly here for external thirdparties/extern if you build them as static and then build OpenMS as dynamic.

**Comment by jpfeuffer** [comment]
But if you want to set it target-based, globally, you can set https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html#variable:CMAKE_POSITION_INDEPENDENT_CODE

Make sure to allow it to be set from outside.

**Comment by poshul** [comment]
Is this going to require changes in our CI tooling as well?

**Comment by jpfeuffer** [comment]
I don't think so

**Comment by timosachsenberg** [comment]
Why do we need to check for WTH_FPIC anyway?
Couldn't we just set the CMAKE_POSITION_INDEPENDENT_CODE target default always to ON and get rid of this blog?
or is there any disadvantage?

**Comment by timosachsenberg** [comment]
> Is this going to require changes in our CI tooling as well?

No, this is just about external libraries that are not included via contrib but directly embedded in our source tree.

**Comment by jpfeuffer** [comment]
Some linkers apparently do not support fpic.
And people might want to build openms completely static.

**Comment by jpfeuffer** [comment]
The modern way to check, is this: https://cmake.org/cmake/help/latest/module/CheckPIESupported.html#module:CheckPIESupported

**Pull request merged**
