### PR TITLE
Clean-up of UTILS documentation

### PR DESCRIPTION
**Pull request by hendrikweisser**
More documentation improvements:
- removed broken entry for PeakPickerRapid (tool removed)
- capitalized headers consistently
- sorted entries in sections alphabetically
- moved "Misc" section to just above "Deprecated"

### CODE REVIEW

**Comment by hroest** [comment]
I guess we removed the PPRapid in 571e27deb6f3d9cbd0b2bc92fd337174a992b090 but we have #548 to add it again. This was Erhans tool, I think we removed it for the 1.11 release and never added it again. I forget why however but I think the plan was to add it again at some point. Maybe @timosachsenberg still remembers?

**Comment by timosachsenberg** [comment]
It had some bugs that lead to crashes and sometimes problems with overshooting fits.

**Comment by hendrikweisser** [comment]
When PPRapid gets added again it should also be added to the documentation page. Surely we don't want to keep a broken link in the meantime.

**Comment by hroest** [comment]
no we dont but we want to keep track of what and why we do stuff :-) sadly, since Erhan is not that active any more I dont really see a big future for that tool anyways

**Pull request merged**
