### PR TITLE
[FEATURE] make OpenMS home directory configurable by environmental

### PR DESCRIPTION
**Pull request by timosachsenberg**
variable (e.g. for parallel installation of KNIME, PD nodes)

@hannesveit

### CODE REVIEW

**Comment by timosachsenberg** [comment]
that we we could set the path to the OpenMS.ini from e.g. an environment created in PD or CD (on calling a node)

**Comment by cbielow** [comment]
looks good. But we don't (-- and probably can't) have tests for this -- please play around a little to make sure no old functionality is broken.

+1

**Comment by cbielow** [comment]
actually, you could write a test...
just use setenv(<someTempDir>) in File_test and see if .OpenMS.ini gets created upon calling getSystemParameters().

**Comment by timosachsenberg** [comment]
probably have to adapt line 437 too

**Comment by timosachsenberg** [comment]
@cbielow I can set the environment variable to a unique folder in the tmp directory and check if the ini was created I guess. I then need to clean the folder up at the end of the test and unset (=remove) the environment variable.

**Comment by cbielow** [comment]
Yes, but no need to unset it if you do it at the end of the test 
(changes are not permanent; its rather similar to setting a $PATH in a 
terminal)

Am 10/31/2015 um 10:05 AM schrieb Timo Sachsenberg:

**Pull request merged**
