### PR TITLE
fix to detect and include file system

### LINKED ISSUE #6496: std::filesystem not properly detected / linked on older compiler
sqlitecpp apparently doesn't properly detect if std::filesystem is present in <filesystem> or <experimental/filesystem>
Appeared first in gitpod which uses ubuntu 18.04 and gcc 7
related:
https://gitlab.kitware.com/cmake/cmake/-/issues/17834
https://github.com/nlohmann/json/issues/3090

first attempt in implementing solution in https://stackoverflow.com/questions/53365538/how-to-determine-whether-to-use-filesystem-or-experimental-filesystem
seems to fix the issue (see linked PR)

### PR DESCRIPTION
**Pull request by timosachsenberg**
## Description

fixes #6496
changes should probably go upstream

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
not sure if that helps, as long as you are still compiling with https://github.com/OpenMS/OpenMS/blob/sqlitecpp_filesystem_fix/src/openms/thirdparty/SQLiteCpp/CMakeLists.txt#L13

you will use C11 on VS19 and VS19 will complain that experimental is deprecated.

**Comment by timosachsenberg** [comment]
But just complains right? The warning can also be disabled

**Comment by jpfeuffer** [comment]
No please don't. Either fix or remove the whole filesystem thing.

**Comment by timosachsenberg** [comment]
k I will try a different approach. E.g. ifdefing the filesystem part

**Pull request closed without merging**
