### PR TITLE
[FEATURE] change default parameters of PeakPickerMRM

### PR DESCRIPTION
**Pull request by hroest**
- use default parameters that have been in OpenSwathWorkflow for a long
  while now
- no more hardcoded minimal peak width

### CODE REVIEW

**Comment by hendrikweisser** [comment]
The changes look good to me, but the "MRMFeatureFinderScoring_test" fails. I think you still have to update that. When this is done, :+1:

**Comment by cbielow** [comment]
+1

**Comment by cbielow** [comment]
can this  be merged?

**Comment by timosachsenberg** [comment]
state of PR here? mergeable?

**Pull request merged**
