### PR TITLE
[FIX-#1703] MzTabExporter: header columns doesn't match with data columns

### PR DESCRIPTION
**Pull request by PetraGutenbrunner**
* create protein-, peptide-, and psm header based on all data instead of the first object in the list.
* check that the optional meta value is written in the correct column
* added class test to check if all header columns are existing
* added class test to check if the data fits to the header column

### CODE REVIEW

**Comment by timosachsenberg** [comment]
there is a test file that needs to be adapted
http://cdash.openms.de/testDetails.php?test=28803973&build=152986
I don't know if it is relevant that the order of opt columns is preserved.

**Comment by PetraGutenbrunner** [comment]
Unfortunately the build above is not available anymore. Is it possible to rerun the tests somehow that I can see which test file needs to be adapted that the test run through?

**Comment by timosachsenberg** [comment]
I restarted the builds

**Comment by timosachsenberg** [comment]
http://cdash.openms.de/testDetails.php?test=29266208&build=155700

**Comment by timosachsenberg** [comment]
I think it might be good to preserve the column order. Would this be difficult to implement?

**Comment by PetraGutenbrunner** [comment]
The different column order is because i changed the container for the optional columns from vector to set, which is sorted ascending. But it seems that the errors of the tests are not because of the different order. The values of the columns don't match. I'm already checking this.

**Comment by PetraGutenbrunner** [comment]
Is there a specific reason why you think that it would be good to preserve the column order?

**Comment by timosachsenberg** [comment]
one reason is that column headers can be followed by a comment line that further annotates it (there was one example in the mzTab examples). another reason is, that users might want it to be preserved.

**Comment by hendrikweisser** [comment]
> one reason is that column headers can be followed by a comment line that further annotates it (there was one example in the mzTab examples)

But we're only creating the mzTab. "Preserving the order" would refer to the order in the input file (e.g. idXML). Is the order of user params/meta values in those formats meaningful?

**Comment by timosachsenberg** [comment]
I would like to have control over the order even if I am only creating it. Also maybe we read it back in in the future.

**Comment by timosachsenberg** [comment]
Note that you added this to MzTab.h class and not to MzTabExporter so the sorting of columns also applies for manually created mzTab's

**Comment by PetraGutenbrunner** [comment]
I will change it back to a vector as it was before you suggested to change it to a set. Then the order of the columns is preserved again.

**Pull request merged**
