### PR TITLE
Addition/text exporter

### PR DESCRIPTION
**Pull request by Leon-Bichmann**

### CODE REVIEW

**Comment by Leon-Bichmann** [comment]
@timosachsenberg

**Comment by hroest** [comment]
@Leon-Bichmann please merge/rebase on top of develop due to our CI issue

**Comment by oliveralka** [comment]
@timosachsenberg we found the style issue.

**Comment by timosachsenberg** [comment]
looks good. Hard to judge if the correct output is generated without test so consider adding a small one.

**Comment by Leon-Bichmann** [comment]
So here are the results from my test example:

Input consensus XML
`<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="file:////home/groepl/Release1.6/share/OpenMS/XSL/ConsensusXML.xsl"?>
<consensusXML version="1.7" experiment_type="itraq" xsi:noNamespaceSchemaLocation="http://open-ms.sourceforge.net/schemas/ConsensusXML_1_7.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<IdentificationRun id="PI_0" date="2008-10-29T10:17:55" search_engine="InsPecT" search_engine_version="20080404">
		<SearchParameters db="" db_version="" taxonomy="" mass_type="average" charges="" enzyme="trypsin" missed_cleavages="0" precursor_peak_tolerance="2" peak_mass_tolerance="0.5" >
		</SearchParameters>
		<ProteinIdentification score_type="" higher_score_better="true" significance_threshold="0">
			<ProteinHit id="PH_0" accession="Q9HP81" score="0" sequence="AATYMWN">
			</ProteinHit>
		</ProteinIdentification>
	</IdentificationRun>
	<UnassignedPeptideIdentification identification_run_ref="PI_0" score_type="Inspect" higher_score_better="true" significance_threshold="1" MZ="405.85" RT="306.58" >
		<PeptideHit score="-1.65100002288818" sequence="AATY" charge="1" aa_before="L" aa_after="Q" protein_refs="PH_0">
			<UserParam type="string" name="target_decoy" value="target"/>
			<UserParam type="string" name="protein_references" value="unique"/>
		</PeptideHit>
	</UnassignedPeptideIdentification>
	<mapList count="1">
		<map id="1" name="attention: no size here" label="iTRAQ_116_" size="0">
			<UserParam type="int" name="channel_name" value="116"/>
			<UserParam type="int" name="channel_id" value="1"/>
			<UserParam type="string" name="channel_description" value=""/>
			<UserParam type="float" name="channel_center" value="116.1"/>
			<UserParam type="string" name="channel_active" value="false"/>
		</map>
	</mapList>
	<consensusElementList>
		<consensusElement id="e_30" quality="0">
			<centroid rt="4149.49" mz="450.26" it="0"/>
			<groupedElementList>
				<element map="1" id="30" rt="4149.49" mz="116.1" it="3.6"/>
			</groupedElementList>
			<PeptideIdentification identification_run_ref="PI_0" score_type="Inspect" higher_score_better="true" significance_threshold="1" MZ="114.09" RT="4149.49" >
				<PeptideHit score="-1.75" sequence="MWN" charge="1" aa_before="T" aa_after="G" protein_refs="PH_0">
					<UserParam type="string" name="target_decoy" value="target"/>
					<UserParam type="string" name="protein_references" value="unique"/>
				</PeptideHit>
			</PeptideIdentification>
		</consensusElement>
	</consensusElementList>
</consensusXML>
`

`#Consensus features extracted from test.consensusXML on 2017-07-24 16:09:49
#MAP    id      filename        label   size    channel_active  channel_center  channel_description     channel_id      channel_name
#RUN    run_id  score_type      score_direction date_time       search_engine_version   parameters
#PROTEIN        score   rank    accession       protein_description     coverage        sequence
#UNASSIGNEDPEPTIDE      rt      mz      score   rank    sequence        charge  aa_before       aa_after        score_type      search_identifier       accessions      protein_references      target_decoy
#CONSENSUS      rt_cf   mz_cf   intensity_cf    charge_cf       width_cf        quality_cf      rt_1    mz_1    intensity_1     charge_1        width_1
#PEPTIDE        rt      mz      score   rank    sequence        charge  aa_before       aa_after        score_type      search_identifier       accessions      protein_references      target_decoy
MAP     1       attention: no size here iTRAQ_116_      0       false   116.1           1       116
RUN     InsPecT_2008-10-29T10:17:55             higher-score-better     2008-10-29T10:17:55     20080404        db=, db_version=, taxonomy=, charges=, mass_type=average, fixed_modifications=, variable_modifications=, enzyme=Trypsin, missed_cleavages=0, peak_mass_tolerance=0.5, precursor_mass_tolerance=2
PROTEIN 0       0       Q9HP81          -1      AATYMWN
UNASSIGNEDPEPTIDE       306.58  405.85  -1.65100002288818       0       AATY    1       L       Q       Inspect InsPecT_2008-10-29T10:17:55     Q9HP81  unique  target
CONSENSUS       4149.49 450.26  0       0       0       0       4149.49 116.1   3.59999990463257        0       0
PEPTIDE 4149.49 114.09  -1.75   0       MWN     1       T       G       Inspect InsPecT_2008-10-29T10:17:55     Q9HP81  unique  target
~
`

**Comment by Leon-Bichmann** [comment]
So here are the results from my test example:

- Input featureXML
- Output contains peptide_hit_metavalues

>>> TextExporter -in test.featureXML -out test.csv -id:add_hit_metavalues 0

```
`<?xml version="1.0" encoding="ISO-8859-1"?>
<featureMap xsi:noNamespaceSchemaLocation="http://open-ms.sourceforge.net/schemas/FeatureXML_1_0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<IdentificationRun id="PI_0" date="2006-03-09T11:31:52" search_engine="Mascot" search_engine_version="">
		<SearchParameters db="" db_version="" taxonomy="" mass_type="monoisotopic" charges="" enzyme="unknown_enzyme" missed_cleavages="0" precursor_peak_tolerance="0" peak_mass_tolerance="0" >
		</SearchParameters>
		<ProteinIdentification score_type="" higher_score_better="true" significance_threshold="0">
			<ProteinHit id="PH_0" accession="ABCDE" score="0" sequence="">
			</ProteinHit>
		</ProteinIdentification>
	</IdentificationRun>
	<UnassignedPeptideIdentification identification_run_ref="PI_0" score_type="" higher_score_better="false" significance_threshold="42.2999992370605" >
		<PeptideHit score="4324.433" sequence="B" charge="23" aa_before="X" aa_after="Y" protein_refs="PH_0">
			<UserParam type="string" name="target_decoy" value="target"/>
			<UserParam type="string" name="protein_references" value="unique"/>
		</PeptideHit>
	</UnassignedPeptideIdentification>
	<featureList count="2">
		<feature id="f_11">
			<position dim="0">14</position>
			<position dim="1">534</position>
			<intensity>100</intensity>
			<quality dim="0">1</quality>
			<quality dim="1">1</quality>
			<overallquality>10</overallquality>
			<charge>2</charge>
			<PeptideIdentification identification_run_ref="PI_0" score_type="bla" higher_score_better="true" significance_threshold="31.8621006011963" MZ="1001" RT="90" >
				<PeptideHit score="35" sequence="D" charge="3" protein_refs="PH_0">
					<UserParam type="string" name="target_decoy" value="target"/>
					<UserParam type="string" name="protein_references" value="unique"/>
				</PeptideHit>
			</PeptideIdentification>
		</feature>
	</featureList>
</featureMap>
`
```

```
`#RUN    run_id  score_type      score_direction date_time       search_engine_version   parameters
#PROTEIN        score   rank    accession       protein_description     coverage        sequence
#UNASSIGNEDPEPTIDE      rt      mz      score   rank    sequence        charge  aa_before       aa_after        score_type      search_identifier       accessions      protein_references      target_decoy
#FEATURE        rt      mz      intensity       charge  width   quality rt_quality      mz_quality      rt_start        rt_end
#PEPTIDE        rt      mz      score   rank    sequence        charge  aa_before       aa_after        score_type      search_identifier       accessions      protein_references      target_decoy
RUN     Mascot_2006-03-09T11:31:52              higher-score-better     2006-03-09T11:31:52             db=, db_version=, taxonomy=, charges=, mass_type=monoisotopic, fixed_modifications=, variable_modifications=, enzyme=unknown_enzyme, missed_cleavages=0, peak_mass_tolerance=0, precursor_mass_tolerance=0
PROTEIN 0       0       ABCDE           -1
UNASSIGNEDPEPTIDE       -1      -1      4324.433        0       B       23      X       Y               Mascot_2006-03-09T11:31:52      ABCDE   unique  target
FEATURE 14      534     100     2       0       10      1       1       -1      -1
PEPTIDE 90      1001    35      0       D       3       X       X       bla     Mascot_2006-03-09T11:31:52      ABCDE   unique  target
`
```

**Pull request merged**
