### PR TITLE
[FEATURE] enable SpectraST test

### PR DESCRIPTION
**Pull request by hroest**
enable spectrast adapter test

### CODE REVIEW

**Comment by hroest** [comment]
@lukaszimmermann can you run this on your local machine and see whether it works? It does work here but for some reason it does not seem to work on travis

**Comment by lukaszimmermann** [comment]
@hoest I can check this weekend

**Comment by lukaszimmermann** [comment]
@hroest 
I ran the test on my machine. The resulting `spectrast.log` file can be found here:
https://github.com/lukaszimmermann/SpectraST/blob/master/logs/example_spectrast.log

Note that:
`Total Number of Searches Performed = 0. `

The result file is thus going to be empty and the test fails.
I don't know the reason, it seems to be a problem of spectrast itself.

You mentioned that the test worked for you locally? Can we compare the `spectrast.log` files, just to make sure that there are no obvious differences?

**Comment by hroest** [comment]
I now have the same issues, there was a file in `/tmp/` that was not overwriten and gave the impression that it worked. Nonetheless, using a recent version of spectrast, building directly from trunk I got it to work

```
$ svn info
Path: .
Working Copy Root Path: /media/data/var/sashimi
URL: https://svn.code.sf.net/p/sashimi/code/trunk/trans_proteomic_pipeline
Relative URL: ^/trunk/trans_proteomic_pipeline
Repository Root: https://svn.code.sf.net/p/sashimi/code
Repository UUID: 4d4d7acd-9f35-0410-af30-e8fdcb3b0dde
Revision: 7676
Node Kind: directory
Schedule: normal
Last Changed Author: eng_jk
Last Changed Rev: 7676
Last Changed Date: 2017-11-09 17:26:18 -0500 (Thu, 09 Nov 2017)
```

maybe we just need to update SpectraST - did you build the current executable yourself? Was it ever working in your hands?

**Comment by lukaszimmermann** [comment]
Yes, I did some preliminary tests in the beginning, which worked. I am going to rebuild the executable and test again with the recent sources. It might be possible that the boost version that I built SpectraST against was different then the one used by TPP.

**Comment by hroest** [comment]
I had a lot of trouble / bad luck with SpectraST but eventually got it working. Apparently just when I was building it the TPP had a serious bug in their XML parser which made it such that they could not read mzML produced by OpenMS. They also did not read in the precursor m/z or charge which led to zero results. I am not sure whether that is the same issue we have with your version but the one in the thirdparty folder clearly does not do any searching or produce any results. Maybe we can try with your sample test data again and see whether that works?

In either case, I got it now working with svn `Revision: 7676`

**Comment by lukaszimmermann** [comment]
Should be fixed by   OpenMS/THIRDPARTY#34

**Comment by timosachsenberg** [comment]
I merged  OpenMS/THIRDPARTY#34 . Can you sync this branch?

**Comment by jpfeuffer** [comment]
What's the status here?

**Comment by jpfeuffer** [comment]
@lukaszimmermann Do you know about the status here?

**Comment by lukaszimmermann** [comment]
I will check later today.

**Comment by lukaszimmermann** [comment]
The tests work on my machine with the current THIRDPARTY executable of SpectraST.

**Comment by jpfeuffer** [comment]
Hmm executable is there on Mac. But does not work.
https://abibuilder.informatik.uni-tuebingen.de/jenkins/view/OpenMS/job/openms_pr_ci/compiler=appleclang-8.0.0,os_label=sierra/ws/SEARCHENGINES/SpectraST/

**Comment by lukaszimmermann** [comment]
Spectrast was not executable on Mac

**Comment by jpfeuffer** [comment]
We might need to pull the thirdparty submodule. I changed the scripts to use them instead of a checkout of head to make sure compatible ones are chosen.

**Comment by jpfeuffer** [comment]
Status? We merged the PR to update Thirdparty. I suggest waiting for the Thirdparty PRs to be merged and then updating your PR accordingly.

**Comment by lukaszimmermann** [comment]
Yes, I agree. I will update this PR once Sirius 4.0 and Maracluster are merged.

**Comment by jpfeuffer** [comment]
rebuild jenkins

**Pull request closed without merging**
