### PR TITLE
Feature/mascot online

### PR DESCRIPTION
**Pull request by hroest**
Adopt the MascotAdapterOnline for the new version of mascot (2.6)

- this is in preparation for the qt5 branch where we need a test for this part of OpenMS
- tests are only turned on with `-DWITH_MASCOT_TEST=On` which should not be used on a regular basis (otherwise the Mascot guys will get angry)

### CODE REVIEW

**Comment by hroest** [comment]
also: it now compiles with `MASCOTREMOTEQUERY_DEBUG` defined

**Comment by timosachsenberg** [comment]
Very cool! Thanks

**Comment by timosachsenberg** [comment]
looks good. feel free to merge

**Comment by timosachsenberg** [comment]
cool will try to sync the qt5 branch

**Pull request merged**
