### PR TITLE
Fix/remove rich peak 1D

### PR DESCRIPTION
**Pull request by timosachsenberg**
RIchPeak1D has been a major source of inefficiencies. This PR should remove the last remainings.

### CODE REVIEW

**Comment by hroest** [comment]
can you also fix
```
src/pyOpenMS/pxds/MSPFile.pxd
src/pyOpenMS/pxds/MSSpectrum.pxd
src/pyOpenMS/pxds/ConsensusFeature.pxd
src/pyOpenMS/pxds/DeNovoIonScoring.pxd
src/pyOpenMS/pxds/SpectrumAlignment.pxd
src/pyOpenMS/pxds/DeNovoIdentification.pxd
src/pyOpenMS/pxds/BaseFeature.pxd
src/pyOpenMS/pxds/RNPxlReport.pxd
src/pyOpenMS/pxds/CalibrationData.pxd
src/pyOpenMS/pxds/RichPeak1D.pxd
src/pyOpenMS/pxds/RichPeak2D.pxd
src/pyOpenMS/pxds/DeNovoAlgorithm.pxd
src/pyOpenMS/pxds/DeNovoPostScoring.pxd
```

**Comment by timosachsenberg** [comment]
Ups..  sure :)

**Comment by timosachsenberg** [comment]
@hroest can you give me some hints on what I need adapt / ge trid of some addon files?
For example
https://github.com/timosachsenberg/OpenMS/blob/fix/removeRichPeak/src/pyOpenMS/addons/SpectrumAlignment.pyx
handels the case where one spectrum is a richpeakspectrum. As this is gone we can get rid of handling this separately (and also are able to remove more templates later in the c++ part)

**Comment by timosachsenberg** [comment]
builds pass. one timeout.
Next steps could be removing template from MSExperiment and MSSpectrum.
Also all functions that used a template to distinguish between RichPeakSpectra and PeakSpectra

**Comment by timosachsenberg** [comment]
thanks!

**Pull request merged**
