### PR TITLE
Feature/spectrum hit annotation/branchof/general spectrum reference annotation

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
smaller changes to https://github.com/OpenMS/OpenMS/pull/2499

**Comment by timosachsenberg** [comment]
@enetz can you take a quick look at the failing test
http://cdash.openms.de/viewTest.php?onlyfailed&buildid=225363
triggers:
```
Error: Unexpected internal error (!theoretical_spec.isSorted() TheoreticalSpectrumGenerator::getSpectrum did not yield a sorted spectrum!)
```

**Comment by enetz** [comment]
hmm, in MSSpectrum the sorting is done based on position values from ContainerType::operator[](i).getPosition(), while isSorted checks if (this->operator[](i - 1).getMZ() > this->operator[](i).getMZ())

is it possible to get different values from ContainerType::operator[](i).getPosition() and this->operator[](i).getMZ() ?
In Peak1D, getMZ() and getPos() return position_[0], but getPosition() returns "the whole" position_

The only reason I can think of, why the spectrum may actually not be sorted, is if the spectrum size is not equal to one of the DataArrays, but that should throw an exception in the MSSpectrum::select() function.
Are there any "IntegerDataArray[0] size (X) does not match spectrum size (Y)" or similar exceptions or warnings?
Does this only happen to the Travis build or also on your local build?

**Comment by timosachsenberg** [comment]
I paste some code here as a notepad ;)
sorting without vs. with data array:
```
  std::sort(ContainerType::begin(), ContainerType::end(), typename PeakType::PositionLess());
vs.
       std::sort(sorted_indices.begin(), sorted_indices.end(), PairComparatorFirstElement<std::pair<typename PeakType::PositionType, Size> >());
```

**Comment by timosachsenberg** [comment]
ok I think we just need to negate the PRECONDITION :P

**Comment by mwalzer** [comment]
:tada:  :+1:

**Comment by hroest** [comment]
> ok I think we just need to negate the PRECONDITION :P

haha I like your approach....

**Pull request merged**
