### PR TITLE
fixes FileInfo TOPP test

### PR DESCRIPTION
**Pull request by lars20070**
Fixes failed test after #1851.

### CODE REVIEW

**Comment by hroest** [comment]
still seems to produce errors:

http://cdash.openms.de/viewTest.php?onlyfailed&buildid=167308

but with a strange error


```
Warning: Parameters file version (1.8.0) does not match the version of this tool (2.0.0).
Error: File empty (the file 'FileInfo_14.tmp' is empty)
Cannot read input file given from parameter '-in1'!
```

so I restarted the build

**Comment by lars20070** [comment]
Even after the re-build, the same tests fail again.

**Comment by cbielow** [comment]
the whitelisting seems to work
  whitelist cases:
    "File name"             1x
    "line 327 column 183"   1x

**Comment by cbielow** [comment]
but the output seems to be truncated/empty in some cases.

e.g., http://cdash.openms.de/testDetails.php?test=30877427&build=167325

**Comment by cbielow** [comment]
I don't see a way how FileInfo would not at least print
```    os << "\n"
       << "-- General information --" << "\n"
       << "\n"
       << "File name: " << in << "\n"
       << "File type: " << FileTypes::typeToName(in_type) << "\n";```

before exiting, so an empty file is unexplicable to me.
If it's empty, there should be an error code and the FileInfo test itself should fail -- which it apparently does not. But the output is still truncated/missing.

@lars20070 : do the tests pass on your machine?

**Comment by lars20070** [comment]
Yes. Under Ubuntu all tests pass.

Even the test `TOPP_FileInfo_14_out1` before now fails.

**Comment by cbielow** [comment]
I'd say merge this and hope this is a Travis issue which they will resolve

**Comment by lars20070** [comment]
+1

**Comment by lars20070** [comment]
Under OS X 10.11.3, all tests pass as well.

**Comment by hroest** [comment]
it seems that the merge commit did not go through

https://travis-ci.org/OpenMS/OpenMS/builds/113354262

I restarted the build

**Comment by lars20070** [comment]
It appears the failing tests are not related to `FileInfo`.

`TOPP_OpenSwathMzMLFileCacher` tests fail under OS X.

**Pull request merged**
