### PR TITLE
[FEATURE] return transformation statistics

### PR DESCRIPTION
**Pull request by timosachsenberg**
make some basic statistics on deviations before/after applying the transformation model available to down-stream tools

### CODE REVIEW

**Comment by hroest** [comment]
you also need to wrap `TransformationStatistics` with Python

**Comment by hroest** [comment]
you can generate the files by 

```
python tools/PythonExtensionChecker.py --bin_path ./build/PATH/HERE --src_path ./ --pxds-out /tmp/  --generate_pxd_for TransformationDescription
python tools/PythonExtensionChecker.py --bin_path ./build/PATH/HERE --src_path ./ --pxds-out /tmp/  --generate_pxd_for TransformationStatistics
```

which gives me

```Cython
$ cat /tmp/TransformationStatistics.pxd 
from Types cimport *
from Param cimport *
from TransformationModel cimport *

cdef extern from "<OpenMS/ANALYSIS/MAPMATCHING/TransformationDescription.h>" namespace "OpenMS::TransformationDescription":
    
    cdef cppclass TransformationStatistics "OpenMS::TransformationDescription::TransformationStatistics":
        TransformationStatistics(TransformationStatistics) nogil except + #wrap-ignore
        libcpp_vector[ size_t ] percents
        double xmin
        double xmax
        double ymin
        double ymax
        libcpp_map[ Size, double ] percentiles_before
        libcpp_map[ Size, double ] percentiles_after

$ cat /tmp/TransformationDescription.pxd 
from Types cimport *
from libcpp cimport bool
from libcpp.pair cimport pair as libcpp_pair
from libcpp.vector cimport vector as libcpp_vector
from Param cimport *
from TransformationModel cimport *

cdef extern from "<OpenMS/ANALYSIS/MAPMATCHING/TransformationDescription.h>" namespace "OpenMS":
    
    cdef cppclass TransformationDescription "OpenMS::TransformationDescription":
        TransformationDescription() nogil except +
        TransformationDescription(TransformationDescription) nogil except +
        TransformationDescription(const DataPoints & data) nogil except +
        void fitModel(const String & model_type, const Param & params) nogil except +
        double apply(double value) nogil except +
        String  getModelType() nogil except +
        void setDataPoints(const DataPoints & data) nogil except +
        void setDataPoints(const libcpp_vector[ libcpp_pair[ double, double ] ] & data) nogil except +
        DataPoints  getDataPoints() nogil except +
        Param  getModelParameters() nogil except +
        void invert() nogil except +
        void getDeviations(libcpp_vector[ double ] & diffs, bool do_apply, bool do_sort) nogil except +
        TransformationStatistics getStatistics() nogil except +
        # NAMESPACE # void printSummary(std::ostream & os) nogil except +
        void getModelTypes(StringList & result) nogil except +

```

its not perfect but works reasonably well.

**Comment by timosachsenberg** [comment]
will leave this for now and fix another day

**Comment by hroest** [comment]
@timosachsenberg can you merge https://github.com/timosachsenberg/OpenMS/pull/16

It seems you deleted the default assignment operator by accident as you introduced a const variable, the compiler produces:

pyopenms/pyopenms_4.cpp:100902:15: error: use of deleted function ‘OpenMS::TransformationDescription::TransformationStatistics& OpenMS::TransformationDescription::TransformationStatistics::operator=(const OpenMS::TransformationDescription::TransformationStatistics&)’
     __pyx_t_1 = __pyx_v_self->inst.get()->getStatistics();
               ^
In file included from pyopenms/pyopenms_4.cpp:758:0:
/home/hr/openmsall/source/OpenMS_trunk/src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/TransformationDescription.h:73:33: note: ‘OpenMS::TransformationDescription::TransformationStatistics& OpenMS::TransformationDescription::TransformationStatistics::operator=(const OpenMS::TransformationDescription::TransformationStatistics&)’ is implicitly deleted because the default definition would be ill-formed:

Again, I feel that if we want to use the "rule of zero" we need to test these cases as I dont have the complete overview over the compiler rules regarding auto-generation of all 5 default-generated functions.

**Pull request merged**
