### PR TITLE
[BUILD] adopt manifest to only include relevant files

### PR DESCRIPTION
**Pull request by hroest**
- exclude examples
- exclude .cpp source file
- exclude large mapping file

### CODE REVIEW

**Comment by hroest** [comment]
also correct CMakeLists.txt as it contains wrong paths, the dlls are not stored in /bin/Release but directly in /bin

**Comment by cbielow** [comment]
-1

Depending on the Generator used, binaries will be created in either ./bin/release|debug (VS solutions) or just ./bin (nmake).

The changes you propose fix it for nmake, but break it for VS.

**Comment by cbielow** [comment]
I don't see a good reason to use nmake instead of VS solutions.
Nmake can only run from cmdline, VS solutions can do both (via msbuild.exe for cmdline and VSStudio for GUI) -- no reason to use nmake IMHO.

**Comment by hroest** [comment]
@cbielow the main reason I used nmake was that this allowed compilation from the commandline and thus reproducible building without opening some GUI tool. However, if that is also possible with the MSVS express generators I am happy to learn how to do it. As a novice, I did not figure out how to do it but this is my fault entirely. If we have one that works, then we dont need to support both, I think.

But can you send me the commands I would use to generate and build OpenMS using the VS generator?

We can then also close this PR

**Comment by cbielow** [comment]
this
https://github.com/OpenMS/OpenMS/blob/develop/tools/build.bat
should do everything you want.

call it from the root of the OpenMS binary-tree, e.g.

c:\dev\openms_VS11\>> .\tools\build.bat FeatureFinderCentroided r t

to build FFcentroided in [r]elease mode using the [t]opp solution file.
Note that the solution file is important, since not all targets are 
defined in the global project solution (as opposed to makefiles).



Am 7/13/2016 um 9:14 PM schrieb Hannes Roest:

**Comment by hroest** [comment]
partly addressed in #2049

**Pull request closed without merging**
