### PR TITLE
fix imputation bug on single peak mass traces

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Might fix: https://github.com/OpenMS/OpenMS/issues/5678

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
To be honest, after looking into the code, I am not sure if this will solve the problem:
https://github.com/OpenMS/OpenMS/blob/2c5d58413f9720e87cf44de657ade5315ea2b6ed/src/openms/source/ANALYSIS/OPENSWATH/PeakPickerMRM.cpp#L54

It does not stop the picking or invalidates the transition group. It just makes sure that it at least picks up a peaks in a certain range around the "center" peak.

https://github.com/OpenMS/OpenMS/blob/2c5d58413f9720e87cf44de657ade5315ea2b6ed/src/openms/source/ANALYSIS/OPENSWATH/PeakPickerMRM.cpp#L200

Did you check this?

**Comment by timosachsenberg** [comment]
I made the change based on @hroest comment:
```Also currently MRMTransitionGroupFinder::createMRMFeature uses a min_peak_width_ so in principle this can be prevent there by setting this to non-zero ```

**Comment by jpfeuffer** [comment]
Ah sorry, didnt check the header. There is another usage of the member:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.h#L277

Ok should be fine

**Review by jpfeuffer — APPROVED** [review]

**Comment by timosachsenberg** [comment]
ok thanks for checking.
Maybe one could even be stricter using the information here:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.h#L237-L238
to check if we have e.g. at least 3 non-zero peaks in the chromatogram - or similar

**Pull request merged**
