### PR TITLE
[FIX] attempt to fix failing PPW tests

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by cbielow** [comment]
could you get rid of `if(NOT DISABLE_WAVELET2DTEST)`
These switches drive me crazy...

**Comment by timosachsenberg** [comment]
OK will do

**Comment by timosachsenberg** [comment]
ok interesting:
in1:  /home/travis/build/timosachsenberg/OpenMS/src/tests/topp/PeakPickerWavelet_3_tmp.dta2d   (line: 2, position/column: 25/33)
474.558	937.275763498803	!
       	                	1917.94

in2:  /home/travis/build/timosachsenberg/OpenMS/src/tests/topp/PeakPickerWavelet_2Dopt_output.dta2d   (line: 2, position/column: 25/33)
474.558	937.287878406725	!
       	                	2534.49

the "instability" seems to be quite large

**Comment by hroest** [comment]
I believe the PPW uses a rather sophisticated model to fit to the data and does optimization until convergence. In theory that should be stable and reproducible and there is no randomness involved, is there?

**Comment by hroest** [comment]
@timosachsenberg is this still an issue with Debug mode and in Release mode as in #1202 ? or is it clang vs gcc? can you do a debug and a release build on your machine and report the resulting dta2 files?

**Comment by timosachsenberg** [comment]
on my machine I get the same results on debug and release

**Comment by cbielow** [comment]
someone using an AMD CPU?

**Comment by timosachsenberg** [comment]
I close this PR as it doesn't solve the problem

**Pull request closed without merging**
