### PR TITLE
[Fix] toList() is deprecated

### LINKED ISSUE #5934: warning: `QList<T> QSet<T>::toList()` is deprecated
```shell
/home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp: In static member function ‘static OpenMS::TOPPASTreeView* OpenMS::TOPPASBase::createTOPPToolsTreeWidget(QWidget*)’:
/home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp:487:52: warning: ‘QList<T> QSet<T>::toList() const [with T = QString]’ is deprecated: Use values() instead. [-Wdeprecated-declarations]
  487 |     QStringList category_list = category_set.toList();
      |                                 ~~~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/qt/QtCore/qitemselectionmodel.h:45,
                 from /usr/include/qt/QtWidgets/qabstractitemview.h:46,
                 from /usr/include/qt/QtWidgets/qtreeview.h:44,
                 from /usr/include/qt/QtWidgets/qtreewidget.h:44,
                 from /usr/include/qt/QtWidgets/QTreeWidget:1,
                 from /home/USER/Development/OpenMs/src/openms_gui/include/OpenMS/VISUAL/TOPPASTreeView.h:41,
                 from /home/USER/Development/OpenMs/src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPASBase.h:43,
                 from /home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp:35:
/usr/include/qt/QtCore/qset.h:265:14: note: declared here
  265 |     QList<T> toList() const { return values(); }
      |              ^~~~~~
```

### PR DESCRIPTION
**Pull request by Amit0617**
# Description

Please include a summary of the change and which issue is fixed.
Fixes #5934 

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

**Comment by Amit0617** [comment]
oh that qsort() one just got merged and wasn't in my pull is creating conflict

**Review by timosachsenberg — APPROVED** [review]

**Review by timosachsenberg — CHANGES_REQUESTED** [review]
did you compile this. looks wrong

**Comment by Amit0617** [comment]
yeah went perfect for me

**Comment by cbielow** [comment]
I don't think this compiles... please check.

**Comment by Amit0617** [comment]
I added a comment to change it so it recompiles and here it is going silently.
```
[  1%] Built target OpenSwathAlgo
[  1%] Automatic MOC for target OpenMS
[  1%] Built target OpenMS_autogen
[  1%] Building CXX object src/openms/CMakeFiles/OpenMS.dir/source/CONCEPT/VersionInfo.cpp.o
[  1%] Linking CXX shared library ../../lib/libOpenMS.so
[ 28%] Built target OpenMS
[ 28%] Automatic MOC for target OpenMS_GUI
[ 28%] Built target OpenMS_GUI_autogen
Consolidate compiler generated dependencies of target OpenMS_GUI
[ 28%] Building CXX object src/openms_gui/CMakeFiles/OpenMS_GUI.dir/source/VISUAL/APPLICATIONS/TOPPASBase.cpp.o
[ 28%] Linking CXX shared library ../../lib/libOpenMS_GUI.so
[ 35%] Built target OpenMS_GUI
[ 36%] Automatic MOC for target INIFileEditor
```

**Comment by Amit0617** [comment]
May be I got that 
Changes
```
    QStringList category_list;
    category_list(category_list.begin(), category_list.end());
```
now it throws error
```
error: no match for call to ‘(QStringList) (QList<QString>::iterator, QList<QString>::iterator)’
  489 |     category_list(category_list.begin(), category_list.end());
      |     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
So `begin()` and `end()` in `category_list`

**Comment by timosachsenberg** [comment]
it doesn't make sense to construct the list with itself

**Comment by Amit0617** [comment]
I sometimes become blind

**Pull request merged**
