### PR TITLE
[FEATURE] use compile feature instead of fixed CXX standard to require only a minimum

### PR DESCRIPTION
**Pull request by jpfeuffer**
This should be tested on multiple compiler versions first.

### CODE REVIEW

**Comment by hroest** [comment]
would this mean that 4.8 does still work?

**Comment by jpfeuffer** [comment]
Good question: If CMake defined 4.8 as fully C11 compatible, yes. I'll check

**Comment by jpfeuffer** [comment]
Otherwise, we might reduce the features needed, such that 4.8 is included.

**Comment by jpfeuffer** [comment]
rebuild jenkins

**Comment by timosachsenberg** [comment]
builds on Trusty: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4

**Pull request merged**
