### PR TITLE
[REFACTOR][FIX] NovorAdapter

### PR DESCRIPTION
**Pull request by oliveralka**
Add java_memory variable 
Fixed removeTempDir 
Edit test (add -java_memory variable #3244)

Further fix from Lukas (thanks a lot) 
QProcess was not working correctly -> Java Process was not started/finished due to a not closed stream.

### CODE REVIEW

**Comment by hroest** [comment]
@oliveralka is there a chance that this will also run on travis or only on the nightly servers?

**Comment by oliveralka** [comment]
@hroest I'm not sure about travis @jpfeuffer? But it should at least run on the nightly server.

**Comment by jpfeuffer** [comment]
Yep. Runs on nightly. That is how we found out that the JVM memory was set too high. We were upgrading OS on our macs though. Not everything is smooth yet (e.g. here)

**Comment by oliveralka** [comment]
rebuild jenkins

**Comment by jpfeuffer** [comment]
Ok mac just failed because of cdash upload being too slow.

**Comment by jpfeuffer** [comment]
MErge to test in nightlies.

**Pull request merged**
