### PR TITLE
[FIX, TEST] attempt to fix ffid test

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
I removed the identification that caused the difference. Let's see if this resolves the issue.

**Comment by jpfeuffer** [comment]
Great. Fine for me, although it would be cool if there would be a more detailed explanation on why there are differences.

**Comment by jpfeuffer** [comment]
By the way: @timosachsenberg did you check if it was the same feature that was causing macOS nightlies to fail?

**Comment by timosachsenberg** [comment]
Yes, it is the same feature. I have no idea why this feature creates this problem. Maybe it is related to the SVM differences between platforms? It could be that the SVM scored both hits of the same elution profile with the same score and on one platform the first hit is selected for targeted extracted, on the other platform the latter.

**Comment by timosachsenberg** [comment]
failed tests unrelated

**Comment by jpfeuffer** [comment]
Sorry, but this did not solve the issue. Better check CDash for the PRs until I can confirm that Jenkins is stable...

**Comment by timosachsenberg** [comment]
hmm seems to be a different issue?

**Pull request merged**
