### PR TITLE
increase margin of clustering grid

### LINKED ISSUE #2401: FeatureFinderMultiplex crash
FeatureFinderMultiplex crashes on one of my simulated mzML files. This doesn't occur on hundreds of other simulated files which are essentially all the same (only difference is some minor random variation introduced by MSSimulator).

Minimal example: [FFMPX_crash.mzML.zip](https://github.com/OpenMS/OpenMS/files/765775/FFMPX_crash.mzML.zip)

Parameters: 

>$ FeatureFinderMultiplex -algorithm:labels "" -algorithm:intensity_cutoff 0.0001 -in FFMPX_crash.mzML -out_features test.featureXML
>Progress of 'loading spectra list':
>-- done [took 0.06 s (CPU), 0.06 s (Wall)] -- 
>Progress of 'filtering LC-MS data':
>-- done [took 0.16 s (CPU), 0.16 s (Wall)] -- 
>Progress of 'clustering filtered LC-MS data':
>Error: Unexpected internal error (This position (x,y)=(300.144,614) is outside the range of the grid. (300.144 < x < 319.939, 550 < y < 749))

### PR DESCRIPTION
**Pull request by lars20070**
Follow-up pull request to #2069. The margin is slightly  increased from `1e-15` to `1e-10`.
Fixes #2401.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Just a question: Why is the margin necessary? Why can't it be exactly at the beginning/end?
I just want to make sure that we do not have to change it again and again.

**Comment by lars20070** [comment]
It should be exactly beginning/end. But due to a rounding error, a point on the border is now strictly smaller. Originally I had suggested `0.001` but `1e-10` should be on the safe side too.
https://github.com/OpenMS/OpenMS/pull/2069#issuecomment-235722077

**Comment by hannesveit** [comment]
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/COMPARISON/CLUSTERING/ClusteringGrid.cpp#L104

Minor comment: maybe write "<= x <=",  "<= y <=" in the error message instead of "< x <", "< y <", since the code does actually include the limit.

**Comment by jpfeuffer** [comment]
And do you actually need the following three if statements then?
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/COMPARISON/CLUSTERING/ClusteringGrid.cpp#L111
Your exception should cover all possible errors in this regard, correct?

**Comment by hannesveit** [comment]
Right, the first two of those are definitely redundant. I would just assign i and j directly.

Then, I think, the third if statement doesn't make sense anymore because i and j are guaranteed to be >= 0 by definition. However, it might still make sense to include a bounds check on i and j here, just in case `grid_spacing_xy_` is somehow corrupt (which isn't tested above). I think the only thing that could go wrong with i and j would be if `grid_spacing_xy_` is not empty and contains only values that are all strictly greater than position.getXY(). In this case, `std::lower_bound` returns `end()` and then the index would equal `end() - begin() == size()`, so we get an index _over_flow.

**Comment by hannesveit** [comment]
... actually, the more I think about it now:

Isn't that a potential bug? Are you sure using `std::less_equal<double>()` is the right thing to do here? I admit I don't know how exactly the `grid_spacing_xy_` are constructed, so maybe I'm wrong. 

But if `min(grid_spacing_xy_) == range_xy_.first` or `max(grid_spacing_xy_) == range_xy_.second` holds, then you will not be able to obtain the iterator pointing to the minimum / maximum value using `std::lower_bound`. `std::lower_bound(grid_spacing_xy_.begin(), grid_spacing_xy_.end(), position.getXY(), std::less_equal<double>()` will return `grid_spacing_xy_.end()` if `position.getXY() == max(grid_spacing_xy_)` (index overflow) and will not return the minimum but the second smallest element if `position.getXY() == min(grid_spacing_xy_)`.

Could that maybe be a problem, or are the `grid_spacing_xy_` somehow contructed in a way that this is expected behavior?

**Comment by jpfeuffer** [comment]
I thought the same but I think it works because he actually does not access the grid cells by index (they are stored in a std::map of index pairs).
Actually using vectors and accessing them with the indices would result in quite a speed-up though. (Although I also did not thoroughly look at how the class is used in the end).

**Comment by jpfeuffer** [comment]
If someone is at it, you could use a sorted structure (e.g. a set) instead of a list as the container in each grid cell.

**Comment by lars20070** [comment]
@hannesveit Here the construction of `range_xy_` from `gris_spacing_xy_`.
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/COMPARISON/CLUSTERING/ClusteringGrid.cpp#L47

**Comment by lars20070** [comment]
@hannesveit and @jpfeuffer, thanks for checking the code so carefully. Maybe we can discuss further optimisations on Gitter or phone?

**Comment by timosachsenberg** [comment]
deque might also be an option

**Comment by jpfeuffer** [comment]
Yes I think it needs to be tested to find out. All your points are valid. I just came across this while expecting the same bug as Hannes.

**Comment by lars20070** [comment]
Just for perspective, in my feature detection use case the filtering step takes `47 min`, and the clustering step takes `3.89 sec`.

Merge?

**Comment by jpfeuffer** [comment]
Ok. Yes, then it is even less worth to investigate alternatives.
I would say +1 for this PR. Maybe we can come up with something that does not need the constant in another PR.

**Comment by jpfeuffer** [comment]
Or can you try a relative comparison with the factor `std::numeric_limits<double>::epsilon()`?

**Comment by lars20070** [comment]
The necessary margin (in Hannes' case) is `> 1e-14`.
As I understand `std::numeric_limits<double>::epsilon()` is smaller.

**Pull request merged**
