### PR TITLE
Use adhoc mac signing identity

### PR DESCRIPTION
**Pull request by poshul**
### **User description**
Treats the lack of SIGNING_IDENTITY or SIGNING_EMAIL as choosing to use the adhoc identity.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

___

### **PR Type**
enhancement, configuration changes

___

### **Description**
- Enhanced macOS package signing process by treating the absence of `SIGNING_IDENTITY` or `SIGNING_EMAIL` as opting for an ad hoc signing identity.
- Updated the warning message to inform users about the use of an ad hoc identity and its implications.
- Introduced a configuration change to set `CPACK_BUNDLE_APPLE_CERT_APP` to `"-"` when no signing identity or email is provided.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>CMakeLists.txt</strong><dd><code>Enhance macOS package signing with ad hoc identity fallback</code></dd></summary>
<hr>

CMakeLists.txt

<li>Updated warning message to include information about using an ad hoc <br>signing identity.<br> <li> Added configuration to set <code>CPACK_BUNDLE_APPLE_CERT_APP</code> to <code>"-"</code> when <br>signing identity or email is not defined.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7740/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by poshul** [comment]
@jpfeuffer this changes the default behavior of our CMAKE system to fall back to the ad hoc signing if we don't have valid ID info.

**Comment by jpfeuffer** [comment]
But does it work?
I still get errors that the identity was not found with this, probably due to quoting.

**Comment by poshul** [comment]
> But does it work? I still get errors that the identity was not found with this, probably due to quoting.

It worked here: https://github.com/OpenMS/OpenMS/actions/runs/12181918745/job/33979671209 I'm running it now to see if it passes in develop.

**Comment by poshul** [comment]
@jpfeuffer looks like the signing worked, but there is a weird error here: https://cdash.seqan.de/build/333383

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/issues/7727

**Pull request merged**
