### PR TITLE
[FEATURE] Updated Unimod database

### PR DESCRIPTION
**Pull request by enetz**
We need some additional modifications, specifically results from cross-linking reactions,
that are not covered by the older unimod.xml in the OpenMS repo, but are covered by this updated unimod.xml from the Unimod downloads page.

### CODE REVIEW

**Comment by hendrikweisser** [comment]
Timo added some custom entries ("RNPXlink...") to the unimod.xml in OpenMS for the RNA-protein crosslinking. Can you make sure they are still in there after the update? There may be other OpenMS-specific entries as well.

@timosachsenberg: The usual nomenclature for crosslinks in Unimod seems to be "Xlink:...". Would it be worth adapting the names for the RNPXLs?

**Comment by timosachsenberg** [comment]
Hi @hendrikweisser . Thanks for pointing this out. FYI I am currently removing the dependency of our RNA cross-linking tools  to a custom unimod. The ones you mentioned are still required though for RNPxl (but not for the newer RNPxlSearch).
RNPxl will be deprecated in the near future (~ 1 year)  and I will remove our custom mods from unimod. In the meantime: @enetz  can you add back the modifications with username_of_poster="Timo" from our old unimox.xml

**Comment by enetz** [comment]
I will search for more OpenMS specific additions in the old file.
If someone else remembers or finds anything, please comment here.

**Comment by timosachsenberg** [comment]
@lars20070 are there any missing?

**Comment by lars20070** [comment]
@enetz If you could add our four modifications (accessions 99987 ... 99990) that would be great.
Thanks.

https://gist.github.com/lars20070/21eadaf1424b9bac7fa71f8fcef2caa8

**Comment by timosachsenberg** [comment]
missing mod is resulting in an IDFileConverter error http://cdash.openms.de/viewTest.php?onlyfailed&buildid=178055

**Comment by enetz** [comment]
About the IDFileConverter, there is no entry missing, but it was extended.
What changed, is that in the old unimod.xml this modification was allowed on 'K' and 'N-term', in the new file 'R' was added as a site for it.
It seems the error is caused by these two lines in the SearchParameters block:
(Change at site specification at the end of the second line, K -> R)
IDFileConverter_10_output.idXML:
                <FixedModification name="Dimethyl:2H(4)13C(2) (K)" />
                <FixedModification name="Dimethyl:2H(4)13C(2) (K)" />
IDFileConverter_10_output.tmp:
		<FixedModification name="Dimethyl:2H(4)13C(2) (K)" />
		<FixedModification name="Dimethyl:2H(4)13C(2) (R)" />

I don't know why the second line was expected at all, since it repeats the same modification.
The pepXML from which the idXML was generated has this line:
<parameter name="residue, modification mass" value="57.021464@C,34.063117@[,34.063117@K"/>
with the mass of this modification (34.063117) repeated.
Maybe the pepXML entry '34.063117@[' was interpreted as '34.063117@R'?
And I guess '@[' was meant to mean 'N-term' or something like that?

**Comment by timosachsenberg** [comment]
hmm that's interesting. Yes I think you are right. This might mean that there is a bug in interpreting 34.063117@[ as N-term in the parse code.

**Comment by enetz** [comment]
Does anybody have an idea about the most recent failed test? Looks like an error in XMLHandler when reading a specific mzML file. Can that be related to the unimod.xml somehow?

**Comment by timosachsenberg** [comment]
@lars20070 do you need  modification site R for the modification Dimethyl:2H(4)13C(2) with record_id="510"

**Comment by lars20070** [comment]
Yes. As listed in UniMod.
http://www.unimod.org/modifications_view.php?editid1=510

**Comment by timosachsenberg** [comment]
@enetz can you readd the modification at R? Maybe we can find a different solution to this.

**Comment by timosachsenberg** [comment]
it now passes - looks good.
Any last minute changes required by @lars20070 ?
@enetz and @jpfeuffer what do you think about my last comment in https://github.com/OpenMS/OpenMS/issues/1949
would it make sense to add these now? The problem is that we would need to add a dummy entry for every amino acid as well and for N-term and C-term. Otherwise it will not show up in the modification selection list (e.g. as "CUSTOM1  (M)" )

**Comment by lars20070** [comment]
The N-term specificity of Unimod 329 is still missing.
http://www.unimod.org/modifications_view.php?editid1=329
@jpfeuffer Thanks for pointing that out.

**Comment by jpfeuffer** [comment]
Ah yes and I am fine with adding CUSTOM entries as placeholder for user defined modifications in KNIME.

**Comment by lars20070** [comment]
@enetz Please simply add this specificity to 329.
```
         <umod:specificity hidden="1" site="N-term" position="Any N-term" classification="Isotopic label"
                           spec_group="3"/>
```

**Comment by jpfeuffer** [comment]
Needs to be merged for some standard SILAC workflows (that are currently converted to KNIME) to work out of the box. Should go into a potential bugfix/source release.

**Comment by enetz** [comment]
This issue was resolved by #2338

**Comment by jpfeuffer** [comment]
Not so fast :)
I am getting errors when building the KNIME descriptors:

```---------------------------------------------------
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler: 
exception of type Parse Error occured in line 104, function void OpenMS::Internal::XMLHandler::fatalError(OpenMS::Internal::XMLHandler::ActionMode, const OpenMS::String&, OpenMS::UInt, OpenMS::UInt) const of /home/jenkins/ws/openms_all/40c74027/source/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp
error message: While loading '/home/jenkins/ws/openms_all/40c74027/source/share/OpenMS/CHEMISTRY/unimod.xml': invalid multi-byte sequence( in line 37666 column 34)
Probable cause: The file suffix (xml) does not match the file content (unknown). Rename the file to fix this. in: /home/jenkins/ws/openms_all/40c74027/source/share/OpenMS/CHEMISTRY/unimod.xml
---------------------------------------------------
/home/jenkins/ws/openms_all/40c74027/source/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp(103): While loading '/home/jenkins/ws/openms_all/40c74027/source/share/OpenMS/CHEMISTRY/unimod.xml': invalid multi-byte sequence( in line 37666 column 34)
Probable cause: The file suffix (xml) does not match the file content (unknown). Rename the file to fix this.```

Is there maybe a validator for the format?

**Pull request closed without merging**
