### PR TITLE
[FIX] renamed LowMemPeakPickerHiRes_RandomAccess to

### PR DESCRIPTION
**Pull request by timosachsenberg**
LowMemPeakPickerHiResRandomAccess

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Ah great. Fixes #2601 if it passes.

**Comment by jpfeuffer** [comment]
Looks good. Should pass. Let's see.

**Comment by hroest** [comment]
well, `./src/utils/LowMemPeakPickerHiRes.cpp` and `./src/utils/LowMemPeakPickerHiRes_RandomAccess.cpp` are not really useful tools and more used for testing whether these algorithms compile and run through properly. 

I dont think that they are useful to anybody, the `LowMemPeakPickerHiRes.cpp` is basically implemented in the `PeakPickerHiRes` anyways, so we could just remove that. We could move the random access part either also into the regular PPHiRes or we could move it to a unit-test file

**Comment by timosachsenberg** [comment]
@hroest sounds good. we are a bit on a tight schedule for the release so I would suggest to remove it in develop for the next release

**Comment by timosachsenberg** [comment]
I would suggest we merge this PR as a quick fix for https://github.com/OpenMS/OpenMS/issues/2601
In 2.4 we proceed with removal

**Comment by jpfeuffer** [comment]
OK sounds good. Reduces confusion for the user.

**Comment by jpfeuffer** [comment]
Only Percolator fails + timeouts. Win is busy with contrib and other PRs.

**Pull request merged**
