### PR TITLE
pyOpenMS 2.0 features 

### PR DESCRIPTION
**Pull request by hroest**
This is a pull request to prepare pyOpenMS for the 2.0 release. It should work with the current version of autowrap (tested with 0.5.1 or revision https://github.com/uweschmitt/autowrap/tree/734a14eebd039332b0ba7058172f34219fc6011d ) so it should be good to merge

- several new classes are wrapped
- abstract base classes are wrapped in one instance
- several new methods are wrapped
- all methods not part of the 2.0 release are in the ignore file
- tests added

### CODE REVIEW

**Comment by hroest** [comment]
6649015 adds a few commits that make this commit work with autowrap 0.5.1 so we can go ahead and merge from my perspective

**Comment by mwalzer** [comment]
like it. Could you just add
*void load(String filename, libcpp_vector[ProteinIdentification] & poid, libcpp_vector[PeptideIdentification] & peid) nogil except +* to MzIdentMLFile.pxd?

**Comment by hroest** [comment]
@mwalzer that should already be in trunk here https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/MzIdentMLFile.pxd#L22 so it should be available already

**Comment by mwalzer** [comment]
no. store, yes. load, no. thx

**Comment by hroest** [comment]
ok, sorry I misread

now it is added

**Comment by hroest** [comment]
after @mwalzer support I opt to merge (also since there are no relevant changes to the C++ code)

**Pull request merged**
