### PR TITLE
[FEATURE] Concurrent MSGF+ database indexing

### LINKED ISSUE #7255: Running MSGF+ in parallel crashes when input DB is new
MSGF+ creates in indexed DB from a FASTA file if it does not find one.
If two instances of MSGF+ run in parallel, they will both try to write/read the same index files and crash with:
```


Standard error: java.lang.NumberFormatException: For input string: ""

	at java.lang.NumberFormatException.forInputString(Unknown Source)

	at java.lang.Integer.parseInt(Unknown Source)

	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.readMetaInfo(CompactFastaSequence.java:516)

<	at java.lang.Integer.parseInt(Unknown Source)
> occurred 2 times
	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.<init>(CompactFastaSequence.java:142)

	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.<init>(CompactFastaSequence.java:89)

	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:235)

	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:113)

	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:61)

Process 'C:/Program Files (x86)/Common Files/Oracle/Java/javapath/java.EXE' did not finish successfully (exit code: ÿ). Please check the log.
```

Our options are:
Have the MSGFAdapter search for the indexed files and
either:
a) abort if index is missing 
b) copy the FASTA file to a temporary directory (where MSGF+ will create an index, which is lost after the adapter finishes)
c) if index is missing, create it, but use some kind of locking mechanism which only allows one adapter to do this

Solution 
a) is the easiest, but also very inconvenient for the user, especially in workflows which use 'DecoyDatabase'; Could be mitigated if the implement a separate MSGFPlus_DB_Adapter, which simply creates the Index; This new Node could be placed right behind DecoyDatabase and thus avoids concurrency issues.
b) is foolproof, but a bit inefficient, especially for very large DB's; could be mitigated by issuing a warning to the user
c) technically challenging to implement locks cross-platform, but convenient and efficient

### PR DESCRIPTION
**Pull request by cbielow**
## Description

fixes #7255 , allowing to run multiple MSGFPlusAdapters of OpenMS concurrently without having to worry about crashing when MSGF+ tries to create an indexed database.

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Can you expose this to the command line (e.g.,  create_index_only).

Would be helpful to distribute it across cluster nodes.

**Comment by cbielow** [comment]
Can be done, but for your usecase it is not required: if the DB is the same for all cluster nodes, the lock will just work fine.
If the DB is different for each node, then thats also ok.
Or did i miss the point?

Am 17.12.2023 13:51 schrieb Julianus Pfeuffer ***@***.***>:

Can you expose this to the command line (e.g., create_index_only).

Would be helpful to distribute it across cluster nodes.

**Comment by cbielow** [comment]
Upon further thought, the lockfile may currently not be suitable for dsitrubuted systems. Will do some tests...

**Review by timosachsenberg — APPROVED** [review]

**Comment by timosachsenberg** [comment]
note that there seem to be some compile errors: https://cdash.openms.de/viewBuildError.php?buildid=199629

**Comment by cbielow** [comment]
> Upon further thought, the lockfile may currently not be suitable for dsitrubuted systems. Will do some tests...

The lock works across nodes in a cluster, which access the same lock file on a network share. The Qt docs for QLockFile are not very chatty about this, but in my setup, it works flawlessly. 
So no need for an extra 'just-index'-flag (which has its own set of problems, such as making input and output files optional)

**Pull request merged**
