### PR TITLE
Make terminal mods are separated by "."

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Synchronized https://github.com/OpenMS/OpenMS/pull/1970

**Comment by timosachsenberg** [comment]
The only change to #1970 is, that the dot is only written at the terminal modification.
This improves compatibility and is nicer to read in the idXML / text files generated.

**Comment by timosachsenberg** [comment]
```
// valid and recommended
AASequence::fromString("DFPIANGER");
// also valid (but not recommended)
AASequence::fromString(".DFPIANGER.");

AASequence::fromString(".(Dimethyl)DFPIANGER");
// is same terminal mod as
AASequence::fromString("(Dimethyl)DFPIANGER");

// recommended for C-term 18O mod:
AASequence::fromString("DFPIANGER.(Label:18O(2))");
// also valid (old style)
AASequence::fromString("DFPIANGER(Label:18O(2))");
```

**Comment by lars20070** [comment]
@timosachsenberg Thanks for that. Only the `FidoAdapter` test remains to be fixed?

**Comment by timosachsenberg** [comment]
any additional comments?

**Comment by lars20070** [comment]
+1

**Comment by hroest** [comment]
pretty cool, @grosenberger have you tested this with our OpenSWATH pipeline? I think it wont have much effect but it would be good to see whether this breaks something...

**Comment by grosenberger** [comment]
Unfortunately not yet, but I agree, this is much needed and will improve our capabilities to differentiate tricky cases. I will have a look as soon as possible.

**Comment by jpfeuffer** [comment]
By the way, during EUBIC winter school I was in contact with Veit Schwämmle who is member of a group with the goal to standardize the representation of proteoforms (i.e. modified peptides and proteins). I signed up to receive any news but it seems they are still in drafting period.
One thing I can say is that they chose "-" over "." to represent termini... doh.

**Pull request merged**
