### PR TITLE
Updated test files to match new MSGFPlus version.

### PR DESCRIPTION
**Pull request by jpfeuffer**
Related to https://github.com/OpenMS/THIRDPARTY/pull/8
The UnitCvRef attribute is what makes it break. I thought it would be better to change the test file instead of whitelisting another line.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
@mwalzer Will this work with the mzID reader already?

**Comment by mwalzer** [comment]
Newest MSGF+ produced files work nicely. But I think we should keep the test files en par with the version in our 3rd-party repo.

**Comment by jpfeuffer** [comment]
Yep. There is also a PR to the repo. We could merge them simultaneously.

**Comment by jpfeuffer** [comment]
Hm.. but I think I have to correct IDFileConverter15, too.

**Comment by jpfeuffer** [comment]
Ok problem was actually the difference in the path to the spectral_data. I whitelisted it as it is machine dependent.

**Comment by timosachsenberg** [comment]
feel free to merge

**Comment by mwalzer** [comment]
Thx

**Pull request merged**
