### PR TITLE
Feature/spline interpol

### PR DESCRIPTION
**Pull request by hroest**
simple code extraction: maximum point estimation using a spline

### CODE REVIEW

**Comment by hroest** [comment]
will make it easier to reuse the code

**Comment by timosachsenberg** [comment]
look good. don't know why windows failed

**Comment by jpfeuffer** [comment]
http://cdash.openms.de/viewBuildError.php?buildid=265589

**Comment by jpfeuffer** [comment]
I guess that was the last build

**Comment by hroest** [comment]
hopefully addressed with 4d374ab029c9c1414cf831f29fc06c63112bb41a

**Pull request merged**
