### PR TITLE
ProteinQuantifier: use peptide-level protein inference results

### PR DESCRIPTION
**Pull request by hendrikweisser**
With these changes, peptide-level data supplied to ProteinQuantifier via parameter "protein_groups" is taken into account for quantification. In particular:
- only peptides listed in the "protein_groups" file are quantified
- peptide-to-protein references are taken from "protein_groups" (not "in", like previously)

This is the counterpart to pull request #1358 for allowing protein quantification based on non-proteotypic ("razor") peptides - see issue #1210.

### CODE REVIEW

**Comment by hendrikweisser** [comment]
Oops, looks like I forgot to update the class test. I'll change that soon!

**Comment by hendrikweisser** [comment]
One of the Travis test runs timed out, the other three ran through fine.

**Comment by timosachsenberg** [comment]
+1

**Comment by lars20070** [comment]
@hendrikweisser In the future, ProteinQuantifier should also write mzTab and simply fill in the protein quantifications.

For now, could the tool output report all proteins given by protein_groups and report NA if a protein could not be quantified? A single list as in other software packages. We would also like a small flag with the information why the protein was not quantified. For example, none of the peptide sequences was quantified at all, some where quantified but greedily taken by another protein, some were quantified but none of them is unique (if unique quantification was chosen).

Such a flag will save much time during beta testing and provide more transparency.

**Comment by oliverschilling** [comment]
That would be a very useful feature indeed!

**Pull request merged**
