### PR TITLE
Add missing QT4 libs

### PR DESCRIPTION
**Pull request by michaelvanvliet**
When installing OpenMS on my Linux machine I had to install some additional libs to get OpenMS to build properly.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Hmm.. can anyone confirm this? In my Dockerfiles it works fine the old way. On the other hand, I did not test with GUI. Maybe it's for GUI-only, in which case we should add another disclaimer.
Thanks for reporting anyway.

**Comment by hroest** [comment]
we currently only have "qt4-dev-tools" and for sure need "libqt4-dev" otherwise it wont compile at all. It seems that "qt4-dev-tools" recommends but does not require "libqt4-dev". So I think this is more explicit and we should accept the PR.

**Comment by jpfeuffer** [comment]
Okay. Then it might have been installed implicitly somehow on the systems I tested on. Fine with me then. +1

**Comment by jpfeuffer** [comment]
Also included in #1945. We can still merge this one if you can not wait, but I suggest to wait for the big merge after the release.

**Comment by cbielow** [comment]
So we can close this PR and wait for merge of master?

**Comment by jpfeuffer** [comment]
That's what I would suggest.

**Comment by cbielow** [comment]
closing as duplicate.
will be merged with master after release.

**Pull request closed without merging**
