### PR TITLE
Feature/chrom by

### PR DESCRIPTION
**Pull request by hroest**
- allow extraction of spectra/chromatogram by id
- fix some issues when no meta data was present in OnDiscMSSpectrum
- add tests

### CODE REVIEW

**Comment by timosachsenberg** [comment]
can we use this from pyOpenMS as well?
Would be nice to make our visualization widgets in pyopenms-extra compatible with on-disc experiments.

**Comment by hroest** [comment]
> can we use this from pyOpenMS as well?

done

> Would be nice to make our visualization widgets in pyopenms-extra compatible with on-disc experiments.

you can already, but access is by integer id and not be native id (string)

**Comment by timosachsenberg** [comment]
rebuild jenkins

**Comment by hroest** [comment]
looks like its ready to merge, before only CodeFactor was complaining so all tests pass. @timosachsenberg merge?

**Pull request merged**
