### PR TITLE
restrict number of spawned processes

### PR DESCRIPTION
**Pull request by timosachsenberg**
## Description

In TOPPView tool discovery

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Do you think it makes sense to add a debug mode for TOPPView, where it tells you, at least during loading, what is happening?

**Comment by timosachsenberg** [comment]
I will check.

**Comment by poshul** [comment]
It looks like we are seeing Sirius test failures here again. No idea why these changes would cause them. @axelwalter any thoughts?

**Comment by timosachsenberg** [comment]
@jpfeuffer I merge this as a fix but I already added the flag to pass verbosity to TOPPView.
Currently it is not used in TOPPToolDiscovery but I could easily add some information.
Question is how we will output that (e.g., we probably can write to std::cout / use our OPENMS_ macros) writing to log files
is probably not that simple because the components are not tied to the logging mechanism.

**Comment by jpfeuffer** [comment]
But didn't you say it failed because of file handles? This is not the same error that is encountered as in the issue.
So I would say the chances that this fixes anything are slim. And tomorrow after the user kindly downloads, extracts, tests etc the tool, we are not any smarter than before. So I wanted to take this chance to be able to see what is going on. Alternative is: you guide them through an lldb debugging session.

**Comment by jpfeuffer** [comment]
I think cout is fine although I don't understand "the components are not tied to the logging mechanism".

**Pull request merged**
