### PR TITLE
[FEATURE] Improvements for PQP conversion / Renaming of classes

### PR DESCRIPTION
**Pull request by grosenberger**
This PR improves the conversion from TSV or TraML to PQP. Instead of ~20min (PHL), this takes now <2min. To achieve this, the necessary PQP indexes during conversion are based on different data structures.

Additionally, the classes TransitionTSVReader and TransitionPQPReader are renamed to TransitionTSVFile and TransitionPQPFile according to the request of @timosachsenberg.

### CODE REVIEW

**Comment by grosenberger** [comment]
I'm not sure why Travis-CI is complaining. Is there some build cache that needs to be reset? Please merge this PR only after merging #3086, #3097 and #3099, as there might be some synchronizing required.

**Comment by timosachsenberg** [comment]
Can you merge against develop and push? Or rebase...

**Comment by grosenberger** [comment]
I did rebase the changes and added support for the other now merged PRs. Building and testing works on my and most of the build systems, however I can't figure out why the remaining Travis build is failing. Is this because I renamed the classes and CMake needs to update?

**Comment by grosenberger** [comment]
Ok, this is ready from my side now. Please let me know, if any other changes should be made before merging.

**Pull request merged**
