### PR TITLE
Feature/sulfur specific averagine

### PR DESCRIPTION
**Pull request by DennisGoldfarb**
Added functionality to estimate isotopic distributions for a peptides and peptide fragments given their mass **and** the exact number of sulfurs in the molecule (instead of just the masses). Let's call them sulfur-specific averagine models. For peptides of similar mass, the number of sulfurs causes a large difference between their isotopic distributions. For example Dirk Valkenborg created separate models to compute isotopic distributions for each case of # sulfurs in the peptide (i.e. 0, 1, 2, etc.) http://www.sciencedirect.com/science/article/pii/S1044030508000597 and http://proteinspector.com/pdf/ghavidel2014a.pdf

The difference is larger for smaller peptides, and since I'm personally working on fragments this was important for me. Typically you wouldn't know how many sulfurs are in the peptide _a priori_ and would have to try a range of values, but I think there are still some uses cases for it. With my current evaluation procedure it appears to make a bigger difference on theoretical data than with experimental data though. On experimental data there appears to be a bias towards larger isotopes that I haven't been able to figure out yet.

**Comparisons on theoretical data:**

I generated the theoretical isotopic distributions of all peptides and all their b/y fragments and checked how well they matched with the averagine method vs sulfur-specific averagine. Note that the x and y-axes aren't synced - they're scaled for each subplot, but have the same binsize when comparing averagine vs sulfur-specific averagine.

precursor_residuals

precursor_chisquared

The headers here (e.g. "0-4") specify which precursor isotopes were theoretically isolated.

fragment_residuals

fragment_chisquared

**Comparisons on low-throughput experimental MS2 data:**

The method compared are the averagine approach for fragment isotopes, sulfur-specific averagine, and exact fragment method. These are for two fragments of Neurotensin which had various precursor isotopes isolated (the isolated isotope is labeled on the right). Averagine and the sulfur-specific Averagine (setting the number of sulfurs to 0 because we know the sequence of the fragment and peptide) were the same for Y7++ because at that particular mass the Averagine method would round to 0 sulfurs.
low_throughput

**Comparisons on high-throughput experimental MS2 data:**

This was a HeLa whole cell lysate performed on an orbitrap lumos with an isolation width of 1.6. I performed a database search and then for each peptide at a 1%FDR I tried to match theoretical fragments to the observed spectra and compared the observed isotopic distribution to the computed ones. Here I only kept fragments where all the expected isotopes were observed. I split the plots based on how many isotopes were observed.

chi-squared_complete_2

| method | median | min | max | count
| ------------- | ------------- | ------------- | ------------- | ------------- |
| ApproxFragment  | 0.004739345  | 1.07001e-11 | 10.2918 | 128484
| ApproxFragmentSulf  | 0.004720605  | 4.21937e-13 | 10.2569 | 128484
| ExactFragment | 0.00439491 | 6.82101e-14 | 11.4251 | 128484

chi-squared_complete_3

| method | median | min | max | count
| ------------- | ------------- | ------------- | ------------- | ------------- |
| ApproxFragment  | 0.0226028  | 9.59216e-07 | 29.912 | 23592
| ApproxFragmentSulf  | 0.0198111  | 7.85389e-09 | 29.9408 | 23592
| ExactFragment | 0.0206527 | 1.02522e-06 | 28.5052 | 23592

chi-squared_complete_4

| method | median | min | max | count
| ------------- | ------------- | ------------- | ------------- | ------------- |
| ApproxFragment  | 0.0401082  | 0.000226775 | 34.5792 | 1148
| ApproxFragmentSulf  | 0.0380023  | 0.000196022 | 33.6667 | 1148
| ExactFragment | 0.0391561 | 1.37692e-05 | 34.8144 | 1148

I appreciate any thoughts and input. Thanks!

### CODE REVIEW

**Comment by hroest** [comment]
this looks great, its almost a model for a perfect pull request: you provide a good rational for the change, show data how this improves the current situation and have included tests, documentation and Python bindings.


> The difference is larger for smaller peptides, and since I'm personally working on fragments this was important for me. Typically you wouldn't know how many sulfurs are in the peptide a priori and would have to try a range of values, but I think there are still some uses cases for it. 

Just out of curiosity, what would these use cases be?

:+1: for adding this.

**Comment by DennisGoldfarb** [comment]
Hi Hannes,

Thanks for the compliment! 

My main goal is to use dynamic isolation widths and offsets in DDA experiments as opposed to the current methods that use the same width and offset throughout the entire experiment. My hypothesis is that I could maximize the amount of precursor ions that are isolated and avoid some interference from co-isolation and therefore increase PSMs. Unfortunately, a dynamic isolation window could isolate a set of precursor ions that make the MS2 ions incompatible with current sequencing algorithms because the mono-isotopic fragment might be very low abundant and/or any de-isotoping method might get confused. So I need a way to de-isotope/transform these odd MS2 spectra into ones that contain only mono-isotopic peaks (even if no mono-isotopic peak was detected). Right now I'm thinking of trying a non-negative least squares approach to de-isotope the MS2 spectra (similar to https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-13-291) and that requires theoretical isotope distribution templates for fragment ions. When I compared the averagine approximated fragment isotope distributions to the exact theoretical distributions, I saw some pretty big deviations and figured out it was because of the sulfurs. My thought then became that I could create templates for each sulfur-specific model up to maybe 3 sulfurs and let the NNLS with some kind of sparsity penalty pick which ones fit best. The idea was more promising when I only had the theoretical comparisons, but now that I see the experimental ones aren't as striking, I might end up not having to use the sulfur-specific models.
	
The other application of de-isotoping MS2 spectra by taking into account which precursor isotopes were isolated is to differentiate between fragments from co-isolated ions. For example if you targeted a +2 precursor and your window should have isolated the M0 and M1 peak, but a +3 precursor was co-isolated (the isolation window wouldn't be centered on it so it could be many different combinations of precursors isotopes), I might be able to tell if the fragment came from the +2 precursor or the +3, or something else based on the isotopic distribution.

The third application I thought of would be to purposely multiplex MS2 scans but using shifted isolation windows for each precursor ion so that they would create very distinct fragment isotope patterns that would make it easy to de-convolute the chimera spectra.
	
So I guess in summary, I need accurate templates of what the fragment distributions will look like, but I'm not sure if the sulfur-specific models will end up being useful. Maybe one day if I figure out what's causing the disagreement between theoretical and experimental data and I can fix or account for it.

**Comment by hroest** [comment]
> The third application I thought of would be to purposely multiplex MS2 scans but using shifted isolation windows for each precursor ion so that they would create very distinct fragment isotope patterns that would make it easy to de-convolute the chimera spectra.

Have you looked at the MSX work and what the MacCoss lab at UWashington is doing on multiplexed spectra? Most of that work is going on in DIA; de-multiplexing is a very hot topic at the moment. I would be very interested to see some work in OpenMS in that direction. Feel free to contact me if you want to go more in this direction.

> So I guess in summary, I need accurate templates of what the fragment distributions will look like, but I'm not sure if the sulfur-specific models will end up being useful. Maybe one day if I figure out what's causing the disagreement between theoretical and experimental data and I can fix or account for it.

I think @hendrikweisser has seen that before as well and was also somewhat puzzled by that - maybe he can comment on his experience with modelling isotope distributions and how well they fit the experimental ones. I think in his case he was even comparing the *exact* distribution of the peptide sequence to the experimental one. However, if you can somehow *quantify* the deviation for Thermo machines, maybe you can build that into a model and then approximate the experimental distribution?

**Comment by timosachsenberg** [comment]
By the way, there is a peptide search engine implementation in OpenMS. It was originally intended for educational purposes only. Meanwhile, it has grown into a rather complete implementation but lacks some features like, for instance, e-value calculation or more advanced scoring functions. Might still be a nice testbed for some of your ideas. See https://github.com/OpenMS/OpenMS/blob/develop/src/utils/SimpleSearchEngine.cpp

**Comment by DennisGoldfarb** [comment]
> Have you looked at the MSX work and what the MacCoss lab at UWashington is doing on multiplexed spectra? Most of that work is going on in DIA; de-multiplexing is a very hot topic at the moment. I would be very interested to see some work in OpenMS in that direction. Feel free to contact me if you want to go more in this direction.

I am familiar with MSX and DIA in general. I think my ideas aren't as applicable to most DIA methods because the isolation windows are large enough for the full precursor isotopic distributions to be isolated. When that happens the fragment isotope distributions are the same as if they were a precursor in an MS1 scan, so there's no way to tell if it came from precursor A or B because it's no longer dependent on them. The only time it might work is when an precursor isotope distribution straddles the DIA window. With MSX it could be pretty useful because they have groups of 4m/z windows so the straddling might happen a lot.

> I think @hendrikweisser has seen that before as well and was also somewhat puzzled by that - maybe he can comment on his experience with modelling isotope distributions and how well they fit the experimental ones. I think in his case he was even comparing the exact distribution of the peptide sequence to the experimental one. However, if you can somehow quantify the deviation for Thermo machines, maybe you can build that into a model and then approximate the experimental distribution?

That's interesting that @hendrikweisser saw that as well. I'm assuming that it was at the MS1 level? So far I've only compared the distributions at the MS2 level, but also with the theoretical exact distributions. I've plotted the residuals for each isotope and there's clearly a trend for higher isotopes to have higher signal than expected (at least when the isolation window is centered on the M0 precursor). To correct for it properly I think I would need to better understand the nature of what's causing the bias because I would use a different approach depending on what it was. For example if the bias comes from a non-uniform isolation efficiency where the higher isotope gets isolated more (though the calibration curves make it look pretty box-y) then those higher precursor isotopes would contribute to all the fragment isotopes but at different amounts (precursor M2 will make M0, M1, and M2 fragments) and I can easily correct for that. If it's something like a non 1:1 ratio of signal vs abundance then I would have to do that differently.

Thanks @timosachsenberg I'll look into that. It would probably make matching the experimental and theoretical fragments easier.

**Comment by hroest** [comment]
any objections to a merge? If not, a member of OpenMS will merge this within the next day or so

**Pull request merged**
