### PR TITLE
Fix #4691 (NucleicAcidSearchEngine mzTab output)

### LINKED ISSUE #4691: NucleicAcidSearchEngine: sequence matches missing in mzTab output
Reported by Joshua Jones and verified by me. Oligonucleotide sequences that match in several places in one RNA are not correctly listed as such in mzTab output ("OLI" section) from NucleicAcidSearchEngine. They only appear once with the last match in the RNA.

(Oligos that match in multiple RNAs will be listed multiple times, but only once per RNA.)

### PR DESCRIPTION
**Pull request by hendrikweisser**
Fix issue with mzTab output of sequences that match multiple times in one RNA (#4691).

### CODE REVIEW

**Comment by hendrikweisser** [comment]
jenkins rebuild

**Comment by jpfeuffer** [comment]
rebuild jenkins

**Comment by jpfeuffer** [comment]
also, maybe executors are full

**Comment by hendrikweisser** [comment]
There's something weird going on with the Jenkins tests here. It looks to me like they failed in the clean-up stage, after building and the actual OpenMS tests were successful.

**Comment by jpfeuffer** [comment]
yes it is "just" the external code test. Should be fixed by now, but it would be best if you wait for a rebuild.

**Comment by hendrikweisser** [comment]
Okay, good to know. I don't mind waiting a bit, and I assume the rebuild is scheduled now (and will run when there's capacity)?

**Comment by hendrikweisser** [comment]
By the way, could we generate a nightly installer for Windows that includes this fix, once it's merged, please?

**Comment by jpfeuffer** [comment]
Yes, Windows is the bottleneck. 3 before your build.
Yes, the nightly installer should be auto-generated, let me know when the PR is merged and on the next day, there is still none.

**Pull request merged**
