### PR TITLE
[FEATURE] ProteinProphetAdapter/TPPAdapter

### PR DESCRIPTION
**Pull request by liangoaix**
TPP PeptideProphet and ProteinProphet adapter. This version is working for XTandemAdapter idXML results. TPP/xinteract program will do the PeptideProphet analysis on the peptideID results and TPP/ProteinProphet will do the protein inference. 
Tests are added into the SEARCHENGINES folder.

### CODE REVIEW

**Comment by hroest** [comment]
what is happening here, is this still active ?

**Comment by liangoaix** [comment]
yes. got stuck in testing on windows. can anyone help?

**Comment by lars20070** [comment]
Can this be merged? - @liangoaix Can you roughly reproduce with XTandemAdapter/TPPAdapter the results from X!Tandem/PeptideProphet/ProteinProphet in TPP?

**Comment by timosachsenberg** [comment]
apart from not being mergable ;) I thought there were some open issues

**Comment by lars20070** [comment]
Ok. I had only looked at the tests. - Just had an enquiry from a potential new user. There is still interest in such an adapter.

**Comment by hroest** [comment]
if the tests are working, I would be in favor of a merge. But of course somebody has to fix the merge conflicts first - @lars20070 if you feel like doing that, you can merge on your machine and then create a new pull request

**Comment by liangoaix** [comment]
I can fix the conflicts and so far tests on Mac and linux work well. I would add a warning of the adapter on windows due to the wrong temp path, is it a solution?

**Comment by liangoaix** [comment]
@lars20070 If don't use the default k score in TPP-X!Tandem, the results (X!Tandem+TPPAdapter and TPP) would be the same in my tests.

**Comment by lars20070** [comment]
Thanks @liangoaix. Is it possible to MS-GF+ searches and TPPAdapter protein inference? Would be a useful check for our Fido results.

**Comment by timosachsenberg** [comment]
any news on this PR? It would be sad to just close it.

**Comment by hroest** [comment]
yes, I would also like to see this merged. The question is whether we merge first or get the testing to a point where we can reproduce the TPP workflow as @liangoaix was trying to do. The question is whether the mapping of probabilities to FDR now allows for a faithful reproduction, any news here?

**Comment by timosachsenberg** [comment]
3 years now... closing

**Pull request closed without merging**
