### PR TITLE
[FEATURE] AbsoluteQuantitation::getOptimizedCalibrationCurve()

### PR DESCRIPTION
**Pull request by pasqoo**
This function optimizes the parameters of the calibration for a single component, instead of a set of components (already implemented in `optimizeCalibrationCurves()`).
Internally, this method also calls said method.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
The interface (maybe only the name) of the new function confused me a bit.
It is certainly no getter and more like an "updateComponentConcentrations". Might be personal taste, but I don't like methods that update results in-place if it can be avoided.

An idea how this could be changed: provide a function that calculates the component concentrations of a **single** component. Building on that you could create the function that does it for all components at once. So this would basically reverse the logic you use now (currently you use a function that updates everything but you actually only want to update a single component).

I only gave it a brief look so maybe there is good reason to do it the other way around... so sorry about that if that is the case.

**Comment by pasqoo** [comment]
I agree that the design of the new method is not exciting, and your solution is more elegant.
The thing is, this new method was not really needed. It's been implemented only to offer some python binding, because users could not currently use what was already implemented (`optimizeCalibrationCurves()`) due to the unsupported nested type argument.
This new method is not meant to be used from the "c++ side".

Do you think a change to the workflow is necessary?

In any case, I think that improving the method's name is a good idea.
Thanks for the proposed name, I'll take that into account.

**Comment by timosachsenberg** [comment]
Ok I see, in this case it is fine with me. Feel free to change the name.

**Comment by pasqoo** [comment]
PR is up to date @timosachsenberg @hroest

**Comment by hroest** [comment]
👍 if it passes tests

**Comment by pasqoo** [comment]
@hroest thanks :smile: 
looks like only the apple config is failing. It complains about files not being readable

**Comment by timosachsenberg** [comment]
If you find time (and maybe just as an additional commit to some unrelated PR) you might want to document that this method is provided primarily to ease python bindings.

**Comment by pasqoo** [comment]
Sure, I'll take care of that.
@timosachsenberg I noticed that I also staged some untracked files in my last commit (an .mzML file and 3 csv files). This was not intended.
The files are output files from other classes' tests.
Should I leave them there, or make a PR to remove those files?

**Comment by timosachsenberg** [comment]
Please remove them in another PR

**Pull request merged**
