### PR TITLE
[FIX] small improvement

### PR DESCRIPTION
**Pull request by hroest**
after #3307 - its so silly it may just work

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Hmm but be careful, this prevents building pyopenms on a VS Command line or powershell

**Comment by jpfeuffer** [comment]
Ah sorry was too quick. But what if there will be the new Cython on Windows?

**Comment by hroest** [comment]
well its anyways only a fix for travis which interprets warnings in stderr as errors

**Comment by jpfeuffer** [comment]
Aaah it's not ctest that decides on error here?

**Pull request closed without merging**
