### PR TITLE
Update Comet on non-Win in THIRDPARTY to match bugfix version.

### PR DESCRIPTION
**Pull request by jpfeuffer**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
@timosachsenberg did you not update Percolator in your earlier PR?

**Comment by timosachsenberg** [comment]
Yes but maybe not the submodule

**Comment by jpfeuffer** [comment]
win workspace was in use by me

**Comment by jpfeuffer** [comment]
rebuild jenkins

**Pull request merged**
