### PR TITLE
SwathWizard icns

### PR DESCRIPTION
**Pull request by oliveralka**
# Description
SwathWizard icons (.icns) for macOS

#4923 (partially)

### CODE REVIEW

**Comment by jpfeuffer** [comment]
To save on the number of installers to test, maybe you could include the Path fix here as well?

**Comment by oliveralka** [comment]
@jpfeuffer What was the consensus of that? Basically an additional path if the first one is empty, which looks at the relative path on the .app location?

**Comment by jpfeuffer** [comment]
Yes,
a) modify plist to have only /use/bin
b) also look in ../../execPath (double-check) for OpenswathWorkflow, at least on mac.

**Comment by cbielow** [comment]
> b) also look in ../../execPath (double-check) for OpenswathWorkflow, at least on mac.

so, https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/SYSTEM/File.h#L273, i.e.
`File::findSiblingTOPPExecutable("OpenSwathWorkflow");` should do it.
@oliveralka Can you modfiy https://github.com/OpenMS/OpenMS/blob/develop/src/openms_gui/source/VISUAL/DIALOGS/SwathTabWidget.cpp#L80 accordingly and test it?

**Comment by oliveralka** [comment]
I will do that and test it.

**Comment by oliveralka** [comment]
The .app worked for me in the bin directory and after copying it to the parent directory.

**Comment by cbielow** [comment]
Thanks @oliveralka @jpfeuffer for taking care of this!

**Pull request merged**
