### PR TITLE
MassCalculator: output is csv

### PR DESCRIPTION
**Pull request by bernt-matthias**
not sure about about the `-in` parameter. Could be csv,tsv,txt since 

> Whitespace, commas or semicolons can de used to delimit the different items.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
I think we can just use tsv for the input but keep the "\t,;"  code for backwards compatibility

**Comment by bernt-matthias** [comment]
Sure. It would also be easy to change the output to tsv..?

**Comment by timosachsenberg** [comment]
sure go for it

**Comment by jpfeuffer** [comment]
> Could be csv,tsv,txt

Why did you go for tsv-only in the end? In any case, the filenames of the test input should be changed accordingly or "txt" has to be allowed additionally.

**Comment by bernt-matthias** [comment]
OK. I can add csv to the allowed extensions for the input.

For the output I would suggest to drop the separator argument and replace it with an optional out_type argument. Then the separator would be determined from this argument or the file extension. Is there another program where I could get inspiration for this?

**Comment by timosachsenberg** [comment]
I would not make it too complicated and just use tab as fixed separator and tsv consistently.

**Comment by bernt-matthias** [comment]
As you wish, just tell me if there is anything else to do.

**Comment by timosachsenberg** [comment]
As always, thanks a lot Bernt! Highly appreciated

**Pull request merged**
