### PR TITLE
Fix/1983

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Escape commas in Strings of StringLists when writing out XML.
Important because Strings are separated by ',' and we need to distinguish the commas in Strings from
the ones separating the Strings.
Reader code also added.

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- /rebase will try to rebase the PR on the current develop branch.
- /reformat (experimental) applies the clang-format style changes as additional commit
- setting the label NoJenkins will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)

### CODE REVIEW

**Comment by cbielow** [comment]
looks good to me

**Review by cbielow — APPROVED** [review]

**Comment by timosachsenberg** [comment]
hmm seems as if Xerxes is automatically decoding `&#44;` to "," so this approach doesn't work (at least for the default methods we use).

**Comment by timosachsenberg** [comment]
need to update one more test. Now descriptions are correctly passed:
```
in1:  /home/jenkins/ws/openms/PR/bldtst/a9154670/build/src/tests/class_tests/openms/AccurateMassSearchEngine_test_396.tmp   (line: 2902, position/column: 170/206)
					<UserParam type="stringList" name="description" value="[Linalyl benzoate,Geranyl benzoate,Falcarinolone,Ginsenoyne E,Ginsenoyne A,Flavidulol B,Flavidulol A,(all-E)-1!
					                                                                                                                                                                     \|8\|10-Heptadecatriene-4\|6-diyne-3\|12-diol]"/>

in2:  /home/jenkins/ws/openms/PR/bldtst/a9154670/source/src/tests/class_tests/openms/data/AccurateMassSearchEngine_output1.consensusXML   (line: 2902, position/column: 170/206)
					<UserParam type="stringList" name="description" value="[Linalyl benzoate,Geranyl benzoate,Falcarinolone,Ginsenoyne E,Ginsenoyne A,Flavidulol B,Flavidulol A,(all-E)-1!
					                                                                                                                                                                     ,8,10-Heptadecatriene-4,6-diyne-3,12-diol]"/>
```

**Comment by timosachsenberg** [comment]
@hendrikweisser is such escaping also needed for the ID datastructure or do store the StringList entries in separate rows?

**Comment by hendrikweisser** [comment]
> is such escaping also needed for the ID datastructure or do store the StringList entries in separate rows?

It's needed in at least one place in `OMSFileStore`:
https://github.com/OpenMS/OpenMS/blob/337fe76788262d76d7feaf997c871d4c2acebc0a/src/openms/source/FORMAT/OMSFileStore.cpp#L482-L483

**Pull request merged**
