### PR TITLE
[FIX] test presence of files in input file lists

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Exit Value | 1
-- | --
1

**Comment by jpfeuffer** [comment]
does TOPPBase use our File.find functions? Cause only those respect searching in share and OpenMS home.

**Comment by timosachsenberg** [comment]
File:exists

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/blob/develop/src/utils/AccurateMassSearch.cpp#L107

**Comment by timosachsenberg** [comment]
fixes https://github.com/OpenMS/OpenMS/issues/4632

**Pull request merged**
