### PR TITLE
uncomment a test comparison for IDPosteriorErrorProbability

### PR DESCRIPTION
**Pull request by bernt-matthias**
At least on Linux systems the comparison seems to work now. Lets see what the CI tests say.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
rebuild jenkins

**Comment by bernt-matthias** [comment]
> rebuild jenkins

Do I need to do anything?

**Comment by timosachsenberg** [comment]
tests are failing so probably this test is not stable on every platform

**Comment by bernt-matthias** [comment]
If I understand it correctly the test that is failing (https://travis-ci.org/github/OpenMS/OpenMS/jobs/655271917) is on linux. Is there a easy possibility to see why it is failing?

**Pull request closed without merging**
