### PR TITLE
[BUILD] pyOpenMS build script for Linux

### PR DESCRIPTION
**Pull request by hroest**
docker script to produce the manylinux wheels

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Can you have a quick look on the codacy suggestions? They seem reasonable. I will try to create a job and add it to our release procedure.

**Comment by hroest** [comment]
hmm I would prefer to leave it as is as I have just used it to generate the wheels and I dont want to re-create all the wheels to test (it takes a few hours)

**Comment by jpfeuffer** [comment]
Ah of course, I meant future releases only. ;)

**Comment by hroest** [comment]
merge @jpfeuffer  ?

**Pull request merged**
