### PR TITLE
[REFACTOR] Use boost::regex instead of regex in SiriusMzTabWriter

### PR DESCRIPTION
**Pull request by lukaszimmermann**
<regex> should perhaps be avoided since it does not work with GCC < 4.9.

### CODE REVIEW

**Comment by oliveralka** [comment]
Looks good. 
Regex is working now as expected on linux, gcc 4.8.5.

**Comment by oliveralka** [comment]
Random build failure or problem?
https://travis-ci.org/OpenMS/OpenMS/jobs/263432664
24 - pyopenms_test_memoryleaktests (Failed)

**Comment by jpfeuffer** [comment]
I guess unrelated. But not 100% sure.

**Comment by lukaszimmermann** [comment]
Could be related to this issue:

https://stackoverflow.com/questions/20133961/memory-leak-in-boostregex-library

**Comment by jpfeuffer** [comment]
If that's true, I guess our options are:
- Ignore
- Try to whitelist this during the check
- Switch to the std:: one and require recent compilers
- Write our own

I would go for the second if that is possible. What do you think @hroest ?

**Comment by cbielow** [comment]
do you really need a regex for this?
`std::string scan_index = path.substr(path.find_last_not_of("0123456789"));`
(untested)

**Comment by lukaszimmermann** [comment]
Very likely. Thanks! Gonna change that.

**Comment by lukaszimmermann** [comment]
Ok, works well.

**Pull request merged**
