### PR TITLE
update Unimod

### PR DESCRIPTION
**Pull request by lars20070**
The pull request updates the Unimod database. The `unimod.xml` file was downloaded from [1] on 28/12/16 and supplemented with mods 99987 to 99995 as in #1993.

[1] http://www.unimod.org/downloads.html

### CODE REVIEW

**Comment by timosachsenberg** [comment]
thanks. Can you also add CUSTOM0 ... CUSTOM9 as additional modifications? This will allow users with KNIME to add custom modifications later.

**Comment by timosachsenberg** [comment]
@lars20070 unfortunately you need to add them for every amino acid and also the termini

**Comment by timosachsenberg** [comment]
not only for K but for all amino acids (+ C and N term):
<umod:specificity hidden="1" site="K" position="Anywhere" classification="Chemical derivative" spec_group="1"/>
 +         <umod:delta mono_mass="0.0" avge_mass="" composition="H(1)">
 +            <umod:element symbol="H" number="1"/>
 +         </umod:delta>

**Comment by timosachsenberg** [comment]
thanks alot. only one thing left: specificity must be "Any C-term" or "Any N-term" respectively... probably doesn't work with "Anywhere"

**Comment by timosachsenberg** [comment]
@enetz I don't remember if you added additional entries but could you give it a quick look if everything is contained that you need?

**Comment by enetz** [comment]
I do not need anything in there, that isn't in the newer version of the normal unimod database.
So for me this is sufficient.

**Comment by timosachsenberg** [comment]
+1

**Comment by jpfeuffer** [comment]
Hey guys,

I am getting errors when building the KNIME descriptors:

```
---------------------------------------------------
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler: 
exception of type Parse Error occured in line 104, function void OpenMS::Internal::XMLHandler::fatalError(OpenMS::Internal::XMLHandler::ActionMode, const OpenMS::String&, OpenMS::UInt, OpenMS::UInt) const of /home/jenkins/ws/openms_all/40c74027/source/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp
error message: While loading '/home/jenkins/ws/openms_all/40c74027/source/share/OpenMS/CHEMISTRY/unimod.xml': invalid multi-byte sequence( in line 37666 column 34)
Probable cause: The file suffix (xml) does not match the file content (unknown). Rename the file to fix this. in: /home/jenkins/ws/openms_all/40c74027/source/share/OpenMS/CHEMISTRY/unimod.xml
---------------------------------------------------
/home/jenkins/ws/openms_all/40c74027/source/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp(103): While loading '/home/jenkins/ws/openms_all/40c74027/source/share/OpenMS/CHEMISTRY/unimod.xml': invalid multi-byte sequence( in line 37666 column 34)
Probable cause: The file suffix (xml) does not match the file content (unknown). Rename the file to fix this.
```


Is there maybe a validator for the format?

**Comment by lars20070** [comment]
@jpfeuffer Not that I know. But maybe drop unimod@unimod.org a line.

**Comment by jpfeuffer** [comment]
Could also be an encode/line ending problem.

**Comment by jpfeuffer** [comment]
Ich wette das \beta im full name des records 1839 ist das Problem. Ist das in der offiziellen unimod version auch drin?

**Comment by jpfeuffer** [comment]
@mwalzer Do our readers support UTF8? I would guess so. Do we have to help them im recognizing this?

Otherwise we just rename the char to its meaning "beta" or "b". Although it is not consistent with the original DB then (probably anyway not the case with our custom entries and only a problem if someone uses this obscure modification).

**Comment by mwalzer** [comment]
Yes, they do. As long as  ```<?xml version="1.0" encoding="UTF-8"?>``` is present, which seems to be the case. 
But I guess that propagates the problem upstream to the data structure read in for fancy characters.

**Comment by jpfeuffer** [comment]
Hm yes this might be the case. Any objections in replacing that character for now and dropping unimod a message? It prevents successful KNIME builds. I suspect it to happen during -write_ctd when it parses unimod to get valid selections for the mods.

**Comment by hroest** [comment]
@jpfeuffer @mwalzer the xerces reader does support UTF8 but our internal string class OpenMS::String does not really support utf8. So basically we store the UTF8 string in a regular string and each UTF8 character resolves to multiple code points which is stored as a single "character" in our string, see http://stackoverflow.com/questions/3011082/c-stdstring-and-utf-8 - thus our `length` functions and iterators will not work.

I think all sorts of stuff would break if you try to store a utf8 string in there, its basically just a `std::string` which has no idea about utf8.

**Comment by mwalzer** [comment]
@hroest Yes, exactly. So this would call for a local workaround for unimod. 
Any ideas on how?

**Comment by jpfeuffer** [comment]
Well for now I changed the beta glyph to the word "beta". Actually I am not sure if the unimod guys are aware of this, since it was the only bad character.

**Comment by timosachsenberg** [comment]
Maybe we should report it to the unimod guys

**Comment by jpfeuffer** [comment]
I wrote them. Keep you updated. Although I think they will stick with allowing any UTF8 char, at least in the full names.

**Comment by jpfeuffer** [comment]
As an update: Usually the maintainers of Unimod review contributions and remove non-ASCII characters (in this case the entry was not even reviewed and had other formatting problems).
But in general, they do allow UTF-8 and we should support this, too (see the referenced issue above).

**Pull request merged**
