### PR TITLE
[FIX] fix names of temporary files

### PR DESCRIPTION
**Pull request by hroest**
- ensure that temporary files do not overlap and are unique for each
  test executed

### CODE REVIEW

**Comment by timosachsenberg** [comment]
should we merge this to master or develop?

**Comment by hroest** [comment]
either works for me, it can lead to test failures so having it in master may be beneficial

**Comment by jpfeuffer** [comment]
I guess it depends if this needs to go in the upcoming source release.
Seems like it for me, so I vote for master.
Thing is, I can't change it for you other than making my own branch and picking your commits. Would you change your target branch for this to master if we all agree?

**Comment by hroest** [comment]
you cannot change the target branch at all http://stackoverflow.com/questions/24159036/how-to-modify-a-pull-request-on-github-to-change-target-branch-to-merge-into  -- so I have to do the same thing and open a new PR

**Pull request merged**
