### PR TITLE
[FIX] fix comet adapter test caused by uninitialized value

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
FYI @Leon-Bichmann

**Comment by jpfeuffer** [comment]
Oh I still would have waited for CI. But this should trigger a RC build now.

**Comment by timosachsenberg** [comment]
ah ok I knew that CI would fail because the relaese branch still contains non working CI targets.
I merged because the first ones passed

**Comment by jpfeuffer** [comment]
Ah yes ok

**Pull request merged**
