### PR TITLE
PercolatorAdapter: rename tab to tsv

### PR DESCRIPTION
**Pull request by bernt-matthias**
fixes part of https://github.com/OpenMS/OpenMS/issues/4407

### CODE REVIEW

**Comment by timosachsenberg** [comment]
looks good - is this tested?

**Comment by bernt-matthias** [comment]
There are tests for both adapters

https://github.com/OpenMS/OpenMS/blob/ce53d13da1fc6f499f4cb0eb7de28a0bdb6e8740/src/tests/topp/THIRDPARTY/third_party_tests.cmake#L184

https://github.com/OpenMS/OpenMS/blob/ce53d13da1fc6f499f4cb0eb7de28a0bdb6e8740/src/tests/topp/THIRDPARTY/third_party_tests.cmake#L351

Not sure if the corresponding arguments are involved in the test.

**Comment by timosachsenberg** [comment]
I don't know if these changes will work.
At least form the documentation it seems that spectraST is expecting xls as an extension.
see http://tools.proteomecenter.org/wiki/index.php?title=Software:SpectraST

**Comment by bernt-matthias** [comment]
See http://tools.proteomecenter.org/wiki/index.php?title=Software:SpectraST#SpectraST_Search_Mode

> .xls format, a tab-delimited column text format

**Comment by timosachsenberg** [comment]
maybe I am missing something here  but if you pass .tab instead of .xls how does spectrast know how to handle it? It doesn't know about .tab and I think it only looks at the extension

**Comment by bernt-matthias** [comment]
Ok. So you suggest to leave everything in temp_directory_body .tab?

**Comment by timosachsenberg** [comment]
Percolator is probably not that picky regarding the input file extension (but we would need to check). For SpectraST they base the semantics on how to handle a file on the extension so we are basically doomed to write out the file in the extension it expects.
Do you need to know all e.g. MIME types of files that are created (even if they are only temporary files?) for technical reasons? We might come up with workarounds (e.g., writing out an xls file  but moving it later to .tab if needed) if really required.

**Comment by bernt-matthias** [comment]
> Do you need to know all e.g. MIME types of files that are created (even if they are only temporary files?) for technical reasons? We might come up with workarounds (e.g., writing out an xls file but moving it later to .tab if needed) if really required.

I don't care for temporary files at all. It's just that consistent semantics of the file extensions are really important for automatic processing (e.g. in workflow engines). Otherwise one is doomed to create tool specific special cases etc. 

So a file should have the extension `csv` if and only if it is a comma separated tabular file. Similarly for tsv <-> tab separated, xls <-> microsoft excel proprietary format. 

This is really important, in particular for formats that can't be distinguished by their content and should be easy for formats for which the extensions are widely accepted.

**Comment by timosachsenberg** [comment]
I think we need to undo the change to spectrast. For percolator it should be fine

**Comment by jpfeuffer** [comment]
what is the status here?

**Comment by bernt-matthias** [comment]
I guess we can only find out with tests .. which I just added.

**Comment by jpfeuffer** [comment]
you meant test #5 right?

**Comment by bernt-matthias** [comment]
Jep. My fault.

**Pull request merged**
