### PR TITLE
IDFilter: new default values ('nan') for filtering by score

### LINKED ISSUE #7530: IDFilter: filtering for FDR=0 is impossible/hard
When using an IDFilter after a FalseDiscoveryRate node, then setting
`-score:pep 0` does not filter anything (it skips the filter), but worse: the user cannot tell (since there is no output message to tell it was skipped).
See https://github.com/OpenMS/OpenMS/blob/develop/src/topp/IDFilter.cpp#L553
This is already marked as problematic in the source code.

One can argue that IDFilter is not even required here, since the FDR node can filter, but that is not the point. IDFilter's user interface is broken here IMHO.

Possible fixes: use a new default other than `0`. Since numbers are somewhat unsuitable, we could go with 'nan' to disable the filter.
In this case however, old pipelines which use INI files, will show altered behaviour (since `0` is used in the INI file as input value, which now filters at FDR=0, instead of doing no filtering at all). This may be problematic in terms of backwards compatibility.
To fix this, we could rename the parameter to `-score:PSM`. This has the following advantages: better name, since this is effectively a PSM FDR, not a peptide FDR anyways. No backwards problems, since the user needs to use updated INI files.

The same issue occurs for `-score:prot` and `-score:protgroup`.

Any opinions/ideas?

### PR DESCRIPTION
**Pull request by cbielow**
## Description

fixes https://github.com/OpenMS/OpenMS/issues/7530

the following parameters get renamed:
+ score:pep -> score:psm; 
+ score:prot -> score:protein
+ score:protgroup -> score:proteingroup

and their new default value is 'nan', which means that no filtering is done. (The old default was `0`).
I.e. setting these values to 0 will activate a filter, which now allows (among other things), to filter for FDR==0 using `-score:psm 0` (which before did no filtering).

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

___

### **PR Type**
Bug fix, Tests

___

### **Description**
- Changed default score filter values to `NAN` for peptide, protein, and protein group scores in `IDFilter.cpp`.
- Updated logging messages to reflect the new score filter logic.
- Replaced `ListUtils::create<String>` with initializer list for file format validation in `IDFilter.cpp`.
- Updated test cases in `CMakeLists.txt` to use new score filter options (`score:psm`, `score:protein`, `score:proteingroup`).

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>IDFilter.cpp</strong><dd><code>Update score filter defaults and logging in IDFilter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/topp/IDFilter.cpp

<li>Changed default score filter values to <code>NAN</code> for peptide, protein, and <br>protein group scores.<br> <li> Updated logging messages to reflect new score filter logic.<br> <li> Replaced <code>ListUtils::create<String></code> with initializer list for file format <br>validation.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7541/files#diff-1f9d296d610e31782ad1a26609f859451dfc735448ee2c4c11c0b6108c61f243">+34/-23</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>CMakeLists.txt</strong><dd><code>Update IDFilter test cases with new score filter options</code>&nbsp; </dd></summary>
<hr>

src/tests/topp/CMakeLists.txt

<li>Updated test cases to use new score filter options (<code>score:psm</code>, <br><code>score:protein</code>, <code>score:proteingroup</code>).<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7541/files#diff-ea7d014a06a87eb982d0c1d6bdec70d26c11d3a50db297ba14095aa0410c4928">+7/-7</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by timosachsenberg** [comment]
hmm doe we need this in 3.2?
- this is a breaking change that probably breaks again quite a lot of workflows that use IDFilter.
- Michael already created the list of changed parameters
- Note that the FalseDiscoveryRate tool allows to filter by q-value directly.

**Comment by cbielow** [comment]
> hmm doe we need this in 3.2?
> 
>     * this is a breaking change that probably breaks again quite a lot of workflows that use IDFilter.

Breaking change, yes -- we can wait for 3.3, but it will still break.

> 
>     * Michael already created the list of changed parameters

@mr-c ? Is it hard to re-do?

> 
>     * Note that the FalseDiscoveryRate tool allows to filter by q-value directly.

I am aware, yes. But the old behaviour is dangerous IMHO and may lead users into doing no FDR at all, when they meant to do a 0% FDR. And the worst thing about it is, they won't even know.

**Comment by mr-c** [comment]
> > ```
> > * Michael already created the list of changed parameters
> > ```
> 
> @mr-c ? Is it hard to re-do?

Not really, no

**Comment by poshul** [comment]
This is not gonna get any easier from putting it off. I say we do this for 3.2.0 and include a note in the release notes explicitly calling out this breaking change, as well as instructions for anyone with issues to contact us.

**Pull request merged**
