### PR TITLE
[FIX] schema simplifications and adaptation of enzyme entry

### PR DESCRIPTION
**Pull request by timosachsenberg**
This PR is mainly a rearrangement of the schema and introduction of common XML types (e.g. PeptideHitType, SearchParametersType, etc.) to make the schema easier readable.
One addition is the adaption of the enzyme entry (changed from enum to a xs:string) as we now support arbitrary enzymes via EnzymeDB.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Anyone know why the hierarchy of SearchParameters and IdentificationRun is different?

ConsensusXML:
bildschirmfoto 2015-10-28 um 10 01 56

IdXML:
bildschirmfoto 2015-10-28 um 10 10 09

**Comment by hendrikweisser** [comment]
> Anyone know why the hierarchy of SearchParameters and IdentificationRun is different?

I don't know the reason, but one observation is that a SearchParameters entry in idXML can be referenced by several IdentificationRuns (via the "search_parameters_ref" attribute).
In consensusXML, the documentation text for "SearchParameters" says that they can be used for several ID runs, but I don't see how that would be possible if they are within different IdentificationRun elements.

**Comment by timosachsenberg** [comment]
probably just a copy and paste error of the documentation. I fixed a few but maybe missed that one.

**Comment by timosachsenberg** [comment]
travis passed - mac timed out. Any comments or proceed with merge?

**Pull request merged**
