### PR TITLE
mutliple DB for AMS

### PR DESCRIPTION
**Pull request by cbielow**
- allow to parse more than one DB during AccurateMassSearch

other minor fixes:
 - avoid Exception (e.g. in TOPPViewIdentification) for unidentified AMS peak
 - allow empty lines in Adduct.tsv file for AMS

### CODE REVIEW

**Comment by cbielow** [comment]
passed. Test failures unrelated.

Merge?

**Comment by timosachsenberg** [comment]
can you post a mztab output

**Comment by cbielow** [comment]
good point. Indeed, its still 'null'

```
![image](https://cloud.githubusercontent.com/assets/6008722/17615309/a65f0efe-606d-11e6-82c0-662f443dbdad.png)

```

**Comment by cbielow** [comment]
merge?

**Comment by timosachsenberg** [comment]
hmm there should be not "-" in that column if the information is not available. but feel free to merge if this is not related to your PR

**Comment by cbielow** [comment]
the "-" is in my DB, so this is the expected behavior. I should 'fix' my DB -- but I have no use for these columns so thats why I just put '-'.

**Pull request merged**
