### PR TITLE
merge develop into qt5 branch

### PR DESCRIPTION
**Pull request by hroest**
merge develop into qt5 branch

@cbielow and @timosachsenberg can you please look at 797cdfd and 22e3f3d - I think here something got screwed up in the last merge and I tried to fix it but I was not too familiar with the code

### CODE REVIEW

**Comment by hroest** [comment]
fixed a segfault in MascotAdaptor. currently the following tests are failing:

```
99% tests passed, 5 tests failed out of 2015

Total Test time (real) =  90.43 sec

The following tests FAILED:
         50 - LPWrapper_test (OTHER_FAULT)
        181 - MzXMLFile_test (Failed)
        575 - TOPPView_test (Not Run)
        1907 - UTILS_ImageCreator_1_out1 (Failed)
        1909 - UTILS_ImageCreator_2_out1 (Failed)
Errors while running CTest
```

**Comment by timosachsenberg** [comment]
MzXML test could be fixed with merge against master

**Comment by hroest** [comment]
I added a few more commits to make travis work better with the qt5 branch, it now compiles through but there is a linking issue with the debug build

**Comment by hroest** [comment]
PS: maybe we could apply 6a37200 to develop to solve the timeouts already

**Pull request merged**
