### PR TITLE
[FEATURE] cleanup of unused code

### PR DESCRIPTION
**Pull request by hroest**
remove some dead code

basically we could remove `getBestModificationByMonoMass` from the code base as we dont really use it and its clunky - we only use `getBestModificationByDiffMonoMass` by simply calculating the mass difference first

### CODE REVIEW

**Comment by enetz** [comment]
I agree. If you know one of them you can calculate the other, so allowing both is redundant.
And it looks like getBestModificationByMonoMass is not used anywhere outside of AASequence anyway.

**Comment by hroest** [comment]
we could also just remove `getBestModificationByMonoMass` completely ?

**Comment by timosachsenberg** [comment]
would be fine with me if it is really not used anywhere else.

**Comment by timosachsenberg** [comment]
tests pass now. should we go on with the merge?

**Pull request merged**
