### PR TITLE
Feature/pyopenms additions

### PR DESCRIPTION
**Pull request by hroest**
some additions to pyOpenMS

- add new classes
- add some new methods

- fix String handling: allows to construct String class with multiple Python string classes (bytes, str, unicode, pyopenms.String)

### CODE REVIEW

**Comment by hroest** [comment]
this should also fix our current pyopenms errors

**Comment by hroest** [comment]
@uweschmitt maybe you have some comments regarding the changes to String, I think it makes things easier by not having to use `b"argument"` some time and sometime `pyopenms.String(b"argument")` which can be confusing. Of course, using unicode has its own issues but as long as dont try to interpret the encoding inside OpenMS, its just a sequence of bytes and not much can go wrong

**Comment by jpfeuffer** [comment]
As soon as @hroest and @uweschmitt have no further additions I vote for merge and test in the nightlies.

**Comment by hroest** [comment]
it seems that one of the drawbacks of the new String treatment is longer compile times and more memory usage. This is not unexpected as we now add a lot of new (autogenerated) code to the .cpp file...

**Comment by jpfeuffer** [comment]
When I try to compile this PR on a linux machine, I have problems with the ConsensusID Class hierarchy. I get errors during parsing of the pxd files because of missing default constructors of the abstract classes ConsensusIDAlgorithm, ConsensusIDAlgorithIdentity and ConsensusIDAlgorithSimilarity.
But when I add them (not very surprisingly) the creation of the pyopenms.cpp fails because these are pure virtual constructors.
Did I do something wrong?

**Comment by hroest** [comment]
ok this is some work in progress, let me look into this. I also plan to fix the memory consumption due to the new String conversions

**Comment by hroest** [comment]
> When I try to compile this PR on a linux machine, I have problems with the ConsensusID Class hierarchy. I get errors during parsing of the pxd files because of missing default constructors of the abstract classes ConsensusIDAlgorithm, ConsensusIDAlgorithIdentity and ConsensusIDAlgorithSimilarity.
But when I add them (not very surprisingly) the creation of the pyopenms.cpp fails because these are pure virtual constructors.
Did I do something wrong?

Thanks for testing, this is indeed a bit an issue. We need to have the `ConsensusIDAlgorithm` abstract base classes declared in pxd so that Cython knows about the type but we cannot wrap it, therefore it has the `wrap-ignore` for the whole class. However the classes you describe are properly labelled as ABSTRACT classes and should not be wrapped:

```
    cdef cppclass ConsensusIDAlgorithmIdentity(ConsensusIDAlgorithm) :
        # wrap-inherits:
        #  ConsensusIDAlgorithm
        # wrap-ignore
        # ABSTRACT class
        ConsensusIDAlgorithmIdentity(ConsensusIDAlgorithmIdentity) nogil except + #wrap-ignore

```

eg. here there should be no wrapper for this class -- at all! as the `wrap-ignore` keyword is applied to the whole class

I will look into this...which version of autowrap are you using? Anyways, I am preparing an updated pull request so if you wait a bit this I can resolve this.

**Comment by jpfeuffer** [comment]
Thanks, I followed the build instructions in the docu and pip installed 0.7.1 for me.

**Comment by hroest** [comment]
which Cython did you install? I just see that the default Cython 0.21 which is shipped with autowrap wont work with these patches...it needs to have Cython 0.22 - that is quite annoying, I will have a look whether we need to upgrade Cython or whether I can get it to work with an older Cython ...

**Comment by hroest** [comment]
ok, now it works with Cython 0.21 for me, can you try again?

**Comment by hroest** [comment]
lets merge and see what the nightlies do ...

**Pull request merged**
