### PR TITLE
Add citation for FeatureFinderIdentification to documentation

### PR DESCRIPTION
**Pull request by hendrikweisser**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
You can additionally do it in the TOPPTool constructor. Then it will also show up on the command line and in the tool description (i.e. KNIME).

**Comment by hendrikweisser** [comment]
> You can additionally do it in the TOPPTool constructor.

Are there predecents/guidelines for that? So far I've seen and added references only in the main documentation.

**Comment by hroest** [comment]
> > You can additionally do it in the TOPPTool constructor.
> 
> Are there predecents/guidelines for that? So far I've seen and added references only in the main documentation.

https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/a07762.html#ab8287673d1342334ccb7519a5c04a7d7

**Comment by cbielow** [comment]
I was about to send a link to the docs, but doing it seemed almost as fast --> see #4304

**Pull request closed without merging**
