### PR TITLE
[FIX] Remove spline2d class, and update remaining files with references to it

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
completes https://github.com/OpenMS/OpenMS/pull/1033

**Comment by timosachsenberg** [comment]
fixed https://github.com/OpenMS/OpenMS/issues/766

Merging and fixing the original branch was a bit more trouble than adding the few changed lines by hand. So I opened a new PR.

**Comment by jpfeuffer** [comment]
cool looks good.

**Comment by jpfeuffer** [comment]
Sorry but I think we forgot about pyOpenMS.

**Comment by jpfeuffer** [comment]
Is there still the class test left, too?

**Comment by jpfeuffer** [comment]
Hmm actually there is no occurrence in the pxds. But we have failures in the pyOpenMS builds related to Spline2d. Maybe pyOpenMS tries to wrap the class_test?
The class test was commented out and was therefore forgotten I think.
https://github.com/OpenMS/OpenMS/blob/ec89b2f6406d19ba41d0137e64f6e7396736fffc/src/tests/class_tests/openms/executables.cmake#L270

**Comment by jpfeuffer** [comment]
I'll create a PR.

**Pull request merged**
