### PR TITLE
[FEATURE] PRIDE-compliant mzid, and refactoring of mod handling

### LINKED ISSUE #2085: AASequence: parsing prefers C-terminal mod. over residue mod.
When parsing amino acid sequences with modifications using `AASequence::fromString`, there may be ambiguities in the interpretation of a mod. at the end of the sequence: Is it a mod. of the last residue or of the C-terminus? (See also #1792.)
OpenMS currently prefers the second interpretation, i.e. it will attribute a mod. to the C-terminus if there is a possible C-term specificity. I believe this choice is suboptimal; it would be better to attribute the mod. to the residue, if the residue can accept that mod., as this seems the more likely scenario.

Furthermore, OpenMS currently doesn't check whether there is a matching residue specificity for a C-terminal mod. For example, in the peptide sequence "PEPM(Oxidation)", the "Oxidation" will be considered as C-terminal, but the only matching mod. is "Oxidation (C-term G)", which doesn't match the "M" in the sequence. Nevertheless, this mod. is assigned, as revealed by `ResidueModification::getFullId`.

### PR DESCRIPTION
**Pull request by hendrikweisser**
Fixes #2085 and solves #1655 for simple cases (no fractionation etc.).

I've added functions in class PercolatorOutfile to infer allowed fixed/variable modifications from search results. This may be useful for other cases where search results come in a format that doesn't specify which modifications were considered. If so, this functionality could be moved e.g. to ProteinIdentification.

I've also refactored the handling of modifications in ModificationsDB, Residue(DB), AASequence etc. The interfaces should now be simpler and more consistent. This also eliminated some errors where OpenMS would allow invalid modifications to be set, e.g. in test cases.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
wouldn't it make sense to get rid of the getModificationName functions? I mean if we can query the modification and call .getName on them why should we have it in the compound class AASequence?

**Comment by timosachsenberg** [comment]
any reason why max_error = 0.0 was removed from the defaults?

**Comment by hendrikweisser** [comment]
> wouldn't it make sense to get rid of the getModificationName functions?

Yes, I can do that. I would then also remove `AASequence::isModified(Size)`, because `seq.isModified(i)` can be replaced by `seq[i].isModified()`. Okay?

**Comment by hendrikweisser** [comment]
> any reason why max_error = 0.0 was removed from the defaults?

Since we're comparing floating point values, zero isn't a useful default tolerance, i.e. it always had to be set to a higher value anyway. If we can come up with a more sensible default value, it may make sense to put that in.

**Comment by timosachsenberg** [comment]
Ok sounds good to me. I don't have a good overview on the max_error issue but seems reasonable.

**Comment by hendrikweisser** [comment]
> I would then also remove AASequence::isModified(Size), because seq.isModified(i) can be replaced by seq[i].isModified(). Okay?

Also `AASequence::getResidue(SignedSize)`. What's the point of having that in addition to `AASequence::getResidue(Size)`, if negative values only lead to an exception?

**Comment by timosachsenberg** [comment]
A lot of the stuff in AASequence doesn't make sense to me and might be there for historical reasons.
If you make the changes I would suggest you do them on a separate PR on top of this one.

**Comment by hendrikweisser** [comment]
> If you make the changes I would suggest you do them on a separate PR on top of this one.

Why? It's already a horrible mess of Percolator-, mzid-, and mod handling-related changes. ;-)

**Comment by hroest** [comment]
>Why? It's already a horrible mess of Percolator-, mzid-, and mod handling-related changes. ;-)

exactly, in order to have cleaner, smaller code packages for review

Also, can you adopt the pyOpenMS pxd files to the new API? e.g. `getNTerminalModification` -> `getNTerminalModificationName` and   `ResidueModification::Term_Specificity` -> `ResidueModification::TermSpecificity` etc

**Comment by hendrikweisser** [comment]
> wouldn't it make sense to get rid of the getModificationName functions?

While removing those functions, I've noticed that they are quite useful because they always give you a return value. If I replace them with `getModification()->getId()`, I always have to add the null pointer check for the result of `getModification()`.
So I think it's better to keep them in.

**Comment by hendrikweisser** [comment]
> Also, can you adopt the pyOpenMS pxd files to the new API? e.g. getNTerminalModification -> getNTerminalModificationName and ResidueModification::Term_Specificity -> ResidueModification::TermSpecificity etc

I knew I forgot something. ;-)
Sorry about that.

**Comment by hendrikweisser** [comment]
I've removed `AASequence::isModified(Size)` and `AASequence::getResidue(SignedSize)` as mentioned, but I've kept the `get[C/NTerminal]ModificationName` functions, as they turned out to be quite useful.

I'm going to open a separate PR for the pyOpenMS changes.

**Comment by hroest** [comment]
> I'm going to open a separate PR for the pyOpenMS changes.

please dont, the changes belong together and we dont want to break the nightly tests if we merge one earlier than later

**Comment by hendrikweisser** [comment]
> please dont, the changes belong together and we dont want to break the nightly tests if we merge one earlier than later

That's what I thought, but Timo and you told me to open a separate PR for additional changes.
Anyway, I'm happy to add the changes to this branch.

**Comment by timosachsenberg** [comment]
No that's fine - I fully agree that pyOpenMS changes should go together. I was more referring to larger API changes in general on top of existing PRs.

**Comment by hendrikweisser** [comment]
I've updated pyOpenMS and everything works on my machine, but I get lots of (unrelated?) failures in three of the automated tests. What now?

**Comment by timosachsenberg** [comment]
According to CDASH http://cdash.openms.de/viewBuildError.php?buildid=188933
this seems to be the culprit
```
/.../OpenMS/src/openms/source/FORMAT/HANDLERS/TraMLHandler.cpp:682:42: error: no member named 'back' in 'OpenMS::String'
                   residue = it->sequence.back();
```

**Comment by hendrikweisser** [comment]
@timosachsenberg: I think you're looking at an earlier build; this is already fixed.

**Comment by hendrikweisser** [comment]
> I think you're looking at an earlier build; this is already fixed.

Nope, sorry. I made that change but forgot to commit it!

**Comment by timosachsenberg** [comment]
+1 - there are some parts I am not completely sure about but I think better to merge now and have more time for testing. It's certainly better now

**Pull request merged**
