### PR TITLE
[NOP] fixed some clang compile warnings

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
I guess the right way would be to define an own macro and set it to PRETTY_FUNCTION on gcc and  to <unknown> or (better) another compiler specific macro like __func_sig__ for the rest.

OR use the protable BOOST_CURRENT_FUNCTION.

See http://www.cplusplus.com/forum/general/179020/

It would need some find&replace, though.

**Comment by timosachsenberg** [comment]
I think you are not allowed to define your own macros with double underscore and PF is also not always implemented as a macro on differt compilers. I think I once tried the boost CF but I can't recall why it was not fit. Maybe the version was too new?

**Comment by timosachsenberg** [comment]
so should I close this PR and we try the BOOST_CURRENT_FUNCTION approach again?

**Comment by jpfeuffer** [comment]
Don't close. But wait. Let's try the other one.

**Comment by timosachsenberg** [comment]
I replaced the macro with the BOOST_CURRENT_FUNCTION so this PR is obsolete

**Pull request closed without merging**
