### PR TITLE
docs: update linux contrib requirements for qt-6

### PR DESCRIPTION
**Pull request by jcharkow**
## Description
As per
https://askubuntu.com/questions/1404353/how-to-install-qt6-on-ubuntu-21-10 qtbase6-dev is not avaliable on ubuntu < 22.04. libqt6opengl6-dev does not seem to be installable however building still seems to work without it.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jcharkow** [comment]
Note that the following TOPP tests fail for me locally though. 

	2292 - TOPP_ExecutePipeline_FDR_NeighborSearch.toppas (Failed)
	2293 - TOPP_ExecutePipeline_QualityControl.toppas (Failed)

**Review by cbielow — APPROVED** [review]
nice. Thanks!

**Comment by cbielow** [comment]
> Note that the following TOPP tests fail for me locally though.
> 
> ```
> 2292 - TOPP_ExecutePipeline_FDR_NeighborSearch.toppas (Failed)
> 2293 - TOPP_ExecutePipeline_QualityControl.toppas (Failed)
> ```

Interesting...
Could you post the output when running the tests? (`ctest -vv ... `)

**Comment by jcharkow** [comment]
It seems that the tests fail because Coment and MSGF+ executables are not found. I don't have these installed so I would expect them not to be found.  Not sure if this is the desired outcome or not.

Output for test 2292:
```
test project /home/joshua/Development/OPENMS/OpenMS-build
    Start 2292: TOPP_ExecutePipeline_FDR_NeighborSearch.toppas
1/2 Test #2292: TOPP_ExecutePipeline_FDR_NeighborSearch.toppas ...***Failed    0.67 sec
Warning: Ignoring WAYLAND_DISPLAY on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
current dry-run state: 1
current dry-run state: 0

DecoyDatabase started. Processing ...

Warning: Only one FASTA input file was provided, which might not contain contaminants. You probably want to have them! Just add the contaminant file to the input file list 'in'.


Skipped 0/2590 peptides with unknown('X') amino acids.


Neighbor peptide statistics for 2590 reference peptides :
 - 0 (0%) peptides contained an 'X' (unknown amino acid) and thus could not be searched for neighbors
 - 1106 (42%) peptides had 0 neighbors
 - 536 (20%) peptides had 1 neighbor
 - 948 (36%) peptides had >=1 neighbors.


DecoyDatabase took 0.33 s (wall), 0.34 s (CPU), 0.01 s (system), 0.33 s (user); Peak Memory Usage: 37 MB.


DecoyDatabase finished!

CometAdapter started. Processing ...

Output file '/home/joshua/Development/OPENMS/OpenMS-build/src/tests/toppas/TOPPAS_out/009-DecoyDatabase-NeighborSearchout_neighbor//18Protein_SoCe_Tr_detergents_trace.fasta' written.

Input file 'comet.exe' could not be found (by searching on PATH). Either provide a full filepath via the '-comet_executable' option or fix your PATH environment !
Error: File not found (the file 'comet.exe' could not be found)


CometAdapter failed!
```

Output for 2293

```
    Start 2293: TOPP_ExecutePipeline_QualityControl.toppas
2/2 Test #2293: TOPP_ExecutePipeline_QualityControl.toppas .......***Failed    1.00 sec
Warning: Ignoring WAYLAND_DISPLAY on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
current dry-run state: 1
current dry-run state: 0

FileInfo started. Processing ...

FileInfo started. Processing ...

FileInfo started. Processing ...

DecoyDatabase started. Processing ...

Warning: Only one FASTA input file was provided, which might not contain contaminants. You probably want to have them! Just add the contaminant file to the input file list 'in'.




Memory usage (loading MS data): 18 MB (working set delta), 18 MB (peak working set delta)


FileInfo took 0.15 s (wall), 0.15 s (CPU), 0.01 s (system), 0.14 s (user); Peak Memory Usage: 49 MB.




Memory usage (loading MS data): 19 MB (working set delta), 19 MB (peak working set delta)


FileInfo took 0.16 s (wall), 0.16 s (CPU), 0.01 s (system), 0.15 s (user); Peak Memory Usage: 50 MB.




Memory usage (loading MS data): 21 MB (working set delta), 21 MB (peak working set delta)


FileInfo took 0.16 s (wall), 0.17 s (CPU), 0.01 s (system), 0.16 s (user); Peak Memory Usage: 52 MB.


FileInfo finished!

Output file '/home/joshua/Development/OPENMS/OpenMS-build/src/tests/toppas/TOPPAS_out/026-FileInfo-out//BSA1.unknown' written.

Output file '/home/joshua/Development/OPENMS/OpenMS-build/src/tests/toppas/TOPPAS_out/026-FileInfo-out//BSA2.unknown' written.

Output file '/home/joshua/Development/OPENMS/OpenMS-build/src/tests/toppas/TOPPAS_out/026-FileInfo-out//BSA3.unknown' written.

DecoyDatabase took 0.43 s (wall), 0.44 s (CPU), 0.01 s (system), 0.43 s (user); Peak Memory Usage: 37 MB.


DecoyDatabase finished!

MSGFPlusAdapter started. Processing ...

MSGFPlusAdapter started. Processing ...

MSGFPlusAdapter started. Processing ...

Input file 'MSGFPlus.jar' could not be found (by searching on PATH). Either provide a full filepath via the '-executable' option or fix your PATH environment !
Error: File not found (the file 'MSGFPlus.jar' could not be found)


Input file 'MSGFPlus.jar' could not be found (by searching on PATH). Either provide a full filepath via the '-executable' option or fix your PATH environment !


Error: File not found (the file 'MSGFPlus.jar' could not be found)
```

**Comment by cbielow** [comment]
ahh... that explains it. Thanks!

**Pull request merged**
