### PR TITLE
Wheels on pr

### PR DESCRIPTION
**Pull request by poshul**
## Description

Add some logic to trigger the wheels build on pull requests minus the publish step. This should be added to our required tests to make sure future PRs don't break pyopenms.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

___

### **PR Type**
enhancement, configuration changes

___

### **Description**
- Added logic to trigger the wheel build process on pull requests to the `develop` branch, excluding the publish step.
- Removed unnecessary commented-out code and debugging statements to streamline the workflow.
- Improved the handling of environment variables and cleanup processes to ensure a cleaner build environment.
- Ensured that the publish step is only executed when the event is not a pull request.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pyopenms-wheels.yml</strong><dd><code>Enhance CI workflow to build wheels on pull requests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

.github/workflows/pyopenms-wheels.yml

<li>Added logic to trigger wheel builds on pull requests to the <code>develop</code> <br>branch.<br> <li> Removed commented-out code and debugging statements for cleaner <br>workflow.<br> <li> Ensured the publish step is skipped for pull requests.<br> <li> Improved environment variable handling and cleanup processes.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7672/files#diff-084f20ae9727db0905c5fbbc32ef797e048c87887ccfc57b0f89b2bf82f45979">+9/-65</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by jpfeuffer** [comment]
I guess ideally you would just enable pyopenms in our CI job or what was the idea here?

**Comment by poshul** [comment]
Yes. This accomplishes that, and leaves the two actions independent.

**Comment by jpfeuffer** [comment]
I think I mean something else. How about just specifying PYOPENMS=ON in the openms-ci-full workflow? You would save a *lot* of compute time.

**Comment by poshul** [comment]
> I think I mean something else. How about just specifying PYOPENMS=ON in the openms-ci-full workflow? You would save a _lot_ of compute time.

Ah, fair. That would definitely be cheaper on compute time. It doesn't get unit-tests though does it?

**Comment by jpfeuffer** [comment]
I think it might. They should be automatically enabled on top of the others if pyopenms is on.

**Comment by timosachsenberg** [comment]
> I think it might. They should be automatically enabled on top of the others if pyopenms is on.

yes first the pyopenms ones are run then the other ones

**Comment by jpfeuffer** [comment]
Potentially you could make an extra step out of it, so people see if libOpenMS builds first but that would be finetuning.

**Pull request closed without merging**
