### PR TITLE
[FIX] adopt activation modes to new obo

### PR DESCRIPTION
**Pull request by hroest**
It seems that some time ago, in 4fea083fd6a3fc820216ef3298860aad5cb5784d the HCD term in the obo file was replaced

```
-[Term]
-id: MS:1000422
-name: high-energy collision-induced dissociation
-def: "A collision-induced dissociation process wherein the projectile ion has the translational energy higher than approximately 1000 eV." [PSI:MS]
-synonym: "HCD" EXACT []
-is_a: MS:1000044 ! dissociation method
```

is now

```
+
+[Term]
+id: MS:1000422
+name: beam-type collision-induced dissociation
+def: "A collision-induced dissociation process that occurs in a beam-type collision cell." [PSI:MS]
+synonym: "HCD" EXACT []
+is_a: MS:1000133 ! collision-induced dissociation
+[Term]
+id: MS:1002481
+name: higher energy beam-type collision-induced dissociation
+def: "A collision-induced dissociation process wherein the projectile ion has the translational energy higher than approximately 1000 eV." [PSI:MS]
+is_a: MS:1000422 ! beam-type collision-induced dissociation

```

while OpenMS still has the old name hardcoded. This leads to warnings when writing and reading the same file again

```
While loading Name of CV term not correct: 'MS:1000422 - high-energy collision-induced dissociation' should be 'beam-type collision-induced dissociation'
```

it seems that in a rather unorthodox change, the `MS:1000422` term got changed from HCD to a very general "beam-type" collision mode

@mwalzer can you comment on whether this is a good idea?

@cbielow can you comment on the impact this will have on `ItraqChannelExtractor.cpp` which seems to use the HCD activation mode CV term

### CODE REVIEW

**Comment by cbielow** [comment]
the iTRAQAnalyzer only cares about the enum in Precursor.
And that is filled in the mzML handler using the ID, not the name. So 
everything should be fine here.

Am 7/29/2016 um 4:26 AM schrieb Hannes Roest:

**Comment by hroest** [comment]
Yes but the problem is that the id changed.

sent from my smartphone -- you may keep any typos you find.

**Comment by cbielow** [comment]
darn.. I completely missed it, sorry.

This is indeed a BIG problem.
@mwalzer ?

**Comment by mwalzer** [comment]
already looking into it ...

**Comment by hroest** [comment]
well it seems what happened was that term `MS:1000422` which used to stand for HCD got replaced by a more generic term "beam type dissociation" and HCD got moved to a child term of `MS:1000422`, namely `MS:1002481`. So one solution for @cbielow would be to simply accept both, the parent and the child term `MS:1000422` and `MS:1002481`, assuming both stand for HCD. 

This change seems really unfortunate from the side of the standardization committee as there will be mzMLs out there where `MS:1000422` will mean something different than in other mzMLs. In the worst case we will have to check the accession number and the description to infer what was intended. Or we simply, for the time being, when seeing `MS:1000422` we add both activation modes to the Precursor?

**Comment by mwalzer** [comment]
So that change was made to introduce a hierarchy of beam-type and a trap-type "HCD". This was due to the fact that there is -to my understanding- Thermo HCD (higher radiofrequency voltage CID to keep the fragmented ions in the c-trap) and real HCD (high energy to induce collision). 
So, the term obviously could have been used for both methods. Unfortunately, the existing term was swapped for one method and another introduced, instead of renaming and repurposing as a parent and introducing two new child ones.
With this configuration, it is assumed, that mzMLs with ```MS:1000422``` were created with real HCD. @hroest @cbielow would this assumption break for yours?

**Comment by hroest** [comment]
>  So, the term obviously could have been used for both methods. Unfortunately, the existing term was swapped for one method and another introduced, instead of renaming and repurposing as a parent and introducing two new child ones.

yes, this is somewhat strange.

Still I think the best move would be to simply check for both terms, old and new, in the Isobaric quant code and accept both.

**Comment by mwalzer** [comment]
mh, I mean, does it matter to the method? I've read that the trap-type produces quite similar fragments to CID though with better signal.
@cbielow on which is it supposed to run? If that is irrelevant, then that solution would be okay.

**Comment by cbielow** [comment]
in iTRAQ its all about the reporter ions at the low m/z range (if you take the standard method and not MS3 notch).
So if both annotations imply that these ions are generated and measured, we can accept both.

**Comment by hroest** [comment]
So let's just change it and accept both.

sent from my smartphone -- you may keep any typos you find.

**Comment by hroest** [comment]
> So let's just change it and accept both.

seems like the best option, @cbielow @mwalzer can we implement this?

**Comment by timosachsenberg** [comment]
any updates on this PR?

**Comment by hroest** [comment]
this is still a problem, we are currently not in sync with the obo and we need to change the code in OpenMS @cbielow @mwalzer

**Comment by mwalzer** [comment]
So, as I see it the PR defines the reach of HCD in `precursor.h` to now be `Precursor::HCID` and `Precursor::BEAM` - which would, as discussed, be a solution to maintain compatibility with old and new files. To reflect that for iTRAQAnalyzer, it would be needed [here?](https://github.com/OpenMS/OpenMS/blob/790e29ee4af30db3d4ae3ce9910155e3e5595627/src/openms/source/ANALYSIS/QUANTITATION/IsobaricChannelExtractor.cpp#L167)

**Pull request closed without merging**
