### PR TITLE
[FIX] add parameter to disable output of warnings in GaussFilter

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Reduces warning in high throughput data.

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by oliveralka** [comment]
Could you check if the failed test is related to the changes:
```
projectroot.src.tests.class_tests.openms.TargetedSpectraExtractor_test
 -  line 808:  TEST_EQUAL(extracted_spectra.size(),18): got '0', expected '18'
```

In general I would say it looks good!

**Comment by timosachsenberg** [comment]
good catch... yes there is a logic error. Will fix

**Comment by oliveralka** [comment]
rebuild jenkins

**Comment by timosachsenberg** [comment]
tests pass

**Pull request merged**
