### PR TITLE
force flag circumvents java time-outs in MSGFPlusAdapter

### LINKED ISSUE #1517: Java not found / time out
Workflows with multiple MSGFPlusAdapter nodes crash occasionally when run with multiple threads in Windows Server 2012. The auxiliary MS-GF+ databases (*.canno etc) have been generated in previous runs. Both java and MSGFPlus.jar are installed.

screenshot from 2015-07-15 11 01 08

### PR DESCRIPTION
**Pull request by lars20070**
The installation of java is now only checked, if the `force` flag is not set. That allows to circumvent time-out crashes when the system is very busy. Resolves #1517.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
HI @lars20070 could you please write a log message that the check is skipped and
 change the description of the -force parameter to describe what its impact for this tool?

**Comment by cbielow** [comment]
I struggle with this solution. 
Wouldnt it be easier to disable the timeout of the java check entirely. 
This should work for everyone and we don't need another flag....
-- 
Sent via mobile phone.

Am 17. August 2015 09:09:55 MESZ, schrieb Timo Sachsenberg <notifications@github.com>:

**Comment by lars20070** [comment]
Fine with me @cbielow. `waitForFinished(-1)` is what I had originally suggested. Either solution works for me.

**Comment by timosachsenberg** [comment]
Sorry if I don't get it. I thought it is sensible to have the timeout as we have it for other processes we start?
Or do you want to disable the timeout only if the force flag is set? (The flag is there anyways)

**Comment by cbielow** [comment]
I dont see the reason for a timeout any longer, other than to detect if 
a system if very busy. But this should be determined differently 
(specifically not by us/OpenMS), and not via a timeout. The other effect 
of a timeout is that stuff crashes, just because the system is busy (but 
not broken per se)....
So +1 for getting rid of the timeout.

Am 8/17/2015 um 1:32 PM schrieb Timo Sachsenberg:

**Comment by lars20070** [comment]
What happens if java is not installed?
Will `waitForFinished(-1)` wait infinitely in this case?

**Comment by hendrikweisser** [comment]
> What happens if java is not installed? Will waitForFinished(-1) wait infinitely in this case?

No, it should return as soon as the process gets executed (with "Command not found" or something).

**Comment by timosachsenberg** [comment]
The 30s are a safeguard against bankruptcy if you run it in the cloud or in a test environment so I would rather not remove it completly...

**Comment by lars20070** [comment]
@timosachsenberg The description of the `force` flag ("Overwrite tool specific checks.") is universal for all tools. IMO, we should not change this description.

**Comment by timosachsenberg** [comment]
Why? I mean the user should know what the force flag does for a tool. It's hard to document it otherwise.

**Comment by lars20070** [comment]
Comments? Merge?

**Pull request merged**
