### PR TITLE
Feature/pydoc

### PR DESCRIPTION
**Pull request by hroest**
adds the following documentation to all classes:

```
Documentation is available at " + classdocu_base + "class%(namespace)s_1_1%(cpp_name)s.html
```

so that the class documentation reads as follows:

```
cdef class FloatDataArray:
    """   
    Cython implementation of _FloatDataArray

    Documentation is available at http://www.openms.de/current_doxygen/html/classOpenMS_1_1DataArrays_1_1FloatDataArray.html

     -- Inherits from ['MetaInfoDescription']

    The representation of extra float data attached to a spectrum or chromatogram.
    Raw data access is proved by `get_peaks` and `set_peaks`, which yields numpy arrays
    """
```

NOTE: We will have to adjust the URL to point to the release documentation

@jpfeuffer do we have a stable redirect from the release docu that we can use? E.g. http://www.openms.de/release24_doxygen or something like that?

### CODE REVIEW

**Comment by hroest** [comment]
PS: depends on https://github.com/uweschmitt/autowrap/pull/87

**Comment by jpfeuffer** [comment]
Hi! www.openms.de/documentation/*
should dynamically redirect to the html folder of the latest release docu.
E.g. www.openms.de/documentation/TOPP_documentation.html
will lead to the latest TOPP docu.
Does that help?

**Comment by hroest** [comment]
>  Does that help?

yes, but it would be even better to have stable releases. This is because we will build pyOpenMS 2.3 and pyOpenMS 2.4 and it would be important to have the right pyOpenMS version point to the matching documentation

**Comment by jpfeuffer** [comment]
OK I added a new redirect rule:
`www.openms.de/doxygen/(.*)`
to
`https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/$1``

see e.g. http://www.openms.de/doxygen/release/2.3.0/html/index.html

**Comment by jpfeuffer** [comment]
The documentation folders will have the same name as the github branches.

**Comment by timosachsenberg** [comment]
hi pyopenms passed - so can we merge that for the release (even if we don't use the new autowrap yet=?

**Pull request merged**
