### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by hroest**
small set of fixes from the IM branch

### CODE REVIEW

**Comment by timosachsenberg** [comment]
http://cdash.openms.de/testDetails.php?test=70020619&build=384490 if fixed

**Comment by timosachsenberg** [comment]
-  line 334:  TEST_EQUAL(std::isnan(scores.im_delta_score),true): got '0', expected '1'

**Comment by timosachsenberg** [comment]
any update?

**Comment by hroest** [comment]
> line 334: TEST_EQUAL(std::isnan(scores.im_delta_score),true): got '0', expected '1'

yes, probably have to change that :-)

**Pull request merged**
