### PR TITLE
[FIX] Fix retrieve of XTandem score from PeptideHit in pepXML store

### PR DESCRIPTION
**Pull request by lukaszimmermann**
In the blocks associated with the if-tests it seems pretty clear that PeptideHit h needs to be tested for the meta value instead of testing the PeptideIdentification (*it). 

The XTandem Scores within the UserParams of the PeptideHit should now correctly be written to the pepXML file.

### CODE REVIEW

**Comment by oliveralka** [comment]
Build ran into time limit - seems ok - merge?

**Comment by jpfeuffer** [comment]
Hm yes, seems like a copy paste bug

**Comment by jpfeuffer** [comment]
Is this not covered by tests? Are you working on that a bit more so you could add a file and a test?
Maybe you could make up a file to test if all important metavalues are written?

**Comment by lukaszimmermann** [comment]
Will do so.

**Comment by hroest** [comment]
yes, please add a test!

Oh the horror of variable names, could they be any less descriptive: `h`, `f` and `it` -- how useful!

**Comment by lukaszimmermann** [comment]
Ok I added the tests.

**Comment by jpfeuffer** [comment]
Great! I give it another try with the timeout. After that I will merge. Thanks!

**Pull request merged**
