### PR TITLE
suppress-unused-function-warnings

### LINKED ISSUE #5940: fix compile warnings on mac
Please mark (or copy the warning if you can't tick checkboxes) the warning that you are planning to fix. If you run into troubles or don't manage to fix it in e.g. one day please uncheck the box again so someone else can take the sub issue.

- [ ] src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathOSWWriter.h:122:10: warning: private field 'sonar_' is not used [-Wunused-private-field]
- [x] src/openms/include/OpenMS/DATASTRUCTURES/Utils/MatrixUtils.h:53:3: warning: unused function 'convertOpenMSMatrix2EigenMatrixXd' [-Wunused-function]
- [x] src/openms/include/OpenMS/DATASTRUCTURES/Utils/MatrixUtils.h:67:3: warning: unused function 'matrixIsIdentityMatrix' [-Wunused-function]
- [ ] src/openms/include/OpenMS/FILTERING/DATAREDUCTION/SplineInterpolatedPeaks.h:160:16: warning: private field 'pos_min_' is not used [-Wunused-private-field]
- [ ] src/openms/include/OpenMS/KERNEL/RangeUtils.h:187:23: note: place parentheses around the '!=' expression to silence this warning - warning: ^ has lower precedence than !=; != will be evaluated first [-Wparentheses]
- [ ] src/openms/source/ANALYSIS/OPENSWATH/TransitionPQPFile.cpp:61:14: warning: unused function 'callback' [-Wunused-function]
- [ ] src/openms/source/FILTERING/CALIBRATION/TOFCalibration.cpp:198:23: warning: unused variable 'spec_iter' [-Wunused-variable]
- [x] src/openms/source/QC/DBSuitability.cpp:377:107: note: use array indexing to silence this warning - warning: adding 'OpenMS::Int' (aka 'int') to a string does not append to the string [-Wstring-plus-int]
- [x] src/openms/source/QC/DBSuitability.cpp:397:107: note: use array indexing to silence this warning - warning: adding 'OpenMS::Int' (aka 'int') to a string does not append to the string [-Wstring-plus-int]
- [ ] src/openms_gui/include/OpenMS/VISUAL/TOPPASVertex.h:191:10: warning: 'OpenMS::TOPPASVertex::paint' hides overloaded virtual function [-Woverloaded-virtual]
- [x] src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp:354:35: warning: comparison of integers of different signs: 'int' and 'OpenMS::Size' (aka 'unsigned long') [-W                                        sign-compare]
- [x] src/tests/class_tests/openms/source/AhoCorasickAmbiguous_test.cpp:431:30: warning: array subscript is of type 'char' [-Wchar-subscripts]  and 431:38: warning: array subscript is of type 'char' [-Wchar-subscripts]
- [ ] src/tests/class_tests/openms/source/LibSVMEncoder_test.cpp:543:30: warning: unused variable 'it' [-Wunused-variable]
- [x] src/tests/class_tests/openms/source/MSChromatogram_test.cpp:901:10: warning: moving a temporary object prevents copy elision [-Wpessimizing-move] - NOTE: disable the warning in the test as we intentionally use std::move here
- [x] src/tests/class_tests/openms/source/MSSpectrum_test.cpp:496:10: warning: moving a temporary object prevents copy elision [-Wpessimizing-move] - NOTE: disable the warning in the test as we intentionally use std::move here

### PR DESCRIPTION
**Pull request by pranavich18**
# Description
This PR suppressing compiler warning for mac incase of Unused Functions. for eg: `src/openms/include/OpenMS/DATASTRUCTURES/Utils/MatrixUtils.h:53:3: warning: unused function 'convertOpenMSMatrix2EigenMatrixXd' [-Wunused-function]`

# Usage of Functions
1.  convertOpenMSMatrix2EigenMatrixXd() -  `/src/openms/source/ANALYSIS/QUANTITATION/IsobaricIsotopeCorrector.cpp, Line:77` & `/src/openms/source/SIMULATION/LABELING/ITRAQLabeler.cpp, Line:233`
2.  matrixIsIdentityMatrix() - `/src/openms/source/ANALYSIS/QUANTITATION/IsobaricIsotopeCorrector.cpp, Line:69` & `/src/openms/source/ANALYSIS/QUANTITATION/IsotopeLabelingMDVs.cpp, Line:80`

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

Fixes #5940 (2nd and 3rd points)

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@cbielow @jpfeuffer do you know why this shows up in the warning?

**Review by jpfeuffer — CHANGES_REQUESTED** [review]
I think the new standard way is to specify maybe_unused
https://en.cppreference.com/w/cpp/language/attributes/maybe_unused

**Comment by timosachsenberg** [comment]
I just wonder because they are apparently used... maybe there is some underlying issue like missing cpp file / CMakeList entry?

**Comment by pranavich18** [comment]
So should I use `[[maybe_unused]]` or remove that as well along with `static`

**Comment by timosachsenberg** [comment]
> its probably because they are `static`, which seems nonsensical here. Better ditch `static` and replace with `inline`. This should also void the warning.

ah I think @cbielow is right! using inline instead of static should work.
see e.g., https://stackoverflow.com/questions/7610668/are-there-any-advantages-to-making-a-free-static-function

**Comment by pranavich18** [comment]
> > its probably because they are `static`, which seems nonsensical here. Better ditch `static` and replace with `inline`. This should also void the warning.
> 
> ah I think @cbielow is right! using inline instead of static should work. see e.g., https://stackoverflow.com/questions/7610668/are-there-any-advantages-to-making-a-free-static-function

Sure! Yea I'll do the suggested changes

**Comment by jpfeuffer** [comment]
should we also switch from boost::shared_ptr to std::shared_ptr?

**Comment by timosachsenberg** [comment]
> should we also switch from boost::shared_ptr to std::shared_ptr?

you would need to check the python bindings for that as well. e.g., I think by default we support boost

**Pull request merged**
