### PR TITLE
[FIX] remove for now

### PR DESCRIPTION
**Pull request by hroest**
fix travis

### CODE REVIEW

**Comment by hroest** [comment]
Sirius Adapter fails again

@oliveralka it seems the compoundScanNumber does not match and it seems to be different every time! can you have a look at this: 
- http://cdash.openms.de/testDetails.php?test=54037578&build=296534
- http://cdash.openms.de/testDetails.php?test=54038602&build=296535

**Comment by oliveralka** [comment]
@hroest 
As a workaround to get the scan number it is encoded in the temporary path of the SIRIUS directory structure. e.g.
`1_20190116_111724_MacBook-Pro.local_36861_2_0-2165004-UNKNOWN2`
So we would have UNKOWN with the index 2 and the scan number (nativeID) 2165004, which is extracted via a regex expression. 

My best guess is that the temporary path of SIRIUS in travis has another motif for this regex "-xxx-" - this would explain the different numbers in multiple runs. 

I can try to fix it by always using the last group. 
The next SiriusAdapter Version with SIRIUS 4.04 will most likely deprecate the current mzTab writers due to a switch of SIRIUS to mztab-m output.

**Comment by oliveralka** [comment]
I added your fix to the SiriusAdapter travis test PR - please see #3926

**Comment by timosachsenberg** [comment]
Close this one?

**Comment by oliveralka** [comment]
I would leave it open since the original build error is not fixed, or?

**Comment by cbielow** [comment]
I'll open another PR to fix the test

**Pull request closed without merging**
