### PR TITLE
Decharger: `-out_fm` not working? Add testfor  `-out_fm` and `-outpairs`

### PR DESCRIPTION
**Pull request by bernt-matthias**
# Description

`-out_fm` seems not to work

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

**Comment by enetz** [comment]
The issue seems to be the `.tmp` file ending. `FileHandler::storeFeatures` does not write the file, if it isn't a feature file type:
https://github.com/OpenMS/OpenMS/blob/62a701944098259fb7cebd4e6affc6c54f32c361/src/openms/source/FORMAT/FileHandler.cpp#L634

**Comment by bernt-matthias** [comment]
I see. 

Maybe one could introduce a `force_type` parameter like here (in this case the type is known in advance, or?) 

https://github.com/OpenMS/OpenMS/blob/62a701944098259fb7cebd4e6affc6c54f32c361/src/openms/source/FORMAT/FileHandler.cpp#L589

and/or at least write out some warning?

**Comment by bernt-matthias** [comment]
> we could use `FeatureXMLFile::store` directly. I am not sure whether this is the right thing to do here

I think at the moment its the only allowed type for this output https://github.com/OpenMS/OpenMS/blob/62a701944098259fb7cebd4e6affc6c54f32c361/src/topp/Decharger.cpp#L115

But we could allow more if desired, I don't care :)

**Comment by bernt-matthias** [comment]
Is there any way to do the clang reformatting automatically?

**Review by timosachsenberg — APPROVED** [review]

**Pull request merged**
