### PR TITLE
update of HMDB to version 3.6. This resolves issue #1799

### PR DESCRIPTION
**Pull request by epoyraz**
There is a big change in the Mapping File, still everything seems correct.
I attached a comparision of the metabolomic workflow (from the Tutorial) with the new dataset.
It works. I get the same number of molecules, but some of the Mappings are a little bit different.
comparison

### CODE REVIEW

**Comment by timosachsenberg** [comment]
great. any idea why the diff between the old HMDB2StructMapping.tsv and the new one is that big?
Here rows are sorted by identifier so I would not expect that many changes.

**Comment by epoyraz** [comment]
This is because the old HMDB2StructMapping.tsv is not sorted and the ordering seems arbitrary.

I sorted the old one and compared the changes: 
Then there are : 
3602 additions , where around 1500 are new compounds. 
And only 406 deletions.

commands i used : 
```
sort -k1 -k2n HMDB2StructMapping.tsv > HMDB2StructMapping_sorted.tsv
diff --side-by-side --suppress-common-lines HMDB2StructMapping_sorted.tsv HMDB2StructMapping_new.tsv >> diff2.txt
cat diff2.txt | grep ">" | wc -l
cat diff2.txt | grep "<" | wc -l
```

**Comment by timosachsenberg** [comment]
@epoyraz if you find time could you create two gists (https://gist.github.com/) for the diff?
So we can quickly inspect it?

**Comment by timosachsenberg** [comment]
+1

**Pull request merged**
