### PR TITLE
[FIX] handles invalid mzML without data type

### LINKED ISSUE #1618: msconvert / numpress generated mzML cannot be read
ProteoWizard's msconvert allows for numpress compression [1]. For example

`msconvert --numpressPic data.wiff`

Loading such mzML files in OpenMS fails, see screenshot.

[1] http://proteowizard.sourceforge.net/tools/msconvert.html

numpress_mzml

### PR DESCRIPTION
**Pull request by hroest**
- proteowizard seems to not set the data type when using ms-numpress
  even though this is required by the standard.
- as ms-numpress does not care about 32/64 bit, this seems to be the
  safest course of action at the moment and makes converted files work
  in OpenMS
- partial fix for #1618
- unsolved: how to deal with the general case when no attribute is provided about the identity of the array (now it at least outputs a warning)

Fixes #1618

### CODE REVIEW

**Comment by hroest** [comment]
all tests pass, so this seems safe to merge

**Comment by timosachsenberg** [comment]
Do the pwiz guys know about this bug?

**Comment by hroest** [comment]
yes, I wrote to them on their mailing list. I will update you if they provide a fix for this but we still have to assume that some pwiz versions will produce invalid mzML

**Comment by hroest** [comment]
https://sourceforge.net/p/proteowizard/mailman/message/34517134/

**Comment by hendrikweisser** [comment]
Would someone (Hannes?) add a test for this feature, please?

**Pull request merged**
