### PR TITLE
Meta value export for TextExporter

### PR DESCRIPTION
**Pull request by cbielow**
Metavalues with a certain user defined frequency (0-100%) can now be exported as additional columns for featureXML.

Some GUI code was adapted to use the new functionality.

This should also enable the export of Fido scores via TextExporter, as mentioned in #1381 (although support for idXML needs to be added in TextExporter).

### CODE REVIEW

**Comment by hendrikweisser** [comment]
> although support for idXML needs to be added in TextExporter

TextExporter already supports idXML as input. Do you mean the functionality for exporting meta values would need to be extended do idXML?

**Comment by cbielow** [comment]
yes :)

Am 5/20/2015 um 4:07 PM schrieb hendrikweisser:

**Comment by cbielow** [comment]
Related to #998

**Comment by timosachsenberg** [comment]
looks good to me

**Comment by timosachsenberg** [comment]
there are some cdash issue that need to be resolved before the merge

**Comment by timosachsenberg** [comment]
+1

**Comment by jpfeuffer** [comment]
Can we somehow make it to work on hierarchies of MetaInfoInterface objects.
Like scanning all Metavalues from all PeptideIdentifications inside all Features?

**Comment by timosachsenberg** [comment]
I don't know of a generic way

**Pull request merged**
