### PR TITLE
[DEPRECATED] suffix array

### PR DESCRIPTION
**Pull request by timosachsenberg**
removed specialized and deprecated suffix array implementations used by PILIS

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Currently not used after removal of PILIS and implementation not general enough that we should keep it in its current form.
Potentially interesting SAs variants that also use LCP are e.g. described in:
http://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-577

**Comment by hroest** [comment]
unless there are some immediate plans to have search functionality in OpenMS, i would say we do away with it

**Comment by cbielow** [comment]
+1 (test failures are unrelated?)

**Comment by cbielow** [comment]
tested again; two unrelated tests fail

+1 for merge

**Pull request merged**
