### PR TITLE
add __repr__

### PR DESCRIPTION
**Pull request by timosachsenberg**
## Description

e.g. allows using pprint(param).

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Should work. Would be cool to automate this in autowrap.

Just annotate a certain C++ in the pxd function to use as "wrap-as-str" and implement 10 lines of code generation.

Using << operator might be hard since they might be defined outside of the class somewhere. But toString is often defined in OpenMS.
You could also add a default value for the name of the function to use.

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/blob/af95149b2d0b2aa24a37da75ade82d7ae6d07cbc/src/pyOpenMS/addons/String.pyx#L42
see str above … do I need to consider Unicode here as well?

**Comment by jpfeuffer** [comment]
Yes but why are you using c_str? I guess the correct repr representation would just be

`return f"String('{self.toString()}')"`

Don't you think?

**Comment by jpfeuffer** [comment]
It actually depends on what you think would be the internal representation of this object.
But I think if you want to be similar to what python3 strings do, you should print something in Unicode.
And maybe add String to make a distinction from a regular python str object.

Repr is for developers. Str for human readability .

**Comment by timosachsenberg** [comment]
> Yes but why are you using c_str? I guess the correct repr representation would just be
> 
> `return f"String('{self.toString()}')"`
> 
> Don't you think?

I did not add this code it exists for 7 years now:) but I guess this might be pre 3.0 code? Should I update?

**Comment by jpfeuffer** [comment]
Yes because I just tested and it fails:
```python
    f = oms.String("foo")
    repr(f)
```

```
Traceback (most recent call last):
  File "/Users/julianuspfeuffer/git/OpenMS/cmake-build-Release-Clang_15.0.0_arm64-apple-darwin23.0.0/pyOpenMS/test.py", line 8, in <module>
    repr(f)
TypeError: __repr__ returned non-string (type bytes)
```

**Comment by jpfeuffer** [comment]
It probably only works for python2

**Comment by timosachsenberg** [comment]
ah thanks. sorry for the stupid question but is ```return f"String('{self.toString()}')"``` correct in the pyx file?
why the extra String in the beginning?

e.g. why not    
    def __repr__(self):
        return self.toString()

like for
 def __unicode__(self):
        return self.toString()

**Comment by jpfeuffer** [comment]
Because repr should create a representation of the object. Not just the contents.
And to differentiate from python std string, it should imho print
String('foo') instead of just 'foo'

**Pull request merged**
