### PR TITLE
[FIX] continue with a debug message if an unknown element (usually

### PR DESCRIPTION
**Pull request by timosachsenberg**
uncommon metals)

### CODE REVIEW

**Comment by cbielow** [comment]
I'm not sure if such hard errors should be allowed. The user might easily not see the warning and then assume that his metabolite of choice was not in the sample, even though OpenMS was just too stupid to parse it....
Showing the error message and quitting seems the better alternative to me. The user can then either remove the compound, or augment Elements.xml to fix the problem.
With https://github.com/OpenMS/OpenMS/pull/1185 we now also reduced the chance of this happening in the first place, right?

**Comment by timosachsenberg** [comment]
Yes thats right but there are many more in the HMDB that are currently not in Elements.xml and I won't find time to enter the remaining ones if we want to have a RC today evening. Maybe we can use the force (flag)?

**Comment by cbielow** [comment]
you mean, allow unknown elements if force flag is true?!
ok.
But then lets open a post 2.0 ticket to remove the flag again and add 
the missing elements.

Am 1/22/2015 um 11:55 schrieb Timo Sachsenberg:

**Comment by timosachsenberg** [comment]
Yeah I agree it is bad. I distribute the remaining elements and we will see if we manage to add them today. If not I will reside to the flag.

**Pull request closed without merging**
