### PR TITLE
[pyopenms] fixes some of the newly introduced bugs

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Please check and add proper fixes.

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

**Comment by hroest** [comment]
I have changed some tests because we remove the zero-intensity values (Tritium) for the regular isotope distributions, but the fine isotope should not have changed

**Comment by timosachsenberg** [comment]
Yeah it is a bit strange because it is methanol + water and I thought the fine isotope structure abundances is mainly defined by isospect.
can you or Josh take a quick look. Bit unsettling... :)

**Comment by jcharkow** [comment]
I've committed what I suggested above to https://github.com/OpenMS/OpenMS/pull/5997/commits/3e47da763f16a50048a6da0afd6399e0c5d1480f. This commit creates new functions specific for the IM calls.

**Comment by timosachsenberg** [comment]
this seems to fix the OpenSWATH error.
The pyOpenMS issue still remains, though.

**Pull request merged**
