### PR TITLE
add clang-tidy

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Please include a summary of the change and which issue is fixed.

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
tested and works in gitpod
could help in modernizing the code to c17

**Comment by timosachsenberg** [comment]
Probably also need to add the extension https://github.com/OpenMS/OpenMS/blob/develop/.gitpod.yml right?
I installed it manually

**Comment by oliveralka** [comment]
hm, can we use java 11 instead of java 8 for example for SIRIUS?

**Comment by timosachsenberg** [comment]
sure feel free to add it to this PR

**Comment by jpfeuffer** [comment]
First we have to make the code compile on c17 before we start modernizing.
Regarding the extension, you have to install it globally instead of per user. It should automatically show up in the yml.

**Comment by timosachsenberg** [comment]
added Java as well

**Review by jpfeuffer — APPROVED** [review]

**Pull request merged**
