### PR TITLE
MapAlignerPoseClustering log filenames during aligment

### PR DESCRIPTION
**Pull request by axelwalter**
As mentioned in #6860 it would be very helpful to see which file gets currently aligned in order to catch corrupted files easily.
Replaced the progress logger with more meaningful information including file names.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Review by timosachsenberg — APPROVED** [review]

**Comment by cbielow** [comment]
this code is problematic when using multiple threads, since the output of a filename and the corresponding `done` are not linked anymore.
You will get output like
```
Aligning 1.featureXML    Aligning 2.featureXML Aligning 3.featureXML
... done ... done
```
+ crash, so which file is it?!

**Comment by cbielow** [comment]
how would a crash manifest? If its an exception, it needs special handling anyway since it should not leave the `omp parallel` (not allowed, abort otherwise).

I was thinking that this could be solved using Progresslogger, if you pass it the number of threads that currently running.
Then it can create an output line for each thread and the user would just need to pass the thread-ID when reporting any progress, e.g.

```
MapAligner progress [45%]
Thread1: Aligning 1.featureXML ...
Thread2: Aligning 2.featureXML ...
Thread3: Aligning 5.featureXML ... done
```
So in this example Thread 1 and 2 are still working, whereas thread 3 has already finished and has nothing further to do.

This needs a bit of terminal magic, but I think many other tools would benefit as well.
When the output is redirected to a file, this would need some attention, as output might still be garbled.

**Comment by cbielow** [comment]
a simpler fix would be to report the filename again when printing ` ... done'.`
However, one still does not know which file caused the problem when running multiple threads, since `n` files are in flight at the same time... It would be best to catch the error and do some extra reporting.

**Comment by axelwalter** [comment]
Thanks @cbielow for the comments. Totally agree with the parallel execution this solution does not make sense. Just checked again with all possible combinations that have failed in the past for featureXML and appropriate messages get printed out.
For mzML file alignment it can crash in some cases (e.g. with a blank file that doesn't share common peaks as in the screenshot).
image

**Comment by axelwalter** [comment]
The mzML issue can be discussed in #7010

**Pull request closed without merging**
