### PR TITLE
[pyOpenMS] convert list [str, ... ] to StringList

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description
Adapted the special_conversion_providers for autowrap.

now StringLists can be passed in python with both bytes and str
[b"string1", b"string2"] and ["string1", "string2"]

More similar to how user could write could before switch to python 3

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Can you add a test for nonASCII strings?

**Comment by timosachsenberg** [comment]
Is there an easy way to also support that for std::vector<std::string> ?
Our param object now uses stl only objects so we can't use a StringList here

**Comment by jpfeuffer** [comment]
Why would you need this? You cannot construct a StringList anyway? Everything will be passed as python lists, no?

**Comment by timosachsenberg** [comment]
Basically I want to use e.g.
param.setTags("key", ["s1", "s2"])
instead of
param.setTags("key", [b"s1", b"s2"])

**Pull request closed without merging**
