### PR TITLE
[FIX] InternalCalibration: calibrate m/z of precursor peaks as well

### PR DESCRIPTION
**Pull request by cbielow**
This PR fixes the overlooked correction of precursor m/z for spectra which are not explicitly targeted,
e.g. if -ms_level == 1, then MS2 precursor information now gets calibrated according to the model applied to MS1. MS2 m/z itself is not changed (unless -ms_level 1 2).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
cool. +1 if pass

**Comment by hroest** [comment]
@cbielow as a follow up question: do we currently have a way to filter by scan function (e.g. MS:1000616) as some vendors (e.g. Waters) do specific scans for lock mass detection and then store this specifically marked with that CV term.

**Comment by hroest** [comment]
:+1:

**Comment by cbielow** [comment]
exposed via a TOPP tool: not that I'm aware of.

Maybe msconvert can do it?

Why would that be interesting?! Do these lock masses get removed in the 
lm-scan while remaining present in all other scans? Would not make a 
huge difference though, since the model is build in a customizable RT 
window.

I'm rather afraid that the instruments internal lm-calibration 
introduces 'jumps', which basically would force us to use small RT 
windows to avoid building a model which contains jumps... but it all 
depends on the data...


Am 10/28/2016 um 6:28 PM schrieb Hannes Roest:

**Comment by hroest** [comment]
yes, I think msconvert can do it.

**Comment by timosachsenberg** [comment]
@cbielow 252 - InternalCalibration_test (Not Run) from travis

**Comment by cbielow** [comment]
test pass (1 timeout)

**Comment by hroest** [comment]
@cbielow was this supposed to go into master?

**Comment by cbielow** [comment]
yes :)


Am 11/1/2016 um 10:40 PM schrieb Hannes Roest:

**Comment by timosachsenberg** [comment]
In some cases I get these kind of plots...
161014_rs_colon_6 mzml picked
Probably because not enough calibrants are present

**Pull request merged**
