### PR TITLE
previous line was never evaluated to true

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by cbielow** [comment]
while you are at it:
`tools/travis/lnx-cibuild.sh: line 64: [: ==: unary operator expected`

I think the quotes are missing.

**Comment by timosachsenberg** [comment]
thanks. It works - cppcheck reports a few bugs. I will fix them

**Comment by timosachsenberg** [comment]
@grosenberger @hroest 

```
          int res_pos = (pseudoRNG() % aa_size);
          int pep_pos = -1;
          size_t pos_trials = 0;
          while (pep_pos < 0 && pos_trials < shuffled_sequence.size())
          {
            pep_pos = (pseudoRNG() % shuffled_sequence.size());
            pep_pos = 5;
```
cppcheck complains about  pep_pos = (pseudoRNG() % shuffled_sequence.size());
should this be res_pos = ... instead?

**Comment by timosachsenberg** [comment]
please also take a look at: http://cdash.openms.de/viewTest.php?onlyfailed&buildid=167625
if you want you can fix these remaining issues in this branch 
(I can do it but maybe it's faster to skip the extra conversation ;)

**Comment by grosenberger** [comment]
@timosachsenberg 
I introduced this function by accident in a recent commit. It is not used anywhere and not exposed to the tools. The problem comes from `pep_pos = 5;`, which I probably added for debugging. I will prepare a PR fixing the problem and either remove the code or fix and write a test for it.

**Comment by timosachsenberg** [comment]
ok I commented the line out - let's see if cppcheck passes for this file. You can provide the PR later.

**Comment by timosachsenberg** [comment]
I merge as the check introduces no new bugs but only reports so far hidden ones. We should fix the newly detected style/static code issues: http://cdash.openms.de/viewTest.php?onlyfailed&buildid=168332 in the next days

**Pull request merged**
