### PR TITLE
Works around issue in apple silicon

### PR DESCRIPTION
**Pull request by poshul**
On M1 OpenSwathWrokflow_21 fails because a feature gets tagged as `potentialOutlier`. There don't appear to be any differences in the values for the feature, and it looks like a case of something genuinely being an edge case to me. We can work around this by just ignoring all the `potentialOutlier` lines

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by poshul** [comment]
@cbielow @hroest I've very little SWATH experience, can either of you opine on this issue, and whether what I'm seeing is a real issue?

**Comment by poshul** [comment]
@jpfeuffer @timosachsenberg  do either of you have objections to merging this?

**Comment by jpfeuffer** [comment]
No but it's a bit weird that we have the previous workarounds with the small epsilon already. I would prefer reverting those if they don't fix anything.

**Comment by timosachsenberg** [comment]
hmm I think we need to find out what is going on here. Having the number of outliers changed from 56 to 0 sounds like the value is rendered totally useless. Do we know if this is used somewhere in tric or other downstream processing tools?

**Comment by poshul** [comment]
56 is not the number of outliers it is the ID of the outlier.

**Comment by poshul** [comment]
The epsilon comparison fixed several other tests, but not this one. I can roll back the changes that were intended to fix this one specifically. Alternatively, I've been playing around on another branch with using our existing Constants::EPSILON (see https://github.com/poshul/OpenMS/tree/feature/epsilon). My understanding is that this would be the "correct" way to handle comparisons to floats, but it does require a goodly amount of changes.

**Comment by timosachsenberg** [comment]
Hmm. I think if we can go with a minimal set of changes that are needed to fix the tests we are good to go here. Hannes or someone else needs to review those in the future and can come up with a better fix.
BTW Constants::EPSILON will work for sure as it is super large 1e-6 as compared to your more conservative 1e-11 but in general there is no small enough constant that works for arbitrary calculations that should return in 0.

**Comment by cbielow** [comment]
> No but it's a bit weird that we have the previous workarounds with the small epsilon already. I would prefer reverting those if they don't fix anything.

I would strongly second that, and vote for not fixing M1 issues so close to release. We should keep it as is  (even it means tests are failing on M1/M2) until we have the time to investigate this after release. Introducing changes which potentially alters the behaviour on all platforms on real datasets is not something we should risk (since we do not have time to test).

**Comment by timosachsenberg** [comment]
Ok so the issue is that:
- replacing ==0 with < 1e-11 fixes several tests (which I personally think would be an ok change if numeric inaccuracies are the direct cause, e.g., caused by fitting an elution profile)
- but: the number of outliers change -> this indicates that something is off with the other logic as well

I think Chris has a valid point that a workaround that changes the behavior could have unexpected consequences on existing workflows, while adding whitelists may hide an underlying flaw in the logic.

So how should we go forward here and the other PRs regarding M1 numeric fixes?

**Comment by tjeerdijk** [comment]
I would side with Chris here. Let the M1/M2 tests fail and go ahead with the release. Investigate the numerical issues for release 3.1

On 6. Jul 2023, at 11:10, Timo Sachsenberg ***@***.******@***.***>> wrote:


Ok so the issue is that:

  *   replacing ==0 with < 1e-11 fixes several tests (which I personally think would be an ok change if numeric inaccuracies are the direct cause, e.g., caused by fitting an elution profile)
  *   but: the number of outliers change -> this indicates that something is off with the other logic as well

I think Chris has a valid point that a workaround that changes the behavior could have unexpected consequences on existing workflows, while adding whitelists may hide an underlying flaw in the logic.

So how should we go forward here and the other PRs regarding M1 numeric fixes?

**Comment by poshul** [comment]
Im good with that plan.

**Pull request closed without merging**
