### PR TITLE
fixes failing tests on Mac Silicon

### LINKED ISSUE #6959: Numerical instability on Mac Silicon M1/M2
...compared to x86-64

This is mainly for documentation purposes:
Some tests (e.g. Deisotoper_test) fail on Mac Silicon.
When debugging, this boils down to simple math operations: `a*b + c` (can anyone see where this is going? :) )

This is a minimal example:
```
#include <iostream>
#include <cstdint>
int main()
{
   uint64_t massi = 4644828916371982459;
   double mass = *(reinterpret_cast<double*>(&massi));

   double z = 3;

   uint64_t two_protons = 4611718788720426353;
   double p2 = *(reinterpret_cast<double*>(&two_protons));

   double new_mass = mass * z - p2;
   auto new_mass_int = *(reinterpret_cast<uint64_t*>(&new_mass));
   std::cout << "new mass (decharged): " << new_mass << " (" << new_mass_int << ")\n";

   double intermediate = mass * z;
   double new_mass_stepwise = intermediate - p2;
   auto new_mass_stepwise_int = *(reinterpret_cast<uint64_t*>(&new_mass_stepwise));
   std::cout << "new mass -stepwise (decharged): " << new_mass_stepwise << " (" << new_mass_stepwise_int << ")\n";

    return new_mass_int - new_mass_stepwise_int;
}
```
If you execute (`clang++ -std=c++17 mini_mini.cpp`), irrespective of any optimization flags, this on an Apple M2 you get:
```
new mass (decharged): 1041.85 (4652296930484129758)
new mass -stepwise (decharged): 1041.85 (4652296930484129757)
```
I.e. the two computations are not equivalent. 
Disassembly using `otool -tvV a.out` shows
```
0000000100003f68        fnmsub  d0, d0, d1, d2
```
i.e. a nasty Fused multiply-add operation which changes the result due to more precision.

Now, the weird thing is, that I did not specify any `-ffast-math` or alike which would allow for such things.
```
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.3.0
```

Per default, **x86-64** will not do FMA operations, on the above example, even if you specify the flags that should enable it:
`-std=gnu++17 -O3 -mavx2 -mfma -ffp-contract=fast -ffast-math`
still gives 
```
new mass (decharged): 1041.85 (4652296930484129757)
new mass -stepwise (decharged): 1041.85 (4652296930484129757)
```

For completeness: You can force GCC/clang on x86-64 to use FMA by using instrinsics (and then it will produce similar, skewed results as M2 does):
```
#include <iostream>
#include <cstdint>
#include <immintrin.h>

inline __m256d fma4( __m256d acc, const double* p1, const double* p2 )
{
    const __m256d a = _mm256_loadu_pd( p1 );
    const __m256d b = _mm256_loadu_pd( p2 );
    return _mm256_fmadd_pd( a, b, acc );
}

int main(int argc, char** argv)
{
   uint64_t massi = 4644828916371982459;

   double z = 3;

   uint64_t two_protons = 4611718788720426353;
   double p2 = *(reinterpret_cast<double*>(&two_protons));


   double mass = *(reinterpret_cast<double*>(&massi));
   double arr[4] = {mass,mass, mass, mass};
   double arrz[4] = {z,z, z, z};
   __m256d acc = _mm256_set1_pd(-p2);
   double res[4];
   _mm256_storeu_pd(res, fma4(acc, &arr[0], &arrz[0]));

   double new_mass = res[0];// mass * z - p2; 
   auto new_mass_int = *(reinterpret_cast<uint64_t*>(&new_mass));
   std::cout << "new mass (decharged): " << new_mass << " (" << new_mass_int << ")\n";
    
   double intermediate = mass * z;
   double new_mass_stepwise = intermediate - p2; 
   auto new_mass_stepwise_int = *(reinterpret_cast<uint64_t*>(&new_mass_stepwise));
   std::cout << "new mass -stepwise (decharged): " << new_mass_stepwise << " (" << new_mass_stepwise_int << ")\n";
   
    return new_mass_int - new_mass_stepwise_int;
}
```

## Solution

add `-ffp-contract=off` as compile flag to Apple Clang to disable FMA.

### PR DESCRIPTION
**Pull request by cbielow**
## Description

fixes #6959 

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by poshul** [comment]
Good find. Does FFP-Contract work on x64 chips?

**Review by timosachsenberg — APPROVED** [review]

**Comment by jpfeuffer** [comment]
Hmm, I am not sure that this is platform specific, rather a compiler version thing.
https://stackoverflow.com/questions/73985098/clang-14-0-0-floating-point-optimizations

I would vote for always adding this flag.

**Comment by jpfeuffer** [comment]
FMA exists since Haswell.

**Comment by cbielow** [comment]
I tried very hard to force FMA on Godbolt wth x64, but GCC did not do it. Should have used Clang -- happens instantaneous :)
Ok, so lets add `-ffp-contract=off` whenever we see a clang. No need to check for the actual version (it will be a NOOP for clang < 14)

**Comment by cbielow** [comment]
funny:
Clang (even old ones with fpcontract=on) will not use FMA at -O0, but use it at -O1 for compile time computation even if the machine does not have FMA instructions... wow. I.e. the result changes depending on optimization level.

**Comment by cbielow** [comment]
however, for runtime computations, Clang will not use FMA, even with `fpcontract=on`, since it is not allowed to insert the required `vfmsub132sd` assembly instruction (since we not not use the `-mfma` flag in OpenMS -- directly or indirectly via march=native).
Now the question is: why does Apple-Clang dare to do this? I could not find any docs, but apparently it does use FMA on AArch64 by default.

**Comment by jpfeuffer** [comment]
Did you test LLVM clang 14? From what I saw, they switched the default from off to on in version 14.

**Comment by jpfeuffer** [comment]
And the newest Apple Clangs have an equivalent version number with the LLVMs again:
So Apple Clang 14 (the one on our mac) should be based on LLVM 14.

**Comment by jpfeuffer** [comment]
ah hmm.. I see.. maybe appleclang "assumes" that it's always a Mac that supports fma? I don't know

**Review by jpfeuffer — APPROVED** [review]

**Comment by cbielow** [comment]
as a follow up: when installing dependencies via brew, they may contain FMA-enabled code on AArch64, i.e. lead to failing tests. The only reliable way to avoid would be a full contrib build where we also use the `fpcontract=off`

**Pull request merged**
