### PR TITLE
[FEATURE] support mzIdentML in TOPPView

### PR DESCRIPTION
**Pull request by hroest**
Allow TOPPView to read mzIdentML files and use them for annotation and for a new layer

### CODE REVIEW

**Comment by timosachsenberg** [comment]
you could add .mzIdentML to the file dialog (annotateWithID)

**Comment by timosachsenberg** [comment]
``` 
QString fname = QFileDialog::getOpenFileName(this,
                                                 "Select protein/AMT identification data",
                                                 current_path_.toQString(),
                                                 "idXML files (*.idXML);featureXML files (*.featureXML); all files (*.*)");
```

**Comment by hroest** [comment]
hmm should we use `.mzid` or `.mzIdentML` for mzIdentML? It seems our tools (e.g. IDFileConverter) prefer `.mzid`. 

However, I would prefer `.mzIdentML` as this is clearer and corresponds the to name of the XML file

**Comment by hroest** [comment]
it seems to be only a hint and not really enforced, so I changed it. However, now it is kind of hard to read (at least on my system) and all files are allowed, e.g. it does not really filter which files are allowed and which ones are not

**Comment by hroest** [comment]
also, why does it say 

"Select protein/AMT identification data"

when we load in mostly peptide id data? maybe @cbielow can answer that as he changed it last 749ee0a9ca32e8a624f45243be98fe45f7bfed34

**Comment by timosachsenberg** [comment]
I think @mwalzer mainly uses mzid and it is also used by other tools so I would go for that

**Comment by timosachsenberg** [comment]
Is in the standard:
7.1 File extension
The file extension for mzIdentML files SHOULD be “.mzid”.

**Comment by mwalzer** [comment]
yeah, community use is widely mzid

**Comment by timosachsenberg** [comment]
@cbielow implemented a way to annotate mass fingerprints. I think this is what it refers to.
see e.g. https://github.com/OpenMS/OpenMS/pull/921

**Comment by hroest** [comment]
should we merge?
 
One issue here: the mzIdentML parser seems to be really inefficient, see #1548 so by exposing this we may have users use a non-optimal feature. Maybe we should first have a stream parser before we expose this?

**Comment by timosachsenberg** [comment]
+1

**Pull request merged**
