### PR TITLE
move templates to cpp file to reduce Seqan exposure

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Attempt to remove compile time and reduce exposure of seqan

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Seems it doesn’t fly on all compilers

**Comment by hroest** [comment]
I looked into this some time ago in order to reduce compilation time for pyOpenMS, there are quite some areas where we pull in stuff into the header files that we probably shouldnt. Here is an (incomplete) start: https://github.com/hroest/OpenMS/commit/5c6348aca0c4b71ac6f7703c039139d92b05fa73 also QString pulls in about 150k LOC from Qt...

**Comment by cbielow** [comment]
> Seems it doesn’t fly on all compilers @cbielow any insights?

I guess you have to add OPENMS_DLLAPI to the function template, because otherwise the templates instanciated in the cpp won't be exported...
just a wild guess though...

**Comment by timosachsenberg** [comment]
will try to play around with the export
right now I get a 
```
ProteomicsLFQ.obj : error LNK2019: unresolved external symbol "public: enum OpenMS::PeptideIndexing::ExitCodes __cdecl OpenMS::PeptideIndexing::run<struct OpenMS::TFI_File>(class OpenMS::FASTAContainer<struct OpenMS::TFI_File> &,class std::vector<class OpenMS::ProteinIdentification,class std::allocator<class OpenMS::ProteinIdentification> > &,class std::vector<class OpenMS::PeptideIdentification,class std::allocator<class OpenMS::PeptideIdentification> > &)" (??$run@UTFI_File@OpenMS@@@PeptideIndexing@OpenMS@@QEAA?AW4ExitCodes@01@AEAV?$FASTAContainer@UTFI_File@OpenMS@@@1@AEAV?$vector@VProteinIdentification@OpenMS@@V?$allocator@VProteinIdentification@OpenMS@@@std@@@std@@AEAV?$vector@VPeptideIdentification@OpenMS@@V?$allocator@VPeptideIdentification@OpenMS@@@std@@@5@@Z) referenced in function "protected: enum OpenMS::TOPPBase::ExitCodes __cdecl ProteomicsLFQ::inferProteinGroups_(class std::vector<class OpenMS::String,class std::allocator<class OpenMS::String> >,class OpenMS::String const &,class std::map<class OpenMS::String,class OpenMS::String,struct std::less<class OpenMS::String>,class std::allocator<struct std::pair<class OpenMS::String const ,class OpenMS::String> > > const &,class std::set<class OpenMS::String,struct std::less<class OpenMS::String>,class std::allocator<class OpenMS::String> > const &,class std::vector<class OpenMS::ProteinIdentification,class std::allocator<class OpenMS::ProteinIdentification> > &,class std::vector<class OpenMS::PeptideIdentification,class std::allocator<class OpenMS::PeptideIdentification> > &)" (?inferProteinGroups_@ProteomicsLFQ@@IEAA?AW4ExitCodes@TOPPBase@OpenMS@@V?$vector@VString@OpenMS@@V?$allocator@VString@OpenMS@@@std@@@std@@AEBVString@4@AEBV?$map@VString@OpenMS@@V12@U?$less@VString@OpenMS@@@std@@V?$allocator@U?$pair@$$CBVString@OpenMS@@V12@@std@@@4@@6@AEBV?$set@VString@OpenMS@@U?$less@VString@OpenMS@@@std@@V?$allocator@VString@OpenMS@@@4@@6@AEAV?$vector@VProteinIdentification@OpenMS@@V?$allocator@VProteinIdentification@OpenMS@@@std@@@6@AEAV?$vector@VPeptideIdentification@OpenMS@@V?$allocator@VPeptideIdentification@OpenMS@@@std@@@6@@Z) [E:\jenkins\ws\openms\PR\bldtst\9447518b\build\src\utils\ProteomicsLFQ.vcxproj]
```

**Comment by timosachsenberg** [comment]
@cbielow thanks for the hint with adding the DLL export

**Pull request merged**
