### PR TITLE
Feature/ms1 openswath

### PR DESCRIPTION
**Pull request by hroest**
allow OpenSwathWorkflow to perform MS1-only extraction and scoring (e.g. if no SWATH-MS data is present)

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Anyone from the SWATH team wants to comment on this?

**Comment by grosenberger** [comment]
Very nice addition! Is it correct that on the user-level all changes happen without settings any parameter and is only dependent on the input data? So if only a MS1 map is supplied, the new mode would be used, where peak picking and scoring is conducted on MS1-level?

If yes, would it make sense to state this difference (MS1-level peak picking instead of MS2-level picking) in the Doxygen documentation of OpenSwathWorkflow?

**Comment by hroest** [comment]
currently you have to turn on `MRMTransitionGroupPicker:use_precursors` to enable this, otherwise MS1 chromatograms wont be picked. Therefore they also wont produce features, so then it wont work.

But you are right that if you only provide an MS1 map *and* provide the `use_precursors` flag, it will implicitely work. Note that even if you provide regular SWATH data and use `use_precursors` you will now get peak picking on the precursor level as well! I will add this to the docu

**Comment by timosachsenberg** [comment]
feel free to merge after adding to the documentation

**Comment by hroest** [comment]
I kind of dropped the ball on this and this probably needs some more work, especially as it will conflict with #2316

**Comment by timosachsenberg** [comment]
conflict is resolved. Still wait?

**Comment by hroest** [comment]
ok, this should be ready to merge

**Comment by timosachsenberg** [comment]
Could you add some more information to this PR or the changelog on what is currently supported? Also to differentiate to the LFQ FF by Hendrik.

**Pull request merged**
