### PR TITLE
MetaboliteAdductDecharger: don't write to opt out if absent

### PR DESCRIPTION
**Pull request by bernt-matthias**

### CODE REVIEW

**Comment by FabianAicheler** [comment]
The consensusmap output is mandatory/the main output, wheras the other two are optional. So I would leave as was, at most one could consider whether to clarify this fact as comments.

**Comment by bernt-matthias** [comment]
Thanks for the comment. In this case the parameter should be changed to mandatory. I change this accordingly.

**Comment by timosachsenberg** [comment]
hmm not sure if that is the best solution.
I think it should be all optional and an error if none of them is set (we don't model that in CTD).
@jpfeuffer what is your take on that?

**Comment by jpfeuffer** [comment]
Would someone ever want two outputs? If not, just make one "out" with restrictions "fxML,cXML" and potentially add an "out_type" parameter.

**Comment by bernt-matthias** [comment]
OK. Also added a test. Since I currently don't have the time to compile it locally I can not contribute the test result files. Alternatively I could remove the DIFF calls from the tests.

**Comment by bernt-matthias** [comment]
Argument help could need an update. Need your input on this.

**Comment by timosachsenberg** [comment]
@FabianAicheler can you assist?

**Comment by jpfeuffer** [comment]
@FabianAicheler You can use https://gitpod.io/#https://github.com/OpenMS/OpenMS/pull/4552
to quickly edit this pull request and push your changes (in case you do not want to set up a new build environment)

**Comment by FabianAicheler** [comment]
Currently looking into whether collaborators need both outputs.

> 
> 
> Argument help could need an update. Need your input on this.

What specifically do you mean?

**Comment by bernt-matthias** [comment]
> What specifically do you mean?

Currently the command line help of the outputs just says "output" or "output file" which seems way to minimalistic :)

**Comment by FabianAicheler** [comment]
So we learned that there are indeed use case scenarios where one is interested in both consensusXml together with featureXml outputs.

For use with Knime, it is preferable that outputs are not flagged as mandatory.

@bernt-matthias Would it be okay for use with Galaxy if we flag all outputs as optional, and only write to them if output filenames were specified for them?

**Comment by FabianAicheler** [comment]
Also sorry about changing statements regarding whether/which output should be mandatory^^ Historically, I recalled there to be some restrictions for Knime, but nowadays node requirements are more flexible.

So the first commit (0fb3e57 ) looks good to me (if it passes tests), I'll think of more verbose descriptions of the outputs.

**Comment by timosachsenberg** [comment]
anything else needed here?

**Comment by bernt-matthias** [comment]
I guess most of the 2nd and 3rd commit should be dropped (I guess the test `!outfile_cm.empty()` should be kept). 

Will try to do this soon. 

@FabianAicheler might add a "more verbose descriptions of the outputs"

**Comment by bernt-matthias** [comment]
OK. Dropped the last two commits (but kept the tests .. without the time to think about them).

**Comment by FabianAicheler** [comment]
I think(?) that removal of the out_type in the test is required, and a small adaption for the second test in order to cover all three potential outputs. Will look into it later today.

**Comment by FabianAicheler** [comment]
OK, so I did some changes to the tests (and added test files) in gitpod. But the gitpod interface is a bit finnicky, and I am not sure whether I really pushed my changes somewhere (or whether that was transformed into a pull request to bernt-matthias).

Corresponding tests worked there. Just wanted to let you all know, will try to clarify with Julianus or other gitpod experts later in Discord(?)^^

**Comment by bernt-matthias** [comment]
@FabianAicheler just checked there is no pull request to my fork.

**Comment by FabianAicheler** [comment]
@bernt-matthias Ok, you should hopefully have a pull request now^^

**Comment by bernt-matthias** [comment]
merged

**Comment by oliveralka** [comment]
looks good!

**Pull request merged**
