### PR TITLE
[Feature] support mismatches in PeptideIndexer 

### PR DESCRIPTION
**Pull request by cbielow**
sometimes mapping peptides with real mismatches is sensible, e.g. if one expects SNPs in other proteins, which might give additional protein hits, or if one wants to be really sure that a certain peptide only maps to one protein even if one allows a few mismatches (i.e. exclude possible SNPs in other proteins as explanation).

Additionally, docs are re-worked a bit.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Just intersted: Would it be possible to specify the type of mismatch that is allowed? e.g. caused by insertion / deletion / SNV

**Comment by cbielow** [comment]
this is purely on protein level and supports only modificiation, no indel.
Not sure if that answers your question.

**Comment by hendrikweisser** [comment]
I think adding this functionality is a good idea. But maybe the parameters of PeptideIndexer could be cleaned up a bit: Is the "full_tolerant_search" parameter (by the way, terribly non-descriptive name) actually needed? Isn't "full_tolerant_search" implied if "aaa_max" or "mismatches_max" is bigger than zero?

**Comment by cbielow** [comment]
Why is 'full_tolerant_search' non-descriptive?

It implies that you search all peptides in 'tolerant' mode, i.e. with 
ambiguous AA from the start, instead of trying to first search peptides 
1:1 in the DB and only use tolerant search on the ones which remain 
unmapped (which is the default, since its much faster).

aaa_max: If we would use this param to replace the 
'full_tolerant_search' param, how do you differentiate between 
'full_tolerant_search' vs. 'exact search + tolerant on the rest' ?

mismatches_max: if >1 then "full_tolerant_search" is required, yes. But 
if its ==0, the same problem as above occurs.

Now, one could argue that this 'mixed' mode is somewhat inconsistent, 
but thats another story :)


Am 2/11/2015 um 11:34 AM schrieb hendrikweisser:

**Comment by hendrikweisser** [comment]
@cbielow: Okay, with your explanation "full_tolerant_search" makes some sense. But that's only because there's a default "semi-tolerant search" mode for which there's no explicit parameter. What is being tolerated (answer: ambiguous amino acids, and now potentially also mismatches) is not immediately apparent, though.

I think the fact that I got confused by the parameters somewhat proves my point. Maybe it would be more explicit to have a string parameter "search_mode" (or "match_mode"?) with different choices: "exact" ("strict"?), "two_pass", "tolerant" ("fuzzy"?). Something like that?

**Comment by cbielow** [comment]
Am 2/11/2015 um 12:49 PM schrieb hendrikweisser:
> @cbielow: Okay, with your explanation "full_tolerant_search" makes
> some sense. But that's only because there's a default "semi-tolerant
> search" mode for which there's no explicit parameter. What is being
> tolerated (answer: ambiguous amino acids, and now potentially also
> mismatches) is not immediately apparent, though.

It says so clearly in the (somewhat lengthy) docs.

>
> I think the fact that I got confused by the parameters somewhat
> proves my point.

Did you read the docs? :)

> Maybe it would be more explicit to have a string
> parameter "search_mode" (or "match_mode"?) with different choices:
> "exact" ("strict"?), "two_pass", "tolerant" ("fuzzy"?). Something
> like that?

I like it! This would add another mode (exact), which is currently not 
available, but why not. I'd go for
"exact", "two_pass" and "tolerant".
Fuzzy is somewhat hinting at mismatches, which is not what one usually 
wants (as compared to allowing ambiguities).

Should this be included in the release? Opinions?

**Comment by timosachsenberg** [comment]
Its a nice feature but I think we should concentrate on the remaining issues for the release.

**Comment by hendrikweisser** [comment]
> Did you read the docs? :)

At some point, but I haven't re-read them now. :-P

> I like it! This would add another mode (exact), which is currently not available, but why not.

You would get this now if you set "aaa_max" to zero. After thinking about it more, I'm actually not sure if this mode would be useful: Are there cases where, if some peptides couldn't be matched using exact search, you would *not* want to do a tolerant search? (If not, a flag like "full_tolerant_search" would be enough.)

Independent of that, wouldn't it make sense to have the option of searching with mismatches only in the second pass (like the default for ambiguous AAs now)? This would get rid of the dependency of "mismatches_max" on "full_tolerant_search".

**Comment by cbielow** [comment]
Am 2/11/2015 um 3:19 PM schrieb hendrikweisser:
>> Did you read the docs? :)
>
> At some point, but I haven't re-read them now. :-P
>
>> I like it! This would add another mode (exact), which is currently
>> not available, but why not.
>
> You would get this now if you set "aaa_max" to zero.

Right.

> After thinking
> about it more, I'm actually not sure if this mode would be useful:
> Are there cases where, if some peptides couldn't be matched using
> exact search, you would *not* want to do a tolerant search? (If not,
> a flag like "full_tolerant_search" would be enough.)

You might want to identify peptides which only map when allowing 
ambiguous AA's. That would be the unmapped ones in this mode.

>
> Independent of that, wouldn't it make sense to have the option of
> searching with mismatches only in the second pass (like the default
> for ambiguous AAs now)? This would get rid of the dependency of
> "mismatches_max" on "full_tolerant_search".

Not sure what you mean. Mismatch-Search is supported algorithmically 
only via the SuffixArray (i.e. tolerant search), not by Aho-Corasick 
(exact search). Now, scientifically you'd use mismatch search to search 
for SNP and alike, and this you'll want to do for ALL peptides, not just 
the subset which you cant explain by exact matching. Hence mismatch 
search is only allowed during full_tolerant_search. Clear? Confusing?

**Comment by hendrikweisser** [comment]
> You might want to identify peptides which only map when allowing ambiguous AA's. That would be the unmapped ones in this mode.

Yeah, okay.

> Now, scientifically you'd use mismatch search to search for SNP and alike, and this you'll want to do for ALL peptides, not just the subset which you cant explain by exact matching.

This was basically my question. Could there be cases where you'd only want to re-search the unexplained ones using approximate matching? I think yes, because you could make the same argument as for ambiguous AAs - if you have a huge dataset/database, it might be prohibitive (and unnecessary) to search everything approximately ("full tolerant"). That assumes that you have used an identification tool capable of finding peptides with SNPs in the first place.

**Comment by cbielow** [comment]
Am 2/11/2015 um 4:18 PM schrieb hendrikweisser:
>> You might want to identify peptides which only map when allowing
>> ambiguous AA's. That would be the unmapped ones in this mode.
>
> Yeah, okay.
>
>> Now, scientifically you'd use mismatch search to search for SNP and
>> alike, and this you'll want to do for ALL peptides, not just the
>> subset which you cant explain by exact matching.
>
> This was basically my question. Could there be cases where you'd only
> want to re-search the unexplained ones using approximate matching? I
> think yes, because you could make the same argument as for ambiguous
> AAs - if you have a huge dataset/database, it might be prohibitive
> (and unnecessary) to search everything approximately ("full
> tolerant"). That assumes that you have used an identification tool
> capable of finding peptides with SNPs in the first place.

Interesting point.
The intention behind this was somewhat the inverse: once you've mapped 
all peptides without mismatches and found some which are unique, how 
certain can you be that another protein  with an unknown SNP (which you 
have not mapped so far) might be the origin of that peptide.
If your peptide is still unique even with mismatches allowed, you can be 
pretty sure its unique (given all the remaining issues with FDR and 
incomplete DBs)...

**Comment by hendrikweisser** [comment]
> The intention behind this was somewhat the inverse: [...]

I understand and this makes total sense. I just think it would be a very small step to also enable this functionality for the second search pass in a "semi-tolerant search", i.e. when "full_tolerant_search" is not set, and having this would be potentially useful.

**Comment by cbielow** [comment]
mhh.. the discussion died of somehow and there was no real conclusion AFAICS

Can we merge this and think about the rest later?

**Comment by cbielow** [comment]
OFC I will resolve conflicts beforehand

**Comment by timosachsenberg** [comment]
Sure.
So you are doing this only on the protein sequences?

**Comment by cbielow** [comment]
all resolved, please merge

**Pull request merged**
