### PR TITLE
add trivial devcontainer config

### PR DESCRIPTION
**Pull request by poshul**
## Description

I've added a trivial devcontainer.json to pull our manylinux contrib image and do development in that container. This should lower the barrier to entry for anyone who wants to poke around the code without making further changes to their machine.

The process to do this is pretty easy:
- Install VSCode, install Docker (not from a snap). 
- Clone OpenMS. 
- Open VSCode, run "Dev Containers: Reopen in Container".
- Launch a new shell in the container (click on the + at the right of the Terminal tab and launch bash). Run `cmake -DOPENMS_CONTRIB_LIBS=/contrib-build`
- build as normal.
## Checklist
- [x] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

___

### **PR Type**
enhancement, configuration changes

___

### **Description**
- Introduced a `devcontainer.json` file to facilitate development using a containerized environment.
- Configured the development container to use the `ghcr.io/openms/contrib_manylinux_2_28:latest` image.
- Aimed to lower the barrier to entry for new contributors by simplifying the setup process.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>devcontainer.json</strong><dd><code>Add development container configuration for OpenMS</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

.devcontainer/devcontainer.json

<li>Added a new <code>devcontainer.json</code> file.<br> <li> Configured the development container with a specific image.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7660/files#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Would be good to add cmake and clangd extension and make the settings such that you just have to press build in the UI.

**Comment by jpfeuffer** [comment]
See .gitpod.yml for extensions
and .vscode-gitpod for settings

**Comment by poshul** [comment]
I've not added the clang specific stuff since its built with gcc on manylinux, but I've added the cmake stuff.

**Comment by jpfeuffer** [comment]
Clangd is the language server that enables code completion, static checks and code navigation.
https://clangd.llvm.org
It works with GCC as well

**Comment by poshul** [comment]
Ah okay. Well regardless, it's not installed on manylinux by default. Do you think it'd be worth adding?

**Comment by jpfeuffer** [comment]
It automatically downloads itself when the extension is installed. I personally would not code without it.

**Comment by poshul** [comment]
@jpfeuffer the settings.json file describes `"clangd.path": "/opt/clangd/bin/clangd"` as far as I can tell it doesn't get installed there.

**Comment by jpfeuffer** [comment]
Yes true. This config is for gitpod, where we install clanged systemwide.

**Comment by jpfeuffer** [comment]
In my experience, if you leave it out, the extension will prompt you and allows you to install it?

**Pull request merged**
