### PR TITLE
Fix build travis

### PR DESCRIPTION
**Pull request by hroest**
try to address #1543

### CODE REVIEW

**Comment by hroest** [comment]
built on #1552

**Comment by cbielow** [comment]
that seems to fix it. So we need to explicitly state the ENV vars, because the initial cache requires them, even though the cmake params have a default value.

**Comment by hroest** [comment]
great, one problem down. still the mac builds (git update problem) and the PPWavelet3 remain

**Comment by jpfeuffer** [comment]
I am looking at the Mac builds. I think I found the problem. Will report in the corresponding issue.

**Pull request merged**
