### PR TITLE
[FIX] Sirius default executable names

### PR DESCRIPTION
**Pull request by oliveralka**
# Description

The default names were set incorrectly (windows), so KNIME was not able to get the path to the correct executable (see #5508). 

I also changed the "is_executable" to "skipexists". I hope with this step it is possible again to set the executable externally if KNIME is not able to find it. This should also be better for galaxy @timosachsenberg @jpfeuffer.

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Good find. What exactly does the change to skipexists do though? Or what are you hoping that it does?

**Comment by oliveralka** [comment]
I hope that if the executable is not in the path, will allow to set it at the Node. 

Currently, you are not able to set the executable anymore for the SiriusAdapter (since it should be in the PATH). 
For the AssayGenerator it should be in the PATH as well, but if you want to use another version, or it is not found you can still set in at the KNIME Node - I use the "skipexists" for it - I hope that is the correct purpose. 

Screenshot 2021-09-01 at 11 16 20
Screenshot 2021-09-01 at 11 16 30

**Comment by oliveralka** [comment]
@jpfeuffer I seems my thoughts are not correct and skipexists does not do what I intended to - is there a way to fix that?

**Comment by jpfeuffer** [comment]
This happens here: https://github.com/OpenMS/OpenMS/blob/ddf175c5251b1ecaaed041474379489781f1eedd/cmake/knime_package_support.cmake#L138

**Comment by oliveralka** [comment]
Ok, hopefully fixed now. 

The "optional" input "executable" should be available for the both nodes (SiriusAdapter, AssayGeneratorMetabo).

Do you think by setting the executable default name - this should work if it is in the PATH (KNIME)?
Or would you have to set it all the time?

**Review by jpfeuffer — APPROVED** [review]

**Pull request merged**
