### PR TITLE
fix crash in PeptideIndexer caused by -1 in missed cleavage

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
1000 is safe as MSGF+ has an upper limit on peptide length

**Comment by timosachsenberg** [comment]
fixes #4619

**Comment by cbielow** [comment]
i did not follow the complete issue, but if PeptideIndexer crashes the underlying bug wont be fixed by this PR, right? should we not fix whatever was causing that?

**Comment by timosachsenberg** [comment]
MSGF+ now writes out missed cleavages = -1 previous version wrote out 1000.
-1 is not supported for this attribute in idXML and Leads to downstream errors

**Pull request merged**
