### PR TITLE
[FEATURE] aggregating, storing consumer consumer

### PR DESCRIPTION
**Pull request by hroest**
- new consumers that allow storage in memory and aggregation of spectra
- add classes for two new consumers, MSDataAggregatingConsumer and
  MSDataStoringConsumerMSDataStoringConsumer
- add tests for both classes

### CODE REVIEW

**Comment by hroest** [comment]
sorry, this depends on #2311 ...

**Comment by hroest** [comment]
this depends on #2313

**Comment by hroest** [comment]
seems to work now, can we merge?

**Comment by jpfeuffer** [comment]
+1

**Pull request merged**
