### PR TITLE
Fix for #2783 (AccurateMassSearch, output file types)

### PR DESCRIPTION
**Pull request by hendrikweisser**
Small fix in AccurateMassSearch, and improvement of the error messages for invalid file types.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
looks good +1. Would it make sense to accept both csv and tsv?

**Comment by hroest** [comment]
> looks good +1. Would it make sense to accept both csv and tsv?

sounds good but I think TSV is reserved for something, e.g. msInspect file, see https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/FORMAT/FileTypes.h#L88 and L94 

I think we should change that, it does not make sense to have TSV only be one file format and honestly I think we should accept TSV and CSV always as people dont distinguish the two (myself included)

**Comment by hendrikweisser** [comment]
> I think we should change that, it does not make sense to have TSV only be one file format and honestly I think we should accept TSV and CSV always as people dont distinguish the two (myself included)

I think the previous guideline (defined by Oliver?) was to use .csv consistently for every character-delimited, tabular text format. One advantage of this is that on Windows, files with .csv extension can be opened in Excel by double-clicking on them (.tsv not, by default).

**Comment by hendrikweisser** [comment]
By the way, why don't we use .mzTab for mzTab files?

**Comment by lars20070** [comment]
@hendrikweisser https://github.com/OpenMS/OpenMS/issues/1462

**Comment by timosachsenberg** [comment]
feel free to change to mzTab

**Comment by hendrikweisser** [comment]
> feel free to change to mzTab

Tried it, but when I then run AccurateMassSearch, I get this error:

```
---------------------------------------------------
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler:
exception of type InvalidParameter occured in line 1015, function void __cdecl OpenMS::TOPPBase::setValidFormats_(const class OpenMS::String &,const class std::vector<class OpenMS::String,class std::allocator<class OpenMS::String> > &,const bool) of C:\Users\hendrik.weisser\Software\OpenMS\src\openms\source\APPLICATIONS\TOPPBase.cpp
error message: The file format 'mzTab' is invalid!
---------------------------------------------------
```

Is mzTab not defined as a file type currently?

**Comment by timosachsenberg** [comment]
nope https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/FORMAT/FileTypes.h

**Comment by jpfeuffer** [comment]
Seems like you also need to change the tests in DataFilter. They check the exact Exception message (which is actually a bit weird).

**Comment by hendrikweisser** [comment]
@jpfeuffer: Okay, I'm taking care of it.

**Comment by hendrikweisser** [comment]
@jpfeuffer: Can we get a new version of the KNIME plug-in that includes this fix, please? Without it, AccurateMassSearch is unusable in the current version.
(I've tried to revert to the previous working version in KNIME, but it errors out saying: "No repository found containing: ...")

**Pull request merged**
