### PR TITLE
[BUILD] use 2 parallel jobs for build

### PR DESCRIPTION
**Pull request by hroest**
According to this [1] we have 2 CPUs for our build, so it makes sense to use both of them but not use more than 2. 

Ref

1. https://docs.travis-ci.com/user/reference/precise/#Virtualization-environments

### CODE REVIEW

**Comment by jpfeuffer** [comment]
As far as I know, ctest_build does not have a PARALLEL option (https://cmake.org/cmake/help/v3.3/command/ctest_build.html)
Only ctest_test.
For building I think you need to use compiler flags (which might be different across platforms.)

**Comment by jpfeuffer** [comment]
And I also experienced what is currently happening. Even though they claim that you only have 2 cores, there is still some speed up if you go higher :)
We could try to find some optimum though

**Comment by jpfeuffer** [comment]
Build pyopenms

**Comment by hroest** [comment]
> And I also experienced what is currently happening. Even though they claim that you only have 2 cores, there is still some speed up if you go higher :)
:-)

**Pull request closed without merging**
