### PR TITLE
[FIX] also parse retention time from scan time entry

### PR DESCRIPTION
**Pull request by timosachsenberg**
let's see if this fixes the problem

### CODE REVIEW

**Comment by timosachsenberg** [comment]
one down, one more to go:
```
Offending lines:			(tab_width = 8, first_column = 1)

in1:  /home/travis/build/timosachsenberg/OpenMS/_build/src/tests/topp/MSGFPlusAdapter_1_out2.tmp.mzid   (line: 4, position/column: 6/7)
  <cv !
      fullName="PSI-MS" version="3.30.0" uri="https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo" id="PSI-MS"/>

in2:  /home/travis/build/timosachsenberg/OpenMS/src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.mzid   (line: 4, position/column: 8/9)
    <cv !
        id="PSI-MS" uri="http://psidev.cvs.sourceforge.net/viewvc/*checkout*/psidev/psi/psi-ms/mzML/controlledVocabulary/psi-ms.obo" version="3.30.0" fullName="PSI-MS"/>
```
I think it is best to update the file

**Comment by hendrikweisser** [comment]
> I think it is best to update the file

If that's the only remaining difference, it may be better to add a "whitelist" entry to the file comparison, to make it work with both versions of MS-GF+. (Or are we going to strictly support only the newest one?)

**Comment by timosachsenberg** [comment]
I don't know if these are the only changes, yet.
I think for now we can keep support fo rboth versions and add the whitelist parameter.

**Comment by timosachsenberg** [comment]
They seem to be very similar but the order of XML entries is different.
Any idea how to handle this?
```
1790: in1:  /nfs/wsi/abi/old-data/sachsenb/OpenMS_IDE/src/tests/topp/MSGFPlusAdapter_1_out2.tmp.mzid   (line: 11, position/column: 15/16)
1790:       <cvParam !
1790:                cvRef="PSI-MS" accession="MS:1002048" name="MS-GF+"/>
1790:
1790: in2:  /nfs/wsi/abi/old-data/sachsenb/OpenMS_IDE/src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.mzid   (line: 11, position/column: 21/22)
1790:             <cvParam !
1790:                      accession="MS:1002048" cvRef="PSI-MS" name="MS-GF+"/>
``´

**Comment by hroest** [comment]
without fully parsing the file into a datastructure and compare these datastructurs using `operator==` I dont really see how to handle this, for sure not with XML-unaware differs. `FuzzyDiff` has some XML awareness in terms of comparing numbers but you would have to add this functionality to it

I opt for simply replacing the file as Hendrik suggested

**Comment by timosachsenberg** [comment]
I will replace them. The changes are a only slightly different internal peptide accession names and the changed meta values for version and database.
by the way, there is a great tool to convert xml files into a canonical version (same order of attributes and elements) that does the trick
```
xmllint --c14n one.xml > 1.xml
xmllint --c14n two.xml > 2.xml
diff 1.xml 2.xml
```

**Comment by timosachsenberg** [comment]
builds now pass with the adapted tests

**Comment by hendrikweisser** [comment]
The "TOPP_MSGFPlusAdapter_1" test now fails on my machine. Is it only supposed to work with the newest MS-GF+ version?

**Comment by timosachsenberg** [comment]
yep the test requires the newest version but the files should still be compatible.
I saw no reason to introduce tests for the older versions as we usually focus on one set of search engine versions for a release

**Comment by hroest** [comment]
@timosachsenberg one side effect is that now `master` also fails on travis  ...

**Comment by timosachsenberg** [comment]
I would ignore that as we merge against develop in a few days for the release preparations.

**Pull request merged**
