### PR TITLE
typo fixes

### LINKED ISSUE #5755: Unmatched peptides found by PeptideIndexer in XTandemAdapter
Hi! We are using XTandemAdapter in our pipeline and we got an error with the message below. Seems like `PeptideIndexer` failed to match some peptides matched by X!Tandem.

```
Aho-Corasick done:
    found 391719 hits for 100666 of 100682 peptides.
  Peptide hits passing enzyme filter: 391719
       ... rejected by enzyme filter: 19071 
  Unmatched peptide: PAREVGDR
  Unmatched peptide: PGPLRRR
  Unmatched peptide: PNC(Carbamidomethyl)TKDSTSGSGEGGK
  Unmatched peptide: PAMNMGPGVR
  Unmatched peptide: PPPSTLC(Carbamidomethyl)SYWALEQGK
  Unmatched peptide: PEQIGLDESGGGGGSDPGEAPTR
  Unmatched peptide: PPTLC(Carbamidomethyl)C(Carbamidomethyl)LKLAFIDPATGKLM(Oxidation)DK
  Unmatched peptide: PLPLSYR
  Unmatched peptide: PLYVALAQR
  Unmatched peptide: PQPQLPKKYATEQPEDEPR
  Unmatched peptide: PVIVEIPHFGSMRGK
  Unmatched peptide: PC(Carbamidomethyl)LDESRFENLGVSSLGER
  Unmatched peptide: PPDAEPPPPFQTQTPPQSLQQPAPPGSER
  Unmatched peptide: PLQSYSQVISRGQAPLAPTHTPEL
  Unmatched peptide: ...
  -----------------------------------
  Peptide statistics
 
    unmatched                : 16 (0 %)
    target/decoy:
      match to target DB only: 73916 (73 %) 
      match to decoy DB only : 26388 (26 %) 
      match to both          : 362 (0 %)
  
    mapping to proteins:
      no match (to 0 protein)         : 16
      unique match (to 1 protein)     : 26631
      non-unique match (to >1 protein): 74035
  -----------------------------------
  Protein statistics
  
    total proteins searched: 201364
    matched proteins       : 96155 (96155 new)
    matched target proteins: 53885 (56 %)
    matched decoy proteins : 42270 (43 %)
    orphaned proteins      : 0 (all removed)
  -----------------------------------
  XTandemAdapter took 07:03 m (wall), 49.67 s (CPU), 3.74 s (system), 45.93 s (user); Peak Memory Usage: 1068 MB.
```

After looking at those sequences, we found that they are all from proteins with an ambiguous start (leading X, see below). So it seems like the case that X!Tandem handles the leading X and cut it off but `PeptideIndexer` does not. But clearly proteins with ambiguous start don't necessarily have to have `P` as the first amino acid after X. We don't understand why those peptides are not "unmatched" by `PeptideIndexer`

<pre><code>>ENSP00000460648.1|ENST00000570557.5|ENSG00000170175.11|OTTHUMG00000108139.5|OTTHUMT00000441002.3|CHRNB1-203|CHRNB1|316
X<b>PAREVGDR</b>VRVSVGLILAQLISLNEKDEEMSTKVYLDLEWTDYRLSWDPAEHDGIDSLRITAESVWLPDVVLLNNNDGN
>ENSP00000456301.1|ENST00000561841.1|ENSG00000065057.9|OTTHUMG00000128744.4|OTTHUMT00000434463.1|NTHL1-202|NTHL1|218
X<b>PGPLRRR</b>EAAAEARKSHSPVKRPRKAQRLRVAYEGSDSEKGEGAEPLKVPVWEPQDWQQQLVNIRAMRNKKDAPVDHLG
>ENSP00000416179.1|ENST00000420137.5|ENSG00000164031.17|OTTHUMG00000131049.5|OTTHUMT00000347522.1|DNAJB14-203|DNAJB14|48
X<b>PNCTKDSTSGSGEGGK</b>GYTKDQVDGVLSLERKRRVVQGVVEIRKEEH
</code></pre>

Btw, on the wiki page of [PeptideIndexer](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_PeptideIndexer.html), the description for `aaa_max` is "Maximal number of ambiguous amino acids (AAAs) allowed when matching to a protein database with AAAs. AAAs are B, J, Z and X!". Does the ! symbol in "X!" just a punctuation or does it have any special meaning?

### PR DESCRIPTION
**Pull request by cbielow**
# Description

X!Tandem's Protein-N-terminal cleavage rules are more flexible than OpenMS' PeptideIndexer allows for.
More specifically, ANY aminoacid (not just 'M') can be cleaved off the protein n-terminus.
This PR makes the behaviour consistent with how X!Tandem calls peptides.

fixes #5755 

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- /rebase will try to rebase the PR on the current develop branch.
- /reformat (experimental) applies the clang-format style changes as additional commit
- setting the label NoJenkins will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)

### CODE REVIEW

**Comment by timosachsenberg** [comment]
looks simple enough. @jpfeuffer any objections?

**Comment by jpfeuffer** [comment]
Do we know where it says ANY in Xtandem docs?

**Comment by jpfeuffer** [comment]
Because it could also just consider X since X matches M

**Comment by timosachsenberg** [comment]
I think I found some code in the X!Tandem source code that skips * and X at the N-terminus of peptides.
```
while((m_pSeq[lStart] == '*' || m_pSeq[lStart] == 'X') && lStart < m_lStartMax) ...
```

**Comment by jpfeuffer** [comment]
Aha! Nice find. Then the PR won't do much good and an extended strategy is required.

**Comment by cbielow** [comment]
> I think I found some code in the X!Tandem source code that skips * and X at the N-terminus of peptides.

Nice find, Timo.
Can you provide a link to the code?!
And why **peptides** and not *protein*?

And all I used to implement the fix was the comment from Ron Beavis here https://github.com/OpenMS/OpenMS/issues/2497#issuecomment-297060269

> Then the PR won't do much good and an extended strategy is required.
Well, it now could lead to some false positives, if truly only 'X' and 'M' are considered by X!Tandem.
The '*' we must not worry about. It is removed before processing in PeptideIndexer.

**Pull request merged**
