### PR TITLE
Implement matched whitelist in FuzzyDiff

### PR DESCRIPTION
**Pull request by hroest**
- implement a matched white list in FuzzyDiff
- use it to addresses the new error seen by Timo in #1206

### CODE REVIEW

**Comment by hroest** [comment]
see also #1205

**Comment by hroest** [comment]
an alternative option is to drop PPWavelet_3

**Comment by timosachsenberg** [comment]
I think it is a practical solution. 
The other alternative: determining the type stored behind base64 encoding in the FuzzyDiff and doing a proper decoding followed by a comparison of decoded strings is more difficult and would require that we encode recognition of CV terms (as stored in the XML) etc. in FuzzyDiff .

**Comment by hroest** [comment]
yes, I would be against making FuzzyDiff more complicated than it currently is

**Pull request merged**
