### PR TITLE
TOPPView refactor

### PR DESCRIPTION
**Pull request by cbielow**
# Description

 * fix variable names in LayerData.h
 * rename enum due to macro clash (when adding OSWData.h header to SpectrumCanvas3D)
 * some refactoring in IDView (prep for OSW integration)

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

### CODE REVIEW

**Review by timosachsenberg — APPROVED** [review]

**Comment by timosachsenberg** [comment]
one idea that came to me: could we just put all the exclusive layer elements in a boost variant?

**Comment by cbielow** [comment]
rebuild jenkins

**Comment by cbielow** [comment]
> 
> 
> one idea that came to me: could we just put all the exclusive layer elements in a boost variant?

This could work for the current use-case, but there might be new ones in the future where we'd need some composition, and then people will start storing pairs etc.. 
Lets keep the idea in mind when we decide what to do. Also, C++17 supports std::variant. No need for boost then.

**Comment by cbielow** [comment]
ready for merge

**Pull request merged**
