### PR TITLE
[TRAVIS] get coin through package management

### PR DESCRIPTION
**Pull request by hroest**
- should help with timeouts

### CODE REVIEW

**Comment by timosachsenberg** [comment]
we now get the
The following tests FAILED:
	 50 - LPWrapper_test (OTHER_FAULT)

**Comment by timosachsenberg** [comment]
I am not sure but I guess the word "failed" might trigger it.
```
checking (Int addRow(std::vector< Int > &row_indices, std::vector< double > &row_values, const String &name, double lower_bound, double upper_bound, Type type)) ... 
LPWrapper_test: OsiClpSolverInterface.cpp:3606: virtual int OsiClpSolverInterface::loadFromCoinModel(CoinModel&, bool): Assertion `integerType' failed.
 +  line 105:  TEST_EQUAL(lp.getNumberOfRows(),3): got 3, expected 3
 +  line 106:  TEST_EQUAL(lp.getRowName(2),"row3"): got row3, expected row3
: passed
```

**Comment by timosachsenberg** [comment]
@FabianAicheler do you know how to handle this assertion?

**Comment by jpfeuffer** [comment]
Maybe you have to go to the CTestConfig and whitelist that one.

**Comment by jpfeuffer** [comment]
https://cmake.org/Wiki/CMake/Testing_With_CTest
see customizing CTest

**Comment by hroest** [comment]
what does that even mean: LPWrapper_test: OsiClpSolverInterface.cpp:3606: virtual int OsiClpSolverInterface::loadFromCoinModel(CoinModel&, bool): Assertion `integerType' failed. ?

It seems like we had that issue before:

- https://github.com/OpenMS/OpenMS/issues/1985
- also other ppl https://groups.google.com/forum/#!msg/cyclus-dev/mcZBvyqa4xw/xwxN2qHpGBYJ

**Comment by hroest** [comment]
in the last few PR, most build failures were due to CoinOR timing out -- we could add a `travis_wait` or we can just install it through apt-get which is the sensible option anyways.

**Comment by timosachsenberg** [comment]
ok so should we merge this PR?

**Comment by timosachsenberg** [comment]
So now we need to fix the LPWrapper_test

**Pull request merged**
