### PR TITLE
FileInfo, field renamed

### PR DESCRIPTION
**Pull request by lars20070**
One of the fields in FileInfo output renamed. Now in line with the name of the corresponding class (PeptideIdentification).

### CODE REVIEW

**Comment by lars20070** [comment]
Build errors (despite Travis restart).

**Comment by lars20070** [comment]
Alternatively, we can call 'peptide hits' = PSMs, and 'peptide identifications' = PSMs of rank 1.

**Comment by timosachsenberg** [comment]
PeptideIdentification = identified spectra

**Comment by timosachsenberg** [comment]
Or matched spectra

**Comment by lars20070** [comment]
spectra -> matched spectra
peptide hits -> peptide spectrum matches (PSM)

**Comment by timosachsenberg** [comment]
As we use it peptidehit are not only PSM but also SSM (small molecule spectrum matches)

**Comment by lars20070** [comment]
Ok. Then let us use the correct description.

spectra -> matched spectra
peptide hits -> peptide (or small molecule) spectrum matches

**Comment by lars20070** [comment]
Let's simply make this change. The rest is fine.
spectra -> matched spectra

**Comment by timosachsenberg** [comment]
fine with me

**Pull request merged**
