### PR TITLE
Update for Visual Studio 2022

### PR DESCRIPTION
**Pull request by Waschi97**
Updated the contrib build system to work with Visual Studio 2022 generator and tool chain.
Also needed to add some includes for `std::array`.

### CODE REVIEW

**Comment by Waschi97** [comment]
Alright, the files are uploaded to abibuilder and the SHA1's seem to be correct. Building the contrib now works with VS22.
I also quickly tested building the contrib on my Ubuntu machine and with VS19 on Windows - both still working.

Merge?

**Comment by jpfeuffer** [comment]
Wait, i think contrib needs to be merged first. Otherwise it points to your branch no?

**Comment by jpfeuffer** [comment]
I.e. make a PR to contrib with just the contrib changes.
Wait for CI.
Merge.
Update contrib commit here.

**Comment by Waschi97** [comment]
Ahh that's how that works. Was wondering...

**Comment by jpfeuffer** [comment]
Something is fishy. tests fail now

**Comment by Waschi97** [comment]
Same tests that failed in the nightly though, right?

**Comment by Waschi97** [comment]
@jpfeuffer did I do something wrong? I don't understand the merge conflict - pulling the OpenMS.git doesn't reveal any conflicts for me...

**Comment by jpfeuffer** [comment]
I think you updated the contrib from the develop status to your branch, and now you updated it from your branch to the master branch.
I think you would have needed to reset to develop first and then update to master.

**Comment by Waschi97** [comment]
hmm..
I reset it with:
`git submodule update --remote` - this did what was expected: contrib commit was '359673e...'
then the following:
`git add contrib` & `git commit`
`cd contrib`
`git checkout master`
`cd ..`
`git add contrib` & `git commit`
`git push`
Doesn't seem to work.. Guess I really don't understand git submodules... 😅

**Pull request closed without merging**
