### PR TITLE
Update PercolatorAdapter.cpp version number (merge after THIRDPARTY update)

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Please include a summary of the change and which issue is fixed.

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

### CODE REVIEW

**Comment by oliveralka** [comment]
@timosachsenberg Should we merge your THIRDPARTY PR and add the new THIRDPARTY here?

**Comment by jpfeuffer** [comment]
we need a macos binary first. Did not find any.

**Comment by jpfeuffer** [comment]
Can you please add the new threads parameter and pass down ours?

**Comment by jpfeuffer** [comment]
Can you go lower than 3 also? Especially on clusters you usually want the exact amount of threads that were specified.

**Comment by timosachsenberg** [comment]
I need to check percolator sourc code. not yet documented

**Review by jpfeuffer — APPROVED** [review]

**Comment by oliveralka** [comment]
There seems to be an issue with reading the levels from the OSWFile.

**Comment by jpfeuffer** [comment]
yes, had to fix an array out of bounds bug. Now it does not list correctly anymore.

**Comment by oliveralka** [comment]
ah, so the -1 is still correct?

**Comment by oliveralka** [comment]
Let me know if that is correct or if it should be fixed differently.

**Comment by jpfeuffer** [comment]
No. It has to be done differently. This accesses out of bounds.

**Pull request merged**
