### PR TITLE
[FIX] Changed NNLS vs. inverse Matrix comparison to warning instead of exception 

### PR DESCRIPTION
**Pull request by oliveralka**
Changed NNLS vs. inverse Matrix comparison to warning instead of exception.

see #2630.

### CODE REVIEW

**Comment by hroest** [comment]
this looks good but for the user it is still unclear what s/he is supposed to do about it...

@cbielow  can we also come to a consensus regarding that

**Comment by cbielow** [comment]
First, it would be best to check which of these two methods is actually better (i.e. more stable), and use that to compute the result (the data only gives the values which are different, so not the whole input array) 
@oliveralka Can you provide the input values for the spectrum which fails and the correction matrix used?

**Comment by oliveralka** [comment]
@cbielow What do you mean by input values? An example workflow with data attached?

**Comment by cbielow** [comment]
a vector of 10 reporter ions, which yields different results :)

**Comment by hroest** [comment]
maybe we could simulate a few cases with different noise levels and then
see which method is closest to the truth?

also, which method do other people use?

**Comment by timosachsenberg** [comment]
I will merge it because it makes the analysis possible but I agree that we should dig into this a bit more.

**Pull request merged**
