### PR TITLE
added string conversion to param and other classes

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Fixes some of the inconveniences introduced with python 3 switch and unicode strings

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
travis timeout

**Comment by jpfeuffer** [comment]
Seems like it was untested though. I expected some changes in the tests to go with it. Can you add a couple of lines to the py tests for the most important functions?

**Comment by timosachsenberg** [comment]
it fixes the pyopenms test (which strangely did not show up before)

**Comment by jpfeuffer** [comment]
Hmm then we have to investigate this.

**Pull request merged**
