### PR TITLE
Make BuildSystem's LibCheck fail-safe

### PR DESCRIPTION
**Pull request by cbielow**
Sometimes a nightly build fails (e.g. http://cdash.openms.de/viewConfigure.php?buildid=116278),
since dumpbin did not deliver the required information before timing out (3 seconds).

This PR fixes:
 - not failing when dumpbin.exe was terminated after timeout (3 sec by default) -- we just assume its the correct arch and report a warning

- timeout  can be increased (e.g. for slow build machines).

 - checking libs only once (and store result in CMake cache) -- when libs are exchanged, the user has to delete the cache to re-run the check.

### CODE REVIEW

**Comment by aiche** [comment]
Looks good, I will try to test it ASAP on a windows machine. If everything works, we should merge.

**Comment by aiche** [comment]
A first test brought the following result .. 

```
-- Adding library OpenMS
--   Checking architecture of link libraries ...
CMake Error at cmake/modules/CheckLibArchitecture.cmake:67 (string):
  string end index: 600 is out of range -1 - 205
Call Stack (most recent call first):
  cmake/add_library_macros.cmake:177 (check_lib_architecture)
  src/openms/CMakeLists.txt:108 (openms_add_library)
```

The next try passed. Any suggestions how to proceed?

**Comment by cbielow** [comment]
The error is the same as before, despite the changes, right?
Then it must the substring call which fails on a string which is shorter than 600.
Maybe testing for length before helps...


Am 9. Januar 2015 22:44:23 MEZ, schrieb Stephan Aiche <notifications@github.com>:
>A first test brought the following result .. 
>
>```
>-- Adding library OpenMS
>--   Checking architecture of link libraries ...
>CMake Error at cmake/modules/CheckLibArchitecture.cmake:67 (string):
>  string end index: 600 is out of range -1 - 205
>Call Stack (most recent call first):
>  cmake/add_library_macros.cmake:177 (check_lib_architecture)
>  src/openms/CMakeLists.txt:108 (openms_add_library)
>```
>
>The next try passed. Any suggestions how to proceed? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenMS/OpenMS/pull/1131#issuecomment-69404173

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by cbielow** [comment]
```
string(LENGTH "${PIPE_OUT_LIB}" PIPE_OUT_LIB_LEN)
if (${PIPE_OUT_LIB_LEN} LESS 600)
  set(PIPE_OUT_LIB_S "${PIPE_OUT_LIB}")
else()
  string(SUBSTRING "${PIPE_OUT_LIB}" 0 600 PIPE_OUT_LIB_S)
endif()
```

should do it. I'll change the PR accordingly tomorrow.

**Comment by cbielow** [comment]
@aiche Could you try again pls?!

**Comment by aiche** [comment]
works

**Pull request merged**
