### PR TITLE
Fix/spectra data type

### PR DESCRIPTION
**Pull request by timosachsenberg**
should fix: https://github.com/OpenMS/OpenMS/issues/1820

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@lars20070

**Comment by hroest** [comment]
still some tests fail:

```
	1748 - TOPP_MSGFPlusAdapter_1_out1 (Failed)
```

**Comment by timosachsenberg** [comment]
Tests passed except unrelated ones

**Comment by lars20070** [comment]
+1

**Pull request merged**
