### PR TITLE
[FIX] fix for boost 1.64

### LINKED ISSUE #2790: Incompatibilities with boost-1.64
Hi all.

I'm rebuilding `OpenMS-2.2.0` against `Boost-1.64` for `Fedora` devel branch but it fails with following error:

```
In file included from /usr/include/boost/numeric/ublas/vector.hpp:21:0,
                 from /usr/include/boost/numeric/ublas/matrix.hpp:18,
                 from /usr/include/boost/accumulators/statistics/covariance.hpp:22,
                 from /builddir/build/BUILD/openms-2.2.0/py2build/src/openms/include/OpenMS/MATH/STATISTICS/StatisticFunctions.h:42,
                 from /builddir/build/BUILD/openms-2.2.0/py2build/src/openms/source/MATH/STATISTICS/LinearRegression.cpp:37:
/usr/include/boost/numeric/ublas/storage.hpp: In member function 'void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)':
/usr/include/boost/numeric/ublas/storage.hpp:299:33: error: 'make_array' is not a member of 'boost::serialization'
             ar & serialization::make_array(data_, s);
                                 ^~~~~~~~~~
/usr/include/boost/numeric/ublas/storage.hpp:299:33: note: suggested alternative: 'make_nvp'
             ar & serialization::make_array(data_, s);
                                 ^~~~~~~~~~
                                 make_nvp
/usr/include/boost/numeric/ublas/storage.hpp: In member function 'void boost::numeric::ublas::bounded_array<T, N, ALLOC>::serialize(Archive&, unsigned int)':
/usr/include/boost/numeric/ublas/storage.hpp:494:33: error: 'make_array' is not a member of 'boost::serialization'
             ar & serialization::make_array(data_, s);
                                 ^~~~~~~~~~
/usr/include/boost/numeric/ublas/storage.hpp:494:33: note: suggested alternative: 'make_nvp'
             ar & serialization::make_array(data_, s);
                                 ^~~~~~~~~~
                                 make_nvp
In file included from /usr/include/boost/accumulators/statistics/covariance.hpp:22:0,
                 from /builddir/build/BUILD/openms-2.2.0/py2build/src/openms/include/OpenMS/MATH/STATISTICS/StatisticFunctions.h:42,
                 from /builddir/build/BUILD/openms-2.2.0/py2build/src/openms/source/MATH/STATISTICS/LinearRegression.cpp:37:
/usr/include/boost/numeric/ublas/matrix.hpp: In member function 'void boost::numeric::ublas::c_matrix<T, M, N>::serialize(Archive&, unsigned int)':
/usr/include/boost/numeric/ublas/matrix.hpp:5977:33: error: 'make_array' is not a member of 'boost::serialization'
             ar & serialization::make_array(data_, N);
                                 ^~~~~~~~~~
/usr/include/boost/numeric/ublas/matrix.hpp:5977:33: note: suggested alternative: 'make_nvp'
             ar & serialization::make_array(data_, N);
                                 ^~~~~~~~~~
                                 make_nvp
make[3]: *** [src/openms/CMakeFiles/OpenMS.dir/build.make:873: src/openms/CMakeFiles/OpenMS.dir/source/MATH/STATISTICS/LinearRegression.cpp.o] Error 1
```

No errors against `boost-1.63`.
I suspect there are some incompatibilities with the newer version of `boost`.

Full build log: https://kojipkgs.fedoraproject.org//work/tasks/9431/20689431/build.log

### PR DESCRIPTION
**Pull request by hroest**
- fixes #2790

### CODE REVIEW

**Comment by hroest** [comment]
I guess older boost libraries dont have this -- we need to wrap it into a preprocessor macro

**Comment by hroest** [comment]
seems to work now, lets wait for windows and then merge?

**Comment by jpfeuffer** [comment]
Wait.. should that be a >=?
Failing on macOS with our contrib boost 1.64

**Comment by hroest** [comment]
> Wait.. should that be a >=?

ups, yes it should be

**Pull request merged**
