### PR TITLE
Fix tool scan in TOPPView

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Async may spawn one thread per topp tool. That's no problem but apparently 
spawning hundreds of processes (=tool execution for ini file reading, one for each thread) seems to hit
a hard limit in file handles or available pipes.

Simplest form of process pool implementation I can come up with :)

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Weren't there multiple suggestions when the PR was open? Why don't we set a fixed number of threads and just distribute the tasks on them (i.e. give them part of the tool list to check).

Your implementation might still spawn an arbitrary number of threads, with all but 6 waiting to access the int? Does it?
Maybe they don't open file handles anymore though.

**Comment by timosachsenberg** [comment]
We previously used Qt for a threadpool implementation.
Then switched to std::async because of reviewer requests. Unfortunately, std c++ doesn't offer threadpools / has only very basic multi threading support.
Now we found out that the processes and open pipes/handles are a problem.
So we fixed that part with a process pool. Having hundreds or thousands of threads is not an issue though so I guess this solution is fine.

**Comment by timosachsenberg** [comment]
In that case the problem occurred after about 80 processes were running in parallel.

**Comment by timosachsenberg** [comment]
Also doesn’t seem detrimental to performance because XML parsing still happens in parallel

**Comment by jpfeuffer** [comment]
I know. However, the last suggestions from Chris and me were such easy std::thread solutions.

**Comment by timosachsenberg** [comment]
Hmm you mean the chunking proposed in https://github.com/OpenMS/OpenMS/pull/5256 ? I think it is possible but then you need another separate thread that fires up the chunks of threads right?  As you can’t do that in the gui thread. Not sure if easier but probably cleaner. On the other hand normal chunking is slower as it waits till a chunk is finished. Here we can fire the next process immediately when the last one was finished.

**Comment by timosachsenberg** [comment]
Let’s come up with a proper thread pool solution at some point  and accept this as temporary fix?

**Comment by timosachsenberg** [comment]
Let’s come up with a proper thread pool solution at some point  and accept this as temporary fix?

**Pull request merged**
