### PR TITLE
[FIX] pyopenms macOS catalina

### PR DESCRIPTION
**Pull request by oliveralka**
ADD sysroot variable to env.py using cmake.
Use variable depending on macOS version (setup.py)

Increased minimal CMake version to 3.1 (similar to OpenMS; CMAKE_OSX_SYSROOT available since 3.0.2)

Refers to #4366

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Maybe add a check for empty somewhere, otherwise it looks good.

**Comment by jpfeuffer** [comment]
And I would maybe add it for mojave already, since the headers are not installed globablly by default there either.
(Yes, you can install manually but not everyone does it)

**Comment by oliveralka** [comment]
`mac_fix_automation_mojave` is now copied to the pyopenms build directory and can be used after 
`python setup.py bdist_wheel` to automatically fix all the library dependencies (including the frameworks).

**Comment by oliveralka** [comment]
mac_fix_automation_mojave.sh does currently not work, since the QT libraries are not copied over into the whl - have to check.

**Comment by oliveralka** [comment]
@jpfeuffer Since there is currently no straight forward way to fix the libraries using the fix_dependencies.rb script internally, since the build/lib folder is not automatically specified in our cmake, should we leave it at that?

**Comment by oliveralka** [comment]
Closed due to merge with #4398

**Pull request closed without merging**
