### PR TITLE
[FIX] pyopenms-nightly

### LINKED ISSUE #4650: pyopenms-nightly builds broken
Conda installation on win and mac not working anymore.

Also we have to fix the overnight day-change bug for pip.

And unify the contribs installation: on mac it still uses a cached version but probably should download as well.

### PR DESCRIPTION
**Pull request by oliveralka**
Fix #4650
1) Download contribs 
2) Try to set timezone to fix overnight day-change bug

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Looks good, but did you figure out, why miniconda is not working anymore. Otherwise it will be hard to debug your other changes.

**Comment by oliveralka** [comment]
Haha yeah, I will try it directly within setup.py.

In case of miniconda it seems that the corresponding download link has changed to 
`https://repo.anaconda.com/miniconda`

**Comment by jpfeuffer** [comment]
Looks v promising. thx

**Comment by jpfeuffer** [comment]
No module pytz.

And we need to reset the install names of the contribs libs. I forgot that. On Jenkins we do that automatically. I can add that.

**Comment by oliveralka** [comment]
Added to the .yml. 

Not sure if needed here as well:
```
tools/travis/lnx-cibuild.before.sh
src/pyOpenMS/dist-scripts/create-manylinux.sh
```

**Comment by oliveralka** [comment]
> And we need to reset the install names of the contribs libs. I forgot that. On Jenkins we do that automatically. I can add that.

The would be great - thanks!

**Comment by oliveralka** [comment]
@jpfeuffer Could you take another look, should be ok like that. Then I will remove the debug branch - and it should be ready for merge.

**Comment by jpfeuffer** [comment]
I mean looks good but now we have to change all the build scripts and build machines. I did not think about that :( I am wondering if a CMake based configure solution would be better. I think the string TIMESTAMP function has timezone support.

**Comment by oliveralka** [comment]
Ok, that was not clear to me as well - I will have a look at a CMAKE based solution.

**Comment by oliveralka** [comment]
It might be not possible to set a different timezone it is either current or UTC...let's see! 
https://cmake.org/cmake/help/v3.0/command/string.html

**Comment by jpfeuffer** [comment]
Hmm I see. Another option would be to use the Git last change date that we parse.
GIT_LC_DATE I think in CMake. This might also be more robust, since all the builds will have the same stamp then. But it wont account for rebuilds.

**Pull request merged**
