### PR TITLE
Feature/osw cli

### PR DESCRIPTION
**Pull request by hroest**
update OpenSWATH CLI, remove some default options (like 14s default peak width) and replace -ppm option with -mz_extraction_window_unit

### CODE REVIEW

**Comment by hroest** [comment]
rebuild jenkins

**Comment by grosenberger** [comment]
Great! Are there any consequences by removing the 14s requirement?

**Comment by grosenberger** [comment]
Ok, sounds good. We also still have ``-Scoring:TransitionGroupPicker:compute_peak_quality true`` enabled by default that remove some peaks. I'm currently assessing whether that makes sense to disable in some scenarios.

**Comment by timosachsenberg** [comment]
merge?

**Pull request merged**
