### PR TITLE
minor optimizations for profile mode

### PR DESCRIPTION
**Pull request by lars20070**
Extends the optimizations from #1626 to profile mode.

### CODE REVIEW

**Comment by lars20070** [comment]
@timosachsenberg The 'getPeakIndex()' in the profile mode used the peak boundaries instead of the 'mz_tolerance_' and is more accurate. Still need to change some code here.

**Comment by timosachsenberg** [comment]
so does the change then make sense for profile mode or should it be better kept as is?

**Comment by lars20070** [comment]
Will write a local version of findNearest(). BTW, the magic number stems from here. 3x peak width.

**Comment by timosachsenberg** [comment]
so this should be closed?

**Comment by lars20070** [comment]
No. - Please merge these minor changes.

**Comment by lars20070** [comment]
Will use #1638 instead.

**Comment by lars20070** [comment]
The left/right tolerances are not known in advance but are part of the spectrum. Guess #1638 cannot be used after all.

**Comment by timosachsenberg** [comment]
What do you mean with "part of the spectrum"

**Comment by lars20070** [comment]
The tolerances are not specified in getPeakIndex(), but I scan through peaks and tolerances i.e. boundaries simultaneously.
https://github.com/OpenMS/OpenMS/pull/1630/files#diff-d3f64d534dd7f30a56e4fac9c0d7a5c8R366

**Comment by timosachsenberg** [comment]
ok I see

**Pull request merged**
