### PR TITLE
Fix license year (2023)

### PR DESCRIPTION
**Pull request by cbielow**
## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Review by jpfeuffer — COMMENTED** [review]
Why not just use:
myyear=`date +'%Y'`

such that this never has to be updated?

**Comment by cbielow** [comment]
In the update script?! Sure...

**Comment by timosachsenberg** [comment]
we have: https://github.com/OpenMS/OpenMS/blob/develop/.github/workflows/update_year_number.yml

**Comment by timosachsenberg** [comment]
I think having the yearly trigger was never discussed (see https://github.com/OpenMS/OpenMS/pull/6777 ). Do we want that? If so, it is easy to add.
I see the point of reusing the script, but would be removing it and putting it in an action not lead to a cleaner, more code centric repo? An action calling a script outside the .github workflow folder can imho easier break than having it in the action but anyway... just wanted to point out that we already have an action for that.

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/pull/6921/files

**Comment by timosachsenberg** [comment]
I see your point. Maybe duplication could be addressed with defining our own actions.
https://stackoverflow.com/questions/59259783/how-to-combine-two-action-yml-files-in-one-repo - just brainstorming

**Comment by jpfeuffer** [comment]
This looks far from finished and way more work than having scripts. Also, does not solve the transferability issue and local testing.

**Comment by jpfeuffer** [comment]
By the way. Actions are written in JS... not sure if anyone would want to do that..

**Comment by timosachsenberg** [comment]
hmm I think there are now multiple ways to do that without JS. e.g. https://docs.github.com/en/actions/creating-actions/creating-a-composite-action but did not look into it in detail

**Comment by cbielow** [comment]
IMHO: The time you invested into solving this using automation is worth doing this 10 years manually already.
And by that time,  the automated workflown would break three times over....


Am 27.06.2023 16:23 schrieb Timo Sachsenberg ***@***.***>:

hmm I think there are now multiple ways to do that without JS. e.g. https://docs.github.com/en/actions/creating-actions/creating-a-composite-action but did not look into it in detail

**Comment by timosachsenberg** [comment]
I bet we then would be the first ones that achieve continuous delivery manually.
BTW that action was a no-brainer and chatgpt can spit it out – you don't even need to write it. It also defines the environment the script runs on. While the original script was/is? mac only etc. (I recall a few problems running it manually on linux.)

**Comment by cbielow** [comment]
> I bet we then would be the first project that achieve continuous delivery manually.

How is running a script **once a year** CD? Unless you run it with every PR as a post-hook, but thats getting out of hand here.

> BTW that action was a no-brainer and chatgpt can spit it out – you don't even need to write it. 

That was not the point.

> It also defines the environment the script runs on. While the original script was/is? mac only etc. (I recall a few problems running it manually on linux.)

This PR uses the linux variant, which I modified to exclude the .git subdir (as already done on Mac). It runs just fine.

If you want to spend time on automating marginal things like this and do it all over when switching to another CI or god knows, then go ahead.

**Pull request closed without merging**
