### PR TITLE
Feature/spec lib update

### PR DESCRIPTION
**Pull request by timosachsenberg**
- some style changes/modernization of code base
- ppm support for queries
- support for isotopic misassignment in queries
- more extensive search parameter annotation in results

### CODE REVIEW

**Comment by hroest** [comment]
we are still waiting on https://github.com/timosachsenberg/OpenMS/pull/13/files

**Comment by timosachsenberg** [comment]
ok I see - the ini files is outdated

**Comment by timosachsenberg** [comment]
cool. tests pass.
Now we might consider how to deal with isotopic misassignments if a very large precursor window was provided.
````
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://open-ms.sourceforge.net/XSL/IdXML.xsl" ?>
<IdXML version="1.5" xsi:noNamespaceSchemaLocation="https://www.openms.de/xml-schema/IdXML_1_5.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SearchParameters id="SP_0" db="/home/hr/openmsall/source/OpenMS/src/tests/topp/SpecLibSearcher_1.MSP" db_version="" taxonomy="" mass_type="monoisotopic" charges="1:5" enzyme="unknown_enzyme" missed_cleavages="0" precursor_peak_tolerance="3" precursor_peak_tolerance_ppm="false" peak_mass_tolerance="0" peak_mass_tolerance_ppm="false" >
	</SearchParameters>
	<IdentificationRun date="2009-08-06T17:19:56" search_engine="" search_engine_version="SpecLibSearcher" search_parameters_ref="SP_0" >
		<ProteinIdentification score_type="ZhangSimilarityScore" higher_score_better="true" significance_threshold="0" >
			<ProteinHit id="PH_0" accession="0" score="0" sequence="" >
			</ProteinHit>
		</ProteinIdentification>
		<PeptideIdentification score_type="ZhangSimilarityScore" higher_score_better="true" significance_threshold="0" >
			<PeptideHit score="0.999999997016446" sequence="AADDKEAC(Carbamidomethyl)FAVEGPK" charge="2" protein_refs="PH_0" >
				<UserParam type="float" name="lib:RT" value="-1"/>
				<UserParam type="float" name="lib:MZ" value="805.379776466771"/>
				<UserParam type="int" name="isotope_error" value="0"/>
			</PeptideHit>
			<PeptideHit score="0.999999997016446" sequence="AADDKEAC(Carbamidomethyl)FAVEGPK" charge="2" protein_refs="PH_0" >
				<UserParam type="float" name="lib:RT" value="-1"/>
				<UserParam type="float" name="lib:MZ" value="805.379776466771"/>
				<UserParam type="int" name="isotope_error" value="1"/>
			</PeptideHit>
		</PeptideIdentification>
	</IdentificationRun>
</IdXML>
```
For a window of 3 Th it (obviously) also matched with isotope misassignment.
 
One possiblility is:
Given, that pc_tol is the m/z window and pc_tol/2 the half-window to the left and right.
We only enable matching of isotopic misassignments if there is no overlap of these windows.
That is, if 0.5*pc_tol  is smaller than 0.5 * m/z difference between isotopic peaks.
or: pc_tol < Constants::C13C12_MASS_DIFF_U / charge

**Comment by timosachsenberg** [comment]
ok done in current commit

**Comment by jpfeuffer** [comment]
There seem to be two copies of the speclibsearcher_1.msp now. One with uppercase and one with lowercase extension. Can you delete one?

**Comment by jpfeuffer** [comment]
Could be the reason why it breaks the nightly tests for IDFileConverter only on Mac.

**Comment by timosachsenberg** [comment]
http://cdash.openms.de/testDetails.php?test=45164471&build=244111

**Comment by jpfeuffer** [comment]
My linked PR tries to fix this now.

**Pull request merged**
