### PR TITLE
Feature/ppxlink

### PR DESCRIPTION
**Pull request by enetz**
The code now produces results, that are relatively close to the original xQuest's and visualizable with the xQuest results manager (webserver).

### CODE REVIEW

**Comment by hroest** [comment]
Great job!

sent from my smartphone -- you may keep any typos you find.

**Comment by hendrikweisser** [comment]
Two questions:
1. Should the "xQuest" utility be renamed to "XQuest" to fit with the TOPP/UTIL naming scheme?
2. Does the tool also work for MS-cleavable, non-labeled cross-linkers, i.e. like XlinkX (http://xlinkx.hecklab.com/)?

**Comment by timosachsenberg** [comment]
@hendrikweisser it's currently a working title and the main aim is to first replicate the xQuest results. It does not support MS-cleavable non-labeled cross-linkers but this is likely an extension we will implement.

**Comment by hendrikweisser** [comment]
Thanks, Timo. I will probably have to analyse some data from a cross-linking experiment with cleavable non-labeled cross-linkers in the future, so I'd be really interested in any progress on that front.

**Comment by timosachsenberg** [comment]
By the way, you will meet Eugen @enetz at the developer meeting

**Pull request merged**
