### PR TITLE
Aho-Corasick DFA

### PR DESCRIPTION
**Pull request by cbielow**
converted NFA to DFA, potentially saving 50% of transitions.
Actual speedup is 20-30% for the AC itself.

+ some better internal docs 
+ fixed a bug when PeptideIndexer found no decoy proteins (idXML annoation was incomplete for all proteinhits)

### CODE REVIEW

**Comment by cbielow** [comment]
Windows build has 4 unrelated (MSGF+) failed tests.
Ready to merge.

**Comment by jpfeuffer** [comment]
rebuild win

**Comment by cbielow** [comment]
@timosachsenberg Makes sense. I added the option.

**Comment by jpfeuffer** [comment]
Aaah found the problem for the failing test. CI was testing the head of your branch instead of the merge commit. Will change now.

**Comment by cbielow** [comment]
WinJenkins still fails unrelated Msgf  tests. 
But good to merge.

**Comment by jpfeuffer** [comment]
Yes I did not restart. Yes good to merge from my side.

**Pull request merged**
