### PR TITLE
Fix RPATH creation in deb package

### PR DESCRIPTION
**Pull request by poshul**
## Description

Debian discourages the use of RPATH (https://wiki.debian.org/RpathIssue). Our current inclusion of it breaks any deb packages we create:
`GLIBC_2.32' not found (required by /lib/x86_64-linux-gnu/libsystemd.so.0)
TOPPView: /usr/bin/../lib/libc.so.6: version GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libsystemd.so.0)
...`
due to our use of our own version of things like libc:
` libc.so.6 => /usr/bin/../lib/libc.so.6 (0x00007cdd89200000)`
but the system version of other libraries that we don't specify as NEEDED in the binaries:
`    libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007cdd90594000)
    libssl.so.1.1 => /lib/libssl.so.1.1 (0x00007cdd88000000)`

This patch resolves that issue by not adding the RPATH to any executables that we package in a deb.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

___

### **PR Type**
bug_fix, configuration changes

___

### **Description**
- Fixed the issue with RPATH creation in Debian packages by adding a condition to skip RPATH installation when the package type is 'deb'.
- This change prevents the inclusion of RPATH in executables, resolving compatibility issues with system libraries.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>CMakeLists.txt</strong><dd><code>Conditional RPATH exclusion for Debian package builds</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

CMakeLists.txt

<li>Added condition to skip RPATH installation for Debian packages.<br> <li> Ensured RPATH is not set for executables in Debian packages.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7671/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by poshul** [comment]
I've tagged @mr-c as our resident Debian expert, and @jpfeuffer as our CMake expert.

**Comment by jpfeuffer** [comment]
This code was never intended for distribution on official Debian channels.
Only our own packages.
Depending on how they do their packaging your change might work.

**Comment by jpfeuffer** [comment]
Note that we ARE actually shipping dependencies which you would not, if you were packaging for an official package. Therefore we should use Rpaths such that our shipped dependencies are actually being used.

Therefore I am not sure if this is the correct way to go.

**Review by mr-c — APPROVED** [review]
Sure, but an official Debian package of `openms` wouldn't use the deb generator feature of cmake and thus wouldn't trigger this code anyhow :-)

`-DCMAKE_SKIP_RPATH=ON` is already manually specified for the `openms` Debian package:  https://salsa.debian.org/debichem-team/openms/-/blob/cfabf8262fb3527110addd52fd89b76a08ad022b/debian/rules#L62

**Comment by jpfeuffer** [comment]
I thought so. Makes sense.

If this is just about our own deb packges @poshul, I think the simple reason is, that you are running the package on a system which does not have a recent enough libc (or building it on a system that is too new).
We specifically do not ship libc as this may result in very subtle bugs.
https://github.com/OpenMS/OpenMS/blob/develop/cmake/package_general.cmake#L78

**Comment by poshul** [comment]
> Note that we ARE actually shipping dependencies which you would not, if you were packaging for an official package. Therefore we should use Rpaths such that our shipped dependencies are actually being used.
> 
> Therefore I am not sure if this is the correct way to go.

What is the intent of shipping our deb? Most of our Linux users (at least the ones I talk to) build from scratch but it's nice to have a controlled package that I can stick on my Ubuntu box and test nightlies and I think we do want to support more users installing from package especially since we offer the deb as our linux "installer"

Whether we are intending to or not we do ship libc:
see `    libc.so.6 => /usr/bin/../lib/libc.so.6 (0x00007cdd89200000)` which is our version.

**Comment by jpfeuffer** [comment]
> > Note that we ARE actually shipping dependencies which you would not, if you were packaging for an official package. Therefore we should use Rpaths such that our shipped dependencies are actually being used.
> > 
> > Therefore I am not sure if this is the correct way to go.
> 
> What is the intent of shipping our deb? Most of our Linux users (at least the ones I talk to) build from scratch but it's nice to have a controlled package that I can stick on my Ubuntu box and test nightlies and I think we do want to support more users installing from package especially since we offer the deb as our linux "installer"

Yes, that was the reason. However it was not worth the maintenance. It will be heavily outdated by now.
It should not ship libc or any low level system libs. It should be built on a manylinux or old ubuntu. Since Debian now has all our dependencies, it should not ship any of those dependencies and you should list them with their package name in the appropriate place in Cmake. (Ideally use auto lookup of dependency Deb packages:
https://github.com/OpenMS/OpenMS/blob/e54180f073d6da906a603038dd1ada5f050d553c/cmake/package_deb.cmake#L59)

> Whether we are intending to or not we do ship libc:
> see `    libc.so.6 => /usr/bin/../lib/libc.so.6 (0x00007cdd89200000)` which is our version.

This is a bug. The package was not touched after a rewrite of the dependency resolution system.

**Comment by poshul** [comment]
> > > Note that we ARE actually shipping dependencies which you would not, if you were packaging for an official package. Therefore we should use Rpaths such that our shipped dependencies are actually being used.
> > > Therefore I am not sure if this is the correct way to go.
> > 
> > 
> > What is the intent of shipping our deb? Most of our Linux users (at least the ones I talk to) build from scratch but it's nice to have a controlled package that I can stick on my Ubuntu box and test nightlies and I think we do want to support more users installing from package especially since we offer the deb as our linux "installer"
> 
> Yes, that was the reason. However it was not worth the maintenance. It will be heavily outdated by now. It should not ship libc or any low level system libs. It should be built on a manylinux or old ubuntu. Since Debian now has all our dependencies, it should not ship any of those dependencies and you should list them with their package name in the appropriate place in Cmake. (Ideally use auto lookup of dependency Deb packages:
> 
> https://github.com/OpenMS/OpenMS/blob/e54180f073d6da906a603038dd1ada5f050d553c/cmake/package_deb.cmake#L59
> )
> 
> > Whether we are intending to or not we do ship libc:
> > see `    libc.so.6 => /usr/bin/../lib/libc.so.6 (0x00007cdd89200000)` which is our version.
> 
> This is a bug. The package was not touched after a rewrite of the dependency resolution system.

Okay, so long as it's a bug and not a feature that I don't understand. I'll go ahead and put those changes in here as well.

**Comment by poshul** [comment]
of our 6 PRE_EXCLUDE_REGEXES we've 3 that aren't shipped:
      ".*/libdl\\..*"
      ".*/libpthread\\..*"
      ".*/linux-vdso.*"      
and 3 that are:
      ".*/ld-linux-.*"
      ".*/libm\\..*"
      ".*/libc\\..*"
The regexes look equivalent between them, so I'm confused

**Comment by poshul** [comment]
moving the exclude regexes to

set(POST_EXCLUDE ".*/ld-linux-.*" ".*/linux-vdso.*" ".*/libm\\..*" ".*/libc\\..*" ".*/libpthread\\..*" ".*/libdl\\..*")
solves the specific issue. But there are still a ton of weird things like cmake files that get included in the package.

**Comment by jpfeuffer** [comment]
Which ones? CMake config files are part of every good package

**Comment by poshul** [comment]
Here's what's included:

-rw-r--r-- root/root      6607 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/CheckLibArchitecture.cmake
-rw-r--r-- root/root      8212 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/CodeCoverage.cmake
-rw-r--r-- root/root      6816 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/CppcheckTargets.cmake
-rw-r--r-- root/root      7407 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/FindCOIN.cmake
-rw-r--r-- root/root      3083 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/FindGLPK.cmake
-rw-r--r-- root/root     48060 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/FindHDF5.cmake
-rw-r--r-- root/root      4250 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/FindLIBSVM.cmake
-rw-r--r-- root/root       341 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/FindSIMDe.cmake
-rw-r--r-- root/root      5414 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/Findcppcheck.cmake
-rw-r--r-- root/root       266 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/Findcppcheck.cpp
-rw-r--r-- root/root      5687 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/GetGitRevisionDescription.cmake
-rw-r--r-- root/root      1202 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/GetGitRevisionDescription.cmake.in
-rw-r--r-- root/root      4166 2024-11-14 10:17 ./usr/lib/cmake/OpenMS/Modules/SelectLibraryConfigurations.cmake
-rw-r--r-- root/root      4808 2024-11-13 12:19 ./usr/lib/cmake/OpenMS/OpenMSConfig.cmake
-rw-r--r-- root/root      3675 2024-11-13 12:19 ./usr/lib/cmake/OpenMS/OpenMSConfigVersion.cmake
-rw-r--r-- root/root      1720 2024-11-07 17:14 ./usr/lib/cmake/OpenMS/OpenMSTargets-release.cmake
-rw-r--r-- root/root      5344 2024-11-14 10:57 ./usr/lib/cmake/OpenMS/OpenMSTargets.cmake

I'll defer to y'all as to whether that's appropriate or not, but since we are not including source in the package (we do include the headers, I'd figured they weren't especially useful.

**Comment by jpfeuffer** [comment]
Yes, all of them are needed

**Comment by poshul** [comment]
> Yes, all of them are needed

Okay, good, then I think just moving when we exclude the system libs should solve the issue. I'm running all the package CI building to make sure I didn't break any of the other build types, is there anything else I should check?

**Comment by jpfeuffer** [comment]
KNIME package might be good to check specifically but I think we do not make use of any step involved in "CMake packaging"

**Comment by poshul** [comment]
I just checked the Linux knime package with this build and it looks good.

**Pull request merged**
