### PR TITLE
problematic example for Simpson rule added to PeakIntegrator class test

### PR DESCRIPTION
**Pull request by lars20070**
Example from https://github.com/OpenMS/OpenMS/issues/3845 added to `PeakIntegrator()` class test.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/issues/3845

**Comment by hroest** [comment]
can you add documentation to the class about this behaviour?

**Comment by pasqoo** [comment]
@lars20070 Nice comment.
Using the doxygen's command `@warning` or `@note` might be beneficial in this case, so that this would be easily noticed in the generated web page.

**Comment by lars20070** [comment]
@pasqoo Agreed. doxygen trumps Latin in the 21st century.

**Comment by lars20070** [comment]
Merge?

**Comment by timosachsenberg** [comment]
can you merge against develop and push

**Comment by lars20070** [comment]
Merge?

**Pull request merged**
