### PR TITLE
Refactoring of mass shift generation in FeatureFinderMultiplex

### PR DESCRIPTION
**Pull request by lars20070**
Isotopic labelling introduces mass shifts between peptide features. Before peptide feature multiplets can be detected, a complete list of all possible mass shifts needs to be constructed. This pull request moves this functionality from `FeatureFinderMultiplex.cpp` to two new classes.

`MultiplexMassPattern` is a data structure for a single mass shift pattern (the equivalent of `MultiplexPeakPattern`for m/z shift patterns). `MultiplexMassPatternList` contains the functionality for the construction of the complete list.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@lars20070 I think the names could be a bit more descriptive.
MultiplexMassPattern and MultiplexPeakPattern could possible be renamed.
maybe something like: MultiplexDeltaMasses and MultiplexIsotopicPeakPositions/MultiplexIsotopicPeakPattern?

**Comment by lars20070** [comment]
How about `IsotopicLabellingDeltaMz`, `IsotopicLabellingDeltaMasses` and `IsotopicLabellingDeltaMassesGenerator`?`

**Comment by timosachsenberg** [comment]
Please correct me if I misunderstood how you use the terms *Mass and *PeakPattern: 
I think you use the term *Mass in your naming convention for shifts between different labelling states and *PeakPattern for the set of mass shifts describing the isotopic peaks.
This is misleading in my view and I would choose a name that allows to better distinguish these different sets of mass (or m/z) shifts. Choosing *DeltaMz and *DeltaMasses does't help here as it would just suggest that both are basically the same (except that one is in Da and the other in Th).

**Comment by lars20070** [comment]
It's best explained with an example. Light and heavy arginine [Arg0, Arg10] give rise to a mass shift pattern [0Da, 10Da], i.e. `IsotopicLabellingMassShifts`. Let's consider only charge states 1+, 2+ and 3+. Then this single mass shift pattern results in three m/z shift patterns, i.e. `IsotopicLabellingMzShifts`.

[0Th, 1Th, 2Th, 10Th, 11Th, 12Th]
[0Th, 0.5Th, 1Th, 5Th, 5.5Th, 6Th]
[0Th, 0.33Th, 0.66Th, 3.33Th, 3.66Th, 4Th]

`IsotopicLabellingMassShifts` and `IsotopicLabellingMzShifts` are representations of the same [Arg0, Arg10] pair in mass and m/z space respectively. The m/z peak pattern describes the complete multiplet, not a single peptide.

**Comment by timosachsenberg** [comment]
That is how I understood it. You may keep it as is if you think your abstraction is more natural. For me it seems just a bit more natural to talk about delta masses (as in modification delta mass) and isotopic patterns instead of mass shifts and mz shifts. Probably because these are quite common terms in mass spec and used in similar contexts.

**Comment by lars20070** [comment]
Ok, I see your point. Let's use `MultiplexDeltaMasses`, `MultiplexDeltaMassesGenerator` and `MultiplexIsotopicPeakPattern`.

**Comment by timosachsenberg** [comment]
Providing a class with restricted access is certainly no mistake but I wonder if:
```
// your documentation
typdef std::vector<double> MultiPlexDeltaMasses;
```
would be sufficient?

**Comment by lars20070** [comment]
The refactoring is in preparation of a `MultiplexResolver` #1441 pull request. I might put more functionality in the class later on.

**Comment by timosachsenberg** [comment]
ok that's fine.

**Comment by lars20070** [comment]
@timosachsenberg I am now extending `MultiplexDeltaMasses` as mentioned earlier. `double` in [1] will become `pair<double, multiset<Modification>>`. For example, a +26 Da mass shift is the result of [Lys8, Lys8, Arg10]. Just want to let you know, before I make the changes.

[1] https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexDeltaMasses.h#L92

**Comment by timosachsenberg** [comment]
Why not use a multimap straight ahead?

**Comment by timosachsenberg** [comment]
concerning speed I would rethink if this is required here.
What you are proposing is useful to map back to the modifications but for spectrum processing the vector of double is much better.

**Comment by lars20070** [comment]
Good idea. So `vector<double>` is replaced by `multiset<double, Modification>`.

I want to test the equality of `multiset<Modification>` objects. For example, [Lys8, Lys8, Arg10]==[Lys8, Arg10]? In my setup, the multisets do not need to be constructed on the fly.

**Comment by timosachsenberg** [comment]
do you want to give a quick phone call?

**Comment by lars20070** [comment]
As discussed on the phone, `vector<double>` would be replaced by `vector<pair<double, multiset<String>>>`.

**Comment by hroest** [comment]
@lars20070 @timosachsenberg I am not so much in favor of complex constructs such as `vector<pair<double, multiset<String>>>` for multiple reasons
- readability: it is very hard to see what is going on here 
- wrapper: the Python wrapper has a hard time to deal with those constructs

I would thus often prefer to have a small struct that contains the data, e.g. 
```
struct DataHolder
{
double val1;
multiset<String> val2;
}
```

this would allow then to access things by a real name instead of simply a `first` and `second`

**Comment by timosachsenberg** [comment]
fine with me if you find a better name ;)

**Comment by hroest** [comment]
@timosachsenberg maybe Lars is the best to suggest a descriptive name?

**Comment by timosachsenberg** [comment]
@hroest good point

**Comment by lars20070** [comment]
Agreed. Thanks @hroest. I will include this in the upcoming PR.

**Pull request merged**
