### PR TITLE
IDFilter reports empty results

### PR DESCRIPTION
**Pull request by cbielow**
if used as filter for uniqueness without the input having been run through 'PeptideIndexer'.
All you get is:
IDFilter: Warning, filtering with 'unique_per_protein' can only be done after indexing the file with 'PeptideIndexer' first.
This can be easily overlooked.

Elevated warning to Error.

@lars20070 : can you check if this fixes your issue?

### CODE REVIEW

**Comment by cbielow** [comment]
I consider this a defect, since the user explicitly asks for a uniqueness filter, but he won;t get one. Instead he's going to wonder why his result is empty.

**Comment by lars20070** [comment]
Thanks @cbielow. I did run PeptideIndexer with missing_decoy_action = warning (since the already FDR filtered pepXML does not contain decoys.) But the PeptideIndexer fails, as with missing_decoy_action = error. - Another bug or do I misinterpret missing_decoy_action?

**Comment by cbielow** [comment]
since this is another can of worms, lets take it offline.
Pls send me an  email with the pipeline and the fasta.

Am 2/16/2015 um 1:04 PM schrieb Lars Nilse:

**Comment by lars20070** [comment]
+1 for the elevation of warning to error

**Pull request merged**
