### PR TITLE
Feature/fix comet

### LINKED ISSUE #3081: Comet(Adapter) not working properly with mzML
I have an issue that may or may not be related to the CometAdapter, but the consequence is that comet searches wont work in my case on Linux. When I search with comet.exe, it skips all the spectra (see `Warning - no spectra searched.`):

```
$ /home/hr/openmsall/builds/openms_git/bin/CometAdapter  -in testout.mzML -database small.fasta -out test.idXML
File '/home/hr/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in '/home/hr/.OpenMS/OpenMS.ini' with defaults!
Progress of 'loading spectra list':
-- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
("-P/tmp/20171207_160648_hr-Precision-5520_2264_1/param.txt", "-N/tmp/20171207_160648_hr-Precision-5520_2264_1/result", "testout.mzML") 
 Comet version "2016.01 rev. 3"

 Search start:  12/07/2017, 04:06:48 PM
 - Input file: testout.mzML
   - Load spectra: Warning - no spectra searched.

 Search end:    12/07/2017, 04:06:48 PM

<File '/home/hr/.OpenMS/OpenMS.ini' is deprecated.> occurred 2 times
Set debug level to >=2 to keep the temporary files at '/tmp/20171207_160648_hr-Precision-5520_2264_1/'
CometAdapter took 0.08 s (wall), 0.07 s (CPU), 0.00 s (system), 0.07 s (user).
<Updating missing/wrong entries in '/home/hr/.OpenMS/OpenMS.ini' with defaults!> occurred 2 times
```

this is reproducible by just calling comet.exe itself:

```
$ /home/hr/openmsall/source/THIRDPARTY/Linux/64bit//comet.exe -Pcomet.params testout.mzML 
 Comet version "2016.01 rev. 3"

 Search start:  12/07/2017, 04:07:58 PM
 - Input file: testout.mzML
   - Load spectra: Warning - no spectra searched.

 Search end:    12/07/2017, 04:07:58 PM
```

however it all works fine when I first convert the data to mzXML:

```
$ /home/hr/openmsall/builds/openms_git/bin/FileConverter -in testout.mzML -out testout.mzXML
File '/home/hr/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in '/home/hr/.OpenMS/OpenMS.ini' with defaults!
Progress of 'loading spectra list':
-- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
Progress of 'storing mzXML file':
-- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
FileConverter took 0.09 s (wall), 0.08 s (CPU), 0.00 s (system), 0.08 s (user).
hr@hr-Precision-5520:/media/doc/project_data/Spyo/analysis$ /home/hr/openmsall/source/THIRDPARTY/Linux/64bit//comet.exe -Pcomet.params testout.mzXML 
 Comet version "2016.01 rev. 3"

 Search start:  12/07/2017, 04:08:25 PM
 - Input file: testout.mzXML
   - Load spectra: 2
     - Search progress: 100%
     - Post analysis:  done
 Search end:    12/07/2017, 04:08:25 PM
```

all data is available at https://www.dropbox.com/s/ad4q73rz2narxqj/comet_problem.tar.gz?dl=0 as comet_problem.tar.gz

### PR DESCRIPTION
**Pull request by hroest**
fixes #3081 by adding certain optional elements into the mzML that comet expects.

@timosachsenberg I guess that is too late for the 2.3 release? it will create some problems as comet basically can crash on mzML files generated by OpenMS

### CODE REVIEW

**Comment by jpfeuffer** [comment]
@hroest I think it is not too late for the release.
@timosachsenberg can you cherry pick this and my docu PR (after you double-checked it) to the release branch and do a direct push or PR? I will then check the results of the resulting build.

**Comment by timosachsenberg** [comment]
yes, can do.

**Comment by hroest** [comment]
@cbielow  @timosachsenberg @jpfeuffer this raises the question whether some of  our optimizations may be a bit too aggressive and we should write out larger mzML files again that are conforming to what other tools expect. We dont want to be in a situation where our mzML files break other tools (even though they are technically valid)

**Comment by hroest** [comment]
see #2458 where this change was introduced

**Pull request merged**
