### PR TITLE
[Update] sirius 4.0.1 build 9

### PR DESCRIPTION
**Pull request by oliveralka**
Update SIRIUS version to 4.0.1 (build 3) to build 9

Fix changing tests.
Scores and fragment annotation. 

Related to https://github.com/OpenMS/THIRDPARTY/pull/52

### CODE REVIEW

**Comment by oliveralka** [comment]
@jpfeuffer This is my current THIRDPARTY branch - I am not sure about the percolator - was THIRDPARTY not updated in OpenMS/OpenMS? 

If the tests work, we can merge THIRDPARTY and I can add the current OpenMS/THIRDPARTY for merging.

**Comment by jpfeuffer** [comment]
Yes the percolator update was just merged yesterday with timos PR. Doesnt matter, you have to update the PR here anyway before merging. This way you can test your executable before merging it in THIRDPARTY.
Links to https://github.com/OpenMS/THIRDPARTY/pull/52

**Comment by jpfeuffer** [comment]
rebuild jenkins

**Comment by oliveralka** [comment]
rebuild jenkins

**Comment by jpfeuffer** [comment]
Ok the THIRDPARTY PR is merged, please update the THIRDPARTY submodule here to point to the current head of THIRDPARTY master.

**Comment by jpfeuffer** [comment]
superseded by #4143

**Pull request closed without merging**
