### PR TITLE
Do not overwrite OPENMS_DATA_PATH in PyOpenMS if it is already set

### PR DESCRIPTION
**Pull request by radusuciu**
# Description

I've got a lot of customizations (mostly to `unimod.xml` ) that I've set in a new directory that is referenced by `OPENMS_DATA_PATH` but PyOpenMS clobbers that on initialization. This simple modification should prevent it from doing so, if there is a path already set.

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@jpfeuffer looks reasonable. We often have both OpenMS and pyOpenMS installed so if versions differ this might lead to problems. E.g., new OpenMS version with Elements.xml removed and old version of pyOpenMS that expects the file to exist in share. Do you think we need to cover that case?

**Comment by jpfeuffer** [comment]
Hmm yes, I am not sure. Maybe we should print an info message that the path is set from outside and will be used?

**Comment by timosachsenberg** [comment]
I agree. Outputting a warning like:
"Warning: OPENMS_DATA_PATH environment variable already exists. pyOpenMS will use it ('" + path + "') to locate data in the OpenMS share folder (e.g., the unimod database)." 
Would suffice @radusuciu can you add this?

**Comment by radusuciu** [comment]
That sounds very reasonable, apologies for the accidental merge commit - I didn't mean to push when I did. I have a slight edit to make to make the line length more reasonable if that's okay with you.

**Comment by radusuciu** [comment]
Regardless of whether or not you accept my stylistic change, thank you very much for being open to this small contribution! This makes my life just a littttle bit easier :)

**Comment by radusuciu** [comment]
An alternative that I just thought about would be to have a different environment variable that is specific to eg. `PYOPENMS_DATA_PATH` or similar.

```python
default_openms_data_path = os.path.join(here, "share/OpenMS")
pyopenms_openms_data_path = os.environ.get("PYOPENMS_DATA_PATH")

os.environ["OPENMS_DATA_PATH"] = pyopenms_openms_data_path or default_openms_data_path 
```

or

```python
default_openms_data_path = os.path.join(here, "share/OpenMS")
os.environ["OPENMS_DATA_PATH"] = os.environ.get("PYOPENMS_DATA_PATH", default_openms_data_path)
```

This probably wouldn't necessitate a warning, just some documentation about `PYOPENMS_DATA_PATH`.

**Comment by timosachsenberg** [comment]
Nice. Thanks for the cleanup. From my side this PR is good to go!

**Review by oliveralka — APPROVED** [review]
Looks good!

**Pull request merged**
