### PR TITLE
[Fix] Add links for new tools to TOPP/Utils docu

### PR DESCRIPTION
**Pull request by jpfeuffer**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Sorry but I can't get rid of this MSP file introduced in #2973. On Mac they are treated as the same file.

**Comment by jpfeuffer** [comment]
Okay I deleted the msp file on GitHub since I think it is the old one. Let's see if it fixes the error.

**Comment by jpfeuffer** [comment]
Ok Windows and Linux pass. Let's test the nightlies.

**Comment by jpfeuffer** [comment]
Merged docu part to release/2.3.0 too

**Comment by lars20070** [comment]
Thanks @jpfeuffer.

**Pull request merged**
