### PR TITLE
[FIX] Fix/id filter blacklist

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
fixes https://github.com/OpenMS/OpenMS/issues/1236

**Comment by cbielow** [comment]
+1

**Comment by cbielow** [comment]
Test failed due to new parameter annotate_ids_with_subelements' ...

http://cdash.openms.de/viewTest.php?onlyfailed&buildid=119893

**Comment by cbielow** [comment]
it only fails on systems which have 'if(WITH_GUI)' during TOPP tests... (at least it should) :)

**Comment by lars20070** [comment]
My #1219 is the culprit. But so far I do not see what needs to be changed.

**Pull request merged**
