### PR TITLE
Writting Spectrum Reference in NovorAdapter

### PR DESCRIPTION
**Pull request by Waschi97**
NovorAdapter used to just write the scan number as a MetaValue.
Using `SpectrumLookup()` now the spectrum reference is written.

### CODE REVIEW

**Review by timosachsenberg — APPROVED** [review]
nice! thanks

**Comment by cbielow** [comment]
wait :)

**Comment by cbielow** [comment]
the current solution loads the whole MSExperiment including data. should be restricted to level2 and without the actual peaks.

**Comment by timosachsenberg** [comment]
Ah right that will make some difference.

**Review by Leon-Bichmann — APPROVED** [review]

**Pull request merged**
