### PR TITLE
[PARAM] disable SN estimation by default, pick only MS1 by default

### PR DESCRIPTION
**Pull request by timosachsenberg**
addresses the parameter issues in https://github.com/OpenMS/OpenMS/issues/2459

### CODE REVIEW

**Comment by mwalzer** [comment]
:+1: 
The corresponding tool's documentation seems to be double on its own page ([even before your changes](http://ftp.math.fu-berlin.de/pub/OpenMS/release-documentation/html/TOPP_PeakPickerHiRes.html)). Can you have a quick look?

**Comment by timosachsenberg** [comment]
good point. Maybe I am blind but I don't see any double include. @jpfeuffer any idea?

**Comment by jpfeuffer** [comment]
It's because the Lowmem version has the same name I guess.
https://github.com/OpenMS/OpenMS/blob/36ccb5c6d443b4ec59b18a6c1cc315e29b516b9c/src/utils/LowMemPeakPickerHiRes.cpp

**Comment by timosachsenberg** [comment]
Ahh I see. I'll but it on a separate entry

**Comment by timosachsenberg** [comment]
ok I added the fix. Let's merge and see if it solves the problem

**Pull request merged**
