### PR TITLE
NumberOfJobs in quickbuild script & add "build" folders to gitignore 

### PR DESCRIPTION
**Pull request by oliveralka**
NumberOfJobs in quickbuild script. 
Add "build" folders to gitignore.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@jpfeuffer will querying the number of jobs interfere with CI?

**Comment by jpfeuffer** [comment]
Hmm I guess this breaks builds within scripts. We do not use the quickbuild script for CI though.
Maybe it is better as a command line parameter when calling the script?

**Comment by oliveralka** [comment]
Ok, my thoughts were that it would be more user friendly this way - since it asks how many jobs you want to use.

**Comment by timosachsenberg** [comment]
@hroest you initiated the idea of the quickbuild script. What is your take on this?

**Comment by timosachsenberg** [comment]
I think both makes sense. e.g., QT has kind of a quick build script that shows a license text the user has to accept

**Comment by hroest** [comment]
well but qt also allows you to skip this with specific commandline options. I think it would be more useful to allow both, e.g. to either use an env-variable or the first argument as the number of jobs and when empty then simply use 1 job. I think it is useful to have the quickbuild script being able to build OpenMS automatically, e.g. in docker containers and such.

**Comment by oliveralka** [comment]
Is the new commit more like it? (test ran into time limit)

**Comment by hroest** [comment]
yes that is what I had in mind

:+1: for merge

**Pull request merged**
