### PR TITLE
Read swath window file with no header

### PR DESCRIPTION
**Pull request by jcharkow**
In response to https://github.com/OpenMS/OpenMS/issues/6055 allow
openSwath to be able to read window files with no header.

# Description

Please include a summary of the change and which issue is fixed.

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

**Comment by timosachsenberg** [comment]
let's try again to apply format changes:
\reformat
last time we got a
```
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push https://github.com/jcharkow/OpenMS.git HEAD:develop

To push to the branch of the same name on the remote, use

    git push https://github.com/jcharkow/OpenMS.git HEAD
```

**Comment by jpfeuffer** [comment]
hub checkout pr checks out the head of the PR into jcharkow-develop.
In the commit action you need to push to the origin branch of the PR. Or checkout the origin branch of the PR in the beginning already instead.

**Comment by jpfeuffer** [comment]
Ok, no actually it should work to push to whatever `hub checkout pr` checks out. The problem is that the fork uses the same branch name:
https://github.com/github/hub/issues/2467

**Comment by timosachsenberg** [comment]
ah good find. ok so we should encourage having a distinct local branch and not open PRs from local develop

**Comment by jcharkow** [comment]
should I re-open this with a new branch with a different name?

**Comment by jcharkow** [comment]
Closing this as reoppned in https://github.com/OpenMS/OpenMS/pull/6077

**Pull request closed without merging**
