### PR TITLE
remove OS X specific code for opening folders

### PR DESCRIPTION
**Pull request by lars20070**
This pull request removes OS X specific code for opening folders. It resolves the TOPPAS issue #1299.

### CODE REVIEW

**Comment by aiche** [comment]
can you check that this works also in older versions of OS X. back then we used this hack since `QDesktopServices` didn't work properly on OS X

**Comment by lars20070** [comment]
Not easily @aiche.

I guess older OS X versions require your hack. Can we detect not just the OS, but specific versions of OS X?

**Comment by cbielow** [comment]
is it OSX or maybe the version of Qt?

**Comment by timosachsenberg** [comment]
Hi @hannesveit can you test this branch on your installation?

**Comment by jpfeuffer** [comment]
Works for me now! MacOS X 10.10.2

**Comment by hannesveit** [comment]
Also works for me on 10.8.5 @timosachsenberg

**Comment by timosachsenberg** [comment]
Due to a lack of  explanation about the source of the original error I think we should include it and test it on different systems. Maybe it was qt / mac related  and got fixed in one of the updates in between.
Any objections?

**Comment by cbielow** [comment]
the first fix by Stephan was
https://github.com/OpenMS/OpenMS/commit/b48c4a875f190bad126cd346b8b0e48dcb0b0e0b
on March 2013.
This should have been at most OS X 10.8 Mountain Lion.

The version of Qt is more difficult. Maybe @Aiche remembers?
4.8 was out back then. But also for Mac?

**Comment by timosachsenberg** [comment]
Branch also works on 10.9 Maverick

**Comment by timosachsenberg** [comment]
I would suggest we merge it and turn it from definitely broken to possibly broken.

**Comment by lars20070** [comment]
+1

**Pull request merged**
