### PR TITLE
[TEST] adapted PScore test

### PR DESCRIPTION
**Pull request by timosachsenberg**
fixed https://github.com/OpenMS/OpenMS/issues/2633

### CODE REVIEW

**Comment by enetz** [comment]
+1

**Comment by enetz** [comment]
Maybe add a test with using the TSG for a theoretical spectrum? Then further changes there affecting this score will be caught by the test next time.

**Comment by timosachsenberg** [comment]
ok I added a test.

**Comment by enetz** [comment]
thanks, this should do it

**Comment by enetz** [comment]
@timosachsenberg this should also be merged into the develop branch

**Comment by hroest** [comment]
@enetz after the release we will merge all changes from the master into the develop...

**Pull request merged**
