### PR TITLE
Update PSMFeatureExtractor.cpp

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by Leon-Bichmann** [comment]
Now Im getting this error again:
Error: Unexpected internal error (Could not convert string 'ollerType=0controllerNumber=1scan=3' to an integer value)

**Comment by Leon-Bichmann** [comment]
In der PercolatorAdapte

**Comment by timosachsenberg** [comment]
sounds familiar. can you link to a past issue?

**Comment by Leon-Bichmann** [comment]
I think it was this one:
https://github.com/Leon-Bichmann/OpenMS/pull/4/commits/5f1ebf5977eb131c68698dfe342cef1759226176

**Pull request merged**
