### PR TITLE
[FEATURE] Support of new percolator parameter

### PR DESCRIPTION
**Pull request by grosenberger**
This PR enables support for a new Percolator hyperparameter to restrict training to the best scoring PSMs.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Hi @grosenberger +1 for this addition. We recently had some confusion in KNIME with the mutually exclusive output parameters. Since I think there is not sensible solution, could you add a warning when both types of output files are given?
E.g. "you can't have both outputs. please deactivate one. In KNIME go to the OutputTypes tab and set one to Inactive"

**Comment by grosenberger** [comment]
Good point. I added a patch for this issue. A cleaner alternative might be to to merge all formats into single ``-in`` and ``-out`` parameters and then have also ``-in_type`` and ``-out_type`` parameters together with file ending detection. Will this result in any other problems? Else, I could also implement this solution if preferred.

**Comment by jpfeuffer** [comment]
Hm good idea. The only issue with that approach is that you could not have both mzid and idXML at the same time anymore. And the user still has to go to the OutputTypes because we do not have an automatic association with the parameters and the creation of an appropriate output file name ending. So, I would say almost equal.

**Comment by jpfeuffer** [comment]
I thought about it a bit. What about using one output and let the application choose the algorithm based on the file ending. Since there are restrictions on the file ending, the user can't choose an arbitrary one anyway. Maybe it is not perfectly represented in the ini then though.
@timosachsenberg any preference?

**Comment by timosachsenberg** [comment]
I think having one mandatory output is best and choosing the algorithm would work.
If algorithms diverge more in the future, we could also think about having two tools.

**Comment by jpfeuffer** [comment]
Cool. Default from extension plus overwrite param. +1

**Pull request merged**
