### PR TITLE
Update CHANGELOG

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by cbielow** [comment]
support for VS2019?

**Comment by timosachsenberg** [comment]
So we add now a note that we suggest to use VS 2019 on windows?

**Comment by cbielow** [comment]
> 
> 
> So we add now a note that we suggest to use VS 2019 on windows?

Its in the installation instructions already.. and VS2015 and 17 are fine if you dont use multiple threads... so its a bit tricky to explain in one sentence.

**Comment by cbielow** [comment]
mention
 - support for VS2019 and GCC 9.1 (#4211)
 - general speed improvements (loading/storing files, handling peptide sequences)
 - TMT16plex support for IsobaricAnalyzer (#4295)
 - extend MaxQuant-compatible mzXML support (via FileConverter) (#4432, #4423)
 - improved MsStats output support (#4181, #4207)
 - TOPPAS improvements (#4266, #4121, #4100)

**Comment by cbielow** [comment]
would it make sense to wait for the galaxy PRs, so we can add 'Galaxy support' to the list? @bernt-matthias

**Comment by bernt-matthias** [comment]
The PR is still for 2.4., but I'm happy to update it right away to 2.5. as soon as there is a conda package. The Galaxy tool release will always follow the OpenMS releases with some delay. I'm optimistic that we can keep this delay small from now since we autogenerate the tools. So I think it makes no sense to wait. 

If not in the release notes, it would be nice if the Galaxy support would be advertised better, e.g. if  here: https://www.openms.de/getting-started/creating-workflows/  a Galaxy instance would be linked that actually has OpenMS installed (https://usegalaxy.eu/). ping @bgruening

**Comment by timosachsenberg** [comment]
I will update the link on the OpenMS webpage

**Comment by bernt-matthias** [comment]
Btw. are there any new data types that I would need to implement in  Galaxy (https://github.com/galaxyproject/galaxy/pull/8109)

**Comment by bgruening** [comment]
We could probably link to usegalaxy.eu directly, this would also be nice for de.NBI I would guess.

**Comment by hroest** [comment]
I suggest to add

- OpenMS and pyOpenMS support for oligonucleotides
- OpenSWATH support for ion mobility extraction and scoring
- OpenSWATH support for metabolite assay library building through SIRIUS (and metabolite extraction and scoring)
- OpenSWATH support for PRM
- library support for HDF5
- support for hyperfine isotopic distributions (through IsoSpec)
- QC Workflow (all in the QC folder)
- json support 

currently we are at 

```
$ bash tools/scripts/git_showdiff.sh  Release2.4.0 develop
Usage: git_showdiff.sh REV1 REV2
 1419 files changed, 103381 insertions(+), 40109 deletions(-)
```

so about 63k new LOC (compared to 46.8 LOC for 2.4, 21k LOC for 2.3 and 24k LOC for 2.2 and 25k LOC for 2.1). However this also reflects that the previous 2.4 release is actually over a year ago and we are not really hitting our goal of 2 releases per year.

**Comment by hendrikweisser** [comment]
I think it's worth adding "Support for RNA mass spectrometry" under "General". It's quite a fundamental addition to the existing proteomics and metabolomics support. (I'm biased, of course.) ;-)

**Comment by timosachsenberg** [comment]
Thanks I will add those

**Comment by hendrikweisser** [comment]
And a minor addition to "Changed Tools":
"ImageCreator uses updated gradients and has gained RT and m/z filtering options" (see #4188)

**Comment by cbielow** [comment]
suggestion: the section where we list the change of parameters in the CHANGELOG is not that informative for most users and clutters the log IMHO.
Should we move this to a separate file (also for earlier years) and just reference the new file (`PARAMETER_CHANGES.log`)?

**Comment by jpfeuffer** [comment]
If you want to make changes, I suggest to do it soon. I'll change the target branch.

**Comment by jpfeuffer** [comment]
I need an uptodate changelog for the release candidate script. Any further updates should be made to the release branch.

**Pull request merged**
