### PR TITLE
TextExporter output filetype(s)

### PR DESCRIPTION
**Pull request by RobertDeibel**
# Description

- Replaced `seperator` option in `TextExporter` with `out_type`. 
- Seperator set implicitly by `out_type` option
- Adjusted .ini files of tests
- added more valid formats to `out` option  
Resolves issue #4734

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

Note: If your PR is failing you can check out http://cdash.openms.de/index.php?project=OpenMS and look for your PR with detailed error messages.

### CODE REVIEW

**Comment by RobertDeibel** [comment]
Some remarks:  
There are only two seperators here. Either `\t` of `,` which is more limiting than before.  

I adjusted the `.ini` files of the tests but it seems that these are generated automatically. I generated a .ini (localy; see [test.ini.txt](https://github.com/OpenMS/OpenMS/files/5754920/test.ini.txt)) but I'm unsure if the others should just be replaced or if this is  done in some other place. 

Does the `out_type` option have to be exposed somehow? The linked issue #4734 talks about tools requiring an out_type how would this be passed?

Lastly maybe using both `seperator` and `out_type` would be an option? Making them mutually exclusive could be an option.

**Comment by jpfeuffer** [comment]
Looks good. If the tests run, the inis were adapted correctly. I don't think they are autogenerated in this case.
If "txt" does not make a difference in the format, leave it out and remove it.

**Comment by timosachsenberg** [comment]
If we specify -out "test.csv" but do not set out_type it will fall back to tsv, right?
Could this be surprising?
Maybe we make out_type optional and if it is not given determine it from the extension of the output file?

**Comment by RobertDeibel** [comment]
Yes, you're right @timosachsenberg and I think this could be surprising. Especially for those not using out_type.
I'll apply the suggested code review and your suggestion.

**Comment by RobertDeibel** [comment]
I'm unsure how to implement your suggestion @timosachsenberg. While it is possible to get the file extension I'm not sure how one would set the out_type parameter programmatically. 
As I see it, most functions of `TOPPBase` return `const` values when referring to parameters and those that do not are `private`.
Any suggestions?

**Comment by jpfeuffer** [comment]
Not sure I understand the question but I would do the following to address @timosachsenberg s comment:
```
if out_type.empty()
 out_type = file.getExtension()
else
 if out_type != file.getExtension
   throw Error or Warn

getSeparatorFromOuttypeLogic(out_type)
```

I don't see a reason to retroactively set the tool's out_type parameter when all you need is the variable in the code. Or what did you have in mind?

**Comment by RobertDeibel** [comment]
Yep you understood correctly. It just seemed me that it was intended by issue #4734, to have out_type always defined. 

But if your solution is the preferred way then everything is clear.

**Comment by hendrikweisser** [comment]
Thanks for tackling this, @RobertDeibel.
There are a number of TOPP tools that allow different output types. Usually this is handled by trying to determine the type from "out" first, with "out_type" being optional. See FileConverter for example:
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FileConverter.cpp#L342
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FileConverter.cpp#L412-L425

One could argue whether "out_type" shouldn't take precedence over "out" if it's specified (like @jpfeuffer suggested above), but I don't think it matters much.

**Comment by timosachsenberg** [comment]
hi @RobertDeibel can you merge develop into your branch and add me as a collaborator? I might add something to the PR.

**Comment by RobertDeibel** [comment]
> hi @RobertDeibel can you merge develop into your branch and add me as a collaborator? I might add something to the PR.

just merged `develop` and as a maintainer you should already have access to this branch.
Add a comment if that is not the case.

**Comment by cbielow** [comment]
caused a CI regression.
Fixed in https://github.com/OpenMS/OpenMS/pull/5176

**Pull request merged**
