### PR TITLE
[BUILD] Try to silence NPY Deprecated warnings in pyopenms

### PR DESCRIPTION
**Pull request by jpfeuffer**
see https://stackoverflow.com/questions/52749662
Might introduce new ones, so let's see.
Can be removed when we switch to Cython 3.

### CODE REVIEW

**Review by timosachsenberg — APPROVED** [review]

**Comment by jpfeuffer** [comment]
Seems to need additional changes. Not sure if worth it.
https://gitlab.kwant-project.org/kwant/kwant/-/merge_requests/251

**Comment by timosachsenberg** [comment]
maybe just switch to cython3 then?

**Comment by jpfeuffer** [comment]
Yes but we need to update all CI

**Comment by jpfeuffer** [comment]
Cython 3 does not have a stable release yet and is not picked up automatically by pip as the newest version.

**Comment by jpfeuffer** [comment]
We would still need that PR to silence the warning I think. Cython3 just makes it not fail.

**Comment by jpfeuffer** [comment]
This PR is actually not going to work with the CMake-based build that we have now. Closing.
We can remember the macros and add them once we use Cython3

**Pull request closed without merging**
