### PR TITLE
Feature/pyopenms further

### PR DESCRIPTION
**Pull request by hroest**
Improved pyopenms

- can wrap singletons (ResidueDB, ElementDB, etc)
- improves support for abstract base classes
- improves support for ISpectrumAccess (abstract base class)
- has code for wrapping of shared_ptr[ISpectrumAccess] (ptr to abstract base class as member) in SwathMap.pyx
- improves support for Isobaric quantification (also with abstract base classes)
- improves support for using pyopenms objects in Python dict and hashes
- adds tests

Work in Progress [WIP] - _do not_ merge before a new autowrap is released with these PR included:
- depends on https://github.com/uweschmitt/autowrap/pull/49
- depends on https://github.com/uweschmitt/autowrap/pull/48

### CODE REVIEW

**Comment by timosachsenberg** [comment]
wow - nice addition!

**Comment by hroest** [comment]
yes, a lot of work and some simplification on the pyOpenMS side due to changes in autowrap. Having singletons is really a bit of a pain but it does work now. There are still quite  a few things we cannot really map at the moment but they have a lot to do with OpenMS as well (e.g. people constructing crazy things using multiple nested sets/vectors/pair) which I think we should fix in OpenMS anyways: rather have a small struct with a clear description of the parameters than a `std::vector<std::pair<String, double> >` where you have no idea what you are supposed to pass as arguments...

**Comment by hroest** [comment]
we can merge as soon as we have updated autowrap: https://github.com/OpenMS/OpenMS/issues/2104

**Comment by hroest** [comment]
the configuration with CMake will not fail if the autowrap version is too low

**Comment by timosachsenberg** [comment]
autowrap is now up to date

**Comment by hroest** [comment]
after fixes, it all looks good on my side so we would be ready to merge.

As this is pyOpenMS only I suggest to merge it for 2.1

**Comment by timosachsenberg** [comment]
ok can you open the same PR against master?

**Pull request merged**
