### PR TITLE
make FFID and map alignment more robust to missing IDs

### PR DESCRIPTION
**Pull request by timosachsenberg**
## Description

Changed some tools to not fail/throw, but just issue a warning.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Sorry to ask, but could you quickly check the single file behaviour of PLFQ as well?
There was an issue on Discord.

**Comment by jpfeuffer** [comment]
On the one hand I really like that you are testing everything corner case, on the other hand the PLFQ tests are already dominating the runtime of the whole test suite with multiple minutes per run on slower computers. Not sure what to do here.

**Comment by timosachsenberg** [comment]
I know... but in this case I think there is no good alternative. IMHO we are currently not really testing corner cases but features (and regressions) of pLFQ.

**Comment by jpfeuffer** [comment]
Maybe for some parts class tests would b enough. E.g. extract the exp design that you know, works and make sure that the constructor in the class test produces this.

**Comment by timosachsenberg** [comment]
tests pass now. ready for review.
no design mode also fixed

**Comment by timosachsenberg** [comment]
I checked... in my ASAN build the _3 test takes 10 times as long as the ones I added. So maybe not worth optimizing them now.

**Review by jpfeuffer — COMMENTED** [review]
+1

**Pull request merged**
