### PR TITLE
enable c11 support

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Anyone knows why MSGF+ would fail? Was there a change in CVs?
```
in1:  /home/travis/build/OpenMS/OpenMS/_build/src/tests/topp/MSGFPlusAdapter_1_out2.tmp.mzid   (line: 106, position/column: 61/62)
        <cvParam cvRef="PSI-MS" accession="MS:1000777" name="!
                                                             spectrum identifier nativeID format"/>

in2:  /home/travis/build/OpenMS/OpenMS/src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.mzid   (line: 106, position/column: 61/62)
        <cvParam cvRef="PSI-MS" accession="MS:1000768" name="!
                                                             Thermo nativeID format"/>
```

**Comment by jpfeuffer** [comment]
Ah sorry wrong PR.

**Comment by jpfeuffer** [comment]
Win CI will start once there is a slot ready.

**Comment by timosachsenberg** [comment]
@jpfeuffer nearly passes on all platforms but fails with http://cdash.openms.de/viewBuildError.php?buildid=229450

**Comment by timosachsenberg** [comment]
can we disable the -Wc++98-compat warning?

**Comment by jpfeuffer** [comment]
Is it built with warning=error or why does it trigger an error?
But yes we could. In theory we do not want to write c98 compatible code anyway anymore right?

**Comment by timosachsenberg** [comment]
I mean its not bad to write c98 code but it should definitely not trigger an error if c98 incompatible code is written ;)

**Comment by jpfeuffer** [comment]
Yes sure. IMO you can add it to compile definitions cmake to the clang compiler flags.
Do not forget to add the pedantic versions.

**Comment by timosachsenberg** [comment]
ok looks good. so let's see if windows ci chokes on this

**Comment by timosachsenberg** [comment]
windows seems to pass

**Comment by jpfeuffer** [comment]
Yep.. well I have to adapt the criteria for success a bit. But it builds and the same tests fail as without the flags :) And I need to link to CDash or increase the Jenkins backlog.

**Comment by enetz** [comment]
@timosachsenberg 
I am trying to compile OpenMS on a windows machine, but I am getting thousands of instances of the same error:
`'noexcept' : unknown override specifier`
with VS2013 x64, which does not support `noexcept`.
So do we no longer support VS2013? Or would it be possible to make workaround (if `noexcept` is the only issue) like the ones discussed here:
https://stackoverflow.com/questions/18387640/how-to-deal-with-noexcept-in-visual-studio

**Comment by timosachsenberg** [comment]
Sorry but I think we probably need to drop support for 2013. Introducing a workaround would only work for noexcept but we already have two lambdas in there.

**Comment by enetz** [comment]
Alright, no problem, just wanted to make sure I actually have to upgrade to VSE2015 (which should work, right?)

**Comment by jpfeuffer** [comment]
I guess 2013 is missing a bit more C++11 features, yes. VS2015 will work. Nightlies and CI is running on it. You could try 2017 ;)

**Comment by jpfeuffer** [comment]
#2693

**Pull request merged**
