### PR TITLE
Some tries to build pyopenms with language_level=3

### PR DESCRIPTION
**Pull request by jpfeuffer**
see #4921

### CODE REVIEW

**Comment by jpfeuffer** [comment]
TODO make the all_modules.py generation py-version independent. Seems to fail with py2 on travis etc.

**Comment by oliveralka** [comment]
Is it enough to remove the dot from the pyopenms import in all_modules.py for language independency? 
https://github.com/OpenMS/OpenMS/blob/4fff096878bbbf52172d8aebfb5aa82dad7cfdae/src/pyOpenMS/create_cpp_extension.py#L212

**Comment by jpfeuffer** [comment]
Maybe? 😄

**Review by poshul — COMMENTED** [review]
This looks good to me. What python versions have you tested it with?

**Comment by jpfeuffer** [comment]
So actually the problem was, that out "tests" did not test the actual import.
I now realized that it builds with the additional include_paths but fails during import because of the missing relative imports in autowrap I think.

**Comment by hroest** [comment]
I remember we had a similar discussion with @poshul a few months ago. First we have to fix this on the autowrap side and honestly we kind of gave up because we run into issues with relative imports:

- see https://github.com/uweschmitt/autowrap/pull/86
- see https://github.com/uweschmitt/autowrap/pull/82

this also had to do with the option `options.language_level = sys.version_info.major`

**Comment by jpfeuffer** [comment]
Hi @hroest regarding that:
See my PR that fixes your fix:  https://github.com/hroest/autowrap/pull/2
I am currently making it cross-platform quickly.

**Comment by jpfeuffer** [comment]
The upstream PR of autowrap was merged.

**Comment by jpfeuffer** [comment]
Hmm but the other pyopenms PR needs to be integrated here.

**Comment by jpfeuffer** [comment]
TODO: use newest contrib: on macOS https://abibuilder.informatik.uni-tuebingen.de/archive/openms/contrib/macOS/10.15.5/x64/appleclang-11.0.0/

**Comment by jpfeuffer** [comment]
Yaaay!

**Review by poshul — APPROVED** [review]
Looks good!

**Pull request merged**
