### PR TITLE
fix python bindings

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Please include a summary of the change and which issue is fixed.

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
pyopenms/pyopenms_6.cpp: In function 'PyObject* __pyx_pf_8pyopenms_10pyopenms_6_4__static_PrecursorCorrection_correctToHighestIntensityMS1Peak(PyObject*, __pyx_obj_8pyopenms_10pyopenms_4_MSExperiment*, double, PyObject*, PyObject*, PyObject*)':
pyopenms/pyopenms_6.cpp:21009:180: error: no matching function for call to 'OpenMS::PrecursorCorrection::correctToHighestIntensityMS1Peak(boost::shared_ptr<OpenMS::MSExperiment>::element_type&, double, bool, std::vector<double>&, std::vector<double>&)'
     __pyx_t_8 = OpenMS::PrecursorCorrection::correctToHighestIntensityMS1Peak((*__pyx_v_exp->inst.get()), ((double)__pyx_v_mz_tolerance), ((bool)__pyx_t_7), __pyx_v_v3, __pyx_v_v4);
                                                                                                                                                                                    ^
In file included from pyopenms/pyopenms_6.cpp:633:0:
/home/jenkins/ws/openms/PR/pyOMSDckr/OpenMS/src/openms/include/OpenMS/FILTERING/CALIBRATION/PrecursorCorrection.h:137:28: note: candidate: static std::set<long unsigned int> OpenMS::PrecursorCorrection::correctToHighestIntensityMS1Peak(OpenMS::MSExperiment&, double, bool, std::vector<double>&, std::vector<double>&, std::vector<double>&)
      static std::set<Size> correctToHighestIntensityMS1Peak(MSExperiment & exp,
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jenkins/ws/openms/PR/pyOMSDckr/OpenMS/src/openms/include/OpenMS/FILTERING/CALIBRATION/PrecursorCorrection.h:137:28: note:   candidate expects 6 arguments, 5 provided

**Comment by eeko-kon** [comment]
Hi @timosachsenberg, is this issue fixed? I am still getting the same error..

**Comment by timosachsenberg** [comment]
It should be fixed in the nightly conda  package of pyOpenMS. If not sorry this was a quick attempt to fix it and we will give it a proper look next week

**Comment by eeko-kon** [comment]
I have the nighly, so it is not fixed. No worries :)

**Comment by eeko-kon** [comment]
The issue is fixed- thank you!

**Pull request merged**
