### PR TITLE
[FIX] retain spectra_data information in ConsensusID

### PR DESCRIPTION
**Pull request by timosachsenberg**
may fix https://github.com/OpenMS/OpenMS/issues/1914

### CODE REVIEW

**Comment by lars20070** [comment]
Looks as if only `ConsensusID` tests need to be updated. - I will do this later today.

**Comment by hendrikweisser** [comment]
One thing that occurred to me in connection with this: If the peptide IDs are annotated with "spectrum_reference" information, that could be used to easily group corresponding IDs from different runs together, rather than clustering based on RT and m/z values.

**Comment by timosachsenberg** [comment]
Hi Hendrik. Yes I think this should be the preferred way.

**Comment by hendrikweisser** [comment]
@timosachsenberg: Okay, I've opened a ticket (https://github.com/OpenMS/OpenMS/issues/1934).

**Comment by lars20070** [comment]
Does not resolve #1914. `spectra_data` is stored in `<ProteinIdentification>`. But in the `ConsensusID` output `<ProteinIdentification>` is empty.
```
<ProteinIdentification score_type="" higher_score_better="true" significance_threshold="0" >
</ProteinIdentification>
```

**Comment by timosachsenberg** [comment]
Hi Lars, at the end of ConsensusID
````      
       // create new identification run
      setProteinIdentifications_(prot_ids);

      // store consensus
      IdXMLFile().store(out, prot_ids, pep_ids);
```
is called.
and setProteinIdentifications_ copies the spectra_data entries.
Can you check were the information is lost?

**Comment by lars20070** [comment]
`setProteinIdentifications_` sets a single empty protein identification run.
https://github.com/timosachsenberg/OpenMS/blob/fix/spectra_data_type/src/topp/ConsensusID.cpp#L198
Nothing is copied.

**Pull request merged**
