### PR TITLE
FeatureFinderIdentification runtime optimization

### PR DESCRIPTION
**Pull request by hendrikweisser**
Following discussion here: https://github.com/OpenMS/OpenMS/pull/2387#issuecomment-286886978
This pull request refactors FeatureFinderIdentification to extract chromatograms (and then detect/score chromatographic peaks) for all peptides together, rather than one by one. This can save several hours of runtime.
The results should be the same as before (except for ordering).

There's a small addition to `ChromatogramExtractor::prepare_coordinates` for convenient use of varying RT start/end points.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@hendrikweisser can you check why tests are failing?

**Comment by timosachsenberg** [comment]
I restarted the builds... let's see if this helps..

**Comment by hendrikweisser** [comment]
> can you check why tests are failing?

I'm on it. There's one test that consistently passes on my Mac, but fails on a Linux system. I'm looking into it.

**Comment by timosachsenberg** [comment]
+1

**Pull request merged**
