### PR TITLE
[FIX] added DefaultParmaHandler inheritance to MRMFeatureFilter.pxd

### PR DESCRIPTION
**Pull request by dmccloskey**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
please also fix: http://cdash.openms.de/viewBuildError.php?buildid=247423

**Comment by timosachsenberg** [comment]
looks good

**Comment by hroest** [comment]
@jpfeuffer it seems that it happened again, win not reporting errors: 

```
(ok)  openms_pr_windows_ci/compiler=msvc-15,os_label=win10_64 — merge run ended 
```

but not all tests passed:

```
All Failed Tests
Test Name
	
Duration
	
Age
 projectroot.src.tests.topp.TOPP_FeatureFinderIdentification_2_out1	0.21 sec	6
```

**Comment by jpfeuffer** [comment]
I just saw it, too. I wanted to set the number of allowed failures to 0 and tried to do that by removing the entry for a limit. Seems like this means unlimited. But I need an open PR to debug.

**Comment by hroest** [comment]
ok makes sense, lets try with a new PR

**Pull request merged**
