### PR TITLE
[FEATURE] [FIX] mass trace RT spacing

### PR DESCRIPTION
**Pull request by cbielow**
currently Mass trace intensity is basically the sum of all peaks in the mass trace multiplied by a constant (1 by default, i.e. the assumed average scan time).
However, this is highly inaccurate, especically if MS1 scans not not evenly spaced or missing.

Changed MassTrace area calculation from arbitrary and global scan distance to actual RT values (to account for unequal spacing due to MS2 or missing scans); fixed bug in ElutionPeakDetection which caused SG-Filter to crash;

Note that the ElutionPeakDetection-test now also finds again two chromatograms; this was increased to 6 after GSL-removal for some reason....

Minor fixes for constness, some typos etc...

### CODE REVIEW

**Comment by mwalzer** [comment]
:+1: 
@cbielow you have not attached a label. I would be in favour for RC1 due to the [FIX] characteristics

**Comment by cbielow** [comment]
I would not mind either way
On one hand, this is experimental, but the changes I made seem rather 
low-invasive and should provide a better quant.
But its tested on a small dataset only.
Maybe someone else can confirm that it works as expected?!
If not, we should consider this RC for a later bugfix release.


Am 2/22/2015 um 11:12 schrieb Mathias Walzer:

**Comment by timosachsenberg** [comment]
Maybe @Metabo can comment on it?

**Comment by timosachsenberg** [comment]
+1 though if you find time you could rename getScanTime to something more expressive (e.g. something like getAverageMS1CycleTime). Scan time is afaik also present as CV term with different meaning.

**Comment by timosachsenberg** [comment]
style an clang passed... others good stalled. I guess its fine but I will restart the CI

**Comment by timosachsenberg** [comment]
third passed this time so let's merge

**Comment by timosachsenberg** [comment]
http://cdash.openms.de/testDetails.php?test=23470101&build=123178

**Pull request merged**
