### PR TITLE
Rename Table/Tree widgets

### PR DESCRIPTION
**Pull request by cbielow**
# Description

renamed View tabs
 - SpectraIdentificationViewWidget --> SpectraIDViewTab
 - SpectraViewWidget --> SpectraTreeTab

### CODE REVIEW

**Comment by timosachsenberg** [comment]
feel free to merge if it passes

**Review by timosachsenberg — APPROVED** [review]

**Comment by timosachsenberg** [comment]
Should we call this ...Tab ? I know it is used there but in principle it should be independent of the container it is placed in

**Comment by cbielow** [comment]
> 
> 
> Should we call this ...Tab ? I know it is used there but in principle it should be independent of the container it is placed in

Assume it stands for tabular data, which is pretty close :)

**Comment by timosachsenberg** [comment]
hmm Q**Tab**Widget vs Q**Table**Widget
but yeah I already approved ;)

**Pull request merged**
