### PR TITLE
[FIX] Posterior Probability in PepXML for LuciphorAdapter

### PR DESCRIPTION
**Pull request by oliveralka**
LuciPhorAdapter (LuXor) needs the Posterior Probability / Phosphoprophet Probability for scoring. 
The score was not written in the PepXMLFile. This commit should fix the issue.

### CODE REVIEW

**Comment by oliveralka** [comment]
tests missing - will work on it

**Comment by hroest** [comment]
looks good :+1:

**Comment by timosachsenberg** [comment]
@grosenberger does the extra analysis results make sense to you? I think you also used it before.

**Comment by grosenberger** [comment]
Looks good. As far as I know LuciPHOr 2 only uses the ``probability`` attribute of the pepXML: https://github.com/dfermin/lucXor/blob/master/src/lucxor/PepXML.java

**Pull request merged**
