### PR TITLE
[Feature] PP-Wavelet's area computation should not depend on m/z spacing

### PR DESCRIPTION
**Pull request by cbielow**
- changed the area integration formula (the area changes in the 5th digit or so due to minor numerical differences)

- removed lots of dead code
- make central functions const (since this is OMP-active code, they rather should be).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
will this fix http://cdash.openms.de/viewTest.php?onlyfailed&buildid=120218 ?

**Comment by cbielow** [comment]
no.

But I also found that PPWavelet gives different results on the (small) class/TOPP test data from time to time.

 

I think it is connected to OMP – so one option is to revert to threads==1 for the tests and see if it solves the problem.

If yes, we need to find the concurrency problem when using threads.

**Comment by timosachsenberg** [comment]
can you resolve merge conflicts?

**Comment by cbielow** [comment]
resolved

**Pull request merged**
