### PR TITLE
[Fix]ed XTandem bug with multiply ocurring proteins.

### LINKED ISSUE #3594: xtandemAdapter reports incorrect protein evidance
Hello,

It seems like xtandemAdapter reports wrong proteins for peptides in idXML (OpenMS version 2.3.0). 

I have attached a very small example of XTandem xml file. The workflow is simply an IDConverter followed by TextExporter. 

It reports that peptide VPLRSILE is coming from sp|Q03517|SCG2_MOUSE and sp|Q99JA0|CALCA_MOUSE but it should report CALC_MOUSE and CALCA_MOUSE. 

In version 2.1.0 it works good. 

[test.zip](https://github.com/OpenMS/OpenMS/files/2166295/test.zip)

Best,
Payam

### PR DESCRIPTION
**Pull request by jpfeuffer**
fixes #3594

### CODE REVIEW

**Comment by timosachsenberg** [comment]
There seems to be a failing test on windows

**Comment by jpfeuffer** [comment]
Weird, I would have thought it only affects parsing and here it seems as the xtandem executable fails.

**Comment by jpfeuffer** [comment]
rebuild jenkins

**Comment by timosachsenberg** [comment]
failed test unrelated

**Pull request merged**
