### PR TITLE
Added ctdVersion required attribute to "tool" element

### PR DESCRIPTION
**Pull request by chahuistle**
See https://raw.githubusercontent.com/WorkflowConversion/CTDSchema/de6110d70afa912dc9aea15203f6d487d4b64037/CTD.xsd for the current CTD version.

### CODE REVIEW

**Comment by cbielow** [comment]
looks good to me
+1

**Comment by timosachsenberg** [comment]
looks good. @chahuistle did you check if this breaks anything on the OpenMS GKN side?

**Comment by timosachsenberg** [comment]
@jpfeuffer will this break anything on the GKN /KNIME side?

**Comment by jpfeuffer** [comment]
GKN was already updated by @chahuistle to Param v1.7.0, so I do not expect any problems.
I am surprised that there weren't any problems until now.
See https://github.com/genericworkflownodes/GenericKnimeNodes/commit/1862a3d5b553a2f6679877efb19c734badc094ad

**Pull request merged**
