### PR TITLE
fix: bug in AbsoluteQuantitation

### PR DESCRIPTION
**Pull request by dmccloskey**
# Description

Small fix in `AbsoluteQuantitation`

## Fixes
- change the term that the `dilution_factor` is applied to (i.e., changed to the correct term :))

### CODE REVIEW

**Comment by timosachsenberg** [comment]
look good. can you add a small regression test?

**Comment by dmccloskey** [comment]
Definitely.  Can you clarify what you mean by "regression test"?

**Comment by timosachsenberg** [comment]
A test that would fail without your fix and that now produces the correct result.
Probably just a few lines in https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/AbsoluteQuantitation_test.cpp

**Comment by dmccloskey** [comment]
Got it.  I will add that in shortly and ping you when it is ready.

**Comment by dmccloskey** [comment]
Just added.  A bit lazy on my part not adding them in to start with :).

**Review by timosachsenberg — APPROVED** [review]

**Pull request merged**
