### PR TITLE
more error information in DataValue exception

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Add slightly additional output as requested in https://github.com/OpenMS/OpenMS/issues/4833
Ideally, we could also output the meta value name that caused an exception.

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

**Comment by jpfeuffer** [comment]
What do you think about adding overloads like

int getMetaValue()
double getMetaValue()

to catch conversion errors together with the meta values names inside the MetaValueInterface class?
Otherwise, successful conversion always needs to be checked and handled by the developer.

**Comment by timosachsenberg** [comment]
I don't know if I understand correctly. What would be the difference to the e.g. (int)getMetaValue() which uses the conversion operator?

**Comment by jpfeuffer** [comment]
It is about catching the Exception and rethrowing with a clear error message including the name that was tried to be converted

**Comment by timosachsenberg** [comment]
Hmm not sure. Right now, it basically returns (something similar to) a variant that can also store units etc. This could make such an interface a bit complex. Maybe it would be good to get rid of the unit at some point here first.

**Comment by jpfeuffer** [comment]
I just mean that in those cases, where you know that you only need the internal value and you know that you want it to be a certain type, those overloaded functions could be used to provide a uniform way for error handling during those conversions.

**Comment by timosachsenberg** [comment]
but you can't overload only by return type

**Comment by jpfeuffer** [comment]
Hmm true, then we would need to change names.. I don't know, just an idea. It would also remove the need for toInt, toDouble, .. in pyopenms. Shifting the problem of course.

**Comment by timosachsenberg** [comment]
rebuild jenkins

**Comment by timosachsenberg** [comment]
will fix

**Comment by hroest** [comment]
It seems this currently only fixes the problem to tell us which type was tried to convert to which other type (and failed) but it may be helpful to also output the *value* that was tried to convert, eg instead of "failed to convert string to int" it may be helpful to have "failed to convert string 'foo' to int"?

**Comment by timosachsenberg** [comment]
Good point. I never planned to come up with a full solution to the issue ;) , but this could be easy to add and would help quite a bit.

**Comment by timosachsenberg** [comment]
added via https://github.com/OpenMS/OpenMS/pull/5856

**Pull request merged**
