### PR TITLE
[FIX, REFACTOR] SiriusAdapter 

### PR DESCRIPTION
**Pull request by oliveralka**
fix: 
Add number parameter (how many candidates should be written) > there was the issue that the number parameter was overwritten and then not set back to the original number. 
TOPP_Test

refactor:
-fingerid parameter is now used if -out_fingerid  (output folder) is set.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
http://cdash.openms.de/viewBuildError.php?buildid=237368

**Comment by lukaszimmermann** [comment]
ups, my bad

**Comment by oliveralka** [comment]
Thanks Timo & Lukas!

**Comment by lukaszimmermann** [comment]
looks good, gonna merge

**Pull request merged**
