### PR TITLE
Pyopenms jenkinsfile (for macOS silicon)

### PR DESCRIPTION
**Pull request by jpfeuffer**
## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
[?25h[33mWARNING [0m Error during upload. Retry with the --verbose option for more details. 
[31mERROR   [0m HTTPError: 409 Conflict from https://pypi.cs.uni-tuebingen.de/         
         Conflict                                                               
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1

GitHub has been notified of this commit’s build result

Finished: FAILURE

**Comment by jpfeuffer** [comment]
Looks like forcing is not supported. So either you implement a build numbering logic or you live with it.

**Comment by jpfeuffer** [comment]
You can do "--skip-existing" then it will not fail but not sure if that is better.

**Comment by timosachsenberg** [comment]
apparently one can also delete the old package: https://stackoverflow.com/questions/24309586/remove-packages-from-local-pypi-index

**Comment by jpfeuffer** [comment]
seems like it. probably we should do the same as in github actions. or also just don't upload when it's not the nightly branch

**Comment by jpfeuffer** [comment]
@timosachsenberg How do you want to go forward? Should I/we implement a solution, or merge first to have some wheels?

**Comment by timosachsenberg** [comment]
Yeah please merge. I think a strategy to upload only nightlies and maybe manually trigger a release upload (with delete of the old package?) would be great.

**Comment by timosachsenberg** [comment]
ok nice. how would the release upload be done? manually using twin?

**Comment by jpfeuffer** [comment]
Yes same, with twine. We just need to set up a different credential for pypi official.

**Pull request merged**
