### PR TITLE
Use logger for pyopenms warnings/errors

### PR DESCRIPTION
**Pull request by radusuciu**
## Description

This change is motivated by my experience when setting a non-default `OPENMS_DATA_PATH` envvar, in which case `pyopenms` will print a warning message. Because `print` function is used, these messages cannot be easily suppressed. If this PR is merged, the user can suppress warning messages like so: `logging.getLogger('pyopenms').setLevel(logging.ERROR)`.

While I was at it, I also tweaked the way errors were logged in this file, and I think readability is improved.

Please let me know if you think the logging levels I've chosen are appropriate. For the first `OPENMS_DATA_PATH` warning, I considered using the INFO level since setting the `OPENMS_DATA_PATH` environment variable is an explicit choice and thus might not warrant a warning. 

## Checklist
- [x] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by poshul** [comment]
I think that overall, we don't have a good unified set of criteria for choosing the logging levels across the project. I think INFO is reasonable for this case given the reasoning you provide above.

**Comment by jpfeuffer** [comment]
The problem is that this will have no effect on anything from our C extension.
You would need to import the logging module into Cython or directly in C and conditionally change our logging macros to use those new functions:
https://gist.github.com/hensing/0db3f8e3a99590006368

**Comment by radusuciu** [comment]
Thanks for pointing out potential issues - I don't have experience writing extension. I'll do some research and testing if you still think it's useful.

This might be relevant:

https://subscription.packtpub.com/book/programming/9781783551675/2/ch02lvl1sec16/logging-from-cc-into-python

**Comment by jpfeuffer** [comment]
Whoever thinks it's worth pursuing, see my untested branch for a potential start:
https://github.com/OpenMS/OpenMS/tree/pylogger

Until then, note that you can set logging for the extension with:
https://github.com/OpenMS/OpenMS/issues/6448

With some limitations:
https://github.com/OpenMS/OpenMS/issues/6827

**Comment by radusuciu** [comment]
@jpfeuffer, thought about this for a bit, and please correct me if I'm wrong, but shouldn't this PR work to allow the user to control the logging of errors/warnings that occur on import of `pyopenms`, even if this solution wouldn't work for errors/warnings that occur in Cython/C bits?

If so, do you think this has value on its own? As it stands my logs are full of this (1 warning per process):

```
Warning: OPENMS_DATA_PATH environment variable already exists. pyOpenMS will use it (/example/OpenMS/) to locate data in the OpenMS share folder (e.g., the unimod database), instead of the default (/venv/lib/python3.11/site-packages/pyopenms/share/OpenMS).
Warning: OPENMS_DATA_PATH environment variable already exists. pyOpenMS will use it (/example/OpenMS/) to locate data in the OpenMS share folder (e.g., the unimod database), instead of the default (/venv/lib/python3.11/site-packages/pyopenms/share/OpenMS).
Warning: OPENMS_DATA_PATH environment variable already exists. pyOpenMS will use it (/example/OpenMS/) to locate data in the OpenMS share folder (e.g., the unimod database), instead of the default (/venv/lib/python3.11/site-packages/pyopenms/share/OpenMS).
Warning: OPENMS_DATA_PATH environment variable already exists. pyOpenMS will use it (/example/OpenMS/) to locate data in the OpenMS share folder (e.g., the unimod database), instead of the default (/venv/lib/python3.11/site-packages/pyopenms/share/OpenMS).
Warning: OPENMS_DATA_PATH environment variable already exists. pyOpenMS will use it (/example/OpenMS/) to locate data in the OpenMS share folder (e.g., the unimod database), instead of the default (/venv/lib/python3.11/site-packages/pyopenms/share/OpenMS).
Warning: OPENMS_DATA_PATH environment variable already exists. pyOpenMS will use it (/example/OpenMS/) to locate data in the OpenMS share folder (e.g., the unimod database), instead of the default (/venv/lib/python3.11/site-packages/pyopenms/share/OpenMS)
```

Adding this warning made sense at the time to me, but given that I'm setting `OPENMS_DATA_PATH` explicitly (something that is a bit hard to accidentally do), the warning seems unnecessary, and better categorized as informational - which we can't really do with `print`.

I completely understand if you'd rather not merge without a unified solution.

**Comment by jpfeuffer** [comment]
You are correct. It helps to a certain degree.
One thing to consider is, that our installers and our conda activate script may set this variable without the knowledge of the user. I think that is why it was a warning.
However,
a) I think the user should have an option to disable the warning
b) I think we should reevaluate the strategy of setting this variable without the knowledge of the user (as also heavily recommended by the conda-forge people). Instead we probably should always fall back to the share relative to the lib.

I would be willing to merge this as a first step but I am a bit afraid that people see this python logging used and think they can control all logging of pyopenms with this.

I see three increasingly difficult but also increasingly accessible solutions:
1. Create a short documentation page about logging in pyopenms-docs to mention the difference between the python logger and the C logger and how to set levels in each.
2. Create a small python-only logging submodule that has functions for setting log levels (and other log related stuff). Those functions will set the log level for both python and C extension. This module is then documented with API docs.
3. Implement the unified logging (as discussed above) where the C extension forwards its log messages to the python logger so everything can be controlled with the standard python logging module.

**Comment by radusuciu** [comment]
All makes sense. I agree that setting an envvar during install is potentially surprising behavior and it would be ideal if that was only ever set by the user -- this would definitely make the warning/info message unnecessary.

After considering your points above, in my opinion this PR isn't worth the potential confusion of having two different and mutually exclusive methods of controlling logging verbosity. Clearing up the envvar issues (and potentially removing the `print` warning) and moving towards unified logging seem like better solutions with no downsides.

**Comment by alhigaylan** [comment]
> All makes sense. I agree that setting an envvar during install is potentially surprising behavior and it would be ideal if that was only ever set by the user -- this would definitely make the warning/info message unnecessary.
> 
> After considering your points above, in my opinion this PR isn't worth the potential confusion of having two different and mutually exclusive methods of controlling logging verbosity. Clearing up the envvar issues (and potentially removing the `print` warning) and moving towards unified logging seem like better solutions with no downsides.

Hi Radu! Thank you for your effort. I'm not sure if you are already aware, but we have active developers on Discord to discuss improvements in a less formal way. Feel free to join :) If you have a specific interest in OpenMS, let me know, and I will try to connect you with relevant people.

**Comment by radusuciu** [comment]
> Hi Radu! Thank you for your effort. I'm not sure if you are already aware, but we have active developers on Discord to discuss improvements in a less formal way. Feel free to join :) If you have a specific interest in OpenMS, let me know, and I will try to connect you with relevant people.

Hi, thank you for the invite! I'm already lurking on there but I'll poke my head out next time I have something to discuss :)

As for specific interests, the first thing that comes to mind is: https://github.com/OpenMS/dockerfiles. Currently at my job I have my own images for OpenMS but I'd be interested in seeing if there's anything I've done that is worth upstreaming, and if there's any cleanup that I can work on in that area. I can follow up on Discord.

**Pull request closed without merging**
