### PR TITLE
[CI] Update cmake version in gitpod file

### PR DESCRIPTION
**Pull request by timosachsenberg**
FYI @KyowonJeong

# Description

Update gitpod docker file to make it work again with current OpenMS version

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

**Comment by jpfeuffer** [comment]
This should be available from the base image:
https://github.com/OpenMS/dockerfiles/blob/master/contrib/Dockerfile#L13

Also forgot "No Jenkins" label

**Comment by timosachsenberg** [comment]
ah thanks. so I just need to link to the new docker repository

**Comment by jpfeuffer** [comment]
By the way, what is wrong? Works for me from the beginning:
Bildschirmfoto 2022-02-21 um 11 39 19

**Comment by timosachsenberg** [comment]
just for the mzML branch there still cmake 3.10 was installed

**Pull request closed without merging**
