### PR TITLE
check for trusty compatibility

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@jpfeuffer fixes lp wrapper test on travis

**Comment by hroest** [comment]
I also have a branch for qt5 that (mostly) builds: feature/qt5-travis-trusty

**Comment by timosachsenberg** [comment]
For your configuration we loose the container build infrastructure and use the fixed instances (because it requires sudo).
Currently, there seems to be no real big benefit from the container infrastructure but this might change. For example, the fixed infrastructure has limited resources that travis afaik prioritizes to paying members. The container infrastructure is on amazon and currently not limited for open source projects.

**Comment by hroest** [comment]
I think using the same trick as in precise should also work in trusty, using `- sourceline: ` for a ppa package

**Pull request merged**
