### PR TITLE
[FEATURE] correct precursor to feature

### PR DESCRIPTION
**Pull request by timosachsenberg**
post OpenMS 2.0 pull request

### CODE REVIEW

**Comment by lars20070** [comment]
@timosachsenberg The screenshot shows a peptide triplet (correctly detected by FFMulti) with all three peptides fragmented at the second isotopic peak, and therefore not mapped (from @ChristianPichlo's beta testing). Will your HighResPrecursorMassCorrector shift the three precursors 0.33Da to the left and therefore resolve this problem?

screen shot 2015-01-31 at 20 59 48

**Comment by timosachsenberg** [comment]
Yes this should work.

----- Original Message -----

**Comment by lars20070** [comment]
@timosachsenberg The release is done. Can this feature now me merged?

**Comment by timosachsenberg** [comment]
we curretnly have some regressions on windows so we have to fix them first
http://cdash.openms.de/index.php?project=OpenMS

**Comment by timosachsenberg** [comment]
regression did not show up on my windows build after cleaning up the old files so I continue with merging

**Comment by lars20070** [comment]
Great. Thanks @timosachsenberg.

**Comment by hroest** [comment]
@timosachsenberg it seems that some functions such as `correctToNearestMS1Peak` are never tested: http://cdash.openms.de/viewCoverageFile.php?buildid=127218&fileid=145680

could you add that please?

**Pull request merged**
