### PR TITLE
Feature / improved match odds score

### PR DESCRIPTION
**Pull request by enetz**
Includes an improved xQuest match odds score algorithm and a new logOccupancyProbability score based on the same idea

### CODE REVIEW

**Comment by enetz** [comment]
@timosachsenberg if you want to try this score, you can access it in
`ANALYSIS/XLMS/XQuestScores::logOccupancyProb`

**Comment by timosachsenberg** [comment]
There were some issues with pyOprnMS

**Comment by hroest** [comment]
@timosachsenberg please dont merge if pyOpenMS doesnt compile, now we have to go and fix it on develop and other PR are compromised!

**Comment by timosachsenberg** [comment]
Sorry. Slipped through. Please merge the revert. Will only be able to take a closer look next week

**Pull request merged**
