### PR TITLE
Revert KNIME incompatible shortcut

### PR DESCRIPTION
**Pull request by jpfeuffer**
maybe should also go to release

### CODE REVIEW

**Comment by jpfeuffer** [comment]
I fixed it through incredibly complicated exception handling in KNIME. I still think it is not worth it to deviate from the schema only to save one column.
How should KNIME know which format to expect if we leave out the "section names". It should at least write it in the header.

**Comment by poshul** [comment]
@jpfeuffer hows this looking now? Are the test errors downstream of the changes made?

**Comment by jpfeuffer** [comment]
Yes every test needs to be changed. Including KNIME nodes to be tested again. And I did not really get feedback on this. And I would like to deprecate the textexporters.
In the end they are basically the same as mzTab (in my opinion even more complicated, but @timosachsenberg disagrees).

**Comment by jpfeuffer** [comment]
Only the very basic exports of e.g. IDs are simpler.
But we do not even export proteins yet, let alone protein groups. Multiple runs will look very complicated, too.
The parsing of the hierarchical export of consensusXMLs especially with different runs etc. is even worse.

**Comment by timosachsenberg** [comment]
We can deprecate them, but we should not remove them yet.

**Comment by timosachsenberg** [comment]
some tests need an update I guess

**Comment by poshul** [comment]
I'm fine with deprecating them. Does that solve the test issue?

**Comment by jpfeuffer** [comment]
In that case we could close this PR and slowly replace occurrences in our tutorials.

**Comment by timosachsenberg** [comment]
Or we keep the PR and update tests but still remove from the tutorials

**Pull request closed without merging**
