### PR TITLE
Feature/feature map statistics

### PR DESCRIPTION
**Pull request by oliveralka**
new output
```
Peptide identifications in features:
Size distribution:
  size 0: 7
  size 1: 2
  size 8: 1

Unassigned peptide identifications: 2
```

### CODE REVIEW

**Comment by hendrikweisser** [comment]
Thanks for the contribution!

I find the wording on this not very intuitive:
```
Peptide identifications in features:
Size distribution:
```

How about:
```
Distribution of peptide identifications (IDs) per feature:
- 0 IDs: 7
- 1 IDs: 2
- 8 IDs: 1
```

**Comment by oliveralka** [comment]
I made the requested changes. 
Fixes #2259.

**Comment by hendrikweisser** [comment]
Thanks. Almost there. Should be "0 IDs" etc. instead of "IDs 0" etc.

**Comment by timosachsenberg** [comment]
@hendrikweisser 

Its the size distribution
so we have 7 features with zero ids:
  IDs 0: 7
two features with one id:
  IDs 1: 2
and one feature with 8 ids:
  IDs 8: 1

the format for printing the distribution is basically the same as for the charges.
here we have:
  charge 2: 7
if we have 7 features with charge 2

So I think the format Oliver chose is more consistent with the other output.

**Comment by hendrikweisser** [comment]
@timosachsenberg:
I disagree, because the way you would say it is different: "charge two" vs. "two IDs". You count the number of IDs, which is why that number should be in front.

**Comment by timosachsenberg** [comment]
then its 2 charges: 5 ;)

**Comment by hendrikweisser** [comment]
> then its 2 charges: 5 ;)

That's not what you'd say, though, is it? Yes, technically you can count the number of charges on the ion, in which case you'd put the number first, but typically you'd say e.g. "charge (state) 2".

**Comment by hendrikweisser** [comment]
More or less independent of that, we could make it even clearer by adding the word "features", e.g. "charge 2: 5 features" or "5 features of charge 2", and "2 IDs: 5 features" or "5 features with 2 IDs".

**Comment by timosachsenberg** [comment]
I don't have a strong opinion on this and can live with any of these. We just choose the format because it is easier to quickly skim over the numbers.

**Comment by hendrikweisser** [comment]
I have a strong opinion on "2 IDs" rather than "IDs 2". ;-)
I have a slight preference for adding "features", as in "charge 2: 5 features", but if that leads to big inconsistencies with the output for other file types, we should leave it out.

While we're making cosmetic changes: @oliveralka, could you add a line break between the "Total ion current" and "Charge distribution" outputs, please?

**Comment by cbielow** [comment]
how about adding a 'x' somewhere, e.g.

charge 2: 5x

The 'x' makes the counted variable easy to identify.

Am 11/11/2016 um 5:40 PM schrieb hendrikweisser:

**Comment by oliveralka** [comment]
I made the following changes: 

- Insert the line break 

```
  Total ion current in features: 36739
 
   Charge distribution:
     charge 2: 4
     charge 3: 6
```

- Changed the output for peptide IDs

```
 Distribution of peptide identifications (IDs) per feature:
    0 IDs: 7
    1 IDs: 2
    8 IDs: 1

```
If there is anything else to consider, please let me know!

**Comment by timosachsenberg** [comment]
+1 I merge because the output is reasonably clear now. If you feel the need to change it please open a new PR.

**Pull request merged**
