### PR TITLE
Added support for RNAse4 digestion of RNA. Fixed buggy regex for prot…

### PR DESCRIPTION
**Pull request by poshul**
### **User description**
…ein digestion by formic acid. Added more specifcity to comment in RNaseDigestion.h

___

### **PR Type**
enhancement, bug_fix

___

### **Description**
- Added new enzyme definitions for RNase_4 and RNase_4p in `Enzymes_RNA.xml`, including specific regex patterns and descriptions.
- Fixed an incorrect regex pattern for Formic_acid in `Enzymes.xml` to correct protein digestion behavior.
- Enhanced the comment in `RNaseDigestion.h` to improve clarity on regex patterns used for RNA digestion.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>RNaseDigestion.h</strong><dd><code>Enhance RNA digestion regex comment specificity</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/openms/include/OpenMS/CHEMISTRY/RNaseDigestion.h

<li>Added specificity to the comment for <code>cuts_after_regexes_</code> to clarify <br>that each regex represents a single nucleotide.<br>

</details>
    

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7486/files#diff-c8cecd827d8e4640131d46a9a624991b79491bfa27379ee6b433c33682403d3b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Enzymes_RNA.xml</strong><dd><code>Add support for RNase_4 and RNase_4p digestion</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
share/OpenMS/CHEMISTRY/Enzymes_RNA.xml

<li>Added new enzyme entries for RNase_4 and RNase_4p with specific <br>cutting patterns and descriptions.<br>

</details>
    

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7486/files#diff-768cab316aa24f920104a070b4162e2eec83c4bacd9466c5d0ad728ecd3e2a50">+18/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Bug_fix
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Enzymes.xml</strong><dd><code>Fix regex for Formic_acid in protein digestion</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
share/OpenMS/CHEMISTRY/Enzymes.xml

<li>Corrected the regex pattern for Formic_acid to fix a bug in protein <br>digestion.<br>

</details>
    

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7486/files#diff-bf2bec04c1bcce8d17ef69adc983747d93ae57bdcef85f7801eb2cda4e09ea25">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Would be great to add tests.

**Comment by timosachsenberg** [comment]
thanks for the other fix.
Are there any unexpected implications because the regex got removed? e.g., I guess not for our digestion code. Is it now empty for all enzymes if requested via the API? is the semantics documented. Did not look into it in detail but this might be relevant...

**Comment by poshul** [comment]
Regex is still used and present for the protease enzymes. We didn't ever
actually use it in the nucleotide code, since a single nucleotide can be
represented as a multi character string. I actually came across this while
adding documentation to the file (a collaborator asked about it) which is
how I was reminded that these were unused.

On Wednesday, May 8, 2024, Timo Sachsenberg ***@***.***>
wrote:
> thanks for the other fix.
> Are there any unexpected implications because the regex got removed?
e.g., I guess not for our digestion code. Is it now empty for all enzymes
if requested via the API? is the semantics documented. Did not look into it
in detail but this might be relevant...
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci3.googleusercontent.com/meips/ADKq_Na7kbZMovKk-Hu9EoTCJuBfnIypF6t3dWmRqrHiT4G1QFMHjc2RamrjGdF-esdegYB4yrrrxzlmeGwij2SmBGYpkYr0j6O5qGSzCHCLu9SMNyd5cBsChgz-caaTO9J3XwCYz-4myTo7RfTe61y3HAYZC8tXlQSN9Aq6LWCbrhGHDr0VAjSANcW4SoVLiRKAarYFu4Ejm7Z5n5Qqm6G_z2Yfgzbxenrp-0vuO1i5OK0C1q29Sz4GVJs=s0-d-e1-ft#https://github.com/notifications/beacon/AABD3CZCPSZXO77KFWB4MV3ZBG773A5CNFSM6AAAAABHJOK3DSWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTT5FDG4W.gif>Message
ID: ***@***.***>

**Comment by timosachsenberg** [comment]
can we fix this design? doesn't make sense to have the same interface if it only returns an empty regex.

**Pull request merged**
