### PR TITLE
[FIX] XTandem out protein parsing

### LINKED ISSUE #4770: Issue with XTandemAdapter
Hi everyone,

I am trying to analyse 3 mzML files created with ThermoRawFileParser from Q-Exactive HF DDA, label-free runs. They work in comet, but with XTandemAdapter I get:
```
ERROR XTandemAdapter       0:101      Failing process stdout: [Progress of 'loading spectra list':, ,   3.28 %               ,   9.83 %               ,   14.76 %               ,   20.31 %               ,   28.03 %               ,   35.55 %               ,   43.43 %               ,   49.33 %               ,   57.01 %               ,   63.61 %               ,   70.23 %               ,   76.70 %               ,   82.94 %               ,   88.83 %               ,   94.40 %               , -- done [took 7.86 s (CPU), 15.47 s (Wall)] -- , Progress of 'loading chromatogram list':, , -- done [took 0.00 s (CPU), 0.02 s (Wall)] -- , Executing: C:/Program Files/KNIME/plugins/de.openms.win32.x86_64_2.6.0.202005112153/payload/bin/XTandem/tandem.exe, Executed C:/Program Files/KNIME/plugins/de.openms.win32.x86_64_2.6.0.202005112153/payload/bin/XTandem/tandem.exe successfully!, Error: Unexpected internal error (the element 'No accession tr|H9J9S0|H9J9S0_BOMMO T-complex protein 1 subunit alpha OS=Bombyx mori OX=7091 GN=101742382... found in run 'XTandem_2020-06-04' for PSM SC(Carbamidomethyl)GDPVRTQNVMAAAAIANIVK_2. Please contact the maintainer of this tool e.g. on GitHub as this should not happen.' could not be found)]
ERROR XTandemAdapter       0:101      Failing process stderr: []
ERROR XTandemAdapter       0:101      Return code: 8
ERROR XTandemAdapter       0:101      Execute failed: Failed to execute node XTandemAdapter
WARN  Output File          0:63       The selected output file and the incoming file have different mime types.
WARN  Output File          0:63       File D:\groups_temp\ext_BOKU\LCMS_-_Haemagglutinin_1 already exists and cannot be overwritten.
ERROR XTandemAdapter       0:101      Failing process stdout: [Progress of 'loading spectra list':, ,   10.92 %               ,   23.39 %               ,   39.46 %               ,   55.39 %               ,   69.60 %               ,   87.46 %               , -- done [took 6.92 s (CPU), 6.93 s (Wall)] -- , Progress of 'loading chromatogram list':, , -- done [took 0.00 s (CPU), 0.00 s (Wall)] -- , Executing: C:/Program Files/KNIME/plugins/de.openms.win32.x86_64_2.6.0.202005112153/payload/bin/XTandem/tandem.exe]
```

As instructed in the error, I am reported the unexpected behaviour. The way I read the message, the issue is with the Adapter, not XTandem! itself (since it seems the latter completed successfully), so I am doing this here. Any idea what might have happened? I am happy to share files if it helps.
Kind regards,

Armel

### PR DESCRIPTION
**Pull request by jpfeuffer**
Always update "current_protein" var to store the refs correctly in the PepEvidence
Fixes #4770

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Looks good

**Comment by timosachsenberg** [comment]
Do You have a test for that?

**Comment by jpfeuffer** [comment]
I added something which I think would have failed before. But I don't have a develop build ready.

**Comment by timosachsenberg** [comment]
feel free to merge

**Pull request merged**
