### PR TITLE
fixes for CometAdapter

### PR DESCRIPTION
**Pull request by cbielow**
[FIX] fixes indexedMZML problem (#4348, always write an Index)
[FEATURE] CometAdapter does now read the comet version. No need for the user to specifiy it via commandline.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Nice. But what kind of mzml is this writing. Afaik We only read the metadata to double check centroidedness.

**Comment by jpfeuffer** [comment]
And do you really want to copy gigabytes of spectra hidden from the user?

**Comment by cbielow** [comment]
> And do you really want to copy gigabytes of spectra hidden from the user?

With a warning (added), yes. Its 'only' MS2 spectra.

**Comment by jpfeuffer** [comment]
Ok looks good. Warning should be enough I guess.

**Comment by jpfeuffer** [comment]
Quick question before merge: what if you want to search MS3?

**Comment by cbielow** [comment]
good point!

**Comment by jpfeuffer** [comment]
This broke the Address Sanitizer. Please have a look.
Is this really how you initialize a smart pointer? Wouldn't you rather use make_unique/shared?

**Comment by jpfeuffer** [comment]
Ah it needs to be unique_ptr<char[]>

**Comment by cbielow** [comment]
ahh darn.. wrong delete operator...
beginner trap :)
and make_unique is C++14 ....
However, I hear we are switching to 17 soon :)

**Pull request merged**
