### PR TITLE
Add support of "no cleavage" for XTandemAdapter & CometAdapter

### LINKED ISSUE #6133: "no cleavage" not supported for X!Tandem and Comet
Currently "no cleavage" isn't supported for X!Tandem and Comet. We are doing some peptide searching so we don't want any enzyme cleavage at all. For Comet, this can be done by specifying the enzyme as "No_cut" and adding an additional entry of "No_cut" to the end of the comet params file. This is suggested by the Comet developer ([see here](https://groups.google.com/g/comet-ms/c/HzhSreCUm_E/m/vQV5kYLLBQAJ)) and also is supported in the latest Comet release. For X!Tandem, we asked the developers but we lost the reference. So it can be done using `[Z]|[Z]`. We already implemented these changes (see below) and had tested it on our test data. Let me know how you guys think and we are happy to submit a PR!

https://github.com/OpenMS/OpenMS/compare/89dd3df90df49d5374c4920b28210de125e2154c...zhuchcn:uclacds-develop

### PR DESCRIPTION
**Pull request by zhuchcn**
## Description

Add support of "no cleavage" for XTandemAdapter and CometAdapter. This seems to work with our own docker image.

Closes #6133 

## Checklist
- [X] Make sure that you are listed in the AUTHORS file
- [X] Add relevant changes and new features to the CHANGELOG file
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by enetz** [comment]
looks good, but can you please also update the failing tests?
Here we specifically have a test that confirms that XTandemAdapter does not support "no cleavage". Now that it does, this needs to change (this should just be a simple change from `false` to `true`):
[in ProteaseDB_test.cpp](https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/ProteaseDB_test.cpp#L122)

There are also failing tests in `ProteaseDigestion_test` and `PeptideIndexing_test` that might be a bit more complicated to fix.
To get detailed outputs of the class tests, you can run e.g.
`ctest -V -R ProteaseDigestion_test`

**Comment by zhuchcn** [comment]
Not very familiar with the testing system yet but will look into those!

**Comment by zhuchcn** [comment]
Tests seem to be fixed. The reason seem to be this. I guess for no cleavage and full specificity, there could still be asp-pro cleavages. Although I don't think users are able to set this option anywhere? 

https://github.com/OpenMS/OpenMS/blob/4e929a2092b0ecaed1da149648ea49294a72686f/src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp#L184

The linting and pyopenms still fail. Linting failures don't seem to be caused by this PR, and I'm not sure about pyopenms build. Jenkins output isn't too helpful.

Also, my knowledge to cmake and ctest is limited, so I'm not quite sure how to test it locally. So I'm just curious is there any documentation of how to build and run the test cases locally?

**Comment by jpfeuffer** [comment]
Thanks you can definitely ignore pyopenms for now.

**Comment by zhuchcn** [comment]
@jpfeuffer Are we holding this PR for other issues/PRs to be resolved?

**Review by jpfeuffer — APPROVED** [review]

**Pull request merged**
