### PR TITLE
Feature/fraction support

### PR DESCRIPTION
**Pull request by timosachsenberg**
rework of https://github.com/OpenMS/OpenMS/pull/2503

don't merge yet

### CODE REVIEW

**Comment by timosachsenberg** [comment]
To test alignment and linking you can try:

```
MapAlignerIdentification -debug 6 -in share/OpenMS/examples/FRACTIONS/BSA1_F1_idmapped.featureXML share/OpenMS/examples/FRACTIONS/BSA1_F2_idmapped.featureXML share/OpenMS/examples/FRACTIONS/BSA2_F1_idmapped.featureXML share/OpenMS/examples/FRACTIONS/BSA2_F2_idmapped.featureXML share/OpenMS/examples/FRACTIONS/BSA3_F1_idmapped.featureXML share/OpenMS/examples/FRACTIONS/BSA3_F2_idmapped.featureXML -out share/OpenMS/examples/FRACTIONS/BSA1_F1_aligned.featureXML share/OpenMS/examples/FRACTIONS/BSA1_F2_aligned.featureXML share/OpenMS/examples/FRACTIONS/BSA2_F1_aligned.featureXML share/OpenMS/examples/FRACTIONS/BSA2_F2_aligned.featureXML share/OpenMS/examples/FRACTIONS/BSA3_F1_aligned.featureXML share/OpenMS/examples/FRACTIONS/BSA3_F2_aligned.featureXML -design share/OpenMS/examples/FRACTIONS/BSA_design.tsv

FeatureLinkerUnlabeledQT -debug 6 -in share/OpenMS/examples/FRACTIONS/BSA1_F1_aligned.featureXML share/OpenMS/examples/FRACTIONS/BSA1_F2_aligned.featureXML share/OpenMS/examples/FRACTIONS/BSA2_F1_aligned.featureXML share/OpenMS/examples/FRACTIONS/BSA2_F2_aligned.featureXML share/OpenMS/examples/FRACTIONS/BSA3_F1_aligned.featureXML share/OpenMS/examples/FRACTIONS/BSA3_F2_aligned.featureXML -out share/OpenMS/examples/FRACTIONS/BSA_linked.consensusXML -design share/OpenMS/examples/FRACTIONS/BSA_design.tsv
```

**Comment by timosachsenberg** [comment]
Current state:
- assumes that order of featureXML also matches the order of mzMLs in design file (this restriction could possibly be removed by matching run information to mzML)
- Supports MapAlignerIdentification and all unlabeled feature linkers

**Comment by hroest** [comment]
seems like a good start, should we merge?

**Comment by timosachsenberg** [comment]
I will merge this as a single squashed commit that is easy to revert in case we encounter major issues ...

**Pull request merged**
