### PR TITLE
Fix/siriusadapternightlies Tries to solve the error in SiriusAdapter test

### PR DESCRIPTION
**Pull request by lukaszimmermann**
I tested on El Capitan with the same compiler (Apple clang++ 7.3.0) as on abibuilder.
The files in the tests are identical, so I could not reproduce the error. Also `FuzzyDIff` passes. I tested the branches `develop` and `nightly`. Currently I lack ideas on how to deal further with the issue. Here, I just regenerated the test file on a Linux machine. Perhaps it helps.

Does anyone have another idea?

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Doesn't the failing test suggest that there is either an additional newline after line 4 or the rest of the MTD lines missing completely?

**Comment by jpfeuffer** [comment]
Have you seen, that the file is basically completely empty?

https://abibuilder.informatik.uni-tuebingen.de/jenkins/job/openms_nightly_packaging/compiler=appleclang-7.3.0,os_label=elcapitan/ws/build/src/tests/topp/SiriusAdapter_1_output.tmp/*view*/

**Comment by lukaszimmermann** [comment]
No, haven't seen the file.  But this is helpful, because the description should definitely not be null.

**Comment by jpfeuffer** [comment]
Test output:
```
2017-08-15 16:22:14.890 SiriusAdapter[47248:48952591] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
2017-08-15 16:22:15.167 SiriusAdapter[47248:48952591] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
Progress of 'loading spectra list':
-- done [took 0.00 s (CPU), 0.00 s (Wall)] --
No MS1 spectrum for this precursor. Occurred 0 times.
0 spectra were skipped due to precursor charge below -1 and above +1.
Charge of 0 was set to +1 due to positive polarity 5 times.
Charge of 0 was set to -1 due to negative polarity 0 times.
Fatal error: Running SiriusAdapter returned an error code or could no compute the input
Deleting temporary directory '/tmp/2017-08-15_162215_abibuilder1.Informatik.Uni-Tuebingen.De_47248_1'. Set debug level to 2 or higher to keep it.
Deleting temporary msfile '/tmp/2017-08-15_162215_abibuilder1.Informatik.Uni-Tuebingen.De_47248_2.ms'. Set debug level to 2 or higher to keep it.
SiriusAdapter took 0.16 s (wall), 0.14 s (CPU), 0.01 s (system), 0.13 s (user).
```

**Comment by jpfeuffer** [comment]
I guess they are doing some weird stuff in their shell scripts.

**Comment by jpfeuffer** [comment]
No sorry, the CFPasteboardRef error come from running it as admin.

**Comment by lukaszimmermann** [comment]
I think that the sirius executable misbehaves for some reason on the build machine. I have access, so I a going to directly take a look.

**Comment by oliveralka** [comment]
May be related to the regex error on linux? There an empty file may be created - was the file totally empty or did it have the "MTD" if it?

**Comment by lukaszimmermann** [comment]
The output says:
Fatal error: Running SiriusAdapter returned an error code or could no compute the input

So I think that sirius cannot be executed on the El Capitan machine (but I do not know yet, why)

**Comment by jpfeuffer** [comment]
Yes, we should start by changing the error code.
And by the way: The test also fails on linux.

**Comment by jpfeuffer** [comment]
Why is the following in the startup script?
CLASSPATH="$APP_HOME/../../../All/Sirius/lib/*:${GUROBI_HOME}/lib/gurobi.jar"

**Comment by lukaszimmermann** [comment]
Ok this explains it. Thanks @jpfeuffer  I am going to prepare a fix.

**Comment by jpfeuffer** [comment]
Should be just ../lib. We only install/clone the binaries specific for a certain platform.

**Comment by jpfeuffer** [comment]
Thanks! and dont forget linux. Windows seems to be ok.

**Comment by jpfeuffer** [comment]
see #2791

**Comment by lukaszimmermann** [comment]
PR with fixed classpath open.

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/THIRDPARTY/pull/16

**Comment by jpfeuffer** [comment]
Still crashes on Linux. I can have a look why but we should definitely think about grabbing the stderr of the child process if possible.

**Comment by lukaszimmermann** [comment]
Yes, we could do that. I won't have time for this issue before Monday, though.

**Comment by jpfeuffer** [comment]
The issue on Linux should be solved with https://github.com/OpenMS/THIRDPARTY/pull/18.
Still would be great if you could improve the error output and fix the executable search in this PR.

**Comment by lukaszimmermann** [comment]
Yes will do that. Thanks for your work.

**Comment by lukaszimmermann** [comment]
Made the requested changes. 

I think that the `-fingerid` parameter of `SiriusAdapter` is redundant. Can't we just call CSIFingerID if the user has provided the `-out_CSIFingerID` parameter and leave the call out otherwise? 
In fact, it does not really make sense to specify `-fingerid` without `-out_CSIFingerID` and vice versa.

@oliveralka  what do you think?

**Comment by lukaszimmermann** [comment]
pyopenms test fail.

**Comment by timosachsenberg** [comment]
ok this PR is finished. consider removing the parameter -fingerid in other PR

**Pull request merged**
