### PR TITLE
fix windows build error

### PR DESCRIPTION
**Pull request by cbielow**
## Description

not sure why this pops up now, since nothing changed since months AFAIKT.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Is this for the regular builds or pyopenms also?
Or only pyopenms? 😅

I'm wondering how you would call the methods if they are not exposed by the DLL API anymore.

**Comment by cbielow** [comment]
I still do not know, why this compiled in the past, but at least I know why it did not compile recently.
According to https://devblogs.microsoft.com/oldnewthing/20140109-00/?p=2123 symbols for inline functions are put into the DLL. So they should be in there, and hence the AAIndex_test should be able to import them during linking. 
However, the AAIndex.h was never part of the compile process of the OpenMS.dll. Hence the symbols where not in there (i.e. nothing included the AAIndex.h within the OpenMS library).
This is fixed now, and thus the symbols are exported into, and imported from the OpenMS.dll. Problem solved.

**Comment by jpfeuffer** [comment]
Super weird. But I'm glad it's fixed.

**Review by jpfeuffer — APPROVED** [review]

**Comment by cbielow** [comment]
git bisect to the rescue. There is your offender:
https://github.com/OpenMS/OpenMS/commit/671b07ee59a97a322adf516fa7e732e81363bd05#diff-a0298eac22865b834a170d0618013f6f07098c50b30ffb8bbf26d183487def52L14
from PR #7402

**Pull request merged**
