### PR TITLE
[SCHEMA] added first proposal for small molecule inclusion in idXML

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
This is a first proposal for a potential extension of idXML. Main aim is to include a similar hierarchy as for peptide/proteins.
SmallMoleculeHits (small molecule spectrum matches) correspond to a single match (e.g. a spectrum of a compound with adduct from a spectral library)
SmallMoleculeIdentification correspond to a spectrum identification (analogous to PeptideIdentification).
CompoundHit (corresponds to a ProteinHit) may be e.g. used to group several small molecule adducts or derivatives of the same compound

maybe later one could also extend the concept to CompoundGroups but I think we should first see if this fits our needs.

**Comment by hroest** [comment]
one thing to consider that I see a lot in small molecules is that people use the MS1 only for a hit, e.g. only the accurate mass (and RT) is used for matching to the db. Would this also be supported or only hits to single matches using a spectral library (e.g. SmallMoleculeHit)?

Otherwise :+1: to include this!

**Comment by timosachsenberg** [comment]
This should be easily possible as references to spectra are optional. Accurate mass results can be stored in a SMHit of  a SMIdent.

**Comment by timosachsenberg** [comment]
To view a graphical representation you can
copy and paste https://raw.githubusercontent.com/timosachsenberg/OpenMS/feature/small_molecule_idXML/share/OpenMS/SCHEMAS/IdXML_1_3.xsd
into:
http://xmlgrid.net/

**Comment by timosachsenberg** [comment]
also models search parameter units in idXML #1471

**Comment by timosachsenberg** [comment]
allows to specify all starts/ends in a protein (as well as aa_before and aa_after) for every peptide evidence. That way we can also store the information neede to calculate proper protein coverage or and information on the flanking amino acids.

**Comment by timosachsenberg** [comment]
@mwalzer I just used a xs:string as entry to allow to store a StringList. Is this the correct way to do this?

**Comment by mwalzer** [comment]
There are better ways. But I did not find, where you would have that?

**Comment by timosachsenberg** [comment]
Better in what regards? I think probably not less size consuming...
We do it for the protein refs in the peptide hit and I wanted to do it analogous for the the aa_before / aa_after.

**Comment by mwalzer** [comment]
But these are xs:IDREFS - in both PeptideHit as in CompoundHit elements ...  so I still don't see where you would have these.
So the better way imo would be to use lists: 
```
<xs:simpleType name="listOfWhatever">
	<xs:list itemType="xs:string"/>
</xs:simpleType> 
...
<xs:attribute name="whatevers" type="listOfWhatever">
```
So everyone reading the schema is forced to entertain the idea of several items in the element

**Comment by timosachsenberg** [comment]
ok I wil add this.

**Comment by timosachsenberg** [comment]
proteomics additions partially addressed in https://github.com/OpenMS/OpenMS/pull/1666

**Comment by FabianAicheler** [comment]
Considering SearchParameters for small molecules:
If I understand it correctly, an 'IdentificationRun' could use all kinds of searches (e.g. AMS, MS2 spectral library search, RT-based)? So the common 'SearchParameters' would need to cover those (to a sensible extent).

Common parameters I can currently think of for small molecule ID:
- Adducts: Which ions were considered. E.g. some lipids are mostly observed as specific ions. (So for AMS for example it would be sensible to restrict the allowed adducts to those one expects)
- Ionization mode: positive, negative, both. Again as example, some lipids are differently/only observed in one mode.
- Different Lists of available fixed and modifications for small molecules (vs. the lists for peptides)
- Different Lists of available fixed and modifications depending on preparation? E.g. in GC, derivatisation is often used.
- Instruments: E.g. which instruments/chromatography to consider for spectral library search. Column type for RT-based ID.

More uncommon ideas:
- SUM Formulas: E.g. rules to restrict considered formulas (see Fiehn Seven Golden Rules): size, element ratios, ...
- Precursor ion list: If people know what to look for and only want results for the subset? Seems to be mostly for convenience (unless the search for all features takes prohibitively long)
- Molecule type: E.g. triglecrol vs cardiolipin. Some molecule types are expected for tissues, and other not.

**Comment by timosachsenberg** [comment]
@FabianAicheler Thanks for the input.
Adducts: Which ions were considered. E.g. some lipids are mostly observed as specific ions. (So for AMS for example it would be sensible to restrict the allowed adducts to those one expects)

So one would typically specify a superset of adducts here?

Ionization mode: positive, negative, both. Again as example, some lipids are differently/only observed in one mode.

would a searched charge range be better?

Different Lists of available fixed and modifications for small molecules (vs. the lists for peptides)

Different Lists of available fixed and modifications depending on preparation? E.g. in GC, derivatisation is often used.

do these have analogues to origin and site specifity? 

Instruments: E.g. which instruments/chromatography to consider for spectral library search. Column type for RT-based ID.

ok

More uncommon ideas:

SUM Formulas: E.g. rules to restrict considered formulas (see Fiehn Seven Golden Rules): size, element ratios, ...
Precursor ion list: If people know what to look for and only want results for the subset? Seems to be mostly for convenience (unless the search for all features takes prohibitively long)

interesting idea... maybe traML would work for that

Molecule type: E.g. triglecrol vs cardiolipin. Some molecule types are expected for tissues, and other not.

ok probably something for meta values

**Comment by FabianAicheler** [comment]
@timosachsenberg 

>Adducts: ...
>So one would typically specify a superset of adducts here?

From my experience yes (if you mean by superset a list of allowed adducts like in the AMS tools)

>Ionization mode: positive, negative, both. Again as example, some lipids are differently/only observed in one mode.
>would a searched charge range be better?

I guess a charge range would suffice? I would expect positive ions for positive mode and negative ions for negative mode (but I am not familiar whether some charges may theoretically occur in both modes).

>Different Lists of available fixed and modifications for small molecules (vs. the lists for peptides)
>Different Lists of available fixed and modifications depending on preparation? E.g. in GC, derivatisation is often used.
>do these have analogues to origin and site specifity?

Afaik derivatization normally happens at specific functional groups, but I am not familiar with GC chemistry. (smarts in addition to modification name might be nice/useful)

**Comment by timosachsenberg** [comment]
Field Name | Identification | Quantification
-------------- | ---------------- | -----------------
identifier | SC | SC
chemical_formula | SC | SC
smiles | SC | SC
inchi_key | SC | SC
description | SC | SC
exp_mass_to_charge | SC | SC
calc_mass_to_charge | SC | SC
charge | SC | SC
retention time | SC | SC
taxid | SC | SC
species | SC | SC
database | SC | SC
database_version | SC | SC
spectra_ref | SC | SC
search_engine | SC | SC
best_search_engine_score[1-n] | SC | SC
modifications | SC | SC
search_engine_score[1-n]_ms_run[1-n] | (not used) | sC
opt_{identifier}_* | sc | sc
reliability  | sc | sc
uri | sc | sc

**Comment by timosachsenberg** [comment]
And here some extension we considered in the mzTab 4 metabolomics meeting:
https://docs.google.com/spreadsheets/d/16GTBqQUkVOhefQxQx8UjTkPn82imQnfZ6uic6Bynxhs/edit?usp=sharing

**Comment by timosachsenberg** [comment]
I dug out another email with some considerations regarding GCx(GC)-MS in mzTab:

1. General Considerations
Distinction between Analytes (the actually measured ions) and Metabolites/Compounds.

Metabolites have no modifications and can not be determined directly. 
Analytes may have modifications through e.g. TMS derivatization, or methoximation and can be measured by a mass spectrometer when they have been ionized.
**TODO: check how we handle this**

One metabolite/compound may be associated to multiple analytes that were created for example through different levels of derivatization (e.g. 1TMS, 2TMS, 3TMS derivatives):
**modeled in the current schema proposal**

As far as I understand the intents for the small molecule summary rows, I would argue that the metabolites/compounds should appear there, while the analytes need to appear in the detailed mzTab (complete, quantification/qualification) variants. Thus, I would 
propose to use the metabolite identifier in the small molecule summary row, while using the 
analyte identifier in the small molecule feature and evidence rows. This however requires that 
some kind of mapping is also provided within the mzTab file between multiple analytes and their corresponding metabolites. 
**modeled in the current schema proposal**

**This is very similar to peptide->protein mapping**

1.2. Implications for GCxGC-MS, or other two-dimensional separations

Retention time for two-dimensional separations is usually expressed by two separate 
retention times, one for each separation column. Thus, retention_time_window 
should support multiple entries to allow definition of a rectangle:

retention_time_window -> 1552, 2.45 | 1567, 2.48

By convention, this could be the lower left coordinate of the rt window and the upper right 
coordinate of the rt window

**NOT modeled in the current schema proposal**

2. Implications for the different mzTab sections:

2.1. Small molecule summary rows

Metabolite/Compound centric view on the experimental results, represents aggregate results 
of individual assays and study variables. 

Multiple analytes and their quantifications contribute to one small molecule summary row.
The association can be made clear by adding an opt_analytes column (maybe something more formalized), that contains a list of the associated analyte identifiers or references to the feature entry ids /evidence entry ids.
**Reference is given from analyte to metabolite/compound so this is probably not needed**

2.2. Small molecule feature rows

(Analyte centric view on linked, small molecule features, with identification, with quantification information)

2.3. Small molecule evidence rows
(Analyte centric view on small molecules, with identification)

Here, it should be made clear, whether the exp_mass_to_charge, calc_mass_to_charge, calc_neutral_mass should reflect the underivatized analyte / metabolite (which is impossible to measure), or whether these should be the m/z values of the acquired derivatized analyte ion.

**Good point we need to consider. I would argue that calc_neutral_mass should be the underivatized neutral mass of the analyte**

Modifications should be specified as a list of CV terms -> requires action to define new CV terms for psi-ms obo. For example Derivatization as the top-level term, with children sylylation (TMS), methoximation, etc. 
[MS:XXXX1,MS:XXXX2]

Whether the analyte was a 1TMS, 2TMS or other derivative should be clear when the database identifier is checked but could this also be a part of the CV term (a term with unit and value/quantity)?

**Comment by timosachsenberg** [comment]
Potential fields for CompoundHits adapted from MzTab for metabolomics meeting
Field Name | modeled by | 
-------------- | ---------------- | 
identifier |
description |
calc_neutral_mass |
chemical_formula |
smiles |  
inchi_key |  
taxid |
species | 
database |  
database_version |  
charges |  
modifications |  
adduct_ions | 
best_search_engine_score[1-n] | 
ambiguity_members |
opt_{identifier}_* |  
reliability  |  
uri |

**Comment by timosachsenberg** [comment]
use case AccurateMassSearch;
RT (in SMID)
MZ (in SMID)
charge (SMH - like for PepH)
adduct_ion (SMH)
score (SMH e.g. mass error)
formula (SMH)
smiles (SMH)
modifications (SMH e.g. derivatisation)

**Comment by timosachsenberg** [comment]
we will focus on MzTab-M and probably not extend idXML (probably new sql-based format based on Hendriks new Datastructure)

**Pull request closed without merging**
