### PR TITLE
Peptide indexer more user friendly

### PR DESCRIPTION
**Pull request by cbielow**
* `auto` mode for 3 settings in PeptideIndexer (all information is taken from input idXML)
  * enzyme specificity
  * enzyme name
  * FASTA filename

* allow removing weird peptides produced by XTandems's special cleavage rules ('X' is a stop codon...)

This PR changes some of the parameters of PI, i.e. old INI files need updating.

### CODE REVIEW

**Comment by cbielow** [comment]
appleclang should be a false positive.

**Comment by jpfeuffer** [comment]
Hmm yes, but we had this twice now. You recently changed this test and moved its data. Should be investigated in a separate PR.

**Comment by cbielow** [comment]
> 
> 
> Hmm yes, but we had this twice now. You recently changed this test and moved its data. Should be investigated in a separate PR.

a first try here #4838

**Comment by jpfeuffer** [comment]
I know. I think that caused it.

**Pull request merged**
