### PR TITLE
FeatureFinderIdentification add test for `-candidates_out`

### PR DESCRIPTION
**Pull request by bernt-matthias**
# Description

The `-candidates_out` option seems unused. 

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

**Comment by timosachsenberg** [comment]
I think it is used in the original publication. Does is cause any troubles?

**Comment by bernt-matthias** [comment]
> I think it is used in the original publication. Does is cause any troubles?

The Galaxy tests (which are generated from the CMakeFile) fail, because the output file is missing. 

This is because the `candidates_out` file is simply not written. 

In case the file is needed, the argument should be used somewhere ...

**Comment by timosachsenberg** [comment]
k will check why it is not used

**Comment by timosachsenberg** [comment]
should be used by algorithms by copying to it: https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FeatureFinderIdentification.cpp#L228

**Comment by bernt-matthias** [comment]
What is this line doing: https://github.com/OpenMS/OpenMS/blob/3cd3db31efef6241030830388dbceccb3d6ffd4e/src/topp/FeatureFinderIdentification.cpp#L209 ? 

If the parameter should be used it might be a good idea to have it covered by a test.

**Comment by bernt-matthias** [comment]
Test now fails with `Error: File not found (the file 'FeatureFinderIdentification_5_candidates.tmp' could not be found)`. Which verifies my observation.

**Comment by enetz** [comment]
this looks like the same issue as in #5920 (`.tmp` file ending), since the same function `FileHandler::storeFeatures` is used to write the file:
https://github.com/OpenMS/OpenMS/blob/62a701944098259fb7cebd4e6affc6c54f32c361/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp#L612

**Comment by timosachsenberg** [comment]
rebuild jenkins

**Review by timosachsenberg — APPROVED** [review]
Thanks! looks good.

**Pull request merged**
