### PR TITLE
Fixes/Features for TOPPAS/TOPPView

### PR DESCRIPTION
**Pull request by cbielow**
[FIX] TOPPAS: name temporary files with correct suffix if possible (when TOPPAS stops, the intermediate files will have a correct suffix); better error checking; better name choice for output files (source edge)

[FIX] TOPPAS: when copy&pasting nodes, insert new nodes next to existing ones & select the new nodes (to readily move them)

[FEATURE] TOPPAS: remember last main Window position for next start			

[FIX] TOPPView: omit modal & blocking Messagebox which warns for values <=0 (delays showing data, especially on large sets); instead show message in the status bar.

[FEATURE] TOPPView: remember last main Window position for next start

### CODE REVIEW

**Comment by timosachsenberg** [comment]
+1

**Comment by hendrikweisser** [comment]
I now get these messages when I close TOPPView:
```
QMainWindow::saveState(): 'objectName' not set for QDockWidget 0x1bc56f0 'Layers;
QMainWindow::saveState(): 'objectName' not set for QDockWidget 0x1bd0680 'Views;
QMainWindow::saveState(): 'objectName' not set for QDockWidget 0x1c56240 'Data filters;
QMainWindow::saveState(): 'objectName' not set for QDockWidget 0x1c60980 'Log;
QMainWindow::saveState(): 'objectName' not set for QToolBar 0x1b9bb30 'Basic tool bar'
QMainWindow::saveState(): 'objectName' not set for QToolBar 0x1bac3c0 '1D tool bar'
QMainWindow::saveState(): 'objectName' not set for QToolBar 0x1bb0710 '2D peak tool bar'
QMainWindow::saveState(): 'objectName' not set for QToolBar 0x1bb4a80 '2D feature tool bar'
QMainWindow::saveState(): 'objectName' not set for QToolBar 0x1bbf650 '2D peak tool bar'
QMainWindow::saveState(): 'objectName' not set for QToolBar 0x1bc2650 '2D identifications tool bar'
```

**Comment by cbielow** [comment]
unrelated and not critical (introduced in 
https://github.com/OpenMS/OpenMS/pull/2123/commits/f11542c42df5149c9b310592927037f2e33fe643 
if I recall correctly)

Am 8/24/2016 um 11:16 AM schrieb hendrikweisser:

**Comment by hendrikweisser** [comment]
@cbielow: Are you still going to get rid of the messages?

**Comment by hendrikweisser** [comment]
@cbielow: Also it's not "unrelated", since it was introduced in this PR. (Maybe you thought I commented on #837 and not here.)

**Comment by cbielow** [comment]
> @cbielow <https://github.com/cbielow>: Also it's not "unrelated", since
 > it was introduced in this PR. (Maybe you thought I commented on #837
 > <https://github.com/OpenMS/OpenMS/issues/837> and not here.)

uhh indeed. The pitfalls of email :)

**Pull request merged**
