### PR TITLE
[PARAM] simplified FileConverter parameters

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
resolves https://github.com/OpenMS/OpenMS/issues/2466

**Comment by hroest** [comment]
actually I dont like the omit index flag - I would prefer a flag where the two options are "true/false" which makes it more descriptive and also clear in a param.xml

**Comment by timosachsenberg** [comment]
k will rework it

**Comment by timosachsenberg** [comment]
@hroest Do you know why the data format and file name has been changed?
```
			<sourceFile id="sf_ru_0" name="FileConverter_4_input.mzXML" location="<TEST_DATA_PATH>">
 -				<cvParam cvRef="MS" accession="MS:1000569" name="SHA-1" value="bfb52b34f2482567ddf4474117ca70c09d96bea1" />
 -				<cvParam cvRef="MS" accession="MS:1000566" name="ISB mzXML format" />
 +			<sourceFile id="sf_ru_0" name="File_test_1.raw" location="">
 +				<cvParam cvRef="MS" accession="MS:1000569" name="SHA-1" value="0000000000000000000000000000000000000000" />
 +				<cvParam cvRef="MS" accession="MS:1000564" name="PSI mzData format" />
  				<cvParam cvRef="MS" accession="MS:1000777" name="spectrum identifier nativeID format" />
  ```

**Comment by hroest** [comment]
@timosachsenberg no, not really, can you try before applying the patch and figure out which code-change causes the change?

**Comment by cbielow** [comment]
as far as I can see, the respective lines where whitelisted, so the change could be from quite a while ago.
Seems also unrelated to this PR, right?
I'd be happy if we could merge this, since #2525 somehow depends on it (loosely).

**Comment by cbielow** [comment]
FileConverter test is failing
http://cdash.openms.de/testDetails.php?test=39331026&build=220084

**Comment by cbielow** [comment]
`offset` and `indexListOffset` might need to go in the whitelist

**Comment by cbielow** [comment]
ok, will merge as discussed. fix is coming the next pr by me

**Comment by timosachsenberg** [comment]
By the way, you can always add such small changes manually to a PR via the web interface.

**Comment by hroest** [comment]
@cbielow @timosachsenberg maybe we should agree to not merge stuff that breaks the build but rather amend the PR

**Comment by timosachsenberg** [comment]
Sure. Was kind of an exception in as I had time monitoring PRs and test results today.

**Pull request merged**
