### PR TITLE
only detect features on MS1 (don't mix levels)

### PR DESCRIPTION
**Pull request by timosachsenberg**
# Description

Fixes issue 5650

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Nice, but depending on the access patterns, wouldn't it be better if those spectra are just skipped to avoid copying the full raw data?

**Comment by timosachsenberg** [comment]
I think the data is handed down to the SWATH classes which probably don't (need to) implement that logic. If someone knows or can point me to a quick and clean way to add that I would be happy to do so.

**Comment by timosachsenberg** [comment]
I will merge this as a quick fix.

**Comment by jpfeuffer** [comment]
Also keep in mind that this copies everything, even though a user already provides filtered data.

**Comment by timosachsenberg** [comment]
Yes, not great I admit, but copying was also done before. On the C++ side I think could add a move version.

**Comment by hroest** [comment]
could we wrap a rvalue version of this function?

```
void setMSData(const PeakMap&& m);
```

**Comment by timosachsenberg** [comment]
that would be one idea yes. I can add it along with the test for the other PR

**Pull request merged**
