### PR TITLE
Feature/tv annot2

### PR DESCRIPTION
**Pull request by timosachsenberg**
Currently disabled by default but can be enabled via context menu
grafik

There is a lot of room for improvements but I think it already addresses the main request by most users.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Addresses https://github.com/OpenMS/OpenMS/issues/3418 and similar user requests

**Comment by timosachsenberg** [comment]
@enetz I think this one is finished.
- Interesting peaks can now automatically annotated (enable via context menu)
- I readded colors to annotations
- I scale SNAP and PERCENTAGE mode so a small margin remains on the top -> annotations are always visible and 100% in axis in percentrage mode doesn't get cropped anymore.

**Comment by timosachsenberg** [comment]
- also added the axis strings to the base class @cbielow  and @hroest

**Comment by timosachsenberg** [comment]
I merge as this fixes a bug I introduced in the last PR

**Comment by enetz** [comment]
@timosachsenberg something went wrong here, I just tried to load my XL-MS idXML file to annotate an mzML file and this error popped up:
`Caught exception: 'NotImplemented' with message 'this method has not been implemented yet. Feel free to complain about it!'`
on the current develop branch.
The automatic annotations are cool though.

**Comment by enetz** [comment]
@timosachsenberg the ID table works fine after the error, the peak annotatition pop-up table looks fine as well, but selecting or double-clicking an ID does not open up the corresponding MS2 spectrum.
The error message can pop up multiple times, e.g. every time I change tabs between scan view and ID view

**Comment by enetz** [comment]
@timosachsenberg reproducible with these test files in tests/topp/:
OpenPepXL_input.mzML
OpenPepXL_output.idXML

**Comment by timosachsenberg** [comment]
hmm works for me...

**Comment by timosachsenberg** [comment]
k found the issues ... preparing a fix

**Comment by timosachsenberg** [comment]
pushed directly...

**Comment by enetz** [comment]
:+1:  solved
thanks!

**Pull request merged**
