### PR TITLE
[FEATURE] clean up file suffix renaming

### PR DESCRIPTION
**Pull request by cbielow**
some easier and more safe way of renaming of files.

### CODE REVIEW

**Comment by cbielow** [comment]
tests pass (except CodeFactor, but the method is not really complex...)

**Comment by timosachsenberg** [comment]
why got this moved from File to FileHandler?

**Comment by timosachsenberg** [comment]
I would have voted for keeping it in File

**Comment by cbielow** [comment]
The new functions are closely linked to FileType, thus FileHandler seemed more logical.
We could move it, or duplicate the function signature in File.h, simply calling FileHandler internally.

**Comment by timosachsenberg** [comment]
it's fine with me but as a (new) user I would probably rather expected that method in a class called file

**Pull request merged**
