### PR TITLE
[BUILD] Output import libraries on Win to build/lib/$Config

### PR DESCRIPTION
**Pull request by jpfeuffer**

### CODE REVIEW

**Comment by hroest** [comment]
:+1: we can merge as travis wont help much here

**Comment by jpfeuffer** [comment]
I did not run a clean build from scratch yet.
Wait that the change of the CMAKE_ARCHIVE_OUTPUT_DIR does not break anything. But it shouldn't.

**Comment by jpfeuffer** [comment]
rebuild win

**Comment by timosachsenberg** [comment]
+1

**Pull request merged**
