### PR TITLE
[FEATURE] Support for both channels and MS runs in cXML -> mzTab

### PR DESCRIPTION
**Pull request by jpfeuffer**
Please wait for merge. I have to test it here, since my system is messed up because of two QT versions.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
+1

**Comment by timosachsenberg** [comment]
can you add the same interface for the other maps (id and feature)

**Comment by jpfeuffer** [comment]
Ok I will

**Comment by jpfeuffer** [comment]
Oh god.. what did I say?!

**Comment by timosachsenberg** [comment]
+1 if tests pass

**Comment by jpfeuffer** [comment]
Only stopwatch fails. Let's merge?

**Pull request merged**
