### PR TITLE
TSG without charge defaults

### PR DESCRIPTION
**Pull request by enetz**
as discussed in #2613 

Removed charge default values for getSpectrum() and set mincharge = 1 and maxcharge = 1 everywhere getSpectrum() was called without specifying the charge.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
+1

**Comment by hroest** [comment]
@enetz shouldnt we also test the function for other values of min/max charge?

**Comment by enetz** [comment]
@hroest  I only set the charge to 1 in those cases, where none was specified before, meaning where the previous default values were used. Of course we already had tests for other charges and charge ranges. Since the charge ranges were already explicitly set in those cases, I did not change them in this PR.

**Comment by hroest** [comment]
ok, great!

**Pull request merged**
