### PR TITLE
[FIX]: deprecated setBackgroundColor

### LINKED ISSUE #5989: warning: `void QTableWidgetItem::setBackgroundColor(const QColor&)` is deprecated
```
/home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/TableView.cpp: In member function ‘QTableWidgetItem* OpenMS::TableView::setAtBottomRow(QTableWidgetItem*, size_t, const QColor&, const QColor&)’:
/home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/TableView.cpp:262:29: warning: ‘void QTableWidgetItem::setBackgroundColor(const QColor&)’ is deprecated: Use QTableWidgetItem::setBackground() instead [-Wdeprecated-declarations]
  262 |     item->setBackgroundColor(background);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
In file included from /usr/include/qt/QtWidgets/QTableWidget:1,
                 from /home/USER/Development/OpenMs/src/openms_gui/include/OpenMS/VISUAL/TableView.h:37,
                 from /home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/TableView.cpp:35:
/usr/include/qt/QtWidgets/qtablewidget.h:142:17: note: declared here
  142 |     inline void setBackgroundColor(const QColor &color)
      |                 ^~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by Amit0617**
# Description

Fixes #5989 
# Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

## How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

</details>

## Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Is your contrib up to date?

**Comment by Amit0617** [comment]
> Is your contrib up to date?
Not when these pull requests were made. I spotted later.

**Comment by timosachsenberg** [comment]
Please update the submodules in your branch so they don’t show up as change

**Comment by Amit0617** [comment]
I would be required to create fresh branch then

**Comment by timosachsenberg** [comment]
no why? just take your branch, go in the submodule
checkout master there, commit that new hash in your local branch,
and push to this PR

**Comment by timosachsenberg** [comment]
something like
```
cd contrib
git checkout master
cd ..
git add contrib
git commit -m "update contrib to master"
git push origin develop19
```

**Review by timosachsenberg — APPROVED** [review]
looks good to me. I assume you checked that the new method was introduced in a Qt version we support.

**Comment by Amit0617** [comment]
was introduced in Qt 4.2. I hope things would be compatible in forward direction.

**Comment by Amit0617** [comment]
isn't there "a way" to use a particular version to compile things in Qt? So that if something is compiling without warnings or errors then it is version compatible

**Pull request merged**
