### PR TITLE
support QC of labeled experiments (iTRAQ/TMT) 

### PR DESCRIPTION
**Pull request by cbielow**
by just supplying the consensusXML to TOPP `QualityControl`.

This PR also separates some QC classes for a cleaner interface (FWHM, PeptideMass).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Would be a great time to look at https://github.com/OpenMS/OpenMS/issues/1260
and how this interferes with QC (e.g. number of quantified, ided spectra).

**Comment by cbielow** [comment]
g++ 4.8.4 from Travis does not like
```
std::map<UInt64, BaseFeature> new_feats;
for (const FeatureHandle& fh : cf.getFeatures())
{
  UInt64 index = fh.getMapIndex();
  new_feats.emplace(index, fh);   // <- cannot create the pair. There is a ctor from FeatureHandle to BaseFeature available
...
```
and fails to compile, see http://cdash.openms.de/viewBuildError.php?buildid=422916. All other compilers happily do it (as they should).
We could fix this by writing less efficient code, but honestly, this compiler is 6 years old now.
Now, to bring up this conversation again: can we get rid of GCC 4.8.4 at this point?
There is also other parts of OpenMS where we needed to do handstands: https://github.com/OpenMS/OpenMS/pull/4273/files

**Comment by cbielow** [comment]
rebuild jenkins

**Comment by cbielow** [comment]
ready for merge. Fails on Win are Comet-related...

**Comment by timosachsenberg** [comment]
@jpfeuffer do you agree that this is ready for merge or do we need some additional checks on how the input (merged vs. not merged) etc. is formated?

**Comment by jpfeuffer** [comment]
I think it will fail if you merged two TMT consensusXMLs but I don't know how often this happens.

**Comment by cbielow** [comment]
This is not how the workflow is currently handling this. only single itraq/tmt experiments are supported.
 ATM.
How hard would you guesstimate to make marging two consensusXMLs valid? There is probably a lot of traps... ??

**Comment by timosachsenberg** [comment]
I think the proper way would be to merge consensusXML column-wise as we do for the fractionated design (also see the FileMerger option) and adapt other code accordingly if necessary.

**Comment by timosachsenberg** [comment]
-append_method append_cols

**Pull request merged**
