### PR TITLE
[FIX] PyOpenMS macOS 11.5.1 (10.16)

### PR DESCRIPTION
**Pull request by oliveralka**
# Description

Small fix for linking of PyOpenMS with system libs (now located in the SDK)
see https://developer.apple.com/forums/thread/655588?answerId=665804022#665804022

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Hmm shouldn't the isysroot take care of it? We are investigating. Do not merge yet

**Comment by jpfeuffer** [comment]
Do you think this was needed in 10.14, too? Would it hurt?
We probably should switch to real version checking soon. The string comparison already fails for 10.9

**Comment by oliveralka** [comment]
As far as I know, the library change to the SKD was introduced in Big Sur (10.16) see link in the PR description.

**Comment by jpfeuffer** [comment]
To be honest, I think we were just lucky that only one SDK was installed all the time (or the most recent one was symlinked to /usr/lib). If the linker needs the sysroot, too to find the right libraries, then this was the case in earlier macOS', too. I would just try it with earlier macOS too. We have GitHub actions with 10.15 no?

**Comment by oliveralka** [comment]
Ok, then let's test it via the GitHub actions. I think it should work. 

Works locally for Big Sur.

**Comment by oliveralka** [comment]
Seems there are some other issues as well
```
(build_pyopenms_39) ➜  20210224_test pip install /Users/alka/Documents/work/software/openms_pyopenms/20210224_test/pyOpenMS/dist/pyopenms-2.7.0-cp39-cp39-macosx_11_0_x86_64.whl 
ERROR: pyopenms-2.7.0-cp39-cp39-macosx_11_0_x86_64.whl is not a supported wheel on this platform.
```
Have to investigate further. Was working before.

**Comment by oliveralka** [comment]
Set `osx_deployment_target` was added to ZLIB in the contrib:
https://github.com/OpenMS/contrib/pull/107

I guess the minimum would now be defined by qt (10.13). Should be fine. 

@jpfeuffer What do you think?

**Comment by jpfeuffer** [comment]
I think this PR is valid in any case. Makes sense that sysroot should go to the link args.

**Review by jpfeuffer — APPROVED** [review]

**Pull request merged**
