### PR TITLE
[ADD] Output SIRIUS workspace (AssayGeneratorMetabo)

### PR DESCRIPTION
**Pull request by oliveralka**
Outputs SIRIUS workspace to allow easier handling of fragmentation trees for decoy generation with passatuto. (Current solution.)

### CODE REVIEW

**Comment by oliveralka** [comment]
rebuild jenkins

**Comment by oliveralka** [comment]
@jpfeuffer I am not sure what happened here - rebuild again? 
https://abibuilder.informatik.uni-tuebingen.de/jenkins/job/openms_pr_ci/compiler=appleclang-9.0.0,os_label=highsierra/3102/console

**Comment by jpfeuffer** [comment]
No, consider it as passed. The tests ran but CDash was not responsive. Since there are no test errors, it means it is good to go. What about pyopenms? The usual memory leaks?

**Comment by oliveralka** [comment]
> What about pyopenms? The usual memory leaks?
Yes

**Comment by jpfeuffer** [comment]
+1 from me. But in the future, could one directly create the files in this workspace or can't you pass it to Sirius?

**Comment by oliveralka** [comment]
> +1 from me. But in the future, could one directly create the files in this workspace or can't you pass it to Sirius? 

Ok lets do it like this for now and I will think about an alternative e.g. passing the workspace to SIRIUS - the problem here is that sometimes it is not able to "merge" the workspace. Basically, if the same workspace is selected multiple times (e.g. multiple files), then SIRIUS might fail. 

Another alternative would be just to move instead of copying the directory.

**Comment by jpfeuffer** [comment]
I see. Ok

**Pull request merged**
