### PR TITLE
Add an additional style test for potential copies in loops

### PR DESCRIPTION
**Pull request by jpfeuffer**
Related to https://github.com/OpenMS/OpenMS/issues/4049

We should probably remove the thirdparty folder from the checks, so wait for merge.
And we could also remove all false positives first.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
See http://cdash.openms.de/viewTest.php?onlyfailed&buildid=308588

**Comment by hroest** [comment]
removal of false positives with `OMS_CODING_TEST_EXCLUDE`

**Comment by hroest** [comment]
down to 84 reports ...

**Comment by hroest** [comment]
down to 33 reports ...

**Comment by hroest** [comment]
down to 0 reports ...

**Pull request merged**
