### PR TITLE
Minor fixes for validity of mzIdentML

### PR DESCRIPTION
**Pull request by hendrikweisser**
Converted idXML files from the DeMix pipeline to mzIdentML. The results had some validation errors (`FileInfo -v`):
- the date cannot be empty (error: "illegal year value '0000-00-00T00:00:00'")
- "ModificationParams" must not be empty (error: "empty content is not valid for content model '(SearchModification+)'")

These problems are fixed here.

A remaining issue is that modifications that were used in the search - and do occur on the peptides - are not listed in the search parameters. However, the mzid files still validate.
There is code to pick up modifications from the peptides and add them to the search parameters in `PercolatorOutfile::getSearchModifications_`. Is there a class/header for "ID data convenience functions" where this could be moved to and reused?

### CODE REVIEW

**Comment by timosachsenberg** [comment]
hmm good question. Static function to extract from vector<PeptideIdentification> in PeptideIdentification.h?

**Comment by mwalzer** [comment]
But shouldn't all modifications looked for be in the SearchParameters regardless of them being present in some psms?

**Comment by hendrikweisser** [comment]
> But shouldn't all modifications looked for be in the SearchParameters regardless of them being present in some psms?

Yes, they should be, but there's no mechanism to ensure that. So you may get a file where this information is missing.

**Comment by hendrikweisser** [comment]
@timosachsenberg:
> Static function to extract from vector in PeptideIdentification.h?
Or we could add it to ProteinIdentification, since that's where the search parameters are stored. Maybe `ProteinIdentification::setSearchModificationsFromPeptides`?

**Comment by timosachsenberg** [comment]
Fine with me (though I afaik ProteinIdentifications did formerly not need to know PeptideIdentifications)

**Comment by hendrikweisser** [comment]
> ProteinIdentifications did formerly not need to know PeptideIdentifications

Which brings us back to the discussion about having an overall Identifications class. ;-)

**Comment by timosachsenberg** [comment]
we'll get back to that :) feel free to add it to PId now

**Comment by hroest** [comment]
well lets fix the validation errors first :-)

**Comment by hroest** [comment]
@hendrikweisser please merge with develop and try to make sure the tests pass..then we can merge!

**Comment by hendrikweisser** [comment]
I've merged "develop" and updated the idXML-to-mzid IDFileConverter test. I've noticed that "FileInfo -v" still gives validation errors for the resulting mzid:
```
File name: /nfs/t17_project/OpenMS/src/tests/topp/IDFileConverter_9_output.mzid
File type: mzid

Validating mzid file against XML schema version 1.1.0
Validation error in file '/nfs/t17_project/OpenMS/src/tests/topp/IDFileConverter_9_output.mzid' line 170 column 217: invalid character encountered
Validation error in file '/nfs/t17_project/OpenMS/src/tests/topp/IDFileConverter_9_output.mzid' line 179 column 30: element 'MzIdentML' declares duplicate identity constraint unique values
Validation error in file '/nfs/t17_project/OpenMS/src/tests/topp/IDFileConverter_9_output.mzid' line 182 column 31: element 'MzIdentML' declares duplicate identity constraint unique values
Validation error in file '/nfs/t17_project/OpenMS/src/tests/topp/IDFileConverter_9_output.mzid' line 185 column 33: element 'MzIdentML' declares duplicate identity constraint unique values
Validation error in file '/nfs/t17_project/OpenMS/src/tests/topp/IDFileConverter_9_output.mzid' line 200 column 34: element 'cvParam' is not allowed for content model '(PeptideEvidenceRef+,Fragmentation?,(cvParam|userParam))'
Validation error in file '/nfs/t17_project/OpenMS/src/tests/topp/IDFileConverter_9_output.mzid' line 204 column 216: invalid character encountered
Validation error in file '/nfs/t17_project/OpenMS/src/tests/topp/IDFileConverter_9_output.mzid' line 207 column 34: element 'cvParam' is not allowed for content model '(PeptideEvidenceRef+,Fragmentation?,(cvParam|userParam))'
Validation error in file '/nfs/t17_project/OpenMS/src/tests/topp/IDFileConverter_9_output.mzid' line 208 column 218: invalid character encountered
Validation error in file '/nfs/t17_project/OpenMS/src/tests/topp/IDFileConverter_9_output.mzid' line 211 column 34: element 'cvParam' is not allowed for content model '(PeptideEvidenceRef+,Fragmentation?,(cvParam|userParam))'
Validation error in file '/nfs/t17_project/OpenMS/src/tests/topp/IDFileConverter_9_output.mzid' line 216 column 13: identity constraint key for element 'MzIdentML' not found
Failed - errors are listed above!
```
The "invalid character" errors look like they come from "nan" entries where numeric values are expected.

**Comment by hendrikweisser** [comment]
> There is code to pick up modifications from the peptides and add them to the search parameters in `PercolatorOutfile::getSearchModifications_`. Is there a class/header for "ID data convenience functions" where this could be moved to and reused?

I think the best place to add this may actually be the class ModificationDefinitionsSet. I'll do so in a separate pull request.

**Comment by hendrikweisser** [comment]
Tests are green, I'm going to merge.

**Comment by hendrikweisser** [comment]
@mwalzer:
I'm seeing a lot of these validation errors now when I convert idXML to mzid:
> Validation error in file '/nfs/t17_project/OpenMS/src/tests/topp/IDFileConverter_9_output.mzid' line 200 column 34: element 'cvParam' is not allowed for content model '(PeptideEvidenceRef+,Fragmentation?,(cvParam|userParam))'

Any idea what those mean?

**Comment by mwalzer** [comment]
I am afraid, since mzid1.1 the PeptideEvidenceRef object does not support the ParamGroup (children of type cvTerm or userParam) anymore :(
But it might also be a cvParam from SpectrumIdentificationItem that is occurring before the Fragmentation element, if there is any.
Can't tell w/o the specific sample. Go over the concrete example together tomorrow?

**Comment by hendrikweisser** [comment]
> Can't tell w/o the specific sample. Go over the concrete example together tomorrow?

I may not have time tomorrow (group outing), but the specific example is the "IDFileConverter_9_output.mzid" test file in "src/tests/topp".

**Comment by mwalzer** [comment]
There are two things wrong _under_ SpectrumIdentificationResult:
* The measure elements in FragmentationTable do not have unique id's 
* PeptideEvidenceRef is _not_ optional anymore

**Comment by hendrikweisser** [comment]
@mwalzer: Thanks for checking this!
> PeptideEvidenceRef is not optional anymore

That's what links to the proteins, right? So what do you do if you don't have a protein association for a peptide?

**Pull request merged**
