### PR TITLE
[fix] add qc-cv legacy CVs

### PR DESCRIPTION
**Pull request by poshul**
# Description

Please include a summary of the change and which issue is fixed.

# Checklist:
- [ x ] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Thanks. Can you include a summary of the change and which issue is fixed so others can look up why this file has been added in the first place?

**Comment by axelwalter** [comment]
Good point. This applies to all tools that work with qcML files, like QcMLFile, QCExporter and QCImporter as well?!
QcMLFile provides fall back names for QC parameters that it does not find but using the legacy cv seems better.

**Review by oliveralka — APPROVED** [review]
Looks good.

**Comment by timosachsenberg** [comment]
is develop the right target branch?

**Comment by poshul** [comment]
> is develop the right target branch?

It should go into both develop and the release branch.

**Pull request merged**
