### PR TITLE
Feature/crux enzymes

### PR DESCRIPTION
**Pull request by hroest**
As discussed in #3114 this PR adds the Crux names and regexes of enzymes to Enzymes.xml. Unfortunately many of them do not map 1:1 to the Enzymes we already have so we need to create several new ones. For reference

```
$ crux tide-index
...
  [--enzyme no-enzyme|trypsin|trypsin/p|chymotrypsin|elastase|clostripain|cyanogen-bromide|iodosobenzoate|proline-endopeptidase|staph-protease|asp-n|lys-c|lys-n|arg-c|glu-c|pepsin-a|elastase-trypsin-chymotrypsin|custom-enzyme]
     Specify the enzyme used to digest the proteins in silico. Available enzymes
     (with the corresponding digestion rules indicated in parentheses) include
     no-enzyme ([X]|[X]), trypsin ([RK]|{P}), trypsin/p ([RK]|[]), chymotrypsin
     ([FWYL]|{P}), elastase ([ALIV]|{P}), clostripain ([R]|[]), cyanogen-bromide
     ([M]|[]), iodosobenzoate ([W]|[]), proline-endopeptidase ([P]|[]),
     staph-protease ([E]|[]), asp-n ([]|[D]), lys-c ([K]|{P}), lys-n ([]|[K]),
     arg-c ([R]|{P}), glu-c ([DE]|{P}), pepsin-a ([FL]|{P}),
     elastase-trypsin-chymotrypsin ([ALIVKRWFY]|{P}). Specifying --enzyme
     no-enzyme yields a non-enzymatic digest. Warning: the resulting index may
     be quite large. Default = trypsin.

...
```

### CODE REVIEW

**Comment by hroest** [comment]
@timosachsenberg this adds quite a batch of new enzymes, and I am not yet convinced whether we really want to add them or not as they seem to be unique to crux

**Comment by timosachsenberg** [comment]
Looks good.

**Comment by timosachsenberg** [comment]
I am not sure about these either but I would keep them in for now so a proper enzyme can be assigned.

**Comment by hroest** [comment]
well I have named them accordingly if they deviate from the OpenMS rule, either +X or /X when there are differences.

**Pull request merged**
