### PR TITLE
[NOP] remove boost unordered from residuedb

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by hroest** [comment]
:+1: if it compiles

**Comment by timosachsenberg** [comment]
now we get the error in a different class that also uses boost::unordered_map

**Comment by hroest** [comment]
I guess there are quite a few places

```
$ grep -R unordered src/openms | cut -f 1 -d ":" | uniq -c
      3 src/openms/source/ANALYSIS/OPENSWATH/MRMIonSeries.cpp
     13 src/openms/source/ANALYSIS/OPENSWATH/MRMAssay.cpp
      9 src/openms/source/ANALYSIS/MAPMATCHING/QTClusterFinder.cpp
      6 src/openms/source/DATASTRUCTURES/QTCluster.cpp
      8 src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMAssay.h
      1 src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMDecoy.h
      2 src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMIonSeries.h
      1 src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.h
      3 src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/QTClusterFinder.h
      8 src/openms/include/OpenMS/DATASTRUCTURES/QTCluster.h
      2 src/openms/include/OpenMS/CONCEPT/UniqueIdIndexer.h
      2 src/openms/include/OpenMS/CHEMISTRY/ResidueDB.h
      2 src/openms/include/OpenMS/CHEMISTRY/DigestionEnzymeDB.h
      3 src/openms/include/OpenMS/COMPARISON/CLUSTERING/HashGrid.h
      4 src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedClustering.h
```

**Comment by hroest** [comment]
so does this mean that we cannot use boost / std unordered_map at the same time due to MSVS?

**Pull request closed without merging**
