### PR TITLE
[TEST FIX] fix pyOpenMS tests

### PR DESCRIPTION
**Pull request by hroest**
fixes the python test

this would have to be backported to the master branch as well to go into the pyOpenMS 2.0 release

### CODE REVIEW

**Comment by timosachsenberg** [comment]
ok I merge it into master

**Comment by hroest** [comment]
currently, they are in the master-pyopenms branch

**Comment by timosachsenberg** [comment]
I merged the master-pyopenms into master
now I apply this patch one master (no full merge as it is based on recent develop)

**Comment by timosachsenberg** [comment]
just saw that is already in develop

**Pull request merged**
