### PR TITLE
[FEATURE] added option to filter single mass traces

### PR DESCRIPTION
**Pull request by timosachsenberg**
simple option to filter unassembled traces before writing them out.

### CODE REVIEW

**Comment by hroest** [comment]
do we need a 7MB test file for this?

**Comment by timosachsenberg** [comment]
No not really as it is already used in another test. I will remove the extra cooy

**Comment by timosachsenberg** [comment]
ok I removed it

**Comment by hroest** [comment]
> ok I removed it

not much point to it unless you squash the commits :-) now its still in the history - however since its duplicated, its compressed well ...

**Comment by timosachsenberg** [comment]
Git does store duplicated files as pointers to 1 file.

**Pull request merged**
