### PR TITLE
IDScoreSwitcher: new UTILS tool for dealing with scores on ID data

### PR DESCRIPTION
**Pull request by hendrikweisser**
This PR primarily adds a new utility for switching between scores stored as meta values in identification data (idXML). Useful e.g. in cases where different types of scores (PEPs, FDRs) are required at different steps in a pipeline.

Also included are some documentation and test improvements for related classes/tools, as well as a small fix in FidoAdapter. I've not made a separate PR for these as they are small changes and I'm reusing test files for testing IDScoreSwitcher.

### CODE REVIEW

**Comment by hendrikweisser** [comment]
On Travis, same situation as with https://github.com/OpenMS/OpenMS/pull/1481: Three builds worked fine, one failed the "TOPP_PeakPickerWavelet_3" test, which is completely unrelated to the changes here.

**Comment by timosachsenberg** [comment]
Hi @hendrikweisser thanks for the tool at it will solve some of our current problems.
I might note that we should consider a way to handle multiple scores consistently in OpenMS data structures, idXML and mzIdentML. It might be worth to discuss if in the future we should explicitly model multiple scores (e.g. a vector of float + CV term) instead of residing to meta values or if we should stick with the secondary scores encoded in meta values.
If we take a look at the controlled vocabulary we have CV terms for most scores and score types in the MS obo in place and they also have a defined score orientations.
A different solution would be to keep meta values but encode the CV term in the score name. That way we also could deduce the score orientation from the ontology.
That way "is/setHigherScoreBetter" is tracked by the score and its associated CV term itself and not by PeptideHit - which in my view would be the correct way to do this.

**Comment by hendrikweisser** [comment]
> I might note that we should consider a way to handle multiple scores consistently in OpenMS data structures, idXML and mzIdentML. It might be worth to discuss if in the future we should explicitly model multiple scores (e.g. a vector of float + CV term) instead of residing to meta values or if we should stick with the secondary scores encoded in meta values.

Yes, definitely. With the move to mzid as our primary format for ID data, we should adapt our library classes to store multiple scores directly - as a vector of float + CV term or perhaps as a vector of pointers to subclasses of a new "ID score" class (maybe we want to also store the allowed range for each score?).

> A different solution would be to keep meta values but encode the CV term in the score name. That way we also could deduce the score orientation from the ontology.

This currently happens when we convert mzid to idXML, but I think we should get away from doing this internally when we move to mzid as the default format. (Since we don't want to keep updating the idXML schema, we'll still have to use "UserParam" elements there.)


The main problem with allowing multiple scores is on the tool side. Tools that currently look at "the" score for sorting or filtering will have to be told explicitly which score (or scores?) to use if there's more than one. (The alternative would be to designate one score as the main one from the beginning - pretty much like we do now -, but this sacrifices flexibility, so I don't really like it.)

**Comment by hendrikweisser** [comment]
Travis results look okay; the one failed test in one build ("TOPP_PeakPickerWavelet_3") is unrelated.

**Comment by timosachsenberg** [comment]
+1

**Pull request merged**
