### PR TITLE
fix scan number extraction for merged spectra

### PR DESCRIPTION
**Pull request by t0mdavid-m**
## Description

For spectra created with `SpectraMerger` the native ids of scans get appended as comma separated values. In `SpectrumLookup::extractScanNumber()` this causes multiple subgroups to be matched even if only one is expected, resulting in misinterpretation of the second scan number as experiment number if the merged spectrum contains two scans or the return of `-1` if >2 scans were merged.

This PR ensures that the scan number of the first scan in the list of merged spectra is returned.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by t0mdavid-m** [comment]
I noticed that `SpectrumMerger` merges all scans into the last scan in the sequence. In order to keep it consistent I adjusted `extract_scan_number()` to report the scan number of the last native id in the sequence.

**Comment by timosachsenberg** [comment]
I think it is fine. I just wonder how fragile this is e.g., if we implement a merger that takes the middle spectrum etc.

**Comment by t0mdavid-m** [comment]
Yes good point I have wondered that as well. While it is a step up from the previous misinterpretation it effectively relies on an implementation detail. I am unsure how to avoid this though (without changing the function signature).

**Review by timosachsenberg — APPROVED** [review]

**Comment by KyowonJeong** [comment]
Look all good for me, in particular for the current mergers.

**Review by KyowonJeong — APPROVED** [review]
Looks all good. Much better than from me...

**Pull request merged**
