### PR TITLE
[FIX] changed path String parameter to input files

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Better to have file parameters as in the other third party adaptors. Also simplifies packaging a bit.

**Comment by hendrikweisser** [comment]
No! I don't like this.

**Comment by hendrikweisser** [comment]
It's idiotic to have a different, overly long parameter name for the same thing (path to the executable) in different wrappers.

**Comment by cbielow** [comment]
I think the change is warranted:
How am I supposed to know as user that I need to change '-exe' from
'FidoChooseParameters' to 'Fido' once I've set alpha and the other params explicitly.
This interdependency would not make sense IMHO.

**Comment by cbielow** [comment]
and different variable names for an executable make sense in different adapters for a common use case in TOPPAS:
If you want to make sure all adapters have equal parameters (e.g. variable mods for Xtandem and OMSSA) you can just use the Alt key to copy param values with identical names. You'd want this for common param settings, but not for the executables (which need to stay different obviously).
Might not be of particular interest in Fido, but applies to other search engine adapers. Just something to keep in mind.

**Comment by timosachsenberg** [comment]
Hi Hendrik,
sorry that this change upsets you but I also think there are good reasons to remove it.
The way it was it was rather ambigous. The string could be: empty, a path to a directory, a path to an executable or the name of an executable + path. This is awkward because a directory is not the same as an executable - in fact there are defined MIME types for executables but no generally accpedted MIME types for directories. In that line, being a string, a GUI can't automatically open a file dialog.
I also think that usability (which I think was your prime concern) is not increased by the additional smartness to create a complete the path to the executable. It is increased by packaging the executables, putting it in the path and using it if the parameter is not set. 
Having one parameter for every exectuable consistently named with the suffix _executable will easy the creation of e.g. KNIME packages in the future as this parameter is easily recognized by the common extension and can be masked without intervention - and if we don't want to mask it we can fill it with an input file.

**Comment by hendrikweisser** [comment]
> How am I supposed to know as user that I need to change '-exe' from 'FidoChooseParameters' to 'Fido' once I've set alpha and the other params explicitly.
> This interdependency would not make sense IMHO.

It's in the documentation. And in most cases you'd leave it empty or pass the directory that contains both executables.

You still have the interdependency even with two parameters, because only one of them is used (needs to be non-empty and correct), but which one depends on the other settings.

**Comment by hendrikweisser** [comment]
> sorry that this change upsets you but I also think there are good reasons to remove it.

I admit that I got upset upon seeing my nice parameter "exe" suddenly replaced by "fidochooseparameters_executable". But your reasoning makes sense, so I'm only going to shorten this parameter to "fidocp_executable" and otherwise leave things as they are. (I would have liked to shorten "executable" to "exe", but unfortunately there's already the precedent in the other tools.)

As a thought, maybe we should add a special file type or a flag for an executable input file, instead of relying on the (undocumented) convention of having names ending in "_executable" to identify them.

**Pull request merged**
