### PR TITLE
Fix/pychecker

### PR DESCRIPTION
**Pull request by jpfeuffer**
Cherry-picked commits from #1910.
Added another fix and redirected PR to master to include for Release preparation.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
+1

**Comment by hroest** [comment]
thanks, does it work now?

**Comment by jpfeuffer** [comment]
Manually on the OSX build machine that previously failed, yes.
I'll merge to see if the full test pipeline also works with it.

**Comment by hroest** [comment]
great, lets hope for the best :-)

**Pull request merged**
