### PR TITLE
[FEATURE] convenience functions, extending internal API

### PR DESCRIPTION
**Pull request by cbielow**
- ppm-error
 - (Rich)Peak(1/2)D C'Tors (explicit to avoid implicit conversion which might be undesired)
 - MSExperiment::set2Ddata with metadata arrays (such that meta data in mzML for example can be displayed in TOPPView)

### CODE REVIEW

**Comment by cbielow** [comment]
all tests pass, merge?

**Comment by timosachsenberg** [comment]
Sorry, I don't get what set2Ddata is really about ;) . For me the interface extension seems quite specialized to a specific use case. Can you give some examples of general use or would be an implementation as static function be better suited? 

Apart of that I think there might be some pyOpenMS stuff missing.
If you find time it would be great if you could do a quick scan over our codebase to see if the novel introduced ppm methods can replace some redundant code.

**Comment by timosachsenberg** [comment]
Wouldn't it be also a good idea to break this up a little. I think the more general use cases are adding a RichPeakSpectrum to an MSExperiment<Peak1D>. Also note that only MS1 is supported right now. IMHO it would make a lot of sense to also allow to e.g. transfer ion annotations to MS2 spectra. Also I don't see how the mass trace part nicely fits in - we have a class for mass trace that should be used if possible.

**Comment by cbielow** [comment]
> Wouldn't it be also a good idea to break this up a little. I think the more general use cases are adding a RichPeakSpectrum to an MSExperiment.

But this is EXACTLY what you can do: `exp.set2DData(myRichSpec);`. Granted, it will be an MS1 spectrum, but someone with a concrete use-case, can either change the MSlevel afterwards, or extend the signature of set2DData. I just don't see why it should be done prematurely.

**Comment by cbielow** [comment]
> Also I don't see how the mass trace part nicely fits in - we have a class for mass trace that should be used if possible.

This is not what you think it is: here, given a feature with mass traces/convex hulls as input, allow to convert not only it's monoisotopic peak, but also the isotopic envelop to and MS1 spectrum, to (for example) make it browsable in TOPPView using the 1d View.

**Comment by cbielow** [comment]
> Apart of that I think there might be some pyOpenMS stuff missing.

I'll have a look

**Comment by cbielow** [comment]
> If you find time it would be great if you could do a quick scan over our codebase to see if the novel introduced ppm methods can replace some redundant code.

Can do.

**Comment by cbielow** [comment]
test pass. Merge?

**Pull request merged**
