### PR TITLE
TOPP: exit on invalid keys AND values from commandline or INI file

### PR DESCRIPTION
**Pull request by cbielow**
Current status for all TOPP tools:
 1) reading non-existing parameters files just gives a warning
 2) reading invalid values (i.e. not within restrictions) from existing parameters will reset the value to default (just giving a warning)

This is true for commandline (CLI) and INI!

this is **BAD**, because:
 - for 1) the user could try to change parameters in the INI file, yet they have no effect (since they were removed in a prior version)
 - for 2) THIS IS REALLY BAD: the user might get behaviour he did not want at all, e.g. if a non-default value changed it, it will not be valid anymore and the user will get default behaviour (which he clearly did not want). Internal checks within TOPPBase were ineffective, because the default would have been set long before... bad bug.

This PR fixes both issues by printing an error and exiting early.

Its quite a huge PR, but the interesting stuff happens in 
832a176

Additionally, one can now adress subsection params for GenericWrapper from the commandline (if -type is provided; just providing an INI file will still not suffice).

**Results (works for both CLI and INI parameters):**
When running a TOPP tool with unknown parameters:
```
$ PeakPickerHiRes.exe -ini "M:/dev/oms2/src/tests/topp/degenerate_cases/PPHiRes_invalidParamName.ini"
Unknown (or deprecated) Parameter 'algorithm:invalidParamName' given in outdated parameter file! Update failed!
Parameters passed to 'PeakPickerHiRes' are invalid. To prevent usage of wrong defaults, please update/fix the parameters!
```
When running a TOPP tool with known parameters but invalid values:
```
$ PeakPickerHiRes.exe "-algorithm:report_FWHM_unit" "THISVALUEISINVALID"
Invalid string parameter value 'THISVALUEISINVALID' for parameter 'report_FWHM_unit' given! Valid values are: 'relative,absolute'. Updating failed!
Parameters passed to 'PeakPickerHiRes' are invalid. To prevent usage of wrong defaults, please update/fix the parameters!
```

### CODE REVIEW

**Comment by cbielow** [comment]
example of wrongly used CLI values in our own test:
https://github.com/OpenMS/OpenMS/commit/7090d24ebb77b424fb2db7b13f1a542fc14318bc
`/home/travis/build/OpenMS/OpenMS/_build/bin/DecoyDatabase "-test" "-in" "/home/travis/build/OpenMS/OpenMS/src/tests/topp/DecoyDatabase_1.fasta" "-out" "DecoyDatabase_2.fasta.tmp" "-decoy_string" "blabla" "-decoy_string_position" "prefix" "-append"`

Note that `-append` is a proper string param, and would have required `- append true/false` to be effective.

**Comment by cbielow** [comment]
ui,... tests passed.. even clang

comments?

**Comment by jpfeuffer** [comment]
Definitely a very important PR. I find it a bit confusing that parameters passed via an ini are called the "old" ones. Did I see that correctly?

**Comment by cbielow** [comment]
yeah, whenever update() comes across an invalid param, it will refer to it as 'old'.
Could not think of something better. Open for suggestions.

**Comment by timosachsenberg** [comment]
outdated

**Comment by cbielow** [comment]
ok, I renamed it.
Should be ready to merge then.

**Comment by cbielow** [comment]
all tests pass (even clang)

**Pull request merged**
