### PR TITLE
[FIX, BUILD] add OnDiscMSExperiment.h to sources.cmake

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by hroest** [comment]
:+1:

**Comment by timosachsenberg** [comment]
I added some more I can make the PR against master. 

By the way, I found out about this because the files are greyed out in CLion.

**Comment by hroest** [comment]
but I guess it was never really a problem for the build, more for the build system and the IDE?

**Comment by timosachsenberg** [comment]
I think it was no problem. Important are probably only the cpp files

**Comment by jpfeuffer** [comment]
Yes, from what I know, as long as the include directories are correctly set:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/CMakeLists.txt#L112
the cpps will find their headers. Nonetheless, IDE users will be grateful for this.

**Pull request merged**
