### PR TITLE
Fix phospho scoring

### PR DESCRIPTION
**Pull request by PetraGutenbrunner**
Following changes were necessary: 
* Limitations: if too many phosphorylation events and sites are in a peptide, the number of permutations gets extremely big. Because of this the calculation times takes extremely long and also the used memory is increasing rapidly. These limitations are now the same as in LuciPHOr.
* Adapt PhosphoScoring output format to LuciphorAdapter output format: the main score of the peptide hit is now the lowest AScore
* Per theoretical spectrum peak only one match to the experimental spectrum per window is allowed. Otherwise it can happen that the number of site determining ion matches are more than the number of site determining ion matches.
* Corrected calculation of number of matched peaks (iteration limit was set wrong)
if the peptide score of the two best scoring peptides is the same, Ascore is set to 0 because no further calculation is necessary, because the number of matched ions of the two peptides are the same. Therefore the algorithm can not tell which peptide is the better one. 
- Changes calculation of site determining ions:
  if two ion masses of the two best scoring theoretical spectra are matching, but another ion mass would also be within the tolerance, this ion within the tolerance should not become a site determining ion. Therefore I included a check if the next ions are also within the tolerance.

  Because of this the number of site determining ions of the two best scoring peptides can differ. Therefore for each peptide their specific number of site determining ions is used to calculate the cumulative binomial probability.

  E.g.: 441.209, 441.217 are all counted as one peak and 441.217 can not be seen as site determining ion
  441.209        441.209
  521.183        441.217

 If this is not considered minus Ascores can occur which is not correct. The scores should be >= 0.

- Test: Ascores changed because of different number of matching peaks
        Added test case for different number of site determining ions

### CODE REVIEW

**Comment by timosachsenberg** [comment]
I don't the explanation: "Otherwise it can happen that the number of site determining ion matches are more than the number of site determining ion matches." ;)

**Comment by PetraGutenbrunner** [comment]
Sorry :) it should mean that the calculated number of site determining ions can be more than actually possible. If the same mass in the theoretical spectrum matches two different peaks in the experimental spectrum I would get two matches, but this is not right, because I should only get one match for the theoretical spectrum mass.

**Comment by timosachsenberg** [comment]
sound good. May it happen that this leads to a skip of a theoretical peak that is not matched (e.g. because a b and y ion have, by chance, very similar masses)?

**Comment by PetraGutenbrunner** [comment]
I think you are right that it could happen that you loose a match. If in the theoretical spectrum b and y are very similar and b already got a match using th.findNearest(window[i].getMZ()); and if b is again the nearest peak although y would also be fine you will loose a match, because b is already matched.

**Comment by PetraGutenbrunner** [comment]
I will change the logic around, that the theoretical spectrum looks up in the experimental spectrum (window_reduced.findNearest(th[i].getMZ())), then every ion of the theoretical one should get a possible match

**Comment by timosachsenberg** [comment]
Sounds good!

**Pull request merged**
