### PR TITLE
[FEATURE] Make CMake work with coin from brew. Complete the vcpkg recipe.

### PR DESCRIPTION
**Pull request by jpfeuffer**
## Description

Allows building with just stuff from homebrew on macOS.
Allows building from just stuff from vcpkg on all platforms (only macOS Intel tested).

Future TODOs:
- Test packaging
- Test usage on other platforms (e.g., on CI)
- Deprecate contrib?

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Review by timosachsenberg — APPROVED** [review]

**Comment by jpfeuffer** [comment]
unfortunately coin-cbc recipe is missing in vcpkg, so this is not complete.

**Comment by jpfeuffer** [comment]
Win unrelated.

**Comment by timosachsenberg** [comment]
does it work now?

**Comment by jpfeuffer** [comment]
Yes. I was using the tool chain file. CLion generated everything once I had a vcpkg json in my folder.
It overwrites the find_package command such that it always searches in the vcpkg folders for packages first.
Problems were missing packages and incomplete CMake support by some.

**Comment by jpfeuffer** [comment]
Removing contrib will take quite some time. You probably need to implement some caching everywhere in CI since rebuilding Qt everytime is not scalable.

**Comment by timosachsenberg** [comment]
That is why I was asking about this FetchContent. As I understood you can configure it in a way that it first tries
to look for system installed libraries and only if missing uses vcpkg.
That way, you can install e.g. Qt from binaries (also in CI).

**Comment by jpfeuffer** [comment]
Hmm well there is a prefer_system_libs option but the problem is, how do you enforce that the same basic libraries are linked into all deps (zlib, bzip, libssl, ...)

**Comment by jpfeuffer** [comment]
Hmm well there is a prefer_system_libs option but the problem is, how do you enforce that the same basic libraries are linked into all deps (zlib, bzip, libssl, ...)

**Comment by jpfeuffer** [comment]
I think a cache on each machine or a central nuget cache would be safer.

**Pull request merged**
