### PR TITLE
[TEST/FIX] Try to fix crux tests by using reverse instead of shuffled

### LINKED ISSUE #3201: Cruxadapter failing on Mac
Not sure why yet. Outputs do not match. Maybe a sorting/random issue? Could be a different boost version there.

### PR DESCRIPTION
**Pull request by jpfeuffer**
Try to fix #3201

### CODE REVIEW

**Comment by jpfeuffer** [comment]
lnx passed, clang timed out, rest busy with the contrib PRs

**Comment by hroest** [comment]
seems like it worked on apple, even though there are unrelated test failures...

**Comment by jpfeuffer** [comment]
I still have some library crashes on mac yes. Windows Logstream failure is reoccuring again.
Compression tests were due to my stupid error that I just fixed in https://github.com/OpenMS/contrib/pull/65

**Comment by jpfeuffer** [comment]
rebuild win

**Comment by jpfeuffer** [comment]
rebuild win

**Comment by jpfeuffer** [comment]
rebuild jenkins

**Pull request merged**
