### PR TITLE
[FEATURE] correct return value for operator[]

### PR DESCRIPTION
**Pull request by hroest**
correctly use reference return value

### CODE REVIEW

**Comment by timosachsenberg** [comment]
cool this would also fix https://github.com/OpenMS/OpenMS/pull/4329 if we add it to AQInfo

**Comment by hroest** [comment]
no, not yet - but this is the first step towards a solution, but we need to also adopt autowrap to generate both `__setitem__` and `__getitem__` functions, which it currently does not do

**Comment by hroest** [comment]
this would probably only work together with https://github.com/uweschmitt/autowrap/pull/91

**Comment by jpfeuffer** [comment]
rebuild jenkins

**Comment by jpfeuffer** [comment]
seems like the autowrap PR was merged. What about this one?

**Comment by timosachsenberg** [comment]
ping

**Pull request merged**
