### PR TITLE
Feature/speclib

### PR DESCRIPTION
**Pull request by hroest**
spectral library work

- fixes tests for SpecLibSearcher
- creates tests for SpectraSTAdapter (test is not functional yet)
- allows MSPFile to read spectrast format

### CODE REVIEW

**Comment by hroest** [comment]
for some reason, the output file is empty when using the SpectraSTAdapter, I will have to investigate this further

**Comment by hroest** [comment]
@lukaszimmermann can you have a look at that test? Can you check whether it works on your machine?

**Comment by lukaszimmermann** [comment]
I am now on it

**Comment by lukaszimmermann** [comment]
@hroest  Can you give me a description of how this file was generated:
SpectrastAdapter_1_output.pep.xml 

How did you invoke spectrast and which version did you use?

**Comment by hroest** [comment]
@lukaszimmermann please see the new PR #2985 

I generated the output pep.xml by running the adaptor but I had several issues with SpectraST itself and the parsing of mzML files by the TPP (see also TPP compatibility flag). The input mzML is the same one used for the comet search, basically I took  the output of the comet search and turned it into a spectral library using SpectraST.

**Pull request closed without merging**
