### PR TITLE
[FIX] omp fix

### PR DESCRIPTION
**Pull request by hroest**
fixes for older openmp version

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Fixed it for Windows but might have broken Linux?

**Comment by jpfeuffer** [comment]
rebuild win

**Comment by jpfeuffer** [comment]
I want to have recent build files on our VM workspace, to test other issues.

**Comment by cbielow** [comment]
solved in #3022

**Comment by hroest** [comment]
thanks!

**Pull request closed without merging**
