### PR TITLE
Feature/metabo decharger neg

### PR DESCRIPTION
**Pull request by FabianAicheler**
Implemented negative mode.

Some of the more advanced inference of edges ( inferMoreEdges_()) and test whether proposed charge is testworthy (charge_testworthy()) are currently disabled for negative mode until further evaluation/testing.

### CODE REVIEW

**Comment by FabianAicheler** [comment]
Here the used test file and output

[features_slim.featureXML.txt](https://github.com/OpenMS/OpenMS/files/1034182/features_slim.featureXML.txt)

[neg_test_ini.ini.txt](https://github.com/OpenMS/OpenMS/files/1034191/neg_test_ini.ini.txt)
[neg_outcm.consensusXML.txt](https://github.com/OpenMS/OpenMS/files/1034183/neg_outcm.consensusXML.txt)
[neg_outfm.featureXML.txt](https://github.com/OpenMS/OpenMS/files/1034184/neg_outfm.featureXML.txt)
[neg_outpairs.consensusXML.txt](https://github.com/OpenMS/OpenMS/files/1034194/neg_outpairs.consensusXML.txt)
[neg_log.log.txt](https://github.com/OpenMS/OpenMS/files/1034185/neg_log.log.txt)

[pos_test_ini.ini.txt](https://github.com/OpenMS/OpenMS/files/1034192/pos_test_ini.ini.txt)
[pos_outcm.consensusXML.txt](https://github.com/OpenMS/OpenMS/files/1034186/pos_outcm.consensusXML.txt)
[pos_outfm.featureXML.txt](https://github.com/OpenMS/OpenMS/files/1034187/pos_outfm.featureXML.txt)
[pos_outpairs.consensusXML.txt](https://github.com/OpenMS/OpenMS/files/1034188/pos_outpairs.consensusXML.txt)
[pos_log.log.txt](https://github.com/OpenMS/OpenMS/files/1034189/pos_log.log.txt)

**Comment by hroest** [comment]
sounds good, some tests of the negative mode data would be nice (unit tests and black box tests)

**Comment by timosachsenberg** [comment]
The following tests FAILED:
	896 - src/openms/source/ANALYSIS/DECHARGING/MetaboliteFeatureDeconvolution.cpp_cpplint_test (Failed)

**Comment by hroest** [comment]
> sounds good, some tests of the negative mode data would be nice (unit tests and black box tests)

**Comment by FabianAicheler** [comment]
Who is codacy/bot and how can I kill it?...

I'll try to improve the pull quality(...) but blackbox tests will follow at a later date. For that I have to first wrap my head around the result output code of the Decharger.

**Comment by timosachsenberg** [comment]
maybe the problems it mentioned are tests we will disable. though we need to agree on that somehow.

**Comment by FabianAicheler** [comment]
I guess they're sensible, but add bloat. Not sure what to prefer.

**Comment by FabianAicheler** [comment]
Eeh, currently timeouts when(/after?) building COINOR.

Can we provide more computing power, or somehow disentangle the contrib build step? Or is it a real failure of the COINOR lib version used in the current pull requests?

**Comment by jpfeuffer** [comment]
I like the codacy checks. But yes, let's see if we can make it more silent (e.g. only the check beneath Travis)

**Comment by jpfeuffer** [comment]
I can not remember any change in the contrib. This is weird.

**Comment by jpfeuffer** [comment]
I removed the comments. But please always check the status.

**Comment by timosachsenberg** [comment]
I can change the comment settings of codacy

**Comment by jpfeuffer** [comment]
I changed that already. Also @FabianAicheler can you run valgrind on your tests. ASan is also failing for Decharger.

**Comment by FabianAicheler** [comment]
@jpfeuffer I will look into valgrind. But that has nothing to do with the build having timeouts right?

**Comment by jpfeuffer** [comment]
No I do not think so. Btw: Can you reproduce the timeouts locally?

**Comment by FabianAicheler** [comment]
The last time I built (a few days ago with current develop) on our abinode, there were no problems. But I'll do a new checkout of contrib and develop.

**Comment by FabianAicheler** [comment]
Test output
Checking .../MetaboliteFeatureDeconvolution.cpp...
Checking .../MetaboliteFeatureDeconvolution.cpp: DC_DEVEL...
/home/travis/build/OpenMS/OpenMS/src/openms/source/ANALYSIS/DECHARGING/MetaboliteFeatureDeconvolution.cpp:1268: style: The scope of the variable 'has_odd' can be reduced.
/home/travis/build/OpenMS/OpenMS/src/openms/source/ANALYSIS/DECHARGING/MetaboliteFeatureDeconvolution.cpp:1273: style: Variable 'has_odd' is assigned a value that is never used.

Maybe I'm too tired, but the error looks like a false positive to me. In addition, the sections were only modified to satisfy codacy -> conflicting expectations?

**Comment by timosachsenberg** [comment]
I think the style test is a false positive by cpplint. The newer version in codacy did not trigger the warning.

**Pull request merged**
