### PR TITLE
Updated documentation for source release 2.0.1

### PR DESCRIPTION
**Pull request by jpfeuffer**
Mainly added updated packages that are needed. Restructured a little bit.
Made the doxygen syntax comparable across different pages at some points.
Supersedes PR #1937. Will be merged to develop after release.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Wait for small amendment for BioDocker.

**Comment by hroest** [comment]
for now I would only mention Biodocker for Linux as I am not so sure how easy it is to run it on Windows. I think for Windows users, it is easier to get our compiled (nightly/release) binaries and not get the docker image

**Comment by FabianAicheler** [comment]
While I wouldn't expect problems with the dockertools for windows, I guess people thinking in Docker containers would also have a linux background/be comfortable with it. So either a separate section for docker in general or as a part of the linux section.

**Comment by hroest** [comment]
see also #1948

**Comment by jpfeuffer** [comment]
Perfect. This PR includes the mention of BioDocker on the install page of Linux. I think that is the way to go for now. It is easy to change later.
Will merge.

**Pull request merged**
