### PR TITLE
Test global definition of NOMINMAX

### PR DESCRIPTION
**Pull request by jpfeuffer**

### CODE REVIEW

**Comment by cbielow** [comment]
you can try it, but if the config.h header is included AFTER the problematic windows header, this will do nothing...

**Comment by jpfeuffer** [comment]
how can you include it from the beginning?

**Comment by cbielow** [comment]
new idea:
https://cmake.org/cmake/help/latest/command/add_definitions.html

this should work globally and be independent of include order

**Comment by jpfeuffer** [comment]
win-ci

**Comment by jpfeuffer** [comment]
labels do not work (builds after every comment) since the Jenkins plugin is complete crap

**Comment by jpfeuffer** [comment]
win-ci

**Comment by jpfeuffer** [comment]
win-ci

**Comment by jpfeuffer** [comment]
win-ci

**Comment by jpfeuffer** [comment]
Seems to work but we get a warning because of the macro redefinition in File.h/cpp. Should I remove the definitions in the files? What if the global compiler definition leads to problems someday?

**Comment by hroest** [comment]
it seems we are not the only ones that have this issue, so we are in good company: https://bugzilla.mozilla.org/show_bug.cgi?id=830801

> What if the global compiler definition leads to problems someday?

lets deal with it when happens?

**Comment by jpfeuffer** [comment]
win-ci

**Comment by jpfeuffer** [comment]
Ok seems to work. But there are a lot of failing tests.

**Comment by jpfeuffer** [comment]
Let's merge anyway. Seems to be another problem.

**Comment by jpfeuffer** [comment]
Solves #2649

**Pull request merged**
