### PR TITLE
start to unify traML vs TraML

### PR DESCRIPTION
**Pull request by bernt-matthias**
becomes anoying for autoconverters

seemingly traML is less common so I went for the majority

Seems that there are still some places left...

# Description

Please include a summary of the change and which issue is fixed.

Also please:
- Make sure that you are listed in the AUTHORS file
- Add relevant changes and new features to the CHANGELOG file

# Checklist:
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by hroest** [comment]
at least in OpenMS, currently `traML` is more often used:

```
$ grep -R setValidF src/topp/ src/utils/ | grep -c TraML
5
$ grep -R setValidF src/topp/ src/utils/ | grep -c traML
15
```

**Comment by timosachsenberg** [comment]
me too. better to go for traML

**Comment by bernt-matthias** [comment]
Maybe it would be a good idea then to check for file extensions in a case insensitive manner? Then one would have backward compatibility and no one needs to rename files and also automatic tool description converters would be happy.

**Comment by timosachsenberg** [comment]
thanks!

**Pull request merged**
