### PR TITLE
explicit notation for N- and C-termini

### LINKED ISSUE #1792: notation for N- and C-terminal modifications
We could use a notation which represents N- and C-termini explicitly. For example

```
nX ... Yc
```

A modification `(m)` can occur on the termini or side chains.

```
n(m)X ... Yc
nX(m) ... Yc
nX ... Y(m)c
nX ... Yc(m)
```

In our current notation, we cannot distinguish between the last two cases.

```
(m)X ... Y
X(m) ... Y
X ... Y(m)
X ... Y(m)
```

In addition, the new notation simplifies the search for terminal modifications by looking for substrings `n(m)` or `c(m)` in the amino acid sequence.

Should we  denote the termini explicitly?

### PR DESCRIPTION
**Pull request by lars20070**
Introduces dots `.` as explicit representation for N- and C-termini in peptide sequences.

Resolves #1792.

### CODE REVIEW

**Comment by hroest** [comment]
I have a few general comments

i) doesnt this notation clash with some that other people that use the dot notation to annotate the prev/next AA, e.g. writing `K.PEPTIDER.P` in order to indicate the position inside the protein? Or does this integrate well with it? e.g. could one use `K.(N-termmod)P(firstAAmod)EPTIDER(lastAAmod).(C-termmod)P` and it would parse correctly?

ii) could you add some tests of the new code path to `AASequence_test`, I somehow did not see them? Is the test case `.(MOD:00051)DFPIANGER.`? Can you add a C-terminal modification and test it as well?

iii) Could you add some documentation on how this really works?

iv) you still have failing tests:
```
The following tests FAILED:

	509 - MRMAssay_test (Failed)

	1752 - TOPP_OMSSAAdapter_1_out (Failed)

	1755 - TOPP_XTandemAdapter_1_out (Failed)

	1758 - TOPP_XTandemAdapter_3_out (Failed)

	1760 - TOPP_MyriMatchAdapter_1_out (Failed)
```

v) @grosenberger this will impact some of our traml files, see https://github.com/lars20070/OpenMS/blob/fix/TerminalMods/src/tests/topp/ConvertTSVToTraML_4_output.TraML#L22 but I dont think this will be a problem, right? This also means the .chrom.mzML will now have ids with dots in them, see here https://github.com/lars20070/OpenMS/blob/fix/TerminalMods/src/tests/topp/ConvertTSVToTraML_4_output.TraML#L103 but as long as we consistently use the same OpenMS version to create the libraries and the assays we should be fine.

vi) In general, would  we handle N/C terminal *protein* modifications the same way?

**Comment by timosachsenberg** [comment]
Hi @hroest.
 i) You are right. The notation was intentionally chosen to resemble the already existing notation with pre/post amino acid (e.g. K.PEPTIDER.P). I don't see it as a clash as the "." denotes the terminus in both notations. So far we don't parse pre/post from the string but this would be possible in the future. We could also think about omitting the "." if no terminal modifications are present. This would retain backward compatibility in most cases (all without terminal mods).

vi) protein terminal modifications would be encoded the same way. Note that we store information about the protein in our peptide evidence class and the same sequence of a peptide might map to internal or terminal parts of a protein.

**Comment by grosenberger** [comment]
@hroest Yes, there might be some challenges ahead with the downstream tools. But I don't see an alternative to the explicit notation.

**Comment by lars20070** [comment]
FYI, @timosachsenberg. Still looking for an exception that occurs when a C-term mod is specified. In that case, simple mods such as `(Phospho)` or `(Dimethyl)` are no longer found in `Modification
sDB`.
```
Error: Caught unexpected exception of type 'ElementNotFound' thrown in line 158 of file '/home/lars/Code/git/OpenMS/src/openms/source/CHEMISTRY/ModificationsDB.cpp' in function 'const OpenMS::ResidueModification& OpenMS::ModificationsDB::getTerminalModification(const OpenMS::String&, OpenMS::ResidueModification::Term_Specificity) const' - Message: the element 'Dimethyl' could not be found
```

**Comment by lars20070** [comment]
@grosenberger Do you want to use the new dot notation in `TraML`? See `peptideRef` in this example.
```
<Transition id="82_1_sp|P0C0L4|CO4A_HUMAN_AAANQMR_381.6818_346.1632" peptideRef="1_sp|P0C0L4|CO4A_HUMAN_.AAAN(Deamidated)QMR._2_-39.95">
```
Then I can include this change in this PR.

**Comment by grosenberger** [comment]
@lars20070 Sounds good. But since we are generating peptideRef using AASequence::toString(), this should already happen by default, right?

**Comment by lars20070** [comment]
Yep. You continue to use `AASequence::toString()` when writing `TraML` and no code change is necessary.

We need to update the `TraML` test files. How did you generate these files? Can we re-generate the `TraML` test files instead of writing an update script?

**Comment by grosenberger** [comment]
Ah yes, that should work and simplify the process. Exactly, those are K from Unimod: http://www.unimod.org/modifications_view.php?editid1=21

**Comment by lars20070** [comment]
@grosenberger Seems during
```
OpenMS::TargetedExperiment exp;
TraMLFile().load(OPENMS_GET_TEST_DATA_PATH("MRMAssay_reannotateTransitions_input.TraML"), exp);
TraMLFile().store(OPENMS_GET_TEST_DATA_PATH("MRMAssay_reannotateTransitions_input_NEW.TraML"), exp);
```
the `AASequence` constructor is never called. Consequently both old and new `TraML` are identical.
Do I need to call `reannotateTransitions()` first? Any advice?

**Comment by grosenberger** [comment]
I think the important line is here: https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/ANALYSIS/OPENSWATH/MRMAssay.cpp#L639

We assemble the peptide ID in this function. The simplest option might to have a helper function that generates the new id and sets it accordingly: https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/ANALYSIS/OPENSWATH/MRMAssay.cpp#L657

This should patch the files, right?

**Comment by lars20070** [comment]
Maybe @hroest has an alternative suggestion. - If not, I will use such a helper function or simply a script to update these twenty `TraML` files. Thanks for the quick answer, @grosenberger.

**Comment by lars20070** [comment]
@hroest Thanks for your good comments. - Hope with the reply from @timosachsenberg and my latest commits they are now all addressed.

**Comment by timosachsenberg** [comment]
As several others have pointed out, this is a rather intrusive change that may affect many downstream tools and scripts.
I would, therefore, like to gather some more opinions on the alternative of **writing** only dots if a terminal modification is contained in the sequence. Note that the current code for **reading** accepts both formats.

**Comment by hroest** [comment]
hmm, I feel that can lead to even more inconsistency if the dots are there sometimes and sometimes not...just out of curiosity, one would *always* get the old behaviour back of one just uses regex to remove all dots in the sequence? I think that is an effort that is not too much to ask, and easy to implement is somebody needs to have the previous behaviour

**Comment by lars20070** [comment]
Yes. Removing the dots in the sequence leads to the old notation. If we announce the new notation on the developer mailing list, this change shouldn't be that difficult. https://github.com/OpenMS/OpenMS/issues/1792#issuecomment-185110099

**Comment by lars20070** [comment]
The new notation would be useful for the analysis of our C-terminomics data.
http://www.nature.com/nmeth/journal/v7/n7/full/nmeth.1467.html
Can we merge this PR?

**Comment by timosachsenberg** [comment]
I think we need more feedback

**Comment by enetz** [comment]
Are there any specific objections to merging this?
This might also help with a clear representation of protein-protein cross-linking, since there are reagents that target side chains and protein termini.
As @timosachsenberg suggested, writing the dots only if a terminal modification is actually contained in the sequence sounds like a good idea to me, as existing code that does not use terminal modifications might be less disturbed this way.

**Comment by timosachsenberg** [comment]
Now that we are able to write out TPP style bracket strings in AASequence (toBracketString(..)) and these use n and c as terminus delimiter, we might think about using them as well.

**Comment by timosachsenberg** [comment]
don't merge before the release

**Comment by timosachsenberg** [comment]
I synchronized it and opened a new pull request:
https://github.com/OpenMS/OpenMS/pull/2333

**Pull request closed without merging**
