### PR TITLE
[FIX] extra params for the Crux tool

### PR DESCRIPTION
**Pull request by hroest**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Ah sorry, I forgot to logout on the win machine. I will rebuild when the others are done.

**Comment by jpfeuffer** [comment]
But cool, this will solve the CMake warning.

**Comment by timosachsenberg** [comment]
rebuild jenkins

**Comment by jpfeuffer** [comment]
Looks good. Cmake had hiccup with parallel building. False positive.

**Comment by timosachsenberg** [comment]
+1

**Pull request merged**
