### PR TITLE
Fix clang ci

### PR DESCRIPTION
**Pull request by timosachsenberg**
## Description

- fix some svm related fluctuations in tests.
- update ci and build instructions

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
only test failing now is: https://cdash.openms.de/test/11715971
which could be glpk related

**Comment by timosachsenberg** [comment]
```
checking MRMFeatureSelectorScore() ... 
: passed

checking ~MRMFeatureSelectorScore() ... : passed
Warning: no subtests performed in '~MRMFeatureSelectorScore()' (line 70)!

checking MRMFeatureSelectorScore::selectMRMFeature() ... 
: passed

checking removeSpaces_() ... 
: passed

checking constructTargTransList_() ... 
: passed

checking weightScore_() ... 
: passed

checking computeScore_() ... 
: passed

checking batchMRMFeaturesQMIP() integer ... 


START DEBUG INFO
[0]		5-HTP		2.03216
[0][0]		5-HTP		29.5228353632885
[0][1]		5-HTP2		29.5228353632885
[1]		Acetylserotonin		5.07083
[1][0]		Acetylserotonin		30.768488494563702
[1][1]		Acetylserotonin2		30.768488494563702
[2]		Acetyltryptamine		6.96528
[2][0]		Acetyltryptamine		28.4325753928028
[2][1]		Acetyltryptamine2		28.4325753928028
[3]		Melatonin		6.96528
[3][0]		Melatonin		28.4325753928028
[3][1]		Melatonin2		28.4325753928028
[4]		Riboflavin		5.07083
[4][0]		Riboflavin		30.768488494563702
[4][1]		Riboflavin2		30.768488494563702
[5]		Serotonin		1.78709
[5][0]		Serotonin		22.6054459245013
[5][1]		Serotonin2		22.6054459245013
[6]		Tryptamine		3.43251
[6][0]		Tryptamine		37.969307969562699
[6][1]		Tryptamine2		37.969307969562699
[7]		Tryptophan		3.43251
[7][0]		Tryptophan		37.969307969562699
[7][1]		Tryptophan2		37.969307969562699
END   DEBUG INFO

: passed

checking batchMRMFeaturesQMIP() continuous ... 
 -  line 312:  TEST_EQUAL(output_selected.size(),11): got '12', expected '11'
 -  line 330:  TEST_REAL_SIMILAR(f->getMetaValue("peak_apex_int"),0.0): got 10313.5, expected 0 (absolute: 10313.5 [1e-05], relative: 0 [1.00001], message: "number_1 is not zero, but number_2 is"
 -  line 331:  TEST_STRING_EQUAL(f->getMetaValue("native_id"),"cytd.cytd_1.Heavy"): got "citr-L.citr-L_1.Heavy", expected "cytd.cytd_1.Heavy"
 -  line 332:  TEST_REAL_SIMILAR(f->getRT(),1.4385963780721): got 0.96764163869222, expected 1.4385963780721 (absolute: 0.47095473937988 [1e-05], relative: 1.48670367266996 [1.00001], message: "ratio of numbers is large"
: failed

checking batchMRMFeaturesQMIP() continuous but smaller experiment ... 


START DEBUG INFO
[0]		5-HTP		2.03215546258545
[0][0]		5-HTP		29.5228353632885
[0][1]		5-HTP2		29.5228353632885
[1]		Acetylserotonin		5.07082551965332
[1][0]		Acetylserotonin		30.768488494563702
[1][1]		Acetylserotonin2		30.768488494563702
[2]		Acetyltryptamine		6.96528256036377
[2][0]		Acetyltryptamine		28.4325753928028
[2][1]		Acetyltryptamine2		28.4325753928028
[3]		Melatonin		6.96528256036377
[3][0]		Melatonin		28.4325753928028
[3][1]		Melatonin2		28.4325753928028
[4]		Riboflavin		5.07082551965332
[4][0]		Riboflavin		30.768488494563702
[4][1]		Riboflavin2		30.768488494563702
[5]		Serotonin		1.78708603594971
[5][0]		Serotonin		22.6054459245013
[5][1]		Serotonin2		22.6054459245013
[6]		Tryptamine		3.43251273956299
[6][0]		Tryptamine		37.969307969562699
[6][1]		Tryptamine2		37.969307969562699
[7]		Tryptophan		3.43251273956299
[7][0]		Tryptophan		37.969307969562699
[7][1]		Tryptophan2		37.969307969562699
END   DEBUG INFO

: passed

checking (created temporary files)...
: passed

Output of successful tests were suppressed. Set the environment variable 'OPENMS_TEST_VERBOSE=True' to enable them.
FAILED
Failed lines: 312 330 331 332 
Using solver 'coinor' ...
Optimal solution found!
<Optimal solution found!> occurred 18 times
<Using solver 'coinor' ...> occurred 18 times
```

**Comment by timosachsenberg** [comment]
@dmccloskey or @jpfeuffer I think the failing test is related to the solver used.
```
 -  line 312:  TEST_EQUAL(output_selected.size(),11): got '12', expected '11'
 -  line 330:  TEST_REAL_SIMILAR(f->getMetaValue("peak_apex_int"),0.0): got 10313.5, expected 0 (absolute: 10313.5 [1e-05], relative: 0 [1.00001], message: "number_1 is not zero, but number_2 is"
 -  line 331:  TEST_STRING_EQUAL(f->getMetaValue("native_id"),"cytd.cytd_1.Heavy"): got "citr-L.citr-L_1.Heavy", expected "cytd.cytd_1.Heavy"
 -  line 332:  TEST_REAL_SIMILAR(f->getRT(),1.4385963780721): got 0.96764163869222, expected 1.4385963780721 (absolute: 0.47095473937988 [1e-05], relative: 1.48670367266996 [1.00001], message: "ratio of numbers is large"
```
Do you know what is correct here? coinor seems to select one additional compound, and also the peak apex int is suddenly non-zero.

**Comment by jpfeuffer** [comment]
Isnt Coin or always preferred?

**Comment by jpfeuffer** [comment]
You can easily query the solver that is used.

**Comment by timosachsenberg** [comment]
it says using solver coinor

**Comment by jpfeuffer** [comment]
I think it uses coinor on the other ci platforms too. This will be a version/determinism problem.

**Comment by timosachsenberg** [comment]
Merge because it fixes two errors. One remaining

**Pull request merged**
