### PR TITLE
Try fixing pyopenms on win with GH actions

### PR DESCRIPTION
**Pull request by jpfeuffer**
Since they upgraded to VS2019 update 16.6,
our builds fail. This is a PR with attempts to fix this.
In the beginning, I revert some changes that I tried with direct commits.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Actually I have no idea about what happens. I just keep this PR if someone finds/knows something.
Until then, no pyopenms nightlies.

**Comment by oliveralka** [comment]
I found a comment, that it was necessary to update `setuptools` before pip. (https://stackoverflow.com/questions/44951456/pip-error-microsoft-visual-c-14-0-is-required)

We are currently not doing that see line 81 (https://github.com/OpenMS/OpenMS/blob/c1e815d875c704cd6a7933def9a10e02e1435967/.github/workflows/pyopenms-wheels.yml#L81)

**Comment by jpfeuffer** [comment]
Yeah, I am pretty sure that 2019 should work (since it worked before, e.g. ~1 week ago). Github "just" updated the version from 16.5 to 16.6 (which included a slightly newer compiler version).
To add to the confusion, if I deactivate conda env beforehand, 3.6 fails already. Now after reverting, 3.6 passes but 3.7 fails..

I don't think we can do much here but hope that people will have a similar problem. I don't even know where to start raising issues: github? setuptools? pip? Microsoft?

**Comment by oliveralka** [comment]
I have also seen these issues maybe they are related:

```
Building Custom Rule D:/a/OpenMS/OpenMS/OpenMS/src/openms/CMakeLists.txt

LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library [D:\a\OpenMS\OpenMS\bld\src\openms\OpenMS.vcxproj]
EXEC : warning : cannot resolve item 'OpenSwathAlgo.dll' [D:\a\OpenMS\OpenMS\bld\src\pyOpenMS\prepare_pyopenms_libs.vcxproj]
EXEC : -- warning : gp_resolved_file_type non-absolute file 'OpenSwathAlgo.dll' returning type 'other' -- possibly incorrect [D:\a\OpenMS\OpenMS\bld\src\pyOpenMS\prepare_pyopenms_libs.vcxproj]
EXEC : warning : cannot resolve item 'OpenMS.dll' [D:\a\OpenMS\OpenMS\bld\src\pyOpenMS\prepare_pyopenms_libs.vcxproj]
  possible problems:
      need more directories?
      need to use InstallRequiredSystemLibraries?
      run in install tree instead of build tree?
```
I guess let's wait for a day or two and see if someone has the similar problems.

**Comment by jpfeuffer** [comment]
Yes I was confused at first, too by these warnings, but I think I checked and they were there before, when it worked as well.

**Comment by oliveralka** [comment]
@jpfeuffer It seems that the compiler is not found - other had a similar issue, but I am not sure if we can fix it the same way:

https://github.com/python-pillow/Pillow/pull/4201

**Comment by jpfeuffer** [comment]
The thing is, we already used windows-2019 successfully before.
Seems more like they messed up the components during the update of VS on that environment:
https://github.com/actions/virtual-environments/issues/1028

**Comment by oliveralka** [comment]
Read a comment, that it worked for someone after installing the "Desktop development with C++" for VS2019 (https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2019).

It seems that python 3.6 builds correctly, but afterwards, 3.7 throws the error.

**Comment by jpfeuffer** [comment]
Indeed, very weird. That's why I am starting to doubt that it is a missing component but maybe a setuptools incompatibility?

**Comment by oliveralka** [comment]
Yes, I also stumbled over the issue you already commented on:
https://github.com/pypa/setuptools/issues/2028

I guess we can wait for a bit longer and see what comes out of it.

**Comment by jpfeuffer** [comment]
Unfortunately, I cant even reproduce on a simple example. So it is related to our complex setup.
https://github.com/jpfeuffer/hello-github-actions/runs/780323701?check_suite_focus=true

**Comment by jpfeuffer** [comment]
I am starting to think it has something to do with conda. Conda also installs a "vc" package together with its python.
We probably should test it with conda on a local Windows machine at some point to rule out errors there.

**Comment by oliveralka** [comment]
Yes, I saw that as well, what we could try is:
Activate conda-env
Install needed packages
Deactivate conda-env
Add only the python executable path to CMake (-DPYTHON_EXECUTABLE:FILEPATH=C:/Python33/python.exe)

Then we would not stay in the conda environment. What do you think?

**Comment by mattip** [comment]
Maybe the conda install of vs tools is changing values in the registry in a way that now requires conda to be activated in order to find the tools?

**Comment by jpfeuffer** [comment]
So this is the problem: https://github.com/pypa/setuptools/blob/8d508965e49028b68e09b930a10340ba09687d35/setuptools/msvc.py#L272

It works outside of CMake. And it worked some time ago. I don't know what happens here.

**Comment by mattip** [comment]
Maybe one of your environment variables (like PATH) is getting close to the limit, and running vcvarsall inside CMake pushes it over the limit? The problem is that stderr is being swallowed. Could you modify your version of setuptools to call `check_output` with `stderr=subprocess.STDOUT` (you may need `shell=True` as well) to catch the actual error?

**Comment by jpfeuffer** [comment]
So, if I decode manually it says:
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.7.2
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
The input line is too long.
The syntax of the command is incorrect.
```

**Comment by jpfeuffer** [comment]
Which confirms your idea @mattip .
However, I do not exactly understand why calling it from inside CMake makes a difference.
According to https://developercommunity.visualstudio.com/content/problem/257260/vcvarsallbat-reports-the-input-line-is-too-long-if.html you are also not supposed to call it repeatedly, but I cannot avoid it since setuptools does it internally.

**Comment by mattip** [comment]
Can you trim some of the PATH components before the step?

**Comment by jpfeuffer** [comment]
Thanks, it worked. And I know that "clearing" parts of the path is the better idea but not nice either. Fiddling with the PATH with a rather hardcoded hack will break the workflow whenever GitHub updates their runners.

**Comment by mattip** [comment]
Maybe open an issue on the image repo https://github.com/actions/virtual-environments/issues

**Comment by jpfeuffer** [comment]
superseded by simple commit 571d820633365b43aec243bb9829df8a61358fce

**Comment by jpfeuffer** [comment]
Thanks a lot for reporting back! Maybe we can use your env var trick, too. It looks a lot cleaner than trying to reduce the PATH.

**Pull request closed without merging**
