### PR TITLE
Feature/decharger no glpk

### PR DESCRIPTION
**Pull request by FabianAicheler**
Switches to coinor as default ILP solver (to conform to "OpenMS all BSD 3-clause"). Removal of glpk lib and referrals at later point.

### CODE REVIEW

**Comment by hroest** [comment]
seems like it is not running on travis:

```

CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:91 (MESSAGE):
  Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY
  COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY
  COIN_OSI_CLP_LIBRARY)
```

**Comment by FabianAicheler** [comment]
I made the changes on a clean clone with the contrib from https://open-ms.svn.sourceforge.net/svnroot/open-ms/contrib

Successfully built and ran on scientific linux 7 without problems. I guess we should fix the travis build to find/use COINOR

**Comment by timosachsenberg** [comment]
related to https://github.com/OpenMS/OpenMS/issues/1985

**Comment by timosachsenberg** [comment]
can you merge against  current develop?

**Comment by FabianAicheler** [comment]
So how do we continue? I am out of ideas, what else to do to get it through Travis. All I know is that it builds and works consistently for me for Windows (8.1 with VS 2015) and Linux.

**Comment by hroest** [comment]
```

-- Found Boost version 1.55.0
-- Found SEQAN: /home/travis/build/OpenMS/OpenMS/contrib/include (found suitable version "1.4.1", required is "1.4.0")
-- Found LIBSVM: /usr/lib/libsvm.so (found suitable version "3.1.0", required is "2.91")
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:91 (MESSAGE):
  Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY
  COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY
  COIN_OSI_CLP_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:252 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindCOIN.cmake:80 (find_package_handle_standard_args)
  src/openms/cmake_findExternalLibs.cmake:90 (find_package)
  src/openms/CMakeLists.txt:63 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by hroest** [comment]
maybe you need to add it here: https://github.com/OpenMS/OpenMS/blob/develop/tools/travis/lnx-cibuild.before.sh#L32

```
build_contrib COINOR
```

**Comment by hroest** [comment]
looks like it worked and gets built but the test is still failing:

```
The following tests FAILED:

	 50 - LPWrapper_test (Failed)
```

**Comment by hroest** [comment]
still fails

```

checking (double getObjectiveValue()) ... 
 -  line 431:  TEST_REAL_SIMILAR(lp.getObjectiveValue(),2): got 0, expected 2 (absolute: 2 [1e-05], relative: 0 [1.00001], message: "number_1 is zero, but number_2 is not small"
: failed

checking (double getColumnValue(Int index)) ... 
 -  line 437:  TEST_REAL_SIMILAR(lp.getColumnValue(0),2): got 0, expected 2 (absolute: 2 [1e-05], relative: 0 [1.00001], message: "number_1 is zero, but number_2 is not small"
 -  line 438:  TEST_REAL_SIMILAR(lp.getColumnValue(1),2): got 1, expected 2 (absolute: 1 [1e-05], relative: 2 [1.00001], message: "ratio of numbers is large"
: failed

checking (Int getNumberOfNonZeroEntriesInRow(Int idx)) ... 

FAILED
Failed lines: 431 437 438 
Using solver 'coinor' ...
Optimal solution found!
<Optimal solution found!> occurred 3 times
<Using solver 'coinor' ...> occurred 3 times
Coin-Or only knows Integer variables, setting variable to integer type
```

**Comment by timosachsenberg** [comment]
so this is good to merge now?

**Comment by FabianAicheler** [comment]
In my opinion yes

**Pull request merged**
