### PR TITLE
[FIX] attempt to fix compile error on windows

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
only PPWavelet failed

**Comment by cbielow** [comment]
why do we need `! defined(OPENMS_COMPILER_GXX)`?
will `! defined(__PRETTY_FUNCTION__)` return false for GXX because its not a macro?!

**Comment by cbielow** [comment]
+1

**Comment by timosachsenberg** [comment]
on gcc: The compiler automagically replaces the identifiers with a string literal containing the appropriate name. Thus, they are neither preprocessor macros, like __FILE__ and __LINE__, nor variables. This means that they catenate with other string literals, and that they can be used to initialize char arrays.

**Comment by jpfeuffer** [comment]
+1 can only get better on windows. If we merge I can test it more easily with the nightly build scripts.

**Comment by timosachsenberg** [comment]
ok lets try it and see if it works

**Pull request merged**
