### PR TITLE
Feature/enable as

### PR DESCRIPTION
**Pull request by hroest**
- remove the gcc split between TOPP and class tests as we now use docker 
- enable Address Sanitizer for the clang-linux builds
- build OS X and no-gui clang without Address Sanitizer

### CODE REVIEW

**Comment by hroest** [comment]
please merge #1642 first

**Comment by timosachsenberg** [comment]
cool

**Comment by timosachsenberg** [comment]
maybe related to this: http://cdash.openms.de/testDetails.php?test=27773817&build=147464

**Comment by hroest** [comment]
hmm interesting, it seemed that initially it all worked and we got a green light from travis? strange, no? 

anyways, PPW3 is maybe not stable enough so we may have to disable it with AS, see #1649

**Pull request merged**
