### PR TITLE
[Fix,Build] Superhirn long test names

### PR DESCRIPTION
**Pull request by jpfeuffer**
Addresses #2136.
Only changes executable (object) and test names, not the actual file names. Not sure if this is the right way to go but it leaves information in the filenames at least.
Anyway it only concerns class_tests.

Also adds a note in the docu about long path names in the build directory.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
+1

**Comment by cbielow** [comment]
mhh.. I dont like these kind of "lets use the build system to fix a problem which originates somewhere else' solutions because:
 - it makes the build system more complex
 - filenames vs. executablenames do not match any longer (what is the name of the make target now and how should a new user know it?)

Why not just shorten the filenames/classnames?! That would be clean IMHO.

**Comment by hendrikweisser** [comment]
I agree with Chris. As an additional argument, if we remove SuperHirn in the future (#2094), we would have to remember to undo these changes in the build system.

**Comment by jpfeuffer** [comment]
Okay. I renamed the source files instead. Basically a batch rename to remove FeatureFinderAlgorithmSH since it is redundant imho. Should not be a big impact concerning that they are class_tests and it is a seldomly used tool.

**Comment by timosachsenberg** [comment]
I think its a valid solution that solves the problem. +1 for merge

**Pull request merged**
