### PR TITLE
[FIX,TEST] attempt to fix PeakPickerWavelet_3 test

### PR DESCRIPTION
**Pull request by hroest**
I will jus try to see what it takes to fix travis and the PeakPickerWavelet_3 test

### CODE REVIEW

**Comment by hroest** [comment]
it seems that PPWavelet_3 uses the "two_dimensional" optimization which turns on the `real_2D_` in `OpenMS/TRANSFORMATIONS/RAW2PEAK/TwoDOptimization.h`. The issue is that I am currently unable to reproduce the issue on my ubuntu 12.04 and 14.04 machines, so I am wondering where the problem comes from.

The code has been substantially altered during the GSL -> Eigen transition but otherwise not been modified since 2011.

**Comment by hroest** [comment]
The last time it still worked was at PR #1470:

- PR #1470 4c6718a6eb31f52761f4dae92ba5a0dca7c505d4 was working on 2015-06-16 https://travis-ci.org/OpenMS/OpenMS/builds/67040656
- PR #1474 05437d87988bc7e8c5fb935c643bd3b2d4ededec failed on 2015-06-17  https://travis-ci.org/OpenMS/OpenMS/builds/67203398
- PR #1475 facd8fe480c3cd2acbaa29988823099b34d6e951 failed on 2015-06-19 https://travis-ci.org/OpenMS/OpenMS/builds/67537191

it seems that PR #1474 is completely unrelated to the problem in PPWavelet. Was there any change in the Eigen library at the same time?

**Comment by hroest** [comment]
Interestingly, running a branch of 4c6718a on travis worked

- 4c6718a on travis: https://travis-ci.org/OpenMS/OpenMS/builds/74475330 == WORKED
- 05437d8 on travis https://travis-ci.org/OpenMS/OpenMS/builds/74486725
- facd8fe on travis: https://travis-ci.org/OpenMS/OpenMS/builds/74486902

**Comment by cbielow** [comment]
4c6718a also worked when originally applied, so why would a branch fail?! 
(I probably miss something here).

Can ANYONE reproduce the failing PeakPicker test and locally debug it?!

**Comment by hroest** [comment]
Some more information on what worked and what did not work:

- facd8fe Merge pull request #1475   :-1: 74486902
- a944384 [FIX, FEATURE] GaussFitte 
- 05437d8 Merge pull request #1474   :-1:  74486725
- e4033a2 [FIX, DOC, INTERNAL] fixe 
- efc4737 fixed compiler warning    
- b541ff9 allow File::find() to wor 
- 4c6718a Merge pull request #1470  :+1: 74475330
- 7bfe21c Merge pull request #1472  -- probably unrelated
- bc0521f fixed scroll bug for 'lef 
- 87d0a3a [INTERNAL] class test fix 
- 61393db [INTERNAL] default params 
- 445d16c [INTERNAL] default params 
- b7ba1b2 Merge pull request #1467  -- probably unrelated 
- 0cbb173 fixed possible undefined  
- 6fb7a77 comment out unused variab 
- 0abd7b2 TOPPView: enable viewing  
- 4109ec5 Merge pull request #1465  :+1: 74733192
- dc28366 Merge pull request #1464  :+1: 74732974
- ...
- 171ebb4 Merge pull request #1455  :+1: 74732779  74732899


numbers are travis build ids, access with https://travis-ci.org/OpenMS/OpenMS/builds/xxx

**Comment by hroest** [comment]
It still seems strange to me that PR  #1474 and  possibly #1475 would cause that behavior. I have now tried to push a few more builds to travis: 

- fe8e04c Merge pull request #1563 w/o pulls 1474-1475 :-1: 76154200 (clang + gcc)
- Merge pull request #1564
- Merge pull request #1562
- Merge pull request #1561
- Merge pull request #1560
- Merge pull request #1556
- Merge pull request #1554
- d7b0e42 Merge pull request #1553 w/o pulls 1474-1475 :-1: 76154087 (clang + gcc)
- Merge pull request #1545
- Merge pull request #1551
- Merge pull request #1542
- Merge pull request #1458
- Merge pull request #1539
- d19ac15 Merge pull request #1531 w/o pulls 1474-1475 :+1:  76153301 , 76152976
- Merge pull request #1532 first attempt to fix ppwave
- Merge pull request #1533
- Merge pull request #1508
- Merge pull request #1529
- Merge pull request #1520
- Merge pull request #1526
- Merge pull request #1522
- Merge pull request #1519
- Merge pull request #1492
- Merge pull request #1440
- 0d23a67 Merge pull request #1490 w/o pulls 1474-1475 :+1:  76035785
- Merge pull request #1507
- Merge pull request #1498
- Merge pull request #1497
- Merge pull request #1486
- Merge pull request #1495
- Merge pull request #1496
- Merge pull request #1494
- cf34067 Merge pull request #1478 w/o pulls 1474-1475 :+1: 76035338
- Merge pull request #1491
- Merge pull request #1493
- Merge pull request #1489
- Merge pull request #1488
- Merge pull request #1481
- Merge pull request #1482
- 36ce6a2 Merge pull request #1457
- 43c2aa8 Merge pull request #1476
- facd8fe Merge pull request #1475 :-1: 74486902
- 05437d8 Merge pull request #1474 :-1: 74486725
- 4c6718a Merge pull request #1470 :+1: 74475330

**Comment by hroest** [comment]
the good news: 
 I got it working based on the current head: https://travis-ci.org/OpenMS/OpenMS/builds/76354165

the bad news: 
I had to revert three pull requests, #1470, #1474 and #1458 - I will try to dig deeper here

**Comment by cbielow** [comment]
I don't see how any of this should be related to PP-Wavelet

Compiler bug?!

**Pull request closed without merging**
