### PR TITLE
[FIX] changed relative path to absolute one so it is the same on every

### PR DESCRIPTION
**Pull request by timosachsenberg**
system

### CODE REVIEW

**Comment by cbielow** [comment]
+1 if passes

**Comment by hroest** [comment]
did not pass: http://cdash.openms.de/testDetails.php?test=27972690&build=148531

**Comment by timosachsenberg** [comment]
Yep. Working on it

**Comment by timosachsenberg** [comment]
This might be interesting for @hendrikweisser and others: I had to replace loading of the mzML file from the FileHandler method to the MzMLFile method. The reason is that the FileHandler method replaces the SourceFile entry by the current filename. This looses the link back to the primary MS file which we will need to implement our experimental design.
I might give a more detailed explanation later, but the idea we (basically Johannes, Julianus, Oliver and me) decided on is to carry over the file information of the first (primary) MS run through the whole workflow by storing it in  intermediate data formats (idXML, featureXML,...). Only for these primary mzML files, the SourceFile information may be set from e.g. the .raw file to the current mzML as done in the current FileHandler implementation. One reason, amongst others, is, that the primary mzML file will be the ones that are usually available in the input folder, while all intermediate mzML files might live in temporary folders.
It might therefor be interesting for us to see where the rewriting of the SourceFile to the current file is currently absolutely needed and where it may also rely on the new mechanism of referencing to the primary MS run.

**Comment by hendrikweisser** [comment]
> This might be interesting for @hendrikweisser and others

Thanks for the hint, Timo. So why are the FileHandler and the MzMLFile method behaving differently ("the FileHandler method replaces the SourceFile entry by the current filename")? Would it make sense to change the FileHandler method?

**Comment by timosachsenberg** [comment]
I think it would make sense. I thought this functionality might be required by some of your tools (e.g. merging mzML files might want to preserve the link to the previous mzML but not the primary mzML.)
If this is not the case, I would vote for changing the default behaviour to keeping the original annotation .

**Pull request merged**
