### PR TITLE
TOPPView support for HiRes displays (macOS)

### PR DESCRIPTION
**Pull request by oliveralka**
# Description

TOPPView support for HiRes displays #4968

# Checklist:
- [X] Make sure that you are listed in the AUTHORS file
- [X] Add relevant changes and new features to the CHANGELOG file
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] New and existing unit tests pass locally with my changes
- [X] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

### CODE REVIEW

**Comment by timosachsenberg** [comment]
On my windows, the fonts are pretty small. Was this a similar issue on MacOS?
image

**Comment by oliveralka** [comment]
@timosachsenberg What is the resolution of your display? MacOS was 2560 x 1440 - and it did not seem to be as small as our screenshot.

**Comment by timosachsenberg** [comment]
3840 x 2160

**Comment by jpfeuffer** [comment]
Yep, should only affect macOS. 
Bildschirmfoto 2020-10-01 um 17 25 01
Bildschirmfoto 2020-10-01 um 17 27 04

**Pull request merged**
