### PR TITLE
Feature/pyopenms str

### PR DESCRIPTION
**Pull request by hroest**
an alternative String handling to #2070 - this generates little bit less C code but it is unclear whether this improves runtime or compile time performance. 

Work In Progress: this requires a newer version of autowrap, so wait with a merge please

### CODE REVIEW

**Comment by hroest** [comment]
this reduces the lines of code of the cpp file by about 17%:

- 1 629 411 LOC
- 1 395 958 LOC

it may be worthwhile the effort but I am not sure whether it substantially reduces compile time

**Comment by hroest** [comment]
the Cython code generated by this is simply:

```

self.inst.get().setName(deref((convString(in_0)).get())) 
```

and the C++ code is then 

``` __pyx_v_self->inst.get()->setName((*__pyx_f_8pyopenms_8pyopenms_convString(__pyx_v_in_0).get()));
```

where the fxn is

```cpp
static boost::shared_ptr<OpenMS::String>  __pyx_f_8pyopenms_8pyopenms_convString(PyObject *__pyx_v_argument_var) {
  char *__pyx_v_c_string_argument_var;
  boost::shared_ptr<OpenMS::String>  __pyx_v_res;
  PyObject *__pyx_v_py_byte_string = NULL;
  boost::shared_ptr<OpenMS::String>  __pyx_r;
  __Pyx_RefNannyDeclarations
  int __pyx_t_1;
  int __pyx_t_2;
  boost::shared_ptr<OpenMS::String>  __pyx_t_3;
  char *__pyx_t_4;
  OpenMS::String *__pyx_t_5;
  int __pyx_t_6;
  PyObject *__pyx_t_7 = NULL;
  PyObject *__pyx_t_8 = NULL;
  int __pyx_lineno = 0;
  const char *__pyx_filename = NULL;
  int __pyx_clineno = 0;
  __Pyx_RefNannySetupContext("convString", 0);

  __pyx_t_1 = __Pyx_TypeCheck(__pyx_v_argument_var, __pyx_ptype_8pyopenms_8pyopenms_String); 
  __pyx_t_2 = (__pyx_t_1 != 0);
  if (__pyx_t_2) {

    __pyx_t_3 = ((struct __pyx_obj_8pyopenms_8pyopenms_String *)__pyx_v_argument_var)->inst;
    __pyx_v_res = __pyx_t_3;

    __pyx_r = __pyx_v_res;
    goto __pyx_L0;

  }

  __pyx_t_2 = PyBytes_Check(__pyx_v_argument_var); 
  __pyx_t_1 = (__pyx_t_2 != 0);
  if (__pyx_t_1) {

    __pyx_t_4 = __Pyx_PyObject_AsString(__pyx_v_argument_var); if (unlikely((!__pyx_t_4) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    try {
      __pyx_t_5 = new OpenMS::String(((char *)__pyx_t_4));
    } catch(...) {
      __Pyx_CppExn2PyErr();
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    }
    __pyx_v_res = boost::shared_ptr<OpenMS::String> (__pyx_t_5);

    __pyx_r = __pyx_v_res;
    goto __pyx_L0;

  }

  __pyx_t_2 = PyString_Check(__pyx_v_argument_var); 
  __pyx_t_6 = (__pyx_t_2 != 0);
  if (!__pyx_t_6) {
  } else {
    __pyx_t_1 = __pyx_t_6;
    goto __pyx_L4_bool_binop_done;
  }
  __pyx_t_6 = PyUnicode_Check(__pyx_v_argument_var); 
  __pyx_t_2 = (__pyx_t_6 != 0);
  __pyx_t_1 = __pyx_t_2;
  __pyx_L4_bool_binop_done:;
  if (__pyx_t_1) {

    __pyx_t_7 = __Pyx_PyObject_GetAttrStr(__pyx_v_argument_var, __pyx_n_s_encode); if (unlikely(!__pyx_t_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_7);
    __pyx_t_8 = __Pyx_PyObject_Call(__pyx_t_7, __pyx_tuple_, NULL); if (unlikely(!__pyx_t_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_8);
    __Pyx_DECREF(__pyx_t_7); __pyx_t_7 = 0;
    __pyx_v_py_byte_string = __pyx_t_8;
    __pyx_t_8 = 0;

    __pyx_t_4 = __Pyx_PyObject_AsString(__pyx_v_py_byte_string); if (unlikely((!__pyx_t_4) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_v_c_string_argument_var = __pyx_t_4;

    try {
      __pyx_t_5 = new OpenMS::String(((char *)__pyx_v_c_string_argument_var));
    } catch(...) {
      __Pyx_CppExn2PyErr();
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    }
    __pyx_v_res = boost::shared_ptr<OpenMS::String> (__pyx_t_5);

    __pyx_r = __pyx_v_res;
    goto __pyx_L0;

  }

  /*else*/ {
    __pyx_t_8 = __Pyx_PyObject_Call(__pyx_builtin_Exception, __pyx_tuple__2, NULL); if (unlikely(!__pyx_t_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_8);
    __Pyx_Raise(__pyx_t_8, 0, 0, 0);
    __Pyx_DECREF(__pyx_t_8); __pyx_t_8 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }

  /* function exit code */
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_7);
  __Pyx_XDECREF(__pyx_t_8);
  __Pyx_WriteUnraisable("pyopenms.pyopenms.convString", __pyx_clineno, __pyx_lineno, __pyx_filename, 0, 0);
  __pyx_L0:;
  __Pyx_XDECREF(__pyx_v_py_byte_string);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}
```


which is, relatively speaking, efficient for the code path when we deal with an OpenMS::String as we only need to enter the first loop and do a single `__Pyx_TypeCheck` to check whether the Python object is the right type and then we extract the shared_ptr and return it. Of course there is the overhead of calling the fuction and the whole `RefNanny` stuff which checks the GIL and increases/decreases some references

**Comment by hroest** [comment]
@uweschmitt any comments? If not, lets merge...

**Comment by uweschmitt** [comment]
@hroest nothing to comment, I'd not care to much about the string conversion performance as a pyopenms user lives in "Python world" anyway and OpenMS ist not a library for sequence processing.

**Comment by hroest** [comment]
lets merge then ...

**Pull request merged**
