### PR TITLE
[FEATURE] write mzML index by default

### PR DESCRIPTION
**Pull request by hroest**
Switch OpenMS to write indexed mzML by default

- turns on the flag by default
- this will require to replace all test files so this might take a large pull request
- I suggest to perform this early in the release cycle so that there is enough time to test

it would be great if all tools could assume by default that they get indexed mzML. Other tools such as proteowizard already write indexed mzML and there is no reason for OpenMS not to. The only thing this might break are the tests but the potential gains are substantial for new low-memory tools

This PR will break the tests initially, the idea is that we replace broken test files with correct ones

### CODE REVIEW

**Comment by hroest** [comment]
potentially we need to adopt the `FuzzyDiff` tool to ignore the actual binary offsets if there are issues on different platforms with the binary indices

**Comment by hroest** [comment]
actually not that many tests failed, "only" 54 failed. 

```
The following tests FAILED:

	1011 - TOPP_BaselineFilter_1_out1 (Failed)

	1015 - TOPP_MapNormalizer_1_out1 (Failed)

	1184 - TOPP_FileMerger_1_out1 (Failed)

	1186 - TOPP_FileMerger_2_out1 (Failed)

	1188 - TOPP_FileMerger_3_out1 (Failed)

	1190 - TOPP_FileMerger_4_out1 (Failed)

	1192 - TOPP_FileMerger_5_out1 (Failed)

	1194 - TOPP_FileMerger_6_out1 (Failed)

	1202 - TOPP_HighResPrecursorMassCorrector_1_out1 (Failed)

	1204 - TOPP_HighResPrecursorMassCorrector_2_out1 (Failed)

	1206 - TOPP_HighResPrecursorMassCorrector_3_out1 (Failed)

	1208 - TOPP_HighResPrecursorMassCorrector_4_out1 (Failed)

	1210 - TOPP_HighResPrecursorMassCorrector_5_out1 (Failed)

	1281 - TOPP_MapAlignerPoseClustering_2_out1 (Failed)

	1282 - TOPP_MapAlignerPoseClustering_2_out2 (Failed)

	1283 - TOPP_MapAlignerPoseClustering_2_out3 (Failed)

	1305 - TOPP_MapAlignerSpectrum_1_out1 (Failed)

	1306 - TOPP_MapAlignerSpectrum_1_out2 (Failed)

	1307 - TOPP_MapAlignerSpectrum_1_out3 (Failed)

	1312 - TOPP_MapRTTransformer_2_out1 (Failed)

	1316 - TOPP_MapRTTransformer_4_out1 (Failed)

	1340 - TOPP_MRMMapping_test_1_out_1 (Failed)

	1348 - TOPP_OpenSwathChromatogramExtractor_test_1_out1 (Failed)

	1350 - TOPP_OpenSwathChromatogramExtractor_test_2_out1 (Failed)

	1352 - TOPP_OpenSwathChromatogramExtractor_test_3_out1 (Failed)

	1374 - TOPP_OpenSwathMzMLFileCacher_test_1_out1 (Failed)

	1377 - TOPP_OpenSwathMzMLFileCacher_test_2_out1 (Failed)

	1397 - TOPP_NoiseFilterGaussian_1_out1 (Failed)

	1399 - TOPP_NoiseFilterGaussian_2_out1 (Failed)

	1401 - TOPP_NoiseFilterGaussian_3_out1 (Failed)

	1403 - TOPP_NoiseFilterGaussian_4_out1 (Failed)

	1405 - TOPP_NoiseFilterSGolay_1_out1 (Failed)

	1407 - TOPP_NoiseFilterSGolay_2_out1 (Failed)

	1409 - TOPP_NoiseFilterSGolay_3_out1 (Failed)

	1411 - TOPP_NoiseFilterSGolay_4_out1 (Failed)

	1413 - TOPP_PeakPickerWavelet_1_out1 (Failed)

	1415 - TOPP_PeakPickerWavelet_2_out1 (Failed)

	1417 - TOPP_PeakPickerWavelet_3_out1 (Failed)

	1419 - TOPP_PeakPickerWavelet_4_out1 (Failed)

	1421 - TOPP_PeakPickerWavelet_5_out1 (Failed)

	1423 - TOPP_PeakPickerHiRes_1_out1 (Failed)

	1425 - TOPP_PeakPickerHiRes_2_out1 (Failed)

	1427 - TOPP_PeakPickerHiRes_3_out1 (Failed)

	1429 - TOPP_PeakPickerHiRes_4_out1 (Failed)

	1431 - TOPP_PeakPickerHiRes_5_out1 (Failed)

	1433 - UTILS_PeakPickerIterative_1_out1 (Failed)

	1435 - UTILS_PeakPickerIterative_2_out1 (Failed)

	1437 - TOPP_LowMemPeakPickerHiRes_1_out1 (Failed)

	1439 - TOPP_LowMemPeakPickerHiRes_RandomAccess_1_out1 (Failed)

	1441 - TOPP_Resampler_1_out1 (Failed)

	1483 - TOPP_SpectraFilterSqrtMower_1_out1 (Failed)

	1485 - TOPP_SpectraFilterWindowMower_1_out1 (Failed)

	1487 - TOPP_SpectraFilterWindowMower_2_out1 (Failed)

	1568 - TOPP_PrecursorMassCorrector_1_out1 (Failed)
```

**Comment by hroest** [comment]
I went through all the files that failed the test and replaced the test files, so now the tests should run. Also I added whitelist arguments to all relevant `FuzzyDiff` calls so it should even work when the actual binary offsets are not numerically identical

**Comment by timosachsenberg** [comment]
+1

**Pull request merged**
