### PR TITLE
masstrace_snr_filtering: is flag

### PR DESCRIPTION
**Pull request by bernt-matthias**
according to the discussion in https://github.com/OpenMS/OpenMS/issues/2350
this should be represented by the restrictions being true,false

Would be nice to have a method to check if there are more such cases.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
I guess we could easily grep it. Which ones do you want to make flags? Everything that is true,false or false,true and has default of false?
I think it would make sense but I did not spend much time thinking about all implications.
Btw, this could also be changed in the CTD creating part of the code, such that the order in each TOPP tool would not matter.

**Comment by bernt-matthias** [comment]
@jpfeuffer good idea, but since I autocreate a commandline for the Galaxy tools from the CTDs the only thing that is imoortant is consistency.

**Comment by jpfeuffer** [comment]
Ah hmm.. just to let you know:
from 2.4 to 2.5 the CTD version will change. You will be able to identify flags then.
They then have the bool type. No more true false magic.

**Comment by bernt-matthias** [comment]
> from 2.4 to 2.5 the CTD version will change. You will be able to identify flags then.
> They then have the bool type. No more true false magic.

Good to know (that there will be more work :) ). In all utils and topp tools?

**Pull request merged**
